Repository pinpoint-apm/pinpoint, pull requests merged in 2018-10, with the labels that each got.

#4687 [#4558] Add grpc transport
  grpc/.gitignore
  grpc/README.md
  grpc/pom.xml
  grpc/src/main/proto/Trace.proto
  grpc/src/main/thrift/Command.thrift
  grpc/src/main/thrift/Flink.thrift
  grpc/src/main/thrift/Pinpoint.thrift
  grpc/src/main/thrift/Trace.thrift
  pom.xml
  profiler/pom.xml
Labels: enhancement, module:project-common

#4696 [#4677] Fix collector namespace
  collector/src/main/java/com/navercorp/pinpoint/collector/cluster/route/filter/AgentEventHandlingFilter.java
  collector/src/main/java/com/navercorp/pinpoint/collector/receiver/thrift/tcp/AgentEventHandler.java
  collector/src/main/java/com/navercorp/pinpoint/collector/receiver/thrift/tcp/AgentLifeCycleEventHandler.java
  collector/src/main/java/com/navercorp/pinpoint/collector/service/AgentEventService.java
  collector/src/main/java/com/navercorp/pinpoint/collector/service/AgentLifeCycleService.java
  collector/src/main/java/com/navercorp/pinpoint/collector/service/StringMetaDataService.java
  collector/src/test/java/com/navercorp/pinpoint/collector/cluster/route/filter/AgentEventHandlingFilterTest.java
  collector/src/test/java/com/navercorp/pinpoint/collector/receiver/thrift/tcp/AgentEventHandlerTest.java
  collector/src/test/java/com/navercorp/pinpoint/collector/receiver/thrift/tcp/AgentLifeCycleEventHandlerTest.java
Labels: enhancement, module:collector

#4748 [#4745] Clean up the duplicate code associated with the Zookeeper
  collector/src/main/java/com/navercorp/pinpoint/collector/cluster/flink/FlinkClusterService.java
  collector/src/main/java/com/navercorp/pinpoint/collector/cluster/zookeeper/DefaultZookeeperClient.java
  collector/src/main/java/com/navercorp/pinpoint/collector/cluster/zookeeper/ZookeeperClient.java
  collector/src/main/java/com/navercorp/pinpoint/collector/cluster/zookeeper/ZookeeperClusterManager.java
  collector/src/main/java/com/navercorp/pinpoint/collector/cluster/zookeeper/ZookeeperClusterService.java
  collector/src/main/java/com/navercorp/pinpoint/collector/cluster/zookeeper/ZookeeperJobWorker.java
  collector/src/main/java/com/navercorp/pinpoint/collector/cluster/zookeeper/ZookeeperUtils.java
  collector/src/main/java/com/navercorp/pinpoint/collector/cluster/zookeeper/exception/ConnectionException.java
  collector/src/main/java/com/navercorp/pinpoint/collector/cluster/zookeeper/exception/NoNodeException.java
  collector/src/main/java/com/navercorp/pinpoint/collector/cluster/zookeeper/exception/TimeoutException.java
  collector/src/main/java/com/navercorp/pinpoint/collector/cluster/zookeeper/exception/UnknownException.java
  collector/src/test/java/com/navercorp/pinpoint/collector/cluster/zookeeper/ZookeeperJobWorkerTest.java
  commons-server/pom.xml
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/cluster/zookeeper/ZookeeperConnectionManager.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/cluster/zookeeper/ZookeeperConstatns.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/cluster/zookeeper/ZookeeperEventWatcher.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/cluster/zookeeper/ZookeeperExceptionResolver.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/cluster/zookeeper/exception/AuthException.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/cluster/zookeeper/exception/BadOperationException.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/cluster/zookeeper/exception/ConnectionException.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/cluster/zookeeper/exception/NoNodeException.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/cluster/zookeeper/exception/PinpointZookeeperException.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/cluster/zookeeper/exception/TimeoutException.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/cluster/zookeeper/exception/UnknownException.java
  flink/src/main/java/com/navercorp/pinpoint/flink/cluster/FlinkServerRegister.java
  web/src/main/java/com/navercorp/pinpoint/web/cluster/zookeeper/ZookeeperClient.java
  web/src/main/java/com/navercorp/pinpoint/web/cluster/zookeeper/ZookeeperClusterDataManager.java
  web/src/main/java/com/navercorp/pinpoint/web/cluster/zookeeper/ZookeeperClusterDataManagerHelper.java
  web/src/main/java/com/navercorp/pinpoint/web/cluster/zookeeper/exception/AuthException.java
  web/src/main/java/com/navercorp/pinpoint/web/cluster/zookeeper/exception/BadOperationException.java
  web/src/main/java/com/navercorp/pinpoint/web/cluster/zookeeper/exception/NoNodeException.java
  web/src/test/java/com/navercorp/pinpoint/web/cluster/zookeeper/ZookeeperClusterTest.java
Labels: cleanup, module:project-common

#4753 [#noissue] update guide
  doc/troubleshooting_network.md
Labels: document

#4750 [#4746] Fix SqlParser.combindBindValues operation
  commons/src/main/java/com/navercorp/pinpoint/common/util/DefaultSqlParser.java
  commons/src/test/java/com/navercorp/pinpoint/common/util/DefaultSqlParserTest.java
Labels: bug

#4768 [#4661] Fix missing nextSpanId
  profiler/src/main/java/com/navercorp/pinpoint/profiler/context/thrift/SpanThriftMessageConverter.java
Labels: bug, module:agent

#4774 [#4772] Specifies a charset to UTF-8 for Kafka Plugin module
  plugins/kafka/src/main/java/com/navercorp/pinpoint/plugin/kafka/KafkaConstants.java
  plugins/kafka/src/main/java/com/navercorp/pinpoint/plugin/kafka/interceptor/ConsumerRecordEntryPointInterceptor.java
  plugins/kafka/src/main/java/com/navercorp/pinpoint/plugin/kafka/interceptor/ProducerSendInterceptor.java
Labels: enhancement, module:plugin

#4793 [#4677] Update Deadlock of Collector
  collector/src/main/java/com/navercorp/pinpoint/collector/dao/hbase/stat/HbaseDeadlockThreadCountDao.java
  collector/src/main/java/com/navercorp/pinpoint/collector/handler/thrift/ThriftAgentEventHandler.java
  collector/src/main/java/com/navercorp/pinpoint/collector/mapper/thrift/event/AgentEventBatchMapper.java
  collector/src/main/java/com/navercorp/pinpoint/collector/mapper/thrift/event/AgentEventMapper.java
  collector/src/main/java/com/navercorp/pinpoint/collector/mapper/thrift/event/DeadlockBoMapper.java
  collector/src/main/java/com/navercorp/pinpoint/collector/mapper/thrift/event/DeadlockEventBoMapper.java
  collector/src/main/java/com/navercorp/pinpoint/collector/mapper/thrift/event/MonitorInfoBoMapper.java
  collector/src/main/java/com/navercorp/pinpoint/collector/mapper/thrift/event/ThreadDumpBoMapper.java
  collector/src/main/java/com/navercorp/pinpoint/collector/mapper/thrift/stat/AgentStatBatchMapper.java
  collector/src/main/java/com/navercorp/pinpoint/collector/mapper/thrift/stat/AgentStatMapper.java
  collector/src/main/java/com/navercorp/pinpoint/collector/mapper/thrift/stat/DeadlockThreadCountBoMapper.java
  collector/src/main/java/com/navercorp/pinpoint/collector/receiver/thrift/tcp/AgentEventHandler.java
  collector/src/main/java/com/navercorp/pinpoint/collector/service/HBaseAgentStatService.java
  collector/src/main/resources/applicationContext-collector.xml
  collector/src/test/java/com/navercorp/pinpoint/collector/handler/thrift/ThriftAgentStatHandlerV2Test.java
  collector/src/test/java/com/navercorp/pinpoint/collector/mapper/thrift/event/AgentEventMapperTest.java
  collector/src/test/java/com/navercorp/pinpoint/collector/mapper/thrift/stat/DeadlockThreadCountBoMapperTest.java
  collector/src/test/java/com/navercorp/pinpoint/collector/receiver/thrift/tcp/AgentEventHandlerTest.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/codec/stat/DeadlockDecoder.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/codec/stat/DeadlockEncoder.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/codec/stat/v2/DeadlockCodecV2.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/event/AgentEventBo.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/event/DeadlockBo.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/event/DeadlockEventBo.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/event/MonitorInfoBo.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/event/ThreadDumpBo.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/event/ThreadState.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/serializer/stat/DeadlockThreadCountSerializer.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/stat/AgentStatBo.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/stat/DeadlockThreadCountBo.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/util/AgentEventMessageDeserializer.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/util/AgentEventMessageDeserializerV1.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/util/AgentEventMessageSerializer.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/util/AgentEventMessageSerializerV1.java
  commons-server/src/test/java/com/navercorp/pinpoint/common/server/bo/codec/stat/TestAgentStatFactory.java
  commons-server/src/test/java/com/navercorp/pinpoint/common/server/bo/codec/stat/v2/DeadlockCodecV2Test.java
  commons-server/src/test/java/com/navercorp/pinpoint/common/server/util/AgentEventMessageSerializerV1Test.java
  web/src/main/java/com/navercorp/pinpoint/web/controller/AgentStatController.java
  web/src/main/java/com/navercorp/pinpoint/web/dao/hbase/stat/AgentStatDaoFactory.java
  web/src/main/java/com/navercorp/pinpoint/web/dao/hbase/stat/v2/HbaseDeadlockDaoV2.java
  web/src/main/java/com/navercorp/pinpoint/web/dao/hbase/stat/v2/HbaseSampledDeadlockDaoV2.java
  web/src/main/java/com/navercorp/pinpoint/web/dao/stat/DeadlockDao.java
  web/src/main/java/com/navercorp/pinpoint/web/mapper/AgentEventMapper.java
  web/src/main/java/com/navercorp/pinpoint/web/mapper/stat/sampling/sampler/DeadlockSampler.java
  web/src/main/java/com/navercorp/pinpoint/web/service/AgentEventServiceImpl.java
  web/src/main/java/com/navercorp/pinpoint/web/service/stat/AgentWarningStatServiceImpl.java
  web/src/main/java/com/navercorp/pinpoint/web/service/stat/DeadlockService.java
  web/src/main/java/com/navercorp/pinpoint/web/util/ThreadDumpUtils.java
  web/src/main/java/com/navercorp/pinpoint/web/view/AgentEventSerializer.java
  web/src/main/resources/applicationContext-web.xml
  web/src/test/java/com/navercorp/pinpoint/web/service/stat/AgentWarningStatServiceTest.java
  web/src/test/java/com/navercorp/pinpoint/web/vo/stat/chart/agent/DeadlockChartGroupTest.java
Labels: enhancement, module:collector, module:web

#4808 [#4785] Refactor Kafka Plugin and Add ConsumerRecords Interceptor.
  agent/src/main/resources-local/pinpoint.config
  agent/src/main/resources-release/pinpoint-real-env-lowoverhead-sample.config
  agent/src/main/resources-release/pinpoint.config
  plugins/kafka/src/main/java/com/navercorp/pinpoint/plugin/kafka/KafkaConstants.java
  plugins/kafka/src/main/java/com/navercorp/pinpoint/plugin/kafka/KafkaMetadataProvider.java
  plugins/kafka/src/main/java/com/navercorp/pinpoint/plugin/kafka/KafkaPlugin.java
  plugins/kafka/src/main/java/com/navercorp/pinpoint/plugin/kafka/interceptor/ConsumerMultiRecordEntryPointInterceptor.java
  plugins/kafka/src/main/java/com/navercorp/pinpoint/plugin/kafka/interceptor/ConsumerRecordEntryPointInterceptor.java
  plugins/kafka/src/test/java/com/navercorp/pinpoint/plugin/kafka/interceptor/ConsumerConstructorInterceptorTest.java
  plugins/kafka/src/test/java/com/navercorp/pinpoint/plugin/kafka/interceptor/ConsumerMultiRecordEntryPointInterceptorTest.java
  plugins/kafka/src/test/java/com/navercorp/pinpoint/plugin/kafka/interceptor/ConsumerPollInterceptorTest.java
  plugins/kafka/src/test/java/com/navercorp/pinpoint/plugin/kafka/interceptor/ConsumerRecordEntryPointInterceptorTest.java
  plugins/kafka/src/test/java/com/navercorp/pinpoint/plugin/kafka/interceptor/ProducerConstructorInterceptorTest.java
  plugins/kafka/src/test/java/com/navercorp/pinpoint/plugin/kafka/interceptor/ProducerSendInterceptorTest.java
Labels: enhancement, module:plugin

#4819 [#noissue] add toString method
  web/src/main/java/com/navercorp/pinpoint/web/alarm/vo/Rule.java
Labels: enhancement

#4825 [#noissue] Refactor ASM class
  profiler-optional/profiler-optional-jdk8/src/test/java/com/navercorp/test/pinpoint/jdk8/interfaces/MethodInterfaceTest.java
  profiler/src/main/java/com/navercorp/pinpoint/profiler/context/provider/InstrumentEngineProvider.java
  profiler/src/main/java/com/navercorp/pinpoint/profiler/instrument/ASMClass.java
  profiler/src/main/java/com/navercorp/pinpoint/profiler/instrument/ASMEngine.java
  profiler/src/main/java/com/navercorp/pinpoint/profiler/instrument/ASMMethod.java
  profiler/src/main/java/com/navercorp/pinpoint/profiler/instrument/ASMNestedClass.java
  profiler/src/main/java/com/navercorp/pinpoint/profiler/instrument/DefaultEngineComponent.java
  profiler/src/main/java/com/navercorp/pinpoint/profiler/instrument/EngineComponent.java
  profiler/src/test/java/com/navercorp/pinpoint/profiler/instrument/ASMClassTest.java
  profiler/src/test/java/com/navercorp/pinpoint/profiler/instrument/ASMMethodNodeAdapterTestMain.java
  profiler/src/test/java/com/navercorp/pinpoint/profiler/instrument/ASMMethodNodeTest.java
Labels: module:agent
