Repository pinpoint-apm/pinpoint, pull requests merged in 2018-04, with the labels that each got.

#3956 [#3955] Javaagent not found in classpath of java9
  bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/AgentDirBaseClassPathResolver.java
  bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/JavaAgentPathResolver.java
  bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/PinpointBootStrap.java
  bootstrap/src/test/java/com/navercorp/pinpoint/bootstrap/JavaAgentPathResolverTest.java
Labels: enhancement, module:agent

#3959 [#3958] ASM version up
  pom.xml
Labels: enhancement, module:agent

#3949 [#3948] Add to function which can add customized HandshakeInterceptor
  web/src/main/java/com/navercorp/pinpoint/web/config/WebSocketConfig.java
  web/src/main/java/com/navercorp/pinpoint/web/websocket/CustomHandshakeInterceptor.java
Labels: enhancement

#3977 [#3976] Javassist version update for java9
  pom.xml
Labels: enhancement, module:agent

#3979 [#3978] Add Java10 to JvmVersion
  commons/src/main/java/com/navercorp/pinpoint/common/util/JvmVersion.java
  commons/src/test/java/com/navercorp/pinpoint/common/util/JvmVersionTest.java
Labels: enhancement, module:project-common

#3975 [#3839] Fix Linux&oracleJDK env
  commons/src/main/java/com/navercorp/pinpoint/common/util/JvmType.java
  commons/src/main/java/com/navercorp/pinpoint/common/util/OsType.java
  profiler/src/main/java/com/navercorp/pinpoint/profiler/context/provider/stat/filedescriptor/FileDescriptorMetricProvider.java
  profiler/src/test/java/com/navercorp/pinpoint/profiler/context/provider/stat/filedescriptor/FileDescriptorMetricProviderTest.java
Labels: bug

#3838 [#3837] Support java 8 interface static/default method
  profiler-optional/profiler-optional-jdk8/src/test/java/com/navercorp/test/pinpoint/jdk8/interfaces/MethodInterface.java
  profiler-optional/profiler-optional-jdk8/src/test/java/com/navercorp/test/pinpoint/jdk8/interfaces/MethodInterfaceClass.java
  profiler-optional/profiler-optional-jdk8/src/test/java/com/navercorp/test/pinpoint/jdk8/interfaces/MethodInterfaceTest.java
  profiler-optional/profiler-optional-jdk8/src/test/java/com/navercorp/test/pinpoint/jdk8/interfaces/SimpleAccessor.java
  profiler-optional/profiler-optional-jdk8/src/test/java/com/navercorp/test/pinpoint/jdk8/interfaces/SimpleClass.java
  profiler-optional/profiler-optional-jdk8/src/test/java/com/navercorp/test/pinpoint/jdk8/interfaces/SimpleInterceptor.java
  profiler-optional/profiler-optional-jdk8/src/test/java/com/navercorp/test/pinpoint/jdk8/interfaces/SimpleInterface.java
  profiler-optional/profiler-optional-jdk8/src/test/java/com/navercorp/test/pinpoint/jdk8/interfaces/SimpleInterfaceClass.java
  profiler-optional/profiler-optional-jdk8/src/test/resources/log4j.xml
  profiler/src/main/java/com/navercorp/pinpoint/profiler/instrument/ASMClass.java
  profiler/src/main/java/com/navercorp/pinpoint/profiler/instrument/ASMClassNodeAdapter.java
  profiler/src/main/java/com/navercorp/pinpoint/profiler/instrument/JavassistClass.java
  profiler/src/test/java/com/navercorp/pinpoint/profiler/instrument/ASMClassTest.java
Labels: enhancement, module:agent

#3984 [#3815] Add RequestTraceReader and ServerRequestRecorder
  bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/RequestTrace.java
  bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/proxy/ProxyHttpHeaderRecorder.java
  bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/request/RequestTraceReader.java
  bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/request/ServerRequestRecorder.java
  bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/request/ServerRequestTrace.java
  bootstrap-core/src/test/java/com/navercorp/pinpoint/bootstrap/plugin/proxy/ProxyHttpHeaderRecorderTest.java
  bootstrap-core/src/test/java/com/navercorp/pinpoint/bootstrap/plugin/request/RequestTraceReaderTest.java
  bootstrap-core/src/test/java/com/navercorp/pinpoint/bootstrap/plugin/request/ServerRequestRecorderTest.java
  plugins/jboss/src/main/java/com/navercorp/pinpoint/plugin/jboss/JbossServerRequestTrace.java
  plugins/jboss/src/main/java/com/navercorp/pinpoint/plugin/jboss/interceptor/StandardHostValveInvokeInterceptor.java
  plugins/jetty/src/main/java/com/navercorp/pinpoint/plugin/jetty/JettyServerRequestTrace.java
  plugins/jetty/src/main/java/com/navercorp/pinpoint/plugin/jetty/interceptor/AbstractServerHandleInterceptor.java
  plugins/jetty/src/main/java/com/navercorp/pinpoint/plugin/jetty/interceptor/Jetty8ServerHandleInterceptor.java
  plugins/jetty/src/main/java/com/navercorp/pinpoint/plugin/jetty/interceptor/Jetty8xServerHandleInterceptor.java
  plugins/jetty/src/main/java/com/navercorp/pinpoint/plugin/jetty/interceptor/ServerHandleInterceptor.java
  plugins/resin/src/main/java/com/navercorp/pinpoint/plugin/resin/ResinServerRequestTrace.java
  plugins/resin/src/main/java/com/navercorp/pinpoint/plugin/resin/interceptor/ServletInvocationInterceptor.java
  plugins/tomcat/src/main/java/com/navercorp/pinpoint/plugin/tomcat/TomcatServerRequestTrace.java
  plugins/tomcat/src/main/java/com/navercorp/pinpoint/plugin/tomcat/interceptor/StandardHostValveInvokeInterceptor.java
  plugins/vertx/src/main/java/com/navercorp/pinpoint/plugin/vertx/VertxHttpServerServerRequestTrace.java
  plugins/vertx/src/main/java/com/navercorp/pinpoint/plugin/vertx/interceptor/ServerConnectionHandleRequestInterceptor.java
  plugins/websphere/src/main/java/com/navercorp/pinpoint/plugin/websphere/WebsphereServerRequestTrace.java
  plugins/websphere/src/main/java/com/navercorp/pinpoint/plugin/websphere/interceptor/AbstractServerHandleInterceptor.java
Labels: module:agent, module:plugin

#3988 [#3986] Upgrade maven plugins for java9, 10
  pom.xml
Labels: module:project-common

#3999 [#3998] Fix to search child-classloader first
  bootstrap-core-optional/src/main/java/com/navercorp/pinpoint/bootstrap/classloader/ParallelCapablePinpointURLClassLoader.java
  bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/classloader/MergedEnumeration2.java
  bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/classloader/PinpointURLClassLoader.java
  bootstrap-core/src/test/java/com/navercorp/pinpoint/bootstrap/classloader/MergedEnumeration2Test.java
Labels: enhancement, module:agent

#4022 [#noissue] Update config
  agent/src/main/resources-local/pinpoint.config
  agent/src/main/resources-release/pinpoint.config
  quickstart/agent/src/main/resources/pinpoint.config
Labels: document

#4026 [#noissue] fix quickstart readme
  quickstart/README.md
Labels: cleanup, document

#4028 [#noissue] Fix get simple class name of Logger
  profiler/src/main/java/com/navercorp/pinpoint/profiler/logging/Slf4jPLoggerAdapter.java
  profiler/src/test/java/com/navercorp/pinpoint/profiler/logging/Slf4jPLoggerAdapterTest.java
Labels: enhancement

#4079 [#4078] fix when select alarm rule memory db
  web/src/main/java/com/navercorp/pinpoint/web/dao/memory/MemoryAlarmDao.java
  web/src/test/java/com/navercorp/pinpoint/web/dao/memory/MemoryAlarmDaoTest.java
Labels: bug
