Repository pinpoint-apm/pinpoint, pull requests merged in 2018-09, with the labels that each got.

#4583 [#4027] Support HeaderV2
  thrift/src/main/java/com/navercorp/pinpoint/io/util/HeaderFactoryV2.java
  thrift/src/main/java/com/navercorp/pinpoint/thrift/io/HeaderTBaseSerializer.java
Labels: enhancement, module:project-common

#4588 [#4582] Add Lambda transform for spring framework Async 5.0.x
  plugins/spring/src/main/java/com/navercorp/pinpoint/plugin/spring/async/SpringAsyncPlugin.java
Labels: enhancement, module:plugin

#4612 [#noissue] Add MatchableTransformTemplateAware in MockPluginSetup
  profiler-test/src/main/java/com/navercorp/pinpoint/test/MockPluginSetup.java
Labels: module:plugin

#4629 [#4625] Change default maven profile
  .travis.yml
  pom.xml
Labels: configuration

#4653 [#noissue] Do not skip test-jar creation
  rpc/pom.xml
Labels: configuration
