Repository pinpoint-apm/pinpoint, pull requests merged in 2019-04, with the labels that each got.

#5438 [#5384] Cleanup code related to cluster
  collector/src/main/java/com/navercorp/pinpoint/collector/cluster/ClusterPointStateChangedEventHandler.java
  collector/src/main/java/com/navercorp/pinpoint/collector/cluster/connection/CollectorClusterAcceptor.java
  collector/src/main/java/com/navercorp/pinpoint/collector/cluster/zookeeper/ZookeeperClusterService.java
  collector/src/main/java/com/navercorp/pinpoint/collector/cluster/zookeeper/ZookeeperProfilerClusterManager.java
  collector/src/main/java/com/navercorp/pinpoint/collector/receiver/AgentLifeCycleChangeEventHandler.java
  collector/src/main/java/com/navercorp/pinpoint/collector/receiver/thrift/tcp/AgentBaseDataReceiver.java
  collector/src/test/java/com/navercorp/pinpoint/collector/cluster/zookeeper/ZookeeperJobWorkerTest.java
  collector/src/test/java/com/navercorp/pinpoint/collector/receiver/thrift/tcp/AgentLifeCycleChangeEventHandlerTest.java
  rpc/src/main/java/com/navercorp/pinpoint/rpc/ExecutionThreadStateChangeEventHandler.java
  rpc/src/main/java/com/navercorp/pinpoint/rpc/LoggingStateChangeEventListener.java
  rpc/src/main/java/com/navercorp/pinpoint/rpc/StateChangeEventListener.java
  rpc/src/main/java/com/navercorp/pinpoint/rpc/client/PinpointClientHandlerState.java
  rpc/src/main/java/com/navercorp/pinpoint/rpc/server/DefaultPinpointServer.java
  rpc/src/main/java/com/navercorp/pinpoint/rpc/server/DefaultPinpointServerState.java
  rpc/src/main/java/com/navercorp/pinpoint/rpc/server/handler/DoNothingChannelStateEventHandler.java
  rpc/src/main/java/com/navercorp/pinpoint/rpc/server/handler/ServerStateChangeEventHandler.java
  rpc/src/test/java/com/navercorp/pinpoint/rpc/server/EventHandlerTest.java
Labels: cleanup

#5443 [#5442] Add HttpHandler option of undertow plugin
  agent/src/main/resources-local/pinpoint.config
  agent/src/main/resources-release/pinpoint.config
  plugins/undertow/src/main/java/com/navercorp/pinpoint/plugin/undertow/UndertowConfig.java
  plugins/undertow/src/main/java/com/navercorp/pinpoint/plugin/undertow/interceptor/ConnectorsExecuteRootHandlerInterceptor.java
Labels: enhancement, module:plugin

#5449 [#5448] parameter validation
  web/src/main/java/com/navercorp/pinpoint/web/controller/UserController.java
  web/src/main/java/com/navercorp/pinpoint/web/controller/UserGroupController.java
  web/src/main/java/com/navercorp/pinpoint/web/util/ValueValidator.java
  web/src/test/java/com/navercorp/pinpoint/web/util/ValueValidatorTest.java
Labels: enhancement, module:web

#5447 Fixes running container agents not showing up in Inspector View agent list
  web/src/main/java/com/navercorp/pinpoint/web/controller/AgentInfoController.java
Labels: bug, module:web

#5455 [#5448] parameter validation
  web/src/main/java/com/navercorp/pinpoint/web/util/ValueValidator.java
Labels: enhancement, module:web

#5460 [#5384] Cleanup code related to cluster
  collector/src/main/java/com/navercorp/pinpoint/collector/cluster/ClusterPoint.java
  collector/src/main/java/com/navercorp/pinpoint/collector/cluster/ClusterPointRepository.java
  collector/src/main/java/com/navercorp/pinpoint/collector/cluster/ClusterPointRouter.java
  collector/src/main/java/com/navercorp/pinpoint/collector/cluster/ClusterPointStateChangedEventHandler.java
  collector/src/main/java/com/navercorp/pinpoint/collector/cluster/TargetClusterPoint.java
  collector/src/main/java/com/navercorp/pinpoint/collector/cluster/ThriftAgentConnection.java
  collector/src/main/java/com/navercorp/pinpoint/collector/cluster/route/AbstractRouteHandler.java
  collector/src/main/java/com/navercorp/pinpoint/collector/cluster/route/DefaultRouteHandler.java
  collector/src/main/java/com/navercorp/pinpoint/collector/cluster/route/StreamRouteHandler.java
  collector/src/main/java/com/navercorp/pinpoint/collector/cluster/zookeeper/ZookeeperProfilerClusterManager.java
Labels: cleanup

#5471 [#cleanup] cleanup unused imports
  collector/src/main/java/com/navercorp/pinpoint/collector/handler/thrift/ThriftApiMetaDataHandler.java
  collector/src/main/java/com/navercorp/pinpoint/collector/mapper/thrift/AgentInfoBoMapper.java
  collector/src/main/java/com/navercorp/pinpoint/collector/mapper/thrift/event/AgentEventBatchMapper.java
  collector/src/main/java/com/navercorp/pinpoint/collector/mapper/thrift/event/AgentEventMapper.java
  collector/src/main/java/com/navercorp/pinpoint/collector/mapper/thrift/stat/AgentStatBatchMapper.java
  collector/src/main/java/com/navercorp/pinpoint/collector/mapper/thrift/stat/AgentStatMapper.java
  collector/src/main/java/com/navercorp/pinpoint/collector/receiver/thrift/PinpointServerAcceptorProvider.java
  plugins/grpc/src/main/java/com/navercorp/pinpoint/plugin/grpc/GrpcClientPlugin.java
  plugins/kafka/src/main/java/com/navercorp/pinpoint/plugin/kafka/KafkaConstants.java
  plugins/netty/src/main/java/com/navercorp/pinpoint/plugin/netty/NettyClientRequestWrapper.java
  plugins/netty/src/main/java/com/navercorp/pinpoint/plugin/netty/NettyConstants.java
  plugins/resttemplate/src/main/java/com/navercorp/pinpoint/plugin/resttemplate/RestTemplateConstants.java
  profiler-test/src/main/java/com/navercorp/pinpoint/test/MockTraceContextFactory.java
  thrift/src/main/java/com/navercorp/pinpoint/thrift/io/DefaultTBaseLocator.java
  thrift/src/main/java/com/navercorp/pinpoint/thrift/io/TCommandRegistry.java
  web/src/main/java/com/navercorp/pinpoint/web/mapper/stat/SampledDataSourceResultExtractor.java
  web/src/main/java/com/navercorp/pinpoint/web/vo/AgentActiveThreadCountList.java
Labels: cleanup

#5468 [#4558] add grpcAgentConnection
  collector/src/main/java/com/navercorp/pinpoint/collector/cluster/GrpcAgentConnection.java
  collector/src/main/java/com/navercorp/pinpoint/collector/cluster/route/DefaultRouteHandler.java
  collector/src/main/java/com/navercorp/pinpoint/collector/receiver/grpc/AgentServer.java
  collector/src/main/java/com/navercorp/pinpoint/collector/receiver/grpc/PinpointGrpcServer.java
  collector/src/main/java/com/navercorp/pinpoint/collector/receiver/grpc/PinpointGrpcServerRepository.java
  collector/src/main/java/com/navercorp/pinpoint/collector/receiver/grpc/service/GrpcCommandService.java
  collector/src/test/java/com/navercorp/pinpoint/collector/cluster/route/GrpcAgentConnectionTest.java
  collector/src/test/java/com/navercorp/pinpoint/collector/receiver/grpc/PinpointGrpcServerTest.java
  grpc/src/main/proto/Command.proto
  profiler/src/main/java/com/navercorp/pinpoint/profiler/context/thrift/CommandGrpcToThriftMessageConverter.java
  profiler/src/main/java/com/navercorp/pinpoint/profiler/context/thrift/CommandThriftToGrpcMessageConverter.java
  profiler/src/main/java/com/navercorp/pinpoint/profiler/receiver/grpc/GrpcCommandDispatcher.java
  profiler/src/main/java/com/navercorp/pinpoint/profiler/receiver/grpc/GrpcEchoService.java
Labels: enhancement, module:agent, module:collector

#5478 [#5384] Cleanup code related to cluster
  rpc/src/main/java/com/navercorp/pinpoint/rpc/stream/AbstractStreamChannel.java
  rpc/src/main/java/com/navercorp/pinpoint/rpc/stream/ClientStreamChannel.java
  rpc/src/main/java/com/navercorp/pinpoint/rpc/stream/NettyClientStreamChannel.java
  rpc/src/main/java/com/navercorp/pinpoint/rpc/stream/ServerStreamChannel.java
  rpc/src/main/java/com/navercorp/pinpoint/rpc/stream/StreamChannel.java
  rpc/src/main/java/com/navercorp/pinpoint/rpc/stream/StreamChannelManager.java
  rpc/src/test/java/com/navercorp/pinpoint/rpc/stream/StreamChannelTest.java
Labels: cleanup

#5484 [#noissue] Fix NPE of NettyPlugin
  plugins/netty/src/main/java/com/navercorp/pinpoint/plugin/netty/interceptor/BootstrapConnectInterceptor.java
  plugins/netty/src/main/java/com/navercorp/pinpoint/plugin/netty/interceptor/ChannelPipelineWriteInterceptor.java
Labels: bug, module:plugin

#5487 [#5384] Fix to send data using invalid objects
  rpc/src/main/java/com/navercorp/pinpoint/rpc/stream/StreamChannelManager.java
Labels: bug, cleanup

#5505 [#4558] Cleanup
  web/src/main/java/com/navercorp/pinpoint/web/service/DotExtractor.java
  web/src/main/java/com/navercorp/pinpoint/web/service/map/FilteredMapBuilder.java
Labels: cleanup

#5507 [#noissue] Fix maven pmd configuration for grpc
  pom.xml
Labels: configuration

#5515 [#5514] change log level for SequenceSpanEventFilter
  collector/src/main/java/com/navercorp/pinpoint/collector/dao/hbase/filter/SequenceSpanEventFilter.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/filter/SequenceSpanEventFilter.java
Labels: enhancement, module:collector

#5518 [#5059] Modify to use standard API of the module
  bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/module/JavaModule.java
  bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/module/Providers.java
  bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/module/UnsupportedJavaModule.java
  bootstrap-java9/src/main/java/com/navercorp/pinpoint/bootstrap/java9/module/JarFileAnalyzer.java
  bootstrap-java9/src/main/java/com/navercorp/pinpoint/bootstrap/java9/module/Java9Module.java
  bootstrap-java9/src/main/java/com/navercorp/pinpoint/bootstrap/java9/module/ModuleBuilder.java
  bootstrap-java9/src/main/java/com/navercorp/pinpoint/bootstrap/java9/module/ModuleSupport.java
  bootstrap-java9/src/main/java/com/navercorp/pinpoint/bootstrap/java9/module/PackageAnalyzer.java
  bootstrap-java9/src/main/java/com/navercorp/pinpoint/bootstrap/java9/module/PackageInfo.java
  bootstrap-java9/src/main/java/com/navercorp/pinpoint/bootstrap/java9/module/ServiceDescriptorParser.java
  bootstrap-java9/src/main/java/com/navercorp/pinpoint/bootstrap/java9/module/ServiceLoaderClassPathLookupHelper.java
  bootstrap-java9/src/test/java/com/navercorp/pinpoint/bootstrap/java9/module/JarFileAnalyzerTest.java
  bootstrap-java9/src/test/java/com/navercorp/pinpoint/bootstrap/java9/module/ModuleBuilderTest.java
  bootstrap-java9/src/test/java/com/navercorp/pinpoint/bootstrap/java9/module/ServiceLoaderClassPathLookupHelperTest.java
Labels: module:agent

#5542 [#4558] Fix StatServer of Collector
  collector/src/main/java/com/navercorp/pinpoint/collector/mapper/grpc/stat/GrpcAgentStatBatchMapper.java
  collector/src/main/java/com/navercorp/pinpoint/collector/receiver/grpc/StatServer.java
  collector/src/main/resources/applicationContext-collector.xml
Labels: enhancement, module:collector

#5545 [#4558] Change gRPC enum
  grpc/src/main/proto/Stat.proto
  grpc/src/main/proto/ThreadDump.proto
Labels: enhancement, module:project-common
