Repository pinpoint-apm/pinpoint, pull requests merged in 2019-03, with the labels that each got.

#5291 [#4558] Add thread-pool settings
  grpc/src/main/java/com/navercorp/pinpoint/grpc/ExecutorUtils.java
  grpc/src/main/java/com/navercorp/pinpoint/grpc/client/ChannelFactory.java
  grpc/src/main/java/com/navercorp/pinpoint/grpc/server/ServerFactory.java
  grpc/src/main/java/io/grpc/internal/PinpointDnsNameResolverProvider.java
  grpc/src/test/java/com/navercorp/pinpoint/grpc/ChannelFactoryTest.java
  grpc/src/test/java/com/navercorp/pinpoint/grpc/CountdownStreamObserver.java
  profiler/src/main/java/com/navercorp/pinpoint/profiler/sender/grpc/GrpcDataSender.java
Labels: module:agent

#5306 [#NOISSUE] cleanup permission code.
  web/src/main/java/com/navercorp/pinpoint/web/controller/AlarmController.java
  web/src/main/java/com/navercorp/pinpoint/web/controller/UserGroupController.java
  web/src/main/java/com/navercorp/pinpoint/web/dao/UserGroupDao.java
  web/src/main/java/com/navercorp/pinpoint/web/dao/memory/MemoryUserGroupDao.java
  web/src/main/java/com/navercorp/pinpoint/web/dao/mysql/MysqlUserGroupDao.java
  web/src/main/java/com/navercorp/pinpoint/web/service/UserGroupService.java
  web/src/main/java/com/navercorp/pinpoint/web/service/UserGroupServiceImpl.java
  web/src/main/resources/mapper/UserGroupMapper.xml
Labels: enhancement

#5311 [#NOISSUE] cleanup permission code.
  web/src/main/java/com/navercorp/pinpoint/web/controller/UserGroupController.java
Labels: enhancement, module:web

#5313 [#5052] change key of property
  doc/alarm.md
  web/src/main/resources/batch.properties
Labels: enhancement, module:web

#5330 [#NOISSUE] cleanup permission code.
  web/src/main/java/com/navercorp/pinpoint/web/controller/AdminController.java
Labels: enhancement, module:web

#5341 [#NOISSUE] cleanup code
  web/src/main/java/com/navercorp/pinpoint/web/controller/AlarmController.java
Labels: enhancement, module:web

#5336 [#4558] Refactor grpc
  collector/src/main/java/com/navercorp/pinpoint/collector/receiver/grpc/AgentServer.java
  collector/src/main/java/com/navercorp/pinpoint/collector/receiver/grpc/GrpcServerResponse.java
  collector/src/main/java/com/navercorp/pinpoint/collector/receiver/grpc/PermissionServerTransportFilter.java
  collector/src/main/java/com/navercorp/pinpoint/collector/receiver/grpc/SpanServer.java
  collector/src/main/java/com/navercorp/pinpoint/collector/receiver/grpc/StatServer.java
  collector/src/main/java/com/navercorp/pinpoint/collector/receiver/grpc/service/AgentService.java
  collector/src/main/java/com/navercorp/pinpoint/collector/receiver/grpc/service/KeepAliveService.java
  collector/src/main/java/com/navercorp/pinpoint/collector/receiver/grpc/service/ServerRequestFactory.java
  collector/src/main/java/com/navercorp/pinpoint/collector/receiver/grpc/service/StatService.java
  collector/src/main/java/com/navercorp/pinpoint/collector/receiver/grpc/service/TraceService.java
  grpc/src/main/java/com/navercorp/pinpoint/grpc/AgentHeaderFactory.java
  grpc/src/main/java/com/navercorp/pinpoint/grpc/HeaderFactory.java
  grpc/src/main/java/com/navercorp/pinpoint/grpc/server/DefaultServerTransportFilter.java
  grpc/src/main/java/com/navercorp/pinpoint/grpc/server/DefaultTransportMetadata.java
  grpc/src/main/java/com/navercorp/pinpoint/grpc/server/HeaderPropagationInterceptor.java
  grpc/src/main/java/com/navercorp/pinpoint/grpc/server/MetadataServerTransportFilter.java
  grpc/src/main/java/com/navercorp/pinpoint/grpc/server/ServerContext.java
  grpc/src/main/java/com/navercorp/pinpoint/grpc/server/ServerFactory.java
  grpc/src/main/java/com/navercorp/pinpoint/grpc/server/TransportMetadata.java
  grpc/src/main/java/com/navercorp/pinpoint/grpc/server/TransportMetadataFactory.java
  grpc/src/main/java/com/navercorp/pinpoint/grpc/server/TransportMetadataServerInterceptor.java
  grpc/src/test/java/com/navercorp/pinpoint/grpc/ChannelFactoryTest.java
Labels: module:agent, module:collector

#5335 [#5334] Fix SpanProcessor - NPE
  profiler/src/main/java/com/navercorp/pinpoint/profiler/context/compress/SpanProcessorV1.java
  profiler/src/main/java/com/navercorp/pinpoint/profiler/context/compress/SpanProcessorV2.java
Labels: bug, module:agent

#5365 [#noissue] cleanup unused code
  collector/src/main/java/com/navercorp/pinpoint/collector/cluster/Cluster.java
  collector/src/main/java/com/navercorp/pinpoint/collector/cluster/route/StreamRouteHandler.java
  rpc/src/main/java/com/navercorp/pinpoint/rpc/StreamCreateResponse.java
Labels: cleanup

#5371 [#5370] StringIndexOutOfBoundsException error in BytesUtils.trimRight()
  commons/src/main/java/com/navercorp/pinpoint/common/util/BytesUtils.java
  commons/src/test/java/com/navercorp/pinpoint/common/util/BytesUtilsTest.java
  thrift/src/test/java/com/navercorp/pinpoint/thrift/util/TCompactProtocolByteSizeTest.java
  thrift/src/test/java/com/navercorp/pinpoint/thrift/util/TCompactProtocolTest.java
Labels: bug, module:project-common

#5373 [#5372] StringIndexOutOfBoundsException error in BytesUtils.trimRight()
  commons/src/main/java/com/navercorp/pinpoint/common/util/BytesUtils.java
  commons/src/test/java/com/navercorp/pinpoint/common/util/BytesUtilsTest.java
  thrift/src/test/java/com/navercorp/pinpoint/thrift/util/TCompactProtocolByteSizeTest.java
  thrift/src/test/java/com/navercorp/pinpoint/thrift/util/TCompactProtocolTest.java
Labels: bug, module:project-common

#5379 [#5378] Add redisson plugin
  agent/src/main/resources-local/pinpoint.config
  agent/src/main/resources-release/pinpoint.config
  commons/src/main/java/com/navercorp/pinpoint/common/trace/ServiceType.java
  plugins/assembly/pom.xml
  plugins/bom/pom.xml
  plugins/pom.xml
  plugins/redis-redisson/.gitignore
  plugins/redis-redisson/README.md
  plugins/redis-redisson/pom.xml
  plugins/redis-redisson/src/main/java/com/navercorp/pinpoint/plugin/redis/redisson/RedissonConstants.java
  plugins/redis-redisson/src/main/java/com/navercorp/pinpoint/plugin/redis/redisson/RedissonMethodNameFilters.java
  plugins/redis-redisson/src/main/java/com/navercorp/pinpoint/plugin/redis/redisson/RedissonPlugin.java
  plugins/redis-redisson/src/main/java/com/navercorp/pinpoint/plugin/redis/redisson/RedissonPluginConfig.java
  plugins/redis-redisson/src/main/java/com/navercorp/pinpoint/plugin/redis/redisson/interceptor/CommandAsyncServiceMethodInterceptor.java
  plugins/redis-redisson/src/main/java/com/navercorp/pinpoint/plugin/redis/redisson/interceptor/RedissonMethodInterceptor.java
  plugins/redis-redisson/src/main/resources/META-INF/pinpoint/type-provider.yml
  plugins/redis-redisson/src/main/resources/META-INF/services/com.navercorp.pinpoint.bootstrap.plugin.ProfilerPlugin
Labels: enhancement, module:plugin

#5385 [#5384] Cleanup code related to cluster
  collector/src/main/java/com/navercorp/pinpoint/collector/cluster/route/AbstractRouteHandler.java
  collector/src/main/java/com/navercorp/pinpoint/collector/cluster/route/DefaultRouteHandler.java
  collector/src/main/java/com/navercorp/pinpoint/collector/cluster/route/StreamRouteHandler.java
  grpc/src/main/thrift/Command.thrift
  rpc/src/main/java/com/navercorp/pinpoint/rpc/PinpointSocket.java
  rpc/src/main/java/com/navercorp/pinpoint/rpc/client/DefaultPinpointClient.java
  rpc/src/main/java/com/navercorp/pinpoint/rpc/client/DefaultPinpointClientHandler.java
  rpc/src/main/java/com/navercorp/pinpoint/rpc/client/PinpointClientHandler.java
  rpc/src/main/java/com/navercorp/pinpoint/rpc/client/PinpointClientHandlerContext.java
  rpc/src/main/java/com/navercorp/pinpoint/rpc/server/DefaultPinpointServer.java
  rpc/src/main/java/com/navercorp/pinpoint/rpc/stream/ClientStreamChannelContext.java
  rpc/src/main/java/com/navercorp/pinpoint/rpc/stream/StreamChannelManager.java
  rpc/src/main/java/com/navercorp/pinpoint/rpc/stream/StreamException.java
  rpc/src/test/java/com/navercorp/pinpoint/rpc/stream/StreamChannelManagerTest.java
  rpc/src/test/java/com/navercorp/pinpoint/test/client/TestPinpointClient.java
  thrift/src/main/java/com/navercorp/pinpoint/thrift/dto/command/TRouteResult.java
  thrift/src/main/thrift/Command.thrift
  web/src/main/java/com/navercorp/pinpoint/web/cluster/DefaultPinpointRouteResponse.java
  web/src/main/java/com/navercorp/pinpoint/web/cluster/FailedPinpointRouteResponse.java
  web/src/main/java/com/navercorp/pinpoint/web/cluster/PinpointRouteResponse.java
  web/src/main/java/com/navercorp/pinpoint/web/service/AgentService.java
  web/src/main/java/com/navercorp/pinpoint/web/service/AgentServiceImpl.java
  web/src/main/java/com/navercorp/pinpoint/web/websocket/ActiveThreadCountWorker.java
  web/src/test/java/com/navercorp/pinpoint/web/cluster/PinpointRouteResponseTest.java
Labels: cleanup

#5388 [#5384] Cleanup code related to cluster
  collector/src/main/java/com/navercorp/pinpoint/collector/cluster/ClusterPointRouter.java
  collector/src/main/java/com/navercorp/pinpoint/collector/cluster/route/StreamEvent.java
  collector/src/main/java/com/navercorp/pinpoint/collector/cluster/route/StreamRouteCloseEvent.java
  collector/src/main/java/com/navercorp/pinpoint/collector/cluster/route/StreamRouteHandler.java
  profiler/src/main/java/com/navercorp/pinpoint/profiler/receiver/CommandDispatcher.java
  profiler/src/main/java/com/navercorp/pinpoint/profiler/receiver/ProfilerStreamCommandService.java
  profiler/src/main/java/com/navercorp/pinpoint/profiler/receiver/service/ActiveThreadCountService.java
  profiler/src/test/java/com/navercorp/pinpoint/profiler/receiver/ProfilerCommandServiceLocatorTest.java
  rpc/src/main/java/com/navercorp/pinpoint/rpc/PinpointSocket.java
  rpc/src/main/java/com/navercorp/pinpoint/rpc/client/DefaultPinpointClient.java
  rpc/src/main/java/com/navercorp/pinpoint/rpc/client/DefaultPinpointClientHandler.java
  rpc/src/main/java/com/navercorp/pinpoint/rpc/client/PinpointClient.java
  rpc/src/main/java/com/navercorp/pinpoint/rpc/client/PinpointClientHandler.java
  rpc/src/main/java/com/navercorp/pinpoint/rpc/client/PinpointClientHandlerContext.java
  rpc/src/main/java/com/navercorp/pinpoint/rpc/client/ReconnectStateClientHandler.java
  rpc/src/main/java/com/navercorp/pinpoint/rpc/server/DefaultPinpointServer.java
  rpc/src/main/java/com/navercorp/pinpoint/rpc/stream/ClientStreamChannel.java
  rpc/src/main/java/com/navercorp/pinpoint/rpc/stream/ClientStreamChannelContext.java
  rpc/src/main/java/com/navercorp/pinpoint/rpc/stream/ClientStreamChannelMessageListener.java
  rpc/src/main/java/com/navercorp/pinpoint/rpc/stream/DisabledServerStreamChannelMessageListener.java
  rpc/src/main/java/com/navercorp/pinpoint/rpc/stream/LoggingStreamChannelMessageListener.java
  rpc/src/main/java/com/navercorp/pinpoint/rpc/stream/ServerStreamChannel.java
  rpc/src/main/java/com/navercorp/pinpoint/rpc/stream/ServerStreamChannelContext.java
  rpc/src/main/java/com/navercorp/pinpoint/rpc/stream/ServerStreamChannelMessageListener.java
  rpc/src/main/java/com/navercorp/pinpoint/rpc/stream/StreamChannel.java
  rpc/src/main/java/com/navercorp/pinpoint/rpc/stream/StreamChannelContext.java
  rpc/src/main/java/com/navercorp/pinpoint/rpc/stream/StreamChannelManager.java
  rpc/src/main/java/com/navercorp/pinpoint/rpc/stream/StreamChannelState.java
  rpc/src/test/java/com/navercorp/pinpoint/rpc/RecordedStreamChannelMessageListener.java
  rpc/src/test/java/com/navercorp/pinpoint/rpc/stream/StreamChannelManagerTest.java
  rpc/src/test/java/com/navercorp/pinpoint/rpc/stream/StreamChannelTest.java
  rpc/src/test/java/com/navercorp/pinpoint/test/client/TestPinpointClient.java
  web/src/main/java/com/navercorp/pinpoint/web/service/AgentService.java
  web/src/main/java/com/navercorp/pinpoint/web/service/AgentServiceImpl.java
  web/src/main/java/com/navercorp/pinpoint/web/websocket/ActiveThreadCountWorker.java
Labels: cleanup, module:project-common

#5394 [#5384] Cleanup code related to cluster
  rpc/src/main/java/com/navercorp/pinpoint/rpc/packet/stream/StreamCode.java
  rpc/src/main/java/com/navercorp/pinpoint/rpc/server/DefaultPinpointServer.java
  rpc/src/main/java/com/navercorp/pinpoint/rpc/stream/ClientStreamChannel.java
  rpc/src/main/java/com/navercorp/pinpoint/rpc/stream/ServerStreamChannel.java
  rpc/src/main/java/com/navercorp/pinpoint/rpc/stream/StreamChannel.java
  rpc/src/main/java/com/navercorp/pinpoint/rpc/stream/StreamChannelManager.java
  rpc/src/main/java/com/navercorp/pinpoint/rpc/stream/StreamChannelRepository.java
Labels: cleanup, module:project-common

#5397 [#4558] Refactor profiler.config
  agent/pom.xml
  agent/src/assembly/component/core.xml
  agent/src/main/resources-local/pinpoint.config
  bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/config/DefaultProfilerConfig.java
  bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/config/DefaultThriftTransportConfig.java
  bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/config/GrpcTransportConfig.java
  bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/config/ProfilerConfig.java
  bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/config/ThriftTransportConfig.java
  bootstrap-core/src/test/java/com/navercorp/pinpoint/bootstrap/config/DefaultProfilerConfigTest.java
  profiler/src/main/java/com/navercorp/pinpoint/profiler/context/module/ApplicationContextModuleFactory.java
  profiler/src/main/java/com/navercorp/pinpoint/profiler/context/provider/PinpointClientFactoryProvider.java
  profiler/src/main/java/com/navercorp/pinpoint/profiler/context/provider/SpanDataSenderProvider.java
  profiler/src/main/java/com/navercorp/pinpoint/profiler/context/provider/SpanStatClientFactoryProvider.java
  profiler/src/main/java/com/navercorp/pinpoint/profiler/context/provider/StatDataSenderProvider.java
  profiler/src/main/java/com/navercorp/pinpoint/profiler/context/provider/TcpDataSenderProvider.java
  profiler/src/main/java/com/navercorp/pinpoint/profiler/context/provider/grpc/GrpcDataSenderProvider.java
  profiler/src/main/java/com/navercorp/pinpoint/profiler/context/provider/grpc/GrpcSpanProcessorProvider.java
  profiler/src/main/java/com/navercorp/pinpoint/profiler/receiver/service/ActiveThreadService.java
  tools/src/main/java/com/navercorp/pinpoint/tools/NetworkAvailabilityChecker.java
Labels: module:agent

#5400 [#5399] Jackson update 2.9.7 -> 2.9.8
  pom.xml
Labels: security

#5404 [#5384] Cleanup code related to cluster
  rpc/src/main/java/com/navercorp/pinpoint/rpc/client/DefaultPinpointClient.java
  rpc/src/main/java/com/navercorp/pinpoint/rpc/client/DefaultPinpointClientHandler.java
  rpc/src/main/java/com/navercorp/pinpoint/rpc/client/PinpointClient.java
  rpc/src/main/java/com/navercorp/pinpoint/rpc/client/PinpointClientHandler.java
  rpc/src/main/java/com/navercorp/pinpoint/rpc/client/PinpointClientHandlerContext.java
  rpc/src/main/java/com/navercorp/pinpoint/rpc/client/ReconnectStateClientHandler.java
  rpc/src/main/java/com/navercorp/pinpoint/rpc/stream/ClientStreamChannel.java
  rpc/src/main/java/com/navercorp/pinpoint/rpc/stream/ServerStreamChannel.java
  rpc/src/main/java/com/navercorp/pinpoint/rpc/stream/StreamChannel.java
  rpc/src/main/java/com/navercorp/pinpoint/rpc/stream/StreamChannelManager.java
  rpc/src/main/java/com/navercorp/pinpoint/rpc/stream/StreamException.java
  rpc/src/test/java/com/navercorp/pinpoint/rpc/stream/StreamChannelManagerTest.java
  rpc/src/test/java/com/navercorp/pinpoint/rpc/stream/StreamChannelTest.java
  rpc/src/test/java/com/navercorp/pinpoint/test/client/TestPinpointClient.java
Labels: cleanup, module:project-common

#5407 [#5406] ASM update 7.0->7.1
  pom.xml
Labels: lib-update

#5409 [#5396] remove/extract logic to set userId value
  web/src/main/java/com/navercorp/pinpoint/web/controller/ConfigController.java
  web/src/main/java/com/navercorp/pinpoint/web/controller/UserGroupController.java
  web/src/main/java/com/navercorp/pinpoint/web/service/UserGroupService.java
  web/src/main/java/com/navercorp/pinpoint/web/service/UserGroupServiceImpl.java
  web/src/main/java/com/navercorp/pinpoint/web/service/UserService.java
  web/src/main/java/com/navercorp/pinpoint/web/service/UserServiceImpl.java
Labels: enhancement, module:web

#5424 [#5384] Cleanup code related to cluster
  collector/src/main/java/com/navercorp/pinpoint/collector/cluster/ClusterPointRouter.java
  collector/src/main/java/com/navercorp/pinpoint/collector/cluster/connection/CollectorClusterAcceptor.java
  collector/src/main/java/com/navercorp/pinpoint/collector/cluster/connection/CollectorClusterConnectionFactory.java
  collector/src/main/java/com/navercorp/pinpoint/collector/cluster/connection/CollectorClusterConnectionOption.java
  collector/src/main/java/com/navercorp/pinpoint/collector/cluster/connection/CollectorClusterConnector.java
  collector/src/main/java/com/navercorp/pinpoint/collector/cluster/route/StreamRouteHandler.java
  profiler/src/main/java/com/navercorp/pinpoint/profiler/context/provider/PinpointClientFactoryProvider.java
  profiler/src/main/java/com/navercorp/pinpoint/profiler/receiver/CommandDispatcher.java
  profiler/src/main/java/com/navercorp/pinpoint/profiler/receiver/service/ActiveThreadCountService.java
  rpc/src/main/java/com/navercorp/pinpoint/rpc/PinpointSocket.java
  rpc/src/main/java/com/navercorp/pinpoint/rpc/client/DefaultPinpointClient.java
  rpc/src/main/java/com/navercorp/pinpoint/rpc/client/DefaultPinpointClientFactory.java
  rpc/src/main/java/com/navercorp/pinpoint/rpc/client/DefaultPinpointClientHandler.java
  rpc/src/main/java/com/navercorp/pinpoint/rpc/client/DefaultPinpointClientHandlerFactory.java
  rpc/src/main/java/com/navercorp/pinpoint/rpc/client/PinpointClientFactory.java
  rpc/src/main/java/com/navercorp/pinpoint/rpc/client/PinpointClientHandler.java
  rpc/src/main/java/com/navercorp/pinpoint/rpc/client/PinpointClientHandlerContext.java
  rpc/src/main/java/com/navercorp/pinpoint/rpc/client/ReconnectStateClientHandler.java
  rpc/src/main/java/com/navercorp/pinpoint/rpc/server/DefaultPinpointServer.java
  rpc/src/main/java/com/navercorp/pinpoint/rpc/server/PinpointServerAcceptor.java
  rpc/src/main/java/com/navercorp/pinpoint/rpc/server/PinpointServerConfig.java
  rpc/src/main/java/com/navercorp/pinpoint/rpc/stream/ClientStreamChannel.java
  rpc/src/main/java/com/navercorp/pinpoint/rpc/stream/ClientStreamChannelEventHandler.java
  rpc/src/main/java/com/navercorp/pinpoint/rpc/stream/DisabledServerStreamChannelMessageListener.java
  rpc/src/main/java/com/navercorp/pinpoint/rpc/stream/LoggingStreamChannelMessageListener.java
  rpc/src/main/java/com/navercorp/pinpoint/rpc/stream/LoggingStreamChannelStateChangeEventHandler.java
  rpc/src/main/java/com/navercorp/pinpoint/rpc/stream/ServerStreamChannel.java
  rpc/src/main/java/com/navercorp/pinpoint/rpc/stream/ServerStreamChannelMessageHandler.java
  rpc/src/main/java/com/navercorp/pinpoint/rpc/stream/ServerStreamChannelMessageListener.java
  rpc/src/main/java/com/navercorp/pinpoint/rpc/stream/StreamChannel.java
  rpc/src/main/java/com/navercorp/pinpoint/rpc/stream/StreamChannelManager.java
  rpc/src/main/java/com/navercorp/pinpoint/rpc/stream/StreamChannelMessageHandler.java
  rpc/src/main/java/com/navercorp/pinpoint/rpc/stream/StreamChannelStateChangeEventHandler.java
  rpc/src/test/java/com/navercorp/pinpoint/rpc/RecordedStreamChannelMessageListener.java
  rpc/src/test/java/com/navercorp/pinpoint/rpc/stream/StreamChannelManagerTest.java
  rpc/src/test/java/com/navercorp/pinpoint/rpc/stream/StreamChannelTest.java
  rpc/src/test/java/com/navercorp/pinpoint/test/client/TestPinpointClient.java
  rpc/src/test/java/com/navercorp/pinpoint/test/server/TestPinpointServerAcceptor.java
  web/src/main/java/com/navercorp/pinpoint/web/service/AgentService.java
  web/src/main/java/com/navercorp/pinpoint/web/service/AgentServiceImpl.java
  web/src/main/java/com/navercorp/pinpoint/web/websocket/ActiveThreadCountWorker.java
Labels: cleanup

#5434 [#5384] Cleanup code related to cluster
  collector/src/main/java/com/navercorp/pinpoint/collector/cluster/AgentInfo.java
  collector/src/main/java/com/navercorp/pinpoint/collector/cluster/ClusterPoint.java
  collector/src/main/java/com/navercorp/pinpoint/collector/cluster/ClusterPointRepository.java
  collector/src/main/java/com/navercorp/pinpoint/collector/cluster/PinpointServerClusterPoint.java
  collector/src/main/java/com/navercorp/pinpoint/collector/cluster/TargetClusterPoint.java
  collector/src/main/java/com/navercorp/pinpoint/collector/cluster/route/AbstractRouteHandler.java
  collector/src/main/java/com/navercorp/pinpoint/collector/cluster/zookeeper/PinpointServerRepository.java
  collector/src/main/java/com/navercorp/pinpoint/collector/cluster/zookeeper/ZookeeperJobWorker.java
  collector/src/main/java/com/navercorp/pinpoint/collector/cluster/zookeeper/ZookeeperProfilerClusterManager.java
  collector/src/main/java/com/navercorp/pinpoint/collector/manage/ClusterManager.java
  collector/src/test/java/com/navercorp/pinpoint/collector/cluster/zookeeper/ZookeeperJobWorkerTest.java
Labels: cleanup
