Repository pinpoint-apm/pinpoint, pull requests merged in 2019-02, with the labels that each got.

#5208 [#5130] delete configuration because remove to set sourcefunction parallel value.
  flink/src/main/java/com/navercorp/pinpoint/flink/Bootstrap.java
  flink/src/main/java/com/navercorp/pinpoint/flink/StatStreamingVer2Job.java
  flink/src/main/java/com/navercorp/pinpoint/flink/config/FlinkConfiguration.java
  flink/src/main/resources/pinpoint-flink.properties
Labels: enhancement, module:flink

#5214 [#5156] Restore the previous SpanEvent
  profiler/src/main/java/com/navercorp/pinpoint/profiler/context/AsyncChildTrace.java
  profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DefaultTrace.java
  profiler/src/test/java/com/navercorp/pinpoint/profiler/context/DefaultTraceTest.java
Labels: bug

#5218 [#5217] Fix CallStack max depth
  bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/config/DefaultProfilerConfig.java
  bootstrap-core/src/test/java/com/navercorp/pinpoint/bootstrap/config/DefaultProfilerConfigTest.java
  profiler/src/main/java/com/navercorp/pinpoint/profiler/context/AsyncChildTrace.java
  profiler/src/main/java/com/navercorp/pinpoint/profiler/context/CallStack.java
  profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DefaultCallStack.java
  profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DefaultTrace.java
  profiler/src/main/java/com/navercorp/pinpoint/profiler/context/SpanEventFactory.java
  profiler/src/test/java/com/navercorp/pinpoint/profiler/context/DefaultTraceTest.java
  profiler/src/test/java/com/navercorp/pinpoint/profiler/context/SpanEventElementFactoryTest.java
  profiler/src/test/java/com/navercorp/pinpoint/profiler/context/SpanEventFactoryTest.java
Labels: bug, module:agent

#5222 [#5217] Fix CallStack max depth
  bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/config/DefaultProfilerConfig.java
  bootstrap-core/src/test/java/com/navercorp/pinpoint/bootstrap/config/DefaultProfilerConfigTest.java
  profiler/src/main/java/com/navercorp/pinpoint/profiler/context/AsyncChildTrace.java
  profiler/src/main/java/com/navercorp/pinpoint/profiler/context/CallStack.java
  profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DefaultCallStack.java
  profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DefaultTrace.java
  profiler/src/main/java/com/navercorp/pinpoint/profiler/context/SpanEventFactory.java
  profiler/src/test/java/com/navercorp/pinpoint/profiler/context/DefaultTraceTest.java
  profiler/src/test/java/com/navercorp/pinpoint/profiler/context/SpanEventElementFactoryTest.java
  profiler/src/test/java/com/navercorp/pinpoint/profiler/context/SpanEventFactoryTest.java
Labels: bug, module:agent

#5224 [#5217] Fix CallStackFactory dummy
  profiler/src/main/java/com/navercorp/pinpoint/profiler/context/SpanEventFactory.java
Labels: bug, module:agent

#5228 [#5156] Incorrectly generated localAsyncId
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/SpanFactory.java
  commons-server/src/test/java/com/navercorp/pinpoint/common/server/bo/SpanFactoryTest.java
Labels: bug, module:collector

#5229 [#noissue] Refactor Trace
  bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/context/Trace.java
  profiler/src/main/java/com/navercorp/pinpoint/profiler/context/AsyncChildTrace.java
  profiler/src/main/java/com/navercorp/pinpoint/profiler/context/AsyncTrace.java
  profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DefaultBaseTraceFactory.java
  profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DefaultTrace.java
  profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DisableTrace.java
  profiler/src/main/java/com/navercorp/pinpoint/profiler/context/id/TraceRootSupport.java
Labels: cleanup

#5237 [#5052] provide defaultSmtpMailSender
  doc/alarm.md
  web/pom.xml
  web/src/main/java/com/navercorp/pinpoint/web/alarm/AlarmMailTemplate.java
  web/src/main/java/com/navercorp/pinpoint/web/alarm/AlarmWriter.java
  web/src/main/java/com/navercorp/pinpoint/web/alarm/DefaultAlarmMessageSender.java
  web/src/main/java/com/navercorp/pinpoint/web/alarm/EmptySmsSender.java
  web/src/main/java/com/navercorp/pinpoint/web/alarm/MailSender.java
  web/src/main/java/com/navercorp/pinpoint/web/alarm/SmsSender.java
  web/src/main/java/com/navercorp/pinpoint/web/alarm/SpringSmtpMailSender.java
  web/src/main/java/com/navercorp/pinpoint/web/batch/BatchConfiguration.java
  web/src/main/java/com/navercorp/pinpoint/web/batch/flink/HealthCheckTasklet.java
  web/src/main/resources/batch.properties
  web/src/main/resources/batch/applicationContext-batch.xml
Labels: enhancement, module:web

#5247 [#noissue] Refactor the life cycle of RpcModule
  profiler/src/main/java/com/navercorp/pinpoint/profiler/context/module/DefaultApplicationContext.java
  profiler/src/main/java/com/navercorp/pinpoint/profiler/context/module/ModuleLifeCycle.java
  profiler/src/main/java/com/navercorp/pinpoint/profiler/context/module/RpcModule.java
  profiler/src/main/java/com/navercorp/pinpoint/profiler/context/module/RpcModuleLifeCycle.java
Labels: cleanup

#5249 [#5052] update doc english version.
  doc/alarm.md
Labels: module:web
