Repository pinpoint-apm/pinpoint, pull requests merged in 2023-11, with the labels that each got.

#10451 [#10444] Remove slf4j dependency, Add log4j2 logger to Netty
  agent/pom.xml
  profiler/src/main/java/com/navercorp/pinpoint/profiler/context/module/GrpcModule.java
Labels: cleanup

#10446 [#noissue] Fixed unstable publishing of collector state
  realtime/realtime-collector/src/main/java/com/navercorp/pinpoint/realtime/collector/service/state/CollectorStateUpdateRunnable.java
  redis/src/main/java/com/navercorp/pinpoint/channel/redis/stream/RedisStreamSubChannel.java
  redis/src/main/java/com/navercorp/pinpoint/channel/redis/stream/RedisStreamSubChannelProvider.java
Labels: module:collector

#10460 [#10444] Cleanup
  basic-login/src/main/java/com/navercorp/pinpoint/login/basic/service/JwtService.java
Labels: cleanup

#10466 [#9631] Change format long to String; spanId, exceptionId
  exceptiontrace/exceptiontrace-web/src/main/java/com/navercorp/pinpoint/exceptiontrace/web/controller/ExceptionTraceController.java
  exceptiontrace/exceptiontrace-web/src/main/java/com/navercorp/pinpoint/exceptiontrace/web/dao/ExceptionTraceDao.java
  exceptiontrace/exceptiontrace-web/src/main/java/com/navercorp/pinpoint/exceptiontrace/web/dao/PinotExceptionTraceDao.java
  exceptiontrace/exceptiontrace-web/src/main/java/com/navercorp/pinpoint/exceptiontrace/web/mapper/ExceptionMetaDataEntityMapper.java
  exceptiontrace/exceptiontrace-web/src/main/java/com/navercorp/pinpoint/exceptiontrace/web/service/ExceptionTraceService.java
  exceptiontrace/exceptiontrace-web/src/main/java/com/navercorp/pinpoint/exceptiontrace/web/service/ExceptionTraceServiceImpl.java
  exceptiontrace/exceptiontrace-web/src/main/java/com/navercorp/pinpoint/exceptiontrace/web/view/ExceptionMetaDataView.java
  exceptiontrace/exceptiontrace-web/src/test/java/com/navercorp/pinpoint/exceptiontrace/web/mapper/ExceptionMetaDataEntityMapperTest.java
Labels: module:web, module:metric

#10468 [#10467] Bump spring-kafka from 2.9.11 to 3.0.12
  exceptiontrace/exceptiontrace-collector/src/main/java/com/navercorp/pinpoint/exceptiontrace/collector/dao/PinotExceptionTraceDao.java
  log/log-collector/pom.xml
  metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/collector/dao/pinot/PinotMetricTagDao.java
  metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/collector/dao/pinot/PinotSystemMetricDataTypeDao.java
  metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/collector/dao/pinot/PinotSystemMetricDoubleDao.java
  metric-module/metric/src/test/java/com/navercorp/pinpoint/metric/collector/dao/pinot/PinotSystemMetricDaoTest.java
  pinot/pinot-kafka/src/main/java/com/navercorp/pinpoint/pinot/kafka/util/KafkaCallbacks.java
  pom.xml
  uristat/uristat-collector/src/main/java/com/navercorp/pinpoint/uristat/collector/dao/PinotUriStatDao.java
Labels: dependencies

#10471 [#noissue] update spotbugs-exclude
  spotbugs-exclude.xml
Labels: Continuous Integration

#10469 [#10462] Allow more pattern for version postfix
  bootstraps/bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/agentdir/AgentDirBaseClassPathResolver.java
  bootstraps/bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/agentdir/JarDescription.java
  bootstraps/bootstrap/src/test/java/com/navercorp/pinpoint/bootstrap/agentdir/AgentVersionTest.java
Labels: module:agent

#10475 [#10474] Bump snakeyaml from1.33 to 2.2
  pom.xml
Labels: dependencies

#10482 [#10481] Improved to operate normally according to profile settings
  flink/src/main/java/com/navercorp/pinpoint/flink/Bootstrap.java
Labels: module:flink

#10483 [#noissue] update spotbugs exclude for dto
  spotbugs-exclude.xml
Labels: Continuous Integration

#10484 [#9631] Check length of agentId
  exceptiontrace/exceptiontrace-web/src/main/java/com/navercorp/pinpoint/exceptiontrace/web/util/ExceptionTraceQueryParameter.java
Labels: module:metric

#10485 [#noissue] Migrate to use jdk base 64
  commons/src/main/java/com/navercorp/pinpoint/common/util/AgentUuidUtils.java
  commons/src/test/java/com/navercorp/pinpoint/common/util/AgentUuidUtilsTest.java
Labels: cleanup

#10488 [#10454] update reactor retry when
  agent/src/main/resources/profiles/local/pinpoint.config
  agent/src/main/resources/profiles/release/pinpoint.config
  plugins/reactor/src/main/java/com/navercorp/pinpoint/plugin/reactor/ReactorPluginConfig.java
  plugins/reactor/src/main/java/com/navercorp/pinpoint/plugin/reactor/interceptor/RetryWhenMainSubscriberInterceptor.java
Labels: enhancement, module:plugin

#10491 [#10454] Update resilience4j hook on error
  agent/src/main/resources/profiles/local/pinpoint.config
  agent/src/main/resources/profiles/release/pinpoint.config
  plugins/resilience4j/src/main/java/com/navercorp/pinpoint/plugin/resilience4j/Resilience4JPluginConfig.java
  plugins/resilience4j/src/main/java/com/navercorp/pinpoint/plugin/resilience4j/interceptor/CircuitBreakerSubscriberInterceptor.java
Labels: enhancement, module:plugin

#10494 [#9631] Use canonical name instead of simple name
  profiler/src/main/java/com/navercorp/pinpoint/profiler/context/exception/model/ExceptionWrapper.java
Labels: module:agent, module:metric

#10489 [#10486] Add package name to class loading rule of agent classloader
  agent/src/main/resources/pinpoint-root.config
  bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/classloader/ProfilerLibs.java
  bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/config/DefaultProfilerConfig.java
  bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/config/ProfilerConfig.java
  bootstraps/bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/PinpointStarter.java
Labels: module:agent

#10502 [#9631] Use getName instead of getCanonicalName
  profiler/src/main/java/com/navercorp/pinpoint/profiler/context/exception/model/ExceptionWrapper.java
Labels: module:agent

#10493 [#10492] Update reactor mark error
  agent/src/main/resources/profiles/local/pinpoint.config
  agent/src/main/resources/profiles/release/pinpoint.config
  plugins/reactor-netty/src/main/java/com/navercorp/pinpoint/plugin/reactor/netty/ReactorNettyPluginConfig.java
  plugins/reactor-netty/src/main/java/com/navercorp/pinpoint/plugin/reactor/netty/interceptor/ClientTransportSubscriberInterceptor.java
  plugins/reactor-netty/src/main/java/com/navercorp/pinpoint/plugin/reactor/netty/interceptor/HttpObserverOnUncaughtExceptionInterceptor.java
  plugins/reactor/src/main/java/com/navercorp/pinpoint/plugin/reactor/ReactorPluginConfig.java
  plugins/reactor/src/main/java/com/navercorp/pinpoint/plugin/reactor/interceptor/OnErrorSubscriberInterceptor.java
Labels: enhancement, module:plugin

#10503 [#9631] Change the name of groupBy attribute more user-friendly
  exceptiontrace/exceptiontrace-web/src/main/java/com/navercorp/pinpoint/exceptiontrace/web/util/GroupByAttributes.java
Labels: module:web

#10501 [#noissue] Cleanup
  plugins/mongodb/src/main/java/com/navercorp/pinpoint/plugin/mongo/WriteContext.java
Labels: cleanup

#10505 [#10504] Geometry filter query in the mongodb is not traced
  plugins/mongodb/src/main/java/com/navercorp/pinpoint/plugin/mongo/MongoConstants.java
  plugins/mongodb/src/main/java/com/navercorp/pinpoint/plugin/mongo/MongoPlugin.java
  plugins/mongodb/src/main/java/com/navercorp/pinpoint/plugin/mongo/WriteContext.java
  plugins/mongodb/src/test/java/com/navercorp/pinpoint/plugin/mongo/WriteContextTest.java
Labels: bug

#10508 [#10444] Cleanup slf4j2 dependency
  agent/pom.xml
  bootstraps/bootstrap-java9/src/main/java/com/navercorp/pinpoint/bootstrap/java9/module/ModuleSupport.java
  pom.xml
  profiler-logging/pom.xml
Labels: dependencies

#10509 [#noissue] Cleanup
  bootstraps/bootstrap-java9/src/main/java/com/navercorp/pinpoint/bootstrap/java9/module/ModuleSupport.java
Labels: cleanup

#10512 [#10511] Update compatibility with slf4j 2.x version upgrade
  basic-login/pom.xml
  batch-alarmsender/pom.xml
  batch/pom.xml
  bootstraps/bootstrap-java9-internal/pom.xml
  collector/pom.xml
  commons-hbase/pom.xml
  commons-mybatis/pom.xml
  commons-server-cluster/pom.xml
  commons-server/pom.xml
  datasource/pom.xml
  flink/pom.xml
  grpc/pom.xml
  metric-module/metric/pom.xml
  pinot/pinot-datasource/pom.xml
  plugins-loader/pom.xml
  profiler-optional/profiler-optional-jdk8/pom.xml
  profiler-optional/profiler-optional-jdk9/pom.xml
  rpc/pom.xml
  test/pom.xml
  thrift-datasender/pom.xml
  thrift/pom.xml
  web/pom.xml
  webhook/pom.xml
Labels: dependencies

#10516 [#noissue] Handle -px as stable release version
  commons/src/main/java/com/navercorp/pinpoint/common/util/IdValidateUtils.java
Labels: module:project-common

#10518 [#10517] Fix nodes is null in transaction info request
  web/src/main/java/com/navercorp/pinpoint/web/calltree/span/CallTreeIterator.java
  web/src/main/java/com/navercorp/pinpoint/web/view/TransactionInfoViewModel.java
  web/src/test/java/com/navercorp/pinpoint/web/calltree/span/CallTreeIteratorTest.java
Labels: bug, module:web

#10519 [#noissue] fix plugins-it failsafe failure ignore
  pom.xml
Labels: Continuous Integration

#10521 [#noissue] fix plugin-it failure ignore
  plugins-it/activemq-it/activemq-5-15-it/pom.xml
  plugins-it/activemq-it/activemq-5-17-it/pom.xml
  plugins-it/cassandra-it/cassandra-2-it/pom.xml
  plugins-it/cassandra-it/cassandra-4-it/pom.xml
  plugins-it/cxf-it/cxf-3-0-it/pom.xml
  plugins-it/cxf-it/cxf-3-6-it/pom.xml
  plugins-it/druid-it/pom.xml
  plugins-it/dubbo-it/pom.xml
  plugins-it/elasticsearch-it/elasticsearch-6-it/pom.xml
  plugins-it/elasticsearch-it/elasticsearch-7-16-it/pom.xml
  plugins-it/fastjson-it/pom.xml
  plugins-it/google-grpc-it/google-grpc-1-42-it/pom.xml
  plugins-it/google-grpc-it/google-grpc-1-8-it/pom.xml
  plugins-it/google-httpclient-it/pom.xml
  plugins-it/gson-it/pom.xml
  plugins-it/hbase-it/pom.xml
  plugins-it/hikaricp-it/hikaricp-4-it/pom.xml
  plugins-it/hikaricp-it/hikaricp-5-it/pom.xml
  plugins-it/httpclient-it/httpclient-3-it/pom.xml
  plugins-it/httpclient-it/httpclient-4-it/pom.xml
  plugins-it/hystrix-it/pom.xml
  plugins-it/ibatis-it/pom.xml
  plugins-it/informix-jdbc-it/pom.xml
  plugins-it/jackson-it/pom.xml
  plugins-it/jdk-http-it/pom.xml
  plugins-it/json-lib-it/pom.xml
  plugins-it/jtds-it/pom.xml
  plugins-it/kafka-it/kafka-2-it/pom.xml
  plugins-it/kafka-it/kafka-3-it/pom.xml
  plugins-it/kotlin-coroutines-it/pom.xml
  plugins-it/lambda-it/pom.xml
  plugins-it/log4j-it/pom.xml
  plugins-it/log4j2-it/pom.xml
  plugins-it/logback-it/pom.xml
  plugins-it/mariadb-jdbc-it/pom.xml
  plugins-it/mongodb-it/mongodb-3-it/pom.xml
  plugins-it/mongodb-it/mongodb-4-it/pom.xml
  plugins-it/mssql-jdbc-it/pom.xml
  plugins-it/mybatis-it/pom.xml
  plugins-it/mysql-jdbc-driver-plugin-it/pom.xml
  plugins-it/netty-it/pom.xml
  plugins-it/ning-asyncclient-it/pom.xml
  plugins-it/okhttp-it/pom.xml
  plugins-it/oracledb-it/oracledb-11-it/pom.xml
  plugins-it/oracledb-it/oracledb-19-it/pom.xml
  plugins-it/paho-mqtt-it/pom.xml
  plugins-it/rabbitmq-it/pom.xml
  plugins-it/redis-lettuce-it/pom.xml
  plugins-it/rxjava-it/pom.xml
  plugins-it/spring-data-r2dbc-it/pom.xml
  plugins-it/spring-it/spring-3-it/pom.xml
  plugins-it/spring-it/spring-6-it/pom.xml
  plugins-it/thrift-it/thrift-0-10-it/pom.xml
  plugins-it/thrift-it/thrift-0-14-it/pom.xml
  test/src/main/java/com/navercorp/pinpoint/test/plugin/junit5/engine/PluginTestEngine.java
Labels: Continuous Integration

#10499 [#10496] reconnect on unexpected error
  profiler/src/main/java/com/navercorp/pinpoint/profiler/sender/grpc/DefaultStreamEventListener.java
  profiler/src/main/java/com/navercorp/pinpoint/profiler/sender/grpc/SpanGrpcDataSender.java
  profiler/src/main/java/com/navercorp/pinpoint/profiler/sender/grpc/StatGrpcDataSender.java
  profiler/src/main/java/com/navercorp/pinpoint/profiler/sender/grpc/stream/DefaultStreamTask.java
Labels: module:agent

#10522 [#9631] Add tenantId for better performance
  exceptiontrace/exceptiontrace-collector/src/main/java/com/navercorp/pinpoint/exceptiontrace/collector/dao/PinotExceptionTraceDao.java
  exceptiontrace/exceptiontrace-collector/src/main/java/com/navercorp/pinpoint/exceptiontrace/collector/entity/ExceptionMetaDataEntity.java
  exceptiontrace/exceptiontrace-collector/src/main/java/com/navercorp/pinpoint/exceptiontrace/collector/service/PinotExceptionTraceService.java
  exceptiontrace/exceptiontrace-collector/src/test/java/com/navercorp/pinpoint/exceptiontrace/collector/mapper/ExceptionMetaDataMapperTest.java
  exceptiontrace/exceptiontrace-common/src/main/java/com/navercorp/pinpoint/exceptiontrace/common/model/ExceptionMetaData.java
  exceptiontrace/exceptiontrace-common/src/main/pinot/pinot-exceptionTrace-offline-table.json
  exceptiontrace/exceptiontrace-common/src/main/pinot/pinot-exceptionTrace-realtime-table.json
  exceptiontrace/exceptiontrace-common/src/main/pinot/pinot-exceptionTrace-schema.json
  exceptiontrace/exceptiontrace-web/src/main/java/com/navercorp/pinpoint/exceptiontrace/web/controller/ExceptionTraceController.java
  exceptiontrace/exceptiontrace-web/src/main/java/com/navercorp/pinpoint/exceptiontrace/web/entity/ExceptionMetaDataEntity.java
  exceptiontrace/exceptiontrace-web/src/main/java/com/navercorp/pinpoint/exceptiontrace/web/util/ExceptionTraceQueryParameter.java
  exceptiontrace/exceptiontrace-web/src/main/resources/exceptiontrace/mapper/ExceptionTraceMapper.xml
Labels: module:collector, module:web, module:metric

#10523 [#noissue] fix plugin-it agent classloader filter
  test/src/main/java/com/navercorp/pinpoint/test/plugin/classloader/PluginAgentTestClassLoader.java
Labels: Continuous Integration

#10526 [#9631] Change annotation name; ExceptionLinkId to ExceptionChainId
  commons/src/main/java/com/navercorp/pinpoint/common/trace/AnnotationKey.java
  profiler/src/main/java/com/navercorp/pinpoint/profiler/context/exception/DefaultExceptionRecordingService.java
  web/src/main/java/com/navercorp/pinpoint/web/vo/callstacks/ExceptionRecord.java
Labels: module:agent, module:web

#10530 [#10529] determine the behavior of individual batch jobs in the properties file.
  batch/src/main/java/com/navercorp/pinpoint/batch/common/BatchJobLauncher.java
  batch/src/main/java/com/navercorp/pinpoint/batch/common/BatchProperties.java
  batch/src/main/resources/applicationContext-batch-schedule.xml
  batch/src/main/resources/batch-root.properties
  batch/src/test/java/com/navercorp/pinpoint/batch/BatchPropertiesTest.java
  datasource/src/main/resources/datasource/jdbc-root.properties
Labels: enhancement, module:batch
