Repository pinpoint-apm/pinpoint, pull requests merged in 2023-07, with the labels that each got.

#10106 [#10081] Added annotative param validations
  web/src/main/java/com/navercorp/pinpoint/web/authorization/controller/ScatterChartController.java
Labels: module:web

#10108 [#10107] Bump maven-clean-plugin from 3.1.0 to 3.3.1
  pom.xml
Labels: dependencies

#10110 [#10109] Bump frontend-maven-plugin from 1.12.0 to 1.13.4
  pom.xml
Labels: dependencies

#10111 [#noissue] Enhanced getting userId from principal
  web/src/main/java/com/navercorp/pinpoint/web/authorization/controller/UserGroupController.java
  web/src/main/java/com/navercorp/pinpoint/web/service/UserServiceImpl.java
  web/src/main/java/com/navercorp/pinpoint/web/util/SecurityContextUtils.java
Labels: module:web

#10115 [#10114] Apply jackson-module-parameter-names
  collector/src/main/resources/applicationContext-collector.xml
  pom.xml
  web/pom.xml
  web/src/main/resources/applicationContext-web.xml
  web/src/test/java/com/navercorp/pinpoint/web/util/JacksonParameterNamesModuleTest.java
  web/src/test/resources/applicationContext-test.xml
Labels: enhancement, dependencies

#10116 [#10114] Remove unnecessary ObjectMapper
  metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/collector/MetricCollectorApp.java
  quickstart/testapp/src/main/java/com/navercorp/pinpoint/testapp/service/remote/HttpRemoteService.java
Labels: cleanup

#10121 [#noissue] Cleanup
  plugins/reactor-netty/src/main/java/com/navercorp/pinpoint/plugin/reactor/netty/interceptor/UriUtils.java
  plugins/weblogic/src/main/java/com/navercorp/pinpoint/plugin/weblogic/ServletRequestImplParameterExtractor.java
  plugins/websphere/src/main/java/com/navercorp/pinpoint/plugin/websphere/IRequestParameterExtractor.java
  profiler-test/src/main/java/com/navercorp/pinpoint/test/MethodDescriptionUtils.java
Labels: cleanup

#10122 [#noissue] Apply ReflectiveOperationException
  bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/classloader/DynamicClassLoaderFactory.java
  bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/classloader/PinpointClassLoaderFactory.java
  bootstraps/bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/ModuleBootLoader.java
  plugins/tomcat/src/main/java/com/navercorp/pinpoint/plugin/tomcat/interceptor/WebappLoaderStartInterceptor.java
  profiler-optional/profiler-optional-jdk8/src/test/java/com/navercorp/pinpoint/profiler/instrument/lambda/LambdaFactoryTest.java
  profiler/src/main/java/com/navercorp/pinpoint/profiler/context/javamodule/JavaModuleFactoryFinder.java
  profiler/src/main/java/com/navercorp/pinpoint/profiler/context/module/DefaultApplicationContext.java
  profiler/src/main/java/com/navercorp/pinpoint/profiler/context/module/DefaultModuleFactoryResolver.java
  profiler/src/main/java/com/navercorp/pinpoint/profiler/context/provider/ShutdownHookRegisterProvider.java
  profiler/src/main/java/com/navercorp/pinpoint/profiler/context/provider/stat/buffer/BufferMetricProvider.java
  profiler/src/main/java/com/navercorp/pinpoint/profiler/context/provider/stat/cpu/CpuLoadMetricProvider.java
  profiler/src/main/java/com/navercorp/pinpoint/profiler/context/provider/stat/filedescriptor/FileDescriptorMetricProvider.java
  profiler/src/main/java/com/navercorp/pinpoint/profiler/instrument/classloading/DefineClassFactory.java
  profiler/src/main/java/com/navercorp/pinpoint/profiler/instrument/classloading/ReflectionDefineClass.java
  profiler/src/main/java/com/navercorp/pinpoint/profiler/instrument/classloading/URLClassLoaderHandler.java
  profiler/src/main/java/com/navercorp/pinpoint/profiler/instrument/lambda/LambdaTransformBootloader.java
  profiler/src/main/java/com/navercorp/pinpoint/profiler/instrument/transformer/InnerClassLambdaMetafactoryTransformer.java
  profiler/src/main/java/com/navercorp/pinpoint/profiler/objectfactory/AutoBindingObjectFactory.java
  profiler/src/main/java/com/navercorp/pinpoint/profiler/plugin/DynamicTransformCallbackProvider.java
  test/src/main/java/com/navercorp/pinpoint/test/plugin/shared/ReflectionDependencyResolver.java
Labels: cleanup

#10118 [#10117] Unified RestTemplate configuration
  batch/src/main/java/com/navercorp/pinpoint/batch/BatchApp.java
  batch/src/main/resources/applicationContext-batch-common.xml
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/config/RestTemplateConfiguration.java
  web/src/main/java/com/navercorp/pinpoint/web/WebHbaseModule.java
  web/src/main/java/com/navercorp/pinpoint/web/install/InstallModule.java
  web/src/main/resources/applicationContext-web.xml
Labels: configuration

#10130 [#10129] Bump hbase2 client from 2.4.17 to 2.5.5-hadoop3
  pom.xml
Labels: dependencies

#10112 [#10088] Separate webhook module
  batch/pom.xml
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/alram/event/DeleteRuleEvent.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/response/Response.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/response/SuccessResponse.java
  pom.xml
  web/pom.xml
  web/src/main/java/com/navercorp/pinpoint/web/PinpointWebModule.java
  web/src/main/java/com/navercorp/pinpoint/web/WebApp.java
  web/src/main/java/com/navercorp/pinpoint/web/alarm/vo/Rule.java
  web/src/main/java/com/navercorp/pinpoint/web/authorization/controller/AlarmController.java
  web/src/main/java/com/navercorp/pinpoint/web/authorization/controller/UserController.java
  web/src/main/java/com/navercorp/pinpoint/web/authorization/controller/UserGroupController.java
  web/src/main/java/com/navercorp/pinpoint/web/authorization/controller/WebhookAlarmController.java
  web/src/main/java/com/navercorp/pinpoint/web/config/ConfigProperties.java
  web/src/main/java/com/navercorp/pinpoint/web/controller/AgentStatisticsController.java
  web/src/main/java/com/navercorp/pinpoint/web/frontend/export/ConfigPropertiesExporter.java
  web/src/main/java/com/navercorp/pinpoint/web/response/AlarmResponse.java
  web/src/main/java/com/navercorp/pinpoint/web/response/CodeResult.java
  web/src/main/java/com/navercorp/pinpoint/web/response/CreateUserGroupResponse.java
  web/src/main/java/com/navercorp/pinpoint/web/response/Response.java
  web/src/main/java/com/navercorp/pinpoint/web/service/AlarmService.java
  web/src/main/java/com/navercorp/pinpoint/web/service/AlarmServiceImpl.java
  web/src/main/java/com/navercorp/pinpoint/web/webhook/WebhookFacadeModule.java
  web/src/main/java/com/navercorp/pinpoint/web/webhook/export/WebhookPropertiesExporter.java
  web/src/main/java/com/navercorp/pinpoint/web/webhook/facade/WebhookAlarmServiceFacade.java
  web/src/main/java/com/navercorp/pinpoint/web/webhook/facade/WebhookAlarmServiceFacadeImpl.java
  web/src/main/resources/application.yml
  web/src/test/java/com/navercorp/pinpoint/web/response/SuccessResponseTest.java
  webhook/pom.xml
  webhook/src/main/java/com/navercorp/pinpoint/web/webhook/WebhookModule.java
  webhook/src/main/java/com/navercorp/pinpoint/web/webhook/controller/WebhookController.java
  webhook/src/main/java/com/navercorp/pinpoint/web/webhook/controller/WebhookSendInfoController.java
  webhook/src/main/java/com/navercorp/pinpoint/web/webhook/dao/MysqlWebhookDao.java
  webhook/src/main/java/com/navercorp/pinpoint/web/webhook/dao/MysqlWebhookSendInfoDao.java
  webhook/src/main/java/com/navercorp/pinpoint/web/webhook/dao/WebhookDao.java
  webhook/src/main/java/com/navercorp/pinpoint/web/webhook/dao/WebhookSendInfoDao.java
  webhook/src/main/java/com/navercorp/pinpoint/web/webhook/model/Webhook.java
  webhook/src/main/java/com/navercorp/pinpoint/web/webhook/model/WebhookResponse.java
  webhook/src/main/java/com/navercorp/pinpoint/web/webhook/model/WebhookSendInfo.java
  webhook/src/main/java/com/navercorp/pinpoint/web/webhook/model/WebhookSendInfoResponse.java
  webhook/src/main/java/com/navercorp/pinpoint/web/webhook/service/WebhookAlarmService.java
  webhook/src/main/java/com/navercorp/pinpoint/web/webhook/service/WebhookAlarmServiceImpl.java
  webhook/src/main/java/com/navercorp/pinpoint/web/webhook/service/WebhookSendInfoService.java
  webhook/src/main/java/com/navercorp/pinpoint/web/webhook/service/WebhookSendInfoServiceImpl.java
  webhook/src/main/java/com/navercorp/pinpoint/web/webhook/service/WebhookService.java
  webhook/src/main/java/com/navercorp/pinpoint/web/webhook/service/WebhookServiceImpl.java
  webhook/src/test/java/com/navercorp/pinpoint/web/webhook/dao/memory/MemoryWebhookDao.java
  webhook/src/test/java/com/navercorp/pinpoint/web/webhook/dao/memory/MemoryWebhookSendInfoDao.java
  webhook/src/test/java/com/navercorp/pinpoint/web/webhook/service/WebhookSendInfoServiceImplTest.java
  webhook/src/test/java/com/navercorp/pinpoint/web/webhook/service/WebhookServiceImplTest.java
Labels: module:web

#9946 [#9945] new api for server map right panel
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/ApplicationMapWithScatterDataV3.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/FilterMapWrap.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/MapWrap.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/histogram/AgentTimeHistogram.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/histogram/ApplicationTimeHistogram.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/histogram/NodeHistogram.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/link/Link.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/link/LinkHistogramSummary.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/nodes/Node.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/nodes/NodeAgentHistogramList.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/nodes/NodeHistogramSummary.java
  web/src/main/java/com/navercorp/pinpoint/web/authorization/controller/ResponseTimeController.java
  web/src/main/java/com/navercorp/pinpoint/web/controller/FilteredMapController.java
  web/src/main/java/com/navercorp/pinpoint/web/controller/MapController.java
  web/src/main/java/com/navercorp/pinpoint/web/service/FilteredMapService.java
  web/src/main/java/com/navercorp/pinpoint/web/service/FilteredMapServiceImpl.java
  web/src/main/java/com/navercorp/pinpoint/web/view/FilterMapWrapSerializer.java
  web/src/main/java/com/navercorp/pinpoint/web/view/LinkSerializer.java
  web/src/main/java/com/navercorp/pinpoint/web/view/NodeSerializer.java
  web/src/main/java/com/navercorp/pinpoint/web/view/TimeSeries/TimeSeriesValueGroupView.java
  web/src/main/java/com/navercorp/pinpoint/web/view/TimeSeries/TimeSeriesValueView.java
  web/src/main/java/com/navercorp/pinpoint/web/view/TimeSeries/TimeSeriesView.java
  web/src/main/java/com/navercorp/pinpoint/web/view/histogram/AgentHistogramView.java
  web/src/main/java/com/navercorp/pinpoint/web/view/histogram/ApplicationHistogramView.java
  web/src/main/java/com/navercorp/pinpoint/web/view/histogram/HistogramView.java
  web/src/main/java/com/navercorp/pinpoint/web/view/histogram/TimeHistogramChart.java
  web/src/main/java/com/navercorp/pinpoint/web/view/histogram/TimeHistogramChartBuilder.java
  web/src/main/java/com/navercorp/pinpoint/web/view/histogram/TimeHistogramType.java
  web/src/main/java/com/navercorp/pinpoint/web/view/histogram/TimeHistogramValueGroupView.java
  web/src/main/java/com/navercorp/pinpoint/web/view/histogram/TimeHistogramValueView.java
  web/src/main/java/com/navercorp/pinpoint/web/vo/ApplicationPairs.java
  web/src/test/java/com/navercorp/pinpoint/web/view/TimeHistogramChartTest.java
Labels: module:web

#10134 [#10131] End of support for hbase 1.x
  README.md
  commons-hbase/pom.xml
  hbase/hbase-schema-manager/pom.xml
  hbase2-module/hbase2-batch/pom.xml
  hbase2-module/hbase2-collector/pom.xml
  hbase2-module/hbase2-flink/pom.xml
  hbase2-module/hbase2-web/pom.xml
  hbase2-module/pom.xml
  pom.xml
Labels: dependencies

#10133 [#10132] Bump maven-surefire-plugin from 3.1.0 to 3.1.2
  pom.xml
Labels: dependencies

#10146 [#10131] Migrate HBase1 API to HBase2 API
  commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/HBaseAdminTemplate.java
  commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/HbaseAdminOperation.java
  hbase/hbase-schema-manager/src/main/java/com/navercorp/pinpoint/hbase/manager/config/AppConfig.java
  hbase/hbase-schema-manager/src/main/java/com/navercorp/pinpoint/hbase/manager/hbase/ReadOnlyAdminTemplate.java
  hbase/hbase-schema/src/main/java/com/navercorp/pinpoint/hbase/schema/core/HtdHbaseSchemaVerifier.java
  hbase/hbase-schema/src/main/java/com/navercorp/pinpoint/hbase/schema/core/command/CreateTableCommand.java
  hbase/hbase-schema/src/main/java/com/navercorp/pinpoint/hbase/schema/core/command/HbaseSchemaCommandManager.java
  hbase/hbase-schema/src/main/java/com/navercorp/pinpoint/hbase/schema/core/command/ModifyTableCommand.java
  hbase/hbase-schema/src/main/java/com/navercorp/pinpoint/hbase/schema/core/command/TableCommand.java
  hbase/hbase-schema/src/main/java/com/navercorp/pinpoint/hbase/schema/service/HbaseSchemaServiceImpl.java
  hbase/hbase-schema/src/test/java/com/navercorp/pinpoint/hbase/schema/core/HtdHbaseSchemaVerifierTest.java
  hbase/hbase-schema/src/test/java/com/navercorp/pinpoint/hbase/schema/core/command/HbaseSchemaCommandManagerTest.java
  hbase/hbase-schema/src/test/java/com/navercorp/pinpoint/hbase/schema/service/HbaseSchemaServiceImplTest.java
Labels: enhancement

#10153 [#noissue] Change AnnotationBo to immutable object
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/AnnotationBo.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/AnnotationFactory.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/serializer/trace/v2/SpanDecoderV0.java
  commons-server/src/test/java/com/navercorp/pinpoint/common/server/bo/serializer/trace/v2/bitfield/SpanEventBitFieldTest.java
  commons-server/src/test/java/com/navercorp/pinpoint/common/server/util/AnnotationUtilsTest.java
  web/src/main/java/com/navercorp/pinpoint/web/calltree/span/LinkedCallTree.java
  web/src/main/java/com/navercorp/pinpoint/web/calltree/span/MetaSpanCallTreeFactory.java
  web/src/main/java/com/navercorp/pinpoint/web/service/SpanServiceImpl.java
  web/src/test/java/com/navercorp/pinpoint/web/filter/LinkFilterTest.java
  web/src/test/java/com/navercorp/pinpoint/web/filter/RpcURLPatternFilterTest.java
  web/src/test/java/com/navercorp/pinpoint/web/mapper/SpanMapperV2Test.java
  web/src/test/java/com/navercorp/pinpoint/web/vo/callstacks/RecordFactoryTest.java
Labels: cleanup

#10156 [#9666] Durable atc for delayed agent list query
  realtime/realtime-web/src/main/java/com/navercorp/pinpoint/web/realtime/RealtimeWebConfig.java
  realtime/realtime-web/src/main/java/com/navercorp/pinpoint/web/realtime/RealtimeWebPropertySources.java
  realtime/realtime-web/src/main/java/com/navercorp/pinpoint/web/realtime/activethread/count/dao/ActiveThreadCountDao.java
  realtime/realtime-web/src/main/java/com/navercorp/pinpoint/web/realtime/activethread/count/dao/ActiveThreadCountFetcherFactory.java
  realtime/realtime-web/src/main/java/com/navercorp/pinpoint/web/realtime/activethread/count/dao/ActiveThreadCountWebDaoConfig.java
  realtime/realtime-web/src/main/java/com/navercorp/pinpoint/web/realtime/activethread/count/dao/CachedFetcherFactory.java
  realtime/realtime-web/src/main/java/com/navercorp/pinpoint/web/realtime/activethread/count/dao/OptimisticFetcher.java
  realtime/realtime-web/src/main/java/com/navercorp/pinpoint/web/realtime/activethread/count/dao/PubSubActiveThreadCountDao.java
  realtime/realtime-web/src/main/java/com/navercorp/pinpoint/web/realtime/activethread/count/service/ActiveThreadCountService.java
  realtime/realtime-web/src/main/java/com/navercorp/pinpoint/web/realtime/activethread/count/service/ActiveThreadCountServiceImpl.java
  realtime/realtime-web/src/main/java/com/navercorp/pinpoint/web/realtime/activethread/count/service/ActiveThreadCountSession.java
  realtime/realtime-web/src/main/java/com/navercorp/pinpoint/web/realtime/activethread/count/service/ActiveThreadCountSessionImpl.java
  realtime/realtime-web/src/main/java/com/navercorp/pinpoint/web/realtime/activethread/count/service/ActiveThreadCountWebServiceConfig.java
  realtime/realtime-web/src/main/java/com/navercorp/pinpoint/web/realtime/activethread/count/service/PeriodicRunner.java
  realtime/realtime-web/src/main/java/com/navercorp/pinpoint/web/realtime/activethread/count/websocket/ActiveThreadCountHandlerImpl.java
  realtime/realtime-web/src/main/java/com/navercorp/pinpoint/web/realtime/activethread/count/websocket/ActiveThreadCountWebSocketConfig.java
  realtime/realtime-web/src/main/java/com/navercorp/pinpoint/web/realtime/activethread/count/websocket/SessionContext.java
  realtime/realtime-web/src/main/java/com/navercorp/pinpoint/web/realtime/activethread/dump/ActiveThreadDumpServiceImpl.java
  realtime/realtime-web/src/main/java/com/navercorp/pinpoint/web/realtime/echo/EchoServiceImpl.java
  realtime/realtime-web/src/main/java/com/navercorp/pinpoint/web/realtime/service/AgentLookupServiceImpl.java
  realtime/realtime-web/src/main/java/com/navercorp/pinpoint/web/realtime/service/RealtimeWebServiceConfig.java
  realtime/realtime-web/src/main/resources/pinpoint-web-realtime.properties
  realtime/realtime-web/src/test/java/com/navercorp/pinpoint/web/realtime/activethread/count/dao/ConstantFetcherTest.java
Labels: module:web

#10155 [#noissue] Remove unnecessary boxing
  bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/util/NumberUtils.java
Labels: cleanup

#10157 [#NOISSUE] cleanup code
  collector/src/main/java/com/navercorp/pinpoint/collector/dao/hbase/stat/DefaultAgentStatDao.java
Labels: enhancement, module:collector

#10158 [#noissue] Cleanup
  collector/src/main/java/com/navercorp/pinpoint/collector/controller/ClusterPointController.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/config/RestTemplateConfiguration.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/util/json/JsonRuntimeException.java
  metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/common/model/mybatis/TagListTypeHandler.java
  realtime/realtime-web/src/main/java/com/navercorp/pinpoint/web/realtime/activethread/count/websocket/ActiveThreadCountHandlerImpl.java
  realtime/realtime-web/src/main/java/com/navercorp/pinpoint/web/realtime/activethread/count/websocket/ActiveThreadCountWebSocketConfig.java
  web/src/main/java/com/navercorp/pinpoint/web/WebSocketConfig.java
  web/src/main/java/com/navercorp/pinpoint/web/websocket/ActiveThreadCountHandler.java
  web/src/main/java/com/navercorp/pinpoint/web/websocket/ActiveThreadCountResponseAggregator.java
  web/src/main/java/com/navercorp/pinpoint/web/websocket/message/PingPongMessage.java
  web/src/main/java/com/navercorp/pinpoint/web/websocket/message/PinpointWebSocketMessageConverter.java
  web/src/test/java/com/navercorp/pinpoint/web/websocket/ActiveThreadCountResponseAggregatorTest.java
  web/src/test/java/com/navercorp/pinpoint/web/websocket/message/PinpointWebSocketMessageConverterTest.java
Labels: cleanup

#10163 [#9631] Turn off exception trace module in release profile
  agent/src/main/resources/profiles/release/pinpoint.config
Labels: module:agent, configuration

#10171 [#noissue] Remove unnecessary tx:annotation-driven
  batch/src/main/resources/applicationContext-batch-dao-config.xml
  metric-module/metric/src/test/resources/pinot/applicationContext-pinot-test.xml
Labels: cleanup

#10174 [#10129] Remove logback dependency of zookeeper
  pom.xml
Labels: cleanup

#10166 [#10165] Use BootLogger to prevent recursive Appender call
  bootstraps/bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/BootLogger.java
  profiler/src/main/java/com/navercorp/pinpoint/profiler/instrument/lambda/LambdaBytecodeLogger.java
Labels: module:agent

#10168 [#10165] Cleanup agent logger configuration
  agent/src/main/resources/log4j2-agent.xml
Labels: module:agent, configuration
