Repository pinpoint-apm/pinpoint, pull requests merged in 2023-02, with the labels that each got.

#9681 [#noissue] Add Intellij configuration directory to gitignore
  .gitignore
Labels: cleanup

#9680 [#noissue] Adding Logger for Kafka Callback
  metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/collector/dao/pinot/PinotMetricTagDao.java
  metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/collector/dao/pinot/PinotSystemMetricDataTypeDao.java
  metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/collector/dao/pinot/PinotSystemMetricDoubleDao.java
  metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/common/util/KafkaCallbacks.java
  metric-module/metric/src/test/java/com/navercorp/pinpoint/metric/collector/dao/pinot/PinotSystemMetricDaoTest.java
  uristat/uristat-collector/src/main/java/com/navercorp/pinpoint/uristat/collector/dao/PinotUriStatDao.java
Labels: module:collector, cleanup, module:metric

#9686 [#noissue] Cleanup
  collector/src/main/java/com/navercorp/pinpoint/collector/service/EmptyAgentUriStatService.java
  uristat/uristat-collector/src/main/java/com/navercorp/pinpoint/uristat/collector/service/PinotAgentUriStatService.java
Labels: cleanup

#9685 [#9684] Add pinpoint-agent-testweb-commons module
  agent-testweb/agent-testweb-commons/pom.xml
  agent-testweb/agent-testweb-commons/src/main/java/com.pinpoint.test.common/view/ApiLinkPage.java
  agent-testweb/agent-testweb-commons/src/main/java/com.pinpoint.test.common/view/HrefTag.java
  agent-testweb/bom/pom.xml
  agent-testweb/mongodb-reactive-plugin-testweb/pom.xml
  agent-testweb/mongodb-reactive-plugin-testweb/src/main/java/com/pinpoint/test/plugin/MongoReactivePluginController.java
  agent-testweb/pom.xml
  agent-testweb/redis-lettuce-plugin-testweb/pom.xml
  agent-testweb/redis-lettuce-plugin-testweb/src/main/java/com/pinpoint/test/plugin/ApiLinkPage.java
  agent-testweb/redis-lettuce-plugin-testweb/src/main/java/com/pinpoint/test/plugin/RedisLettucePluginController.java
  agent-testweb/vertx-3-plugin-testweb/pom.xml
  agent-testweb/vertx-3-plugin-testweb/src/main/java/com/pinpoint/test/plugin/ApiLinkPage.java
  agent-testweb/vertx-3-plugin-testweb/src/main/java/com/pinpoint/test/plugin/Vertx3PluginTestStarter.java
  agent-testweb/vertx-3-plugin-testweb/src/main/java/com/pinpoint/test/plugin/Vertx3VerticalMain.java
  agent-testweb/vertx-4-plugin-testweb/pom.xml
  agent-testweb/vertx-4-plugin-testweb/src/main/java/com/pinpoint/test/plugin/ApiLinkPage.java
  agent-testweb/vertx-4-plugin-testweb/src/main/java/com/pinpoint/test/plugin/Vertx4PluginTestStarter.java
Labels: module:test

#9687 [#noissue] Cleanup
  bootstraps/bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/BootLogger.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/util/ServerBootLogger.java
  profiler-optional/profiler-optional-jdk8/src/test/java/com/navercorp/test/pinpoint/jdk8/interfaces/MethodInterfaceTest.java
  profiler-test/src/main/java/com/navercorp/pinpoint/test/MockApplicationContextFactory.java
  profiler-test/src/main/java/com/navercorp/pinpoint/test/MockApplicationContextModule.java
  profiler-test/src/main/java/com/navercorp/pinpoint/test/OrderedSpanRecorder.java
  profiler-test/src/main/java/com/navercorp/pinpoint/test/PluginApplicationContextModule.java
  profiler/src/main/java/com/navercorp/pinpoint/profiler/instrument/ASMClass.java
  profiler/src/main/java/com/navercorp/pinpoint/profiler/instrument/ASMEngine.java
  profiler/src/main/java/com/navercorp/pinpoint/profiler/monitor/DeadlockMonitorTask.java
  profiler/src/test/java/com/navercorp/pinpoint/profiler/instrument/ASMClassTest.java
  profiler/src/test/java/com/navercorp/pinpoint/profiler/instrument/ASMMethodNodeAdapterTestMain.java
  tools/src/main/java/com/navercorp/pinpoint/tools/network/AbstractNetworkChecker.java
  web/src/main/java/com/navercorp/pinpoint/web/util/ThreadDumpUtils.java
Labels: cleanup

#9692 [#9595] Fix missing close of DisableTrace
  profiler/src/main/java/com/navercorp/pinpoint/profiler/context/AsyncDisableTrace.java
  profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DefaultTrace.java
  profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DisableTrace.java
  profiler/src/main/java/com/navercorp/pinpoint/profiler/context/id/ListenableAsyncState.java
Labels: module:agent

#9698 [#noissue] enhance system metric dataType query
  metric-module/metric/src/main/resources/pinot-web/mapper/pinot/MetricDataTypeMapper.xml
Labels: module:metric

#9700 [#9595] Refactor AsyncContext
  bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/context/AsyncContext.java
  bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/context/AsyncContextUtils.java
  bootstraps/bootstrap-core/src/test/java/com/navercorp/pinpoint/bootstrap/context/AsyncContextUtilsTest.java
  profiler/src/main/java/com/navercorp/pinpoint/profiler/context/AsyncContexts.java
  profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DefaultAsyncContext.java
  profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DefaultAsyncContextFactory.java
  profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DisableAsyncContext.java
  profiler/src/main/java/com/navercorp/pinpoint/profiler/context/StatefulAsyncContext.java
  profiler/src/main/java/com/navercorp/pinpoint/profiler/context/StatefulDisableAsyncContext.java
  profiler/src/test/java/com/navercorp/pinpoint/profiler/context/DefaultAsyncContextTest.java
  profiler/src/test/java/com/navercorp/pinpoint/profiler/context/StatefulAsyncContextTest.java
  profiler/src/test/java/com/navercorp/pinpoint/profiler/instrument/mock/accessor/MockAsyncContext.java
Labels: module:agent

#9704 [#9702] Update reactor-netty plugin
  agent-testweb/spring-webflux-plugin-testweb/pom.xml
  agent-testweb/spring-webflux-plugin-testweb/src/main/java/com/pinpoint/test/plugin/SpringWebfluxPluginController.java
  plugins/reactor-netty/src/main/java/com/navercorp/pinpoint/plugin/reactor/netty/HttpCallContext.java
  plugins/reactor-netty/src/main/java/com/navercorp/pinpoint/plugin/reactor/netty/HttpCallContextAccessor.java
  plugins/reactor-netty/src/main/java/com/navercorp/pinpoint/plugin/reactor/netty/ReactorNettyPlugin.java
  plugins/reactor-netty/src/main/java/com/navercorp/pinpoint/plugin/reactor/netty/interceptor/AbstractHttpServerHandleInterceptor.java
  plugins/reactor-netty/src/main/java/com/navercorp/pinpoint/plugin/reactor/netty/interceptor/ChannelOperationsInterceptor.java
  plugins/reactor-netty/src/main/java/com/navercorp/pinpoint/plugin/reactor/netty/interceptor/HttpIOHandlerObserverConstructorInterceptor.java
  plugins/reactor-netty/src/main/java/com/navercorp/pinpoint/plugin/reactor/netty/interceptor/HttpIOHandlerObserverOnStateChangeInterceptor.java
  plugins/reactor-netty/src/main/java/com/navercorp/pinpoint/plugin/reactor/netty/interceptor/HttpServerHandleHttpServerStateInterceptor.java
  plugins/reactor-netty/src/main/java/com/navercorp/pinpoint/plugin/reactor/netty/interceptor/HttpServerHandleStateInterceptor.java
Labels: enhancement, module:plugin

#9709 [#9595] Clean up async context end-point patterns
  bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/interceptor/AsyncContextSpanEventEndPointInterceptor.java
  plugins/akka-http/src/main/java/com/navercorp/pinpoint/plugin/akka/http/interceptor/AsyncContextSpanEventEndPointInterceptor.java
  plugins/akka-http/src/main/java/com/navercorp/pinpoint/plugin/akka/http/interceptor/RequestContextImplCompleteInterceptor.java
  plugins/akka-http/src/main/java/com/navercorp/pinpoint/plugin/akka/http/interceptor/RequestContextImplFailInterceptor.java
  plugins/akka-http/src/main/java/com/navercorp/pinpoint/plugin/akka/http/interceptor/RequestContextImplRedirectInterceptor.java
  plugins/akka-http/src/test/java/com/navercorp/pinpoint/plugin/akka/http/interceptor/RequestContextImplCompleteInterceptorTest.java
  plugins/akka-http/src/test/java/com/navercorp/pinpoint/plugin/akka/http/interceptor/RequestContextImplFailInterceptorTest.java
  plugins/grpc/src/main/java/com/navercorp/pinpoint/plugin/grpc/interceptor/server/GrpcAsyncContextSpanEventEndPointInterceptor.java
  plugins/grpc/src/main/java/com/navercorp/pinpoint/plugin/grpc/interceptor/server/ServerHalfCloseListenerInterceptor.java
  plugins/grpc/src/main/java/com/navercorp/pinpoint/plugin/grpc/interceptor/server/ServerListenerInterceptor.java
  plugins/netty/src/main/java/com/navercorp/pinpoint/plugin/netty/interceptor/ChannelCloseMethodInterceptor.java
  plugins/rabbitmq/src/main/java/com/navercorp/pinpoint/plugin/rabbitmq/client/interceptor/ConsumerHandleDeliveryInterceptor.java
  plugins/reactor-netty/src/main/java/com/navercorp/pinpoint/plugin/reactor/netty/interceptor/ChannelOperationsInterceptor.java
  plugins/user/src/main/java/com/navercorp/pinpoint/plugin/user/interceptor/MQExternalClientHandlerInterceptor.java
  plugins/vertx/src/main/java/com/navercorp/pinpoint/plugin/vertx/interceptor/AsyncContextSpanEventEndPointInterceptor.java
  plugins/vertx/src/main/java/com/navercorp/pinpoint/plugin/vertx/interceptor/HandleExceptionInterceptor.java
  plugins/vertx/src/main/java/com/navercorp/pinpoint/plugin/vertx/interceptor/HttpServerResponseImplInterceptor.java
Labels: enhancement, module:plugin, module:agent

#9710 [#9967] Cleanup
  plugins/tomcat/src/main/java/com/navercorp/pinpoint/plugin/tomcat/jakarta/TomcatAsyncListenerAdaptor.java
  plugins/tomcat/src/main/java/com/navercorp/pinpoint/plugin/tomcat/jakarta/interceptor/RequestStartAsyncInterceptor.java
  plugins/tomcat/src/main/java/com/navercorp/pinpoint/plugin/tomcat/javax/TomcatAsyncListenerAdaptor.java
  plugins/tomcat/src/main/java/com/navercorp/pinpoint/plugin/tomcat/javax/interceptor/RequestStartAsyncInterceptor.java
Labels: cleanup

#9715 [#9595] Fix an issue where metric values in non sampling state were incorrect
  plugins/tomcat/src/main/java/com/navercorp/pinpoint/plugin/tomcat/jakarta/interceptor/RequestStartAsyncInterceptor.java
  plugins/tomcat/src/main/java/com/navercorp/pinpoint/plugin/tomcat/javax/interceptor/RequestStartAsyncInterceptor.java
  profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DefaultBaseTraceFactory.java
  profiler/src/main/java/com/navercorp/pinpoint/profiler/context/active/ActiveTraceRepository.java
  profiler/src/main/java/com/navercorp/pinpoint/profiler/context/active/DefaultActiveTraceRepository.java
  profiler/src/main/java/com/navercorp/pinpoint/profiler/context/active/EmptyActiveTraceRepository.java
Labels: enhancement, module:agent

#9722 [#9595] Remove close state check
  profiler/src/main/java/com/navercorp/pinpoint/profiler/context/AsyncDefaultTrace.java
  profiler/src/main/java/com/navercorp/pinpoint/profiler/context/AsyncDisableTrace.java
Labels: module:agent

#9725 [#9724] To defend against nullPointerexception when select hostGroupName about system metric function
  metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/web/service/SystemMetricHostInfoServiceImpl.java
Labels: enhancement, module:metric

#9737 [#5649] change partition key of kafka for system metric double table
  metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/collector/dao/pinot/PinotSystemMetricDoubleDao.java
Labels: module:metric
