Repository pinpoint-apm/pinpoint, pull requests merged in 2023-05, with the labels that each got.

#9916 [#9915] Replace SocketUtils in springframework
  collector/src/test/java/com/navercorp/pinpoint/collector/receiver/DataReceiverGroupTest.java
  collector/src/test/java/com/navercorp/pinpoint/collector/receiver/thrift/udp/NettyUdpReceiverTest.java
  collector/src/test/java/com/navercorp/pinpoint/collector/receiver/thrift/udp/UDPReceiverTest.java
  commons-server-cluster/src/test/java/com/navercorp/pinpoint/common/server/cluster/zookeeper/ConnectionTest.java
  commons-server-cluster/src/test/java/com/navercorp/pinpoint/common/server/cluster/zookeeper/CuratorZookeeperClientTest.java
  plugins-it/google-grpc-it/src/test/java/com/navercorp/pinpoint/plugin/grpc/HelloWorldSimpleServer.java
  plugins-it/google-grpc-it/src/test/java/com/navercorp/pinpoint/plugin/grpc/HelloWorldStreamServer.java
  plugins-it/google-grpc-it2/src/test/java/com/navercorp/pinpoint/plugin/grpc/HelloWorldSimpleServer.java
  plugins-it/google-grpc-it2/src/test/java/com/navercorp/pinpoint/plugin/grpc/HelloWorldStreamServer.java
  plugins-it/plugins-it-utils/pom.xml
  plugins-it/plugins-it-utils/src/main/java/com/navercorp/pinpoint/pluginit/utils/SocketUtils.java
  plugins-it/plugins-it-utils/src/main/java/com/navercorp/pinpoint/pluginit/utils/WebServer.java
  plugins-it/plugins-it-utils/src/test/java/com/navercorp/pinpoint/pluginit/utils/SocketUtilsTest.java
  plugins-it/rabbitmq-it/src/test/java/com/navercorp/pinpoint/plugin/rabbitmq/RabbitMQClientITBase.java
  plugins-it/rabbitmq-it/src/test/java/com/navercorp/pinpoint/plugin/rabbitmq/util/RabbitMQTestConstants.java
  web/src/test/java/com/navercorp/pinpoint/web/cluster/ClusterTest.java
Labels: cleanup

#9901 [#9893] Remove unnecessary log4j configurations in collector starter
  metric-module/collector-starter/src/main/resources/profiles/local/log4j2.xml
  metric-module/collector-starter/src/main/resources/profiles/release/log4j2.xml
Labels: module:collector, configuration, module:metric

#9906 [#9905] Fix kafka on call tree view
  commons/src/main/java/com/navercorp/pinpoint/common/trace/ServiceType.java
  commons/src/main/java/com/navercorp/pinpoint/common/trace/ServiceTypeCategory.java
  web/src/main/java/com/navercorp/pinpoint/web/calltree/span/LinkedCallTree.java
  web/src/main/java/com/navercorp/pinpoint/web/calltree/span/SpanAligner.java
  web/src/main/java/com/navercorp/pinpoint/web/mapper/SpanMapperV2.java
Labels: bug, module:web

#9705 [#noissue] Handle ByteString annotation values of protobuf
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/AnnotationFactory.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/grpc/GrpcAnnotationHandler.java
Labels: module:project-common

#9917 [#9918] Support version like patch form
  bootstraps/bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/agentdir/AgentDirBaseClassPathResolver.java
  bootstraps/bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/agentdir/JarDescription.java
  bootstraps/bootstrap/src/test/java/com/navercorp/pinpoint/bootstrap/agentdir/AgentVersionTest.java
Labels: bug, module:agent

#9921 [#9920] Modify binary naming rule of agent-testweb to maven standard
  agent-testweb/cassandra4-plugin-testweb/src/main/resources/application.yml
  agent-testweb/jdk-http-plugin-testweb/pom.xml
  agent-testweb/pom.xml
  agent-testweb/postgresql-plugin-testweb/src/main/resources/application.yml
  agent-testweb/spring-data-r2dbc-plugin-testweb/src/main/resources/application.yml
  pom.xml
Labels: cleanup

#9923 [#noissue] Cleanup testweb
  agent-testweb/agent-proxy-plugin-testweb/pom.xml
  agent-testweb/agentsdk-async-testweb/pom.xml
  agent-testweb/cassandra3-plugin-testweb/pom.xml
  agent-testweb/cassandra4-plugin-testweb/pom.xml
  agent-testweb/dubbo-plugin-testweb/pom.xml
  agent-testweb/elasticsearch-8-plugin-testweb/pom.xml
  agent-testweb/elasticsearch-plugin-testweb/pom.xml
  agent-testweb/httpclient4-plugin-testweb/pom.xml
  agent-testweb/httpclient5-plugin-testweb/pom.xml
  agent-testweb/jdk-http-plugin-testweb/pom.xml
  agent-testweb/kafka-plugin-testweb/pom.xml
  agent-testweb/mongodb-plugin-testweb/pom.xml
  agent-testweb/mongodb-reactive-plugin-testweb/pom.xml
  agent-testweb/paho-mqtt-plugin-testweb/pom.xml
  agent-testweb/pom.xml
  agent-testweb/postgresql-plugin-testweb/pom.xml
  agent-testweb/reactor-netty-plugin-testweb/pom.xml
  agent-testweb/reactor-plugin-testweb/pom.xml
  agent-testweb/redis-lettuce-plugin-testweb/pom.xml
  agent-testweb/rocketmq-plugin-testweb/rocketmq-original/pom.xml
  agent-testweb/spring-cloud-gateway-plugin-testweb/pom.xml
  agent-testweb/spring-data-r2dbc-plugin-testweb/pom.xml
  agent-testweb/spring-webflux-plugin-testweb/pom.xml
  agent-testweb/thread-plugin-testweb/pom.xml
  agent-testweb/thrift-plugin-testweb/pom.xml
Labels: cleanup

#9926 [#noissue] Add pinpoint-spring-boot3-testweb
  agent-testweb/pom.xml
  agent-testweb/spring-boot3-testweb/pom.xml
  agent-testweb/spring-boot3-testweb/src/main/java/com/pinpoint/test/springboot3/SpringBoot3DemoApplication.java
  agent-testweb/spring-boot3-testweb/src/main/java/com/pinpoint/test/springboot3/controller/TestController.java
  agent-testweb/spring-boot3-testweb/src/main/java/com/pinpoint/test/springboot3/service/TestService.java
  agent-testweb/spring-boot3-testweb/src/main/resources/application.yml
  pom.xml
Labels: module:test

#9927 [#noissue] Add spring-boot3-webflux-plugin-testweb
  agent-testweb/pom.xml
  agent-testweb/spring-boot3-webflux-plugin-testweb/pom.xml
  agent-testweb/spring-boot3-webflux-plugin-testweb/src/main/java/com/pinpoint/test/plugin/SpringBoot3WebfluxPluginController.java
  agent-testweb/spring-boot3-webflux-plugin-testweb/src/main/java/com/pinpoint/test/plugin/SpringBoot3WebfluxPluginTestStarter.java
  agent-testweb/spring-boot3-webflux-plugin-testweb/src/main/resources/application.yml
  agent-testweb/spring-boot3-webflux-plugin-testweb/src/main/resources/static/logo.png
  pom.xml
Labels: module:test

#9934 [#noissue] Added function names, idleness in flink
  flink/src/main/java/com/navercorp/pinpoint/flink/StatStreamingVer2Job.java
Labels: module:flink

#9924 [#noissue] Remove color tag in log4j2 logging format except local
  collector/src/main/resources/log4j2-spring.xml
  web/src/main/resources/log4j2-spring.xml
Labels: module:collector, module:web, configuration

#9935 [#9893] Merge agent log4j2 profiles
  agent/src/main/resources/log4j2.xml
  agent/src/main/resources/profiles/local/log4j2.xml
  profiler-logging/src/main/java/com/navercorp/pinpoint/profiler/logging/Log4j2LoggingSystem.java
Labels: module:agent, configuration

#9933 [#9922] Enhanced resource reclaimation in hbase2 client
  commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/ConnectionFactoryBean.java
  commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/HBaseAsyncOperationFactory.java
  commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/HadoopResourceCleanerRegistry.java
  commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/TableMultiplexerAsyncOperation.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/stat/join/JoinApplicationStatBo.java
  flink/src/main/java/com/navercorp/pinpoint/flink/Bootstrap.java
  flink/src/main/java/com/navercorp/pinpoint/flink/cluster/FlinkServerRegister.java
  flink/src/main/java/com/navercorp/pinpoint/flink/receiver/TcpSourceFunction.java
  hbase2-module/hbase2-flink/pom.xml
  hbase2-module/hbase2-flink/src/main/java/com/navercorp/pinpoint/flink/hbase/Hbase2HadoopResourceCleanerRegistry.java
  hbase2-module/hbase2-flink/src/main/java/org/apache/hbase/thirdparty/io/netty/buffer/PoolArenaCleaner.java
  hbase2-module/hbase2-flink/src/main/resources/applicationContext-flink-extend.xml
  hbase2-module/pom.xml
Labels: module:flink

#9939 [#9922] Separated flink-clean.xml
  flink/src/main/resources/applicationContext-flink-clean.xml
  flink/src/main/resources/applicationContext-flink.xml
  hbase2-module/hbase2-flink/src/main/resources/applicationContext-flink-clean.xml
  hbase2-module/hbase2-flink/src/main/resources/applicationContext-flink-extend.xml
Labels: module:flink

#9937 [#noissue] Removed hard-coded default agent profile
  bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/config/DefaultProfilerConfig.java
  bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/config/Profiles.java
  bootstraps/bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/config/ProfilePropertyLoader.java
  bootstraps/bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/config/SimplePropertyLoader.java
  tools/src/main/java/com/navercorp/pinpoint/tools/NetworkAvailabilityChecker.java
Labels: module:agent

#9949 [#9666] Add redis pubsub atc,atd,echo
  redis/src/test/java/com/navercorp/pinpoint/redis/pubsub/RedisReqResTest.java
  web/src/main/java/com/navercorp/pinpoint/web/AuthorizationConfig.java
  web/src/main/java/com/navercorp/pinpoint/web/PinpointWebModule.java
  web/src/main/java/com/navercorp/pinpoint/web/WebServiceConfig.java
Labels: module:web

#9951 [#9950] Bump maven-surefire-plugin from 3.0.0-M7 to 3.1.0
  pom.xml
Labels: dependencies

#9953 [#9952] Bump maven-compiler-plugin from 3.8.1 to 3.11.0
  pom.xml
Labels: dependencies

#9955 [#9893] Change filename log4j2.xml→log4j2-agent.xml
  agent/src/main/resources/log4j2-agent.xml
  agent/src/main/resources/pinpoint-root.config
  agent/src/main/resources/profiles/local/pinpoint.config
  agent/src/main/resources/profiles/release/pinpoint.config
  bootstraps/bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/config/ProfilePropertyLoader.java
  bootstraps/bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/config/SimpleLogConfigResolver.java
  bootstraps/bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/config/SimplePropertyLoader.java
  profiler-logging/src/main/java/com/navercorp/pinpoint/profiler/logging/Log4j2LoggingSystem.java
Labels: module:agent, configuration

#9960 [#9958] fix duplicated active trace
  profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DefaultBaseTraceFactory.java
Labels: bug, module:agent

#9963 [#9962] backport: fix duplicated active trace
  profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DefaultBaseTraceFactory.java
Labels: bug, module:agent

#9965 [#9964] Bump maven-resources-plugin from 3.2.0 to 3.3.1
  pom.xml
Labels: dependencies

#9967 [#9966] Bump maven-enforcer-plugin from 3.0.0 to 3.3.0
  pom.xml
Labels: dependencies

#9969 [#9968] Bump maven-jar-plugin from 3.2.0 to 3.3.0
  pom.xml
Labels: dependencies

#9972 [#9971] Bump jacoco-maven-plugin from 0.8.6 to 0.8.10
  pom.xml
Labels: dependencies

#9974 [#9973] Bump maven-assembly-plugin from 3.3.0 to 3.6.0
  agent/pom.xml
  pom.xml
Labels: dependencies

#9976 [#9893] Align Log4j2 loggingsystem lookup orders
  profiler-logging/src/main/java/com/navercorp/pinpoint/profiler/logging/Log4j2LoggingSystem.java
Labels: module:agent

#9977 [#noissue] Remove isParsed state of RouteResponse
  web/src/main/java/com/navercorp/pinpoint/web/cluster/DefaultPinpointRouteResponse.java
  web/src/main/java/com/navercorp/pinpoint/web/cluster/RouteResponseParser.java
  web/src/main/java/com/navercorp/pinpoint/web/service/AgentServiceImpl.java
  web/src/test/java/com/navercorp/pinpoint/web/cluster/PinpointRouteResponseTest.java
Labels: cleanup

#9978 [#9666] Fixed realtime to maintain valid value
  realtime/realtime-web/src/main/java/com/navercorp/pinpoint/web/realtime/activethread/count/dao/ActiveThreadCountFetcherFactory.java
  realtime/realtime-web/src/main/java/com/navercorp/pinpoint/web/realtime/activethread/count/dao/ActiveThreadCountWebDaoConfig.java
  realtime/realtime-web/src/main/java/com/navercorp/pinpoint/web/realtime/activethread/count/dao/OptimisticFetcher.java
Labels: module:web

#9982 [#9893] Fix test failure due to changed log4j2 lookup filename
  plugins-it/mariadb-jdbc-it/src/test/resources/log4j2-test.xml
Labels: module:plugin, module:test

#9985 [#9932] Fix testcase failure
  commons-profiler/src/main/java/com/navercorp/pinpoint/common/profiler/message/DefaultResultResponse.java
  profiler-test/src/main/java/com/navercorp/pinpoint/test/classloader/TestClassList.java
  profiler-test/src/main/java/com/navercorp/pinpoint/test/rpc/MockMessageConverter.java
  profiler-test/src/main/java/com/navercorp/pinpoint/test/rpc/MockRpcModule.java
  profiler/src/main/java/com/navercorp/pinpoint/profiler/context/grpc/GrpcMessageToResultConverter.java
Labels: cleanup

#9994 [#9993] Bump maven-dependency-plugin from 3.4.0 to 3.6.0
  pom.xml
Labels: dependencies

#9992 [#9991] Bump build-helper-maven-plugin from 3.2.0 to 3.4.0
  pom.xml
  profiler-optional/profiler-optional-parent/pom.xml
Labels: dependencies

#9995 [#NOISSUE] fix test fail
  metric-module/metric/src/test/java/com/navercorp/pinpoint/metric/collector/dao/pinot/PinotSystemMetricDaoTest.java
Labels: enhancement, module:web, module:metric

#9996 [#9932] Remove thrift dependency of Tools module
  tools/pom.xml
  tools/src/main/java/com/navercorp/pinpoint/tools/NetworkAvailabilityChecker.java
  tools/src/main/java/com/navercorp/pinpoint/tools/network/AbstractNetworkChecker.java
  tools/src/main/java/com/navercorp/pinpoint/tools/network/TCPChecker.java
  tools/src/main/java/com/navercorp/pinpoint/tools/network/UDPChecker.java
  tools/src/main/java/com/navercorp/pinpoint/tools/network/grpc/GrpcTransportConfig.java
  tools/src/main/java/com/navercorp/pinpoint/tools/network/thrift/ThriftTransportConfig.java
  tools/src/main/java/com/navercorp/pinpoint/tools/utils/IOUtils.java
  tools/src/main/java/com/navercorp/pinpoint/tools/utils/Logger.java
  tools/src/main/java/com/navercorp/pinpoint/tools/utils/NumberUtils.java
  tools/src/main/java/com/navercorp/pinpoint/tools/utils/PropertyResolver.java
  tools/src/test/java/com/navercorp/pinpoint/tools/utils/PropertyResolverTest.java
Labels: cleanup

#9997 [#9989] Update maven-shade-plugin configuration
  pom.xml
Labels: configuration

#9986 [#9932] Rename directory name for thrift-datasender
  pom.xml
  thrift-datasender/pom.xml
  thrift-datasender/src/main/java/com/navercorp/pinpoint/thrift/sender/ByteMessage.java
  thrift-datasender/src/main/java/com/navercorp/pinpoint/thrift/sender/MaxBytesLengthPredicate.java
  thrift-datasender/src/main/java/com/navercorp/pinpoint/thrift/sender/MessageSerializer.java
  thrift-datasender/src/main/java/com/navercorp/pinpoint/thrift/sender/PortUnreachableHandler.java
  thrift-datasender/src/main/java/com/navercorp/pinpoint/thrift/sender/ReconnectEventListenerRegistry.java
  thrift-datasender/src/main/java/com/navercorp/pinpoint/thrift/sender/RefreshStrategy.java
  thrift-datasender/src/main/java/com/navercorp/pinpoint/thrift/sender/RequestMessage.java
  thrift-datasender/src/main/java/com/navercorp/pinpoint/thrift/sender/RequestMessageFactory.java
  thrift-datasender/src/main/java/com/navercorp/pinpoint/thrift/sender/RetryMessage.java
  thrift-datasender/src/main/java/com/navercorp/pinpoint/thrift/sender/RetryQueue.java
  thrift-datasender/src/main/java/com/navercorp/pinpoint/thrift/sender/RetryRequestMessage.java
  thrift-datasender/src/main/java/com/navercorp/pinpoint/thrift/sender/TcpDataSender.java
  thrift-datasender/src/main/java/com/navercorp/pinpoint/thrift/sender/ThriftMessageSerializer.java
  thrift-datasender/src/main/java/com/navercorp/pinpoint/thrift/sender/ThriftUdpMessageSerializer.java
  thrift-datasender/src/main/java/com/navercorp/pinpoint/thrift/sender/UdpDataSender.java
  thrift-datasender/src/main/java/com/navercorp/pinpoint/thrift/sender/UdpDataSenderFactory.java
  thrift-datasender/src/main/java/com/navercorp/pinpoint/thrift/sender/UdpSocketAddressProvider.java
  thrift-datasender/src/main/java/com/navercorp/pinpoint/thrift/sender/WriteFailFutureListener.java
  thrift-datasender/src/main/java/com/navercorp/pinpoint/thrift/sender/message/CommandGrpcToThriftMessageConverter.java
  thrift-datasender/src/main/java/com/navercorp/pinpoint/thrift/sender/message/ThreadDumpThriftMessageConverter.java
  thrift-datasender/src/main/java/com/navercorp/pinpoint/thrift/sender/message/ThreadStateThriftMessageConverter.java
  thrift-datasender/src/test/java/com/navercorp/pinpoint/thrift/sender/RefreshStrategyTest.java
  thrift-datasender/src/test/java/com/navercorp/pinpoint/thrift/sender/RetryMessageTest.java
  thrift-datasender/src/test/java/com/navercorp/pinpoint/thrift/sender/RetryQueueTest.java
  thrift-datasender/src/test/java/com/navercorp/pinpoint/thrift/sender/TcpDataSenderReconnectTest.java
  thrift-datasender/src/test/java/com/navercorp/pinpoint/thrift/sender/TcpDataSenderTest.java
  thrift-datasender/src/test/java/com/navercorp/pinpoint/thrift/sender/UdpDataSenderTest.java
  thrift-datasender/src/test/java/com/navercorp/pinpoint/thrift/sender/UdpSocketTest.java
  thrift-datasender/src/test/resources/log4j2-test.xml
Labels: cleanup

#9998 [#noissue] Cleanup
  plugins/redis-lettuce/src/main/java/com/navercorp/pinpoint/plugin/redis/lettuce/interceptor/AttachEndPointInterceptor.java
  plugins/redis-lettuce/src/main/java/com/navercorp/pinpoint/plugin/redis/lettuce/interceptor/RedisClientConstructorInterceptor.java
  plugins/redis-lettuce/src/main/java/com/navercorp/pinpoint/plugin/redis/lettuce/interceptor/RedisClusterClientConstructorInterceptor.java
  plugins/redis-lettuce/src/main/java/com/navercorp/pinpoint/plugin/redis/lettuce/interceptor/RunnableNewInstanceInterceptor.java
  plugins/redis/src/main/java/com/navercorp/pinpoint/plugin/redis/jedis/interceptor/AttachEndPointInterceptor.java
Labels: cleanup

#9999 [#noissue] Cleanup
  commons/src/main/java/com/navercorp/pinpoint/common/util/ArrayArgumentUtils.java
  commons/src/test/java/com/navercorp/pinpoint/common/util/ArrayArgumentUtilsTest.java
Labels: cleanup

#9980 [#9979] add pinot offline table ingestionConfig
  metric-module/metric/src/main/pinot/pinot-double-offline-table.json
  uristat/uristat-common/src/main/pinot/pinot-uriStat-offline-table.json
Labels: module:metric

#10004 [#10003] backport: add pinot offline table ingestionConfig
  metric-module/metric/src/main/pinot/pinot-double-offline-table.json
  uristat/uristat-common/src/main/pinot/pinot-uriStat-offline-table.json
Labels: bug, module:metric
