Repository pinpoint-apm/pinpoint, pull requests merged in 2023-08, with the labels that each got.

#10178 [#noissue] Optimize memory usage
  web/src/main/java/com/navercorp/pinpoint/web/mapper/ApiMetaDataMapper.java
  web/src/main/java/com/navercorp/pinpoint/web/mapper/MapStatisticsCalleeMapper.java
  web/src/main/java/com/navercorp/pinpoint/web/mapper/MapStatisticsCallerMapper.java
  web/src/main/java/com/navercorp/pinpoint/web/mapper/ResponseTimeMapper.java
  web/src/main/java/com/navercorp/pinpoint/web/mapper/SqlMetaDataMapper.java
  web/src/main/java/com/navercorp/pinpoint/web/mapper/StringMetaDataMapper.java
Labels: module:web

#10183 [#9597] change reponse spec. Improved data parsing logic during dao calls
  inspector-module/inspector-web/src/main/java/com/navercorp/pinpoint/inspector/web/dao/pinot/MultiValueTagTypeHandler.java
  inspector-module/inspector-web/src/main/java/com/navercorp/pinpoint/inspector/web/view/InspectorMetricView.java
  inspector-module/inspector-web/src/main/resources/inspector/web/inspector-definition.yml
  metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/web/util/TagUtils.java
Labels: module:web

#10185 [#9948] Refactor SqlMetaDataService
  bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/context/TraceContext.java
  profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DefaultTraceContext.java
  profiler/src/main/java/com/navercorp/pinpoint/profiler/context/provider/metadata/SqlMetadataServiceProvider.java
  profiler/src/main/java/com/navercorp/pinpoint/profiler/context/recorder/WrappedSpanEventRecorder.java
  profiler/src/main/java/com/navercorp/pinpoint/profiler/metadata/CachingSqlNormalizer.java
  profiler/src/main/java/com/navercorp/pinpoint/profiler/metadata/DefaultCachingSqlNormalizer.java
  profiler/src/main/java/com/navercorp/pinpoint/profiler/metadata/DefaultSqlMetaDataService.java
  profiler/src/main/java/com/navercorp/pinpoint/profiler/metadata/SimpleCachingSqlNormalizer.java
  profiler/src/main/java/com/navercorp/pinpoint/profiler/metadata/SqlCacheService.java
  profiler/src/main/java/com/navercorp/pinpoint/profiler/metadata/SqlMetaDataService.java
  profiler/src/main/java/com/navercorp/pinpoint/profiler/metadata/SqlUidMetaDataService.java
  profiler/src/main/java/com/navercorp/pinpoint/profiler/metadata/UidCachingSqlNormalizer.java
  profiler/src/test/java/com/navercorp/pinpoint/profiler/cache/SimpleCacheTest.java
  profiler/src/test/java/com/navercorp/pinpoint/profiler/metadata/SimpleCachingSqlNormalizerTest.java
  profiler/src/test/java/com/navercorp/pinpoint/profiler/metadata/SqlCacheServiceTest.java
  profiler/src/test/java/com/navercorp/pinpoint/profiler/metadata/SqlUidMetaDataServiceTest.java
Labels: module:agent

#10180 [#9666] Moved realtime module from starter into basic
  collector/pom.xml
  collector/src/main/java/com/navercorp/pinpoint/collector/CollectorApp.java
  collector/src/main/java/com/navercorp/pinpoint/collector/PinpointCollectorModule.java
  collector/src/main/java/com/navercorp/pinpoint/collector/cluster/AgentConnectionImpl.java
  collector/src/main/java/com/navercorp/pinpoint/collector/cluster/AgentConnectionRepositoryImpl.java
  collector/src/main/java/com/navercorp/pinpoint/collector/cluster/RealtimeCollectorModuleAdaptorConfig.java
  commons/src/main/java/com/navercorp/pinpoint/common/task/TimerTaskDecorator.java
  commons/src/main/java/com/navercorp/pinpoint/common/task/TimerTaskDecoratorFactory.java
  metric-module/collector-starter/pom.xml
  metric-module/collector-starter/src/main/java/com/navercorp/pinpoint/collector/starter/multi/application/MultiApplication.java
  metric-module/web-starter/pom.xml
  metric-module/web-starter/src/main/java/com/navercorp/pinpoint/web/starter/multi/MetricAndWebApp.java
  realtime/realtime-collector/pom.xml
  realtime/realtime-collector/src/main/java/com/navercorp/pinpoint/realtime/collector/RealtimeCollectorModule.java
  realtime/realtime-collector/src/main/java/com/navercorp/pinpoint/realtime/collector/service/AgentConnection.java
  realtime/realtime-collector/src/main/java/com/navercorp/pinpoint/realtime/collector/service/AgentConnectionRepository.java
  realtime/realtime-collector/src/main/java/com/navercorp/pinpoint/realtime/collector/service/ClusterAgentCommandService.java
  realtime/realtime-collector/src/main/java/com/navercorp/pinpoint/realtime/collector/service/RealtimeCollectorServiceConfig.java
  realtime/realtime-web/pom.xml
  realtime/realtime-web/src/main/java/com/navercorp/pinpoint/web/realtime/RealtimeWebModule.java
  realtime/realtime-web/src/main/java/com/navercorp/pinpoint/web/realtime/activethread/count/WebActiveThreadCountConfig.java
  realtime/realtime-web/src/main/java/com/navercorp/pinpoint/web/realtime/activethread/count/service/ActiveThreadCountServiceImpl.java
  realtime/realtime-web/src/main/java/com/navercorp/pinpoint/web/realtime/activethread/count/service/ActiveThreadCountSessionImpl.java
  realtime/realtime-web/src/main/java/com/navercorp/pinpoint/web/realtime/activethread/count/service/ActiveThreadCountWebServiceConfig.java
  realtime/realtime-web/src/main/java/com/navercorp/pinpoint/web/realtime/activethread/count/websocket/ActiveThreadCountWebSocketConfig.java
  realtime/realtime-web/src/main/java/com/navercorp/pinpoint/web/realtime/activethread/count/websocket/RedisActiveThreadCountWebSocketHandler.java
  realtime/realtime-web/src/main/java/com/navercorp/pinpoint/web/realtime/activethread/dump/RedisActiveThreadDumpService.java
  realtime/realtime-web/src/main/java/com/navercorp/pinpoint/web/realtime/activethread/dump/WebActiveThreadDumpConfig.java
  realtime/realtime-web/src/main/java/com/navercorp/pinpoint/web/realtime/echo/RedisEchoService.java
  realtime/realtime-web/src/main/java/com/navercorp/pinpoint/web/realtime/echo/WebEchoConfig.java
  realtime/realtime-web/src/main/java/com/navercorp/pinpoint/web/realtime/service/RealtimeWebServiceConfig.java
  web/pom.xml
  web/src/main/java/com/navercorp/pinpoint/web/PinpointWebModule.java
  web/src/main/java/com/navercorp/pinpoint/web/WebApp.java
  web/src/main/java/com/navercorp/pinpoint/web/WebSocketConfig.java
  web/src/main/java/com/navercorp/pinpoint/web/realtime/AgentLookupServiceImpl.java
  web/src/main/java/com/navercorp/pinpoint/web/realtime/RedisActiveThreadCountHandlerAdaptor.java
  web/src/main/java/com/navercorp/pinpoint/web/realtime/RedisActiveThreadDumpServiceAdaptor.java
  web/src/main/java/com/navercorp/pinpoint/web/realtime/RedisEchoServiceAdaptor.java
  web/src/main/java/com/navercorp/pinpoint/web/realtime/RedisRealtimeWebModuleAdaptorConfig.java
  web/src/main/java/com/navercorp/pinpoint/web/websocket/ActiveThreadCountHandler.java
  web/src/main/java/com/navercorp/pinpoint/web/websocket/ActiveThreadCountResponseAggregator.java
  web/src/main/java/com/navercorp/pinpoint/web/websocket/PinpointWebSocketTimerTaskDecoratorFactory.java
  web/src/main/java/com/navercorp/pinpoint/web/websocket/WorkerActiveManager.java
  web/src/test/java/com/navercorp/pinpoint/web/websocket/ActiveThreadCountResponseAggregatorTest.java
  web/src/test/java/com/navercorp/pinpoint/web/websocket/PinpointWebSocketTimerTaskDecoratorTest.java
Labels: module:collector, module:web

#10188 [#10187] Fix NPE in the reactor-netty plugin
  plugins/reactor-netty/src/main/java/com/navercorp/pinpoint/plugin/reactor/netty/interceptor/HttpIOHandlerObserverOnStateChangeInterceptor.java
Labels: bug, module:plugin

#10190 [#noissue] Cleanup
  agent-testweb/grpc-plugin-testweb/src/main/java/com/pinpoint/test/plugin/HelloWorldClient.java
  agent-testweb/rocketmq-plugin-testweb/rocketmq-springcloud-stream/src/main/java/com/pinpoint/test/plugin/RocketMQSpringCloudStreamConsumer.java
  agent-testweb/thrift-plugin-testweb/src/main/java/com/pinpoint/test/plugin/server/HttpEchoTestServer.java
  agent-testweb/thrift-plugin-testweb/src/main/java/com/pinpoint/test/plugin/server/ThriftEchoTestServer.java
  batch-alarmsender/src/main/java/com/navercorp/pinpoint/batch/alarm/vo/sender/payload/PinotAlarmWebhookPayload.java
  commons/src/main/java/com/navercorp/pinpoint/common/util/MathUtils.java
  plugins/spring-data-r2dbc/src/main/java/com/navercorp/pinpoint/plugin/spring/r2dbc/interceptor/h2/H2DatabaseInfoParser.java
  profiler-optional/profiler-optional-jdk8/src/main/java/com/navercorp/pinpoint/profiler/instrument/lambda/MethodInstReplacer.java
  profiler/src/main/java/com/navercorp/pinpoint/profiler/context/monitor/DefaultDataSourceMonitorRegistryService.java
  profiler/src/main/java/com/navercorp/pinpoint/profiler/objectfactory/AutoBindingObjectFactory.java
  rpc/src/main/java/com/navercorp/pinpoint/rpc/client/DefaultPinpointClientHandler.java
  rpc/src/main/java/com/navercorp/pinpoint/rpc/server/DefaultPinpointServer.java
  test/src/main/java/com/navercorp/pinpoint/test/plugin/AbstractPluginForkedTestSuite.java
  test/src/main/java/com/navercorp/pinpoint/test/plugin/AbstractPluginTestSuite.java
  test/src/main/java/com/navercorp/pinpoint/test/plugin/junit5/descriptor/PluginForkedTestUnitTestDescriptor.java
Labels: cleanup

#10193 [#noissue] Remove unnecessary thrift classes
  collector/src/main/java/com/navercorp/pinpoint/collector/mapper/thrift/ThriftBoMapper.java
  collector/src/main/java/com/navercorp/pinpoint/collector/mapper/thrift/stat/ThriftActiveTraceBoMapper.java
  collector/src/main/java/com/navercorp/pinpoint/collector/mapper/thrift/stat/ThriftAgentStatBatchMapper.java
  collector/src/main/java/com/navercorp/pinpoint/collector/mapper/thrift/stat/ThriftAgentStatMapper.java
  collector/src/main/java/com/navercorp/pinpoint/collector/mapper/thrift/stat/ThriftCpuLoadBoMapper.java
  collector/src/main/java/com/navercorp/pinpoint/collector/mapper/thrift/stat/ThriftDataSourceBoMapper.java
  collector/src/main/java/com/navercorp/pinpoint/collector/mapper/thrift/stat/ThriftDeadlockThreadCountBoMapper.java
  collector/src/main/java/com/navercorp/pinpoint/collector/mapper/thrift/stat/ThriftDirectBufferBoMapper.java
  collector/src/main/java/com/navercorp/pinpoint/collector/mapper/thrift/stat/ThriftFileDescriptorBoMapper.java
  collector/src/main/java/com/navercorp/pinpoint/collector/mapper/thrift/stat/ThriftJvmGcBoMapper.java
  collector/src/main/java/com/navercorp/pinpoint/collector/mapper/thrift/stat/ThriftJvmGcDetailedBoMapper.java
  collector/src/main/java/com/navercorp/pinpoint/collector/mapper/thrift/stat/ThriftJvmGcTypeMapper.java
  collector/src/main/java/com/navercorp/pinpoint/collector/mapper/thrift/stat/ThriftLoadedClassBoMapper.java
  collector/src/main/java/com/navercorp/pinpoint/collector/mapper/thrift/stat/ThriftResponseTimeBoMapper.java
  collector/src/main/java/com/navercorp/pinpoint/collector/mapper/thrift/stat/ThriftStatMapper.java
  collector/src/main/java/com/navercorp/pinpoint/collector/mapper/thrift/stat/ThriftTotalThreadCountBoMapper.java
  collector/src/main/java/com/navercorp/pinpoint/collector/mapper/thrift/stat/ThriftTransactionBoMapper.java
  collector/src/main/java/com/navercorp/pinpoint/collector/util/ByteBufferFactory.java
  collector/src/main/java/com/navercorp/pinpoint/collector/util/DatagramPacketFactory.java
  collector/src/main/java/com/navercorp/pinpoint/collector/util/DefaultObjectPool.java
  collector/src/main/java/com/navercorp/pinpoint/collector/util/ObjectPool.java
  collector/src/main/java/com/navercorp/pinpoint/collector/util/ObjectPoolFactory.java
  collector/src/main/java/com/navercorp/pinpoint/collector/util/PooledObject.java
  collector/src/test/java/com/navercorp/pinpoint/collector/mapper/thrift/stat/ThriftActiveTraceBoMapperTest.java
  collector/src/test/java/com/navercorp/pinpoint/collector/mapper/thrift/stat/ThriftBoMapperTestBase.java
  collector/src/test/java/com/navercorp/pinpoint/collector/mapper/thrift/stat/ThriftCpuLoadBoMapperTest.java
  collector/src/test/java/com/navercorp/pinpoint/collector/mapper/thrift/stat/ThriftDeadlockThreadCountBoMapperTest.java
  collector/src/test/java/com/navercorp/pinpoint/collector/mapper/thrift/stat/ThriftDirectBufferBoMapperTest.java
  collector/src/test/java/com/navercorp/pinpoint/collector/mapper/thrift/stat/ThriftFileDescriptorBoMapperTest.java
  collector/src/test/java/com/navercorp/pinpoint/collector/mapper/thrift/stat/ThriftLoadedClassCountBoMapperTest.java
  collector/src/test/java/com/navercorp/pinpoint/collector/mapper/thrift/stat/ThriftResponseTimeBoMapperTest.java
  collector/src/test/java/com/navercorp/pinpoint/collector/mapper/thrift/stat/ThriftTotalThreadCountBoMapperTest.java
  collector/src/test/java/com/navercorp/pinpoint/collector/util/DatagramPacketFactoryTest.java
  collector/src/test/java/com/navercorp/pinpoint/collector/util/DefaultObjectPoolTest.java
Labels: cleanup

#10192 [##10131] Remove hbase2-module
  flink/src/main/java/com/navercorp/pinpoint/flink/hbase/Hbase2HadoopResourceCleanerRegistry.java
  flink/src/main/java/org/apache/hbase/thirdparty/io/netty/buffer/PoolArenaCleaner.java
  flink/src/main/resources/applicationContext-flink-clean.xml
  hbase2-module/hbase2-batch/pom.xml
  hbase2-module/hbase2-collector/pom.xml
  hbase2-module/hbase2-collector/src/main/java/com/navercorp/pinpoint/collector/Hbase2CollectorApp.java
  hbase2-module/hbase2-flink/pom.xml
  hbase2-module/hbase2-flink/src/main/resources/applicationContext-flink-clean.xml
  hbase2-module/hbase2-web/.gitignore
  hbase2-module/hbase2-web/pom.xml
  hbase2-module/hbase2-web/src/main/java/com/navercorp/pinpoint/web/Hbase2WebApp.java
  hbase2-module/pom.xml
  pom.xml
Labels: cleanup

#10184 [#noissue] Cleanup spring-kafka dependency
  metric-module/metric/pom.xml
  pinot/pinot-kafka/pom.xml
  pom.xml
  uristat/uristat-collector/pom.xml
Labels: cleanup, dependencies

#10202 [#noissue] Added logs for responding pubsub demands
  realtime/realtime-common/src/test/java/com/navercorp/pinpoint/util/ThrottleTest.java
  redis/src/main/java/com/navercorp/pinpoint/pubsub/endpoint/PubSubServerImpl.java
Labels: module:collector

#10206 [#10205] Provides a function to configure the pinot broker list
  pinot/pinot-config/src/main/java/com/navercorp/pinpoint/pinot/config/PinotDataSourceProperties.java
  pinot/pinot-config/src/main/java/com/navercorp/pinpoint/pinot/config/PinotDatasourceConfiguration.java
  pinot/pinot-datasource/src/main/java/com/navercorp/pinpoint/pinot/datasource/PinotDataSource.java
Labels: module:collector, module:web

#10207 [#9948] Add missing beans in batch module
  batch/src/main/resources/applicationContext-batch-web-component.xml
Labels: module:batch

#10212 [#noissue] Change xml config to java config in flink module
  flink/src/main/java/com/navercorp/pinpoint/flink/Bootstrap.java
  flink/src/main/java/com/navercorp/pinpoint/flink/FlinkModule.java
  flink/src/main/resources/applicationContext-cache.xml
  flink/src/main/resources/applicationContext-flink.xml
Labels: module:flink, configuration

#10213 [#noissue] Cleanup Batch configuration
  batch/src/main/java/com/navercorp/pinpoint/batch/BatchApp.java
  batch/src/main/java/com/navercorp/pinpoint/batch/BatchModule.java
  batch/src/main/resources/applicationContext-batch-datasource.xml
  batch/src/main/resources/applicationContext-batch-schedule.xml
Labels: cleanup, configuration

#10217 [#noissue] Cleanup
  collector/src/main/resources/application.yml
  commons-hbase/pom.xml
  commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/config/HbaseNamespaceConfiguration.java
  web/src/main/resources/application.yml
Labels: cleanup

#10219 [#10218] Realtime ATC on redis can switch application
  realtime/realtime-web/src/main/java/com/navercorp/pinpoint/web/realtime/activethread/count/websocket/RedisActiveThreadCountWebSocketHandler.java
Labels: bug, module:web

#10224 [#9631] Pass handlers to constructor
  collector/src/main/resources/applicationContext-collector-grpc.xml
Labels: module:collector, module:metric

#10225 [#9631] Fix type for GrpcAgentInfoHandler
  collector/src/main/java/com/navercorp/pinpoint/collector/handler/grpc/GrpcAgentInfoHandler.java
  collector/src/main/resources/applicationContext-collector-grpc.xml
Labels: bug

#10226 [#noissue] Refactor UriStat module
  uristat/uristat-web/src/main/java/com/navercorp/pinpoint/uristat/web/UriStatWebConfig.java
  uristat/uristat-web/src/main/java/com/navercorp/pinpoint/uristat/web/chart/DefaultUriStatChartType.java
  uristat/uristat-web/src/main/java/com/navercorp/pinpoint/uristat/web/chart/UriStatApdexChart.java
  uristat/uristat-web/src/main/java/com/navercorp/pinpoint/uristat/web/chart/UriStatChartType.java
  uristat/uristat-web/src/main/java/com/navercorp/pinpoint/uristat/web/chart/UriStatChartTypeFactory.java
  uristat/uristat-web/src/main/java/com/navercorp/pinpoint/uristat/web/chart/UriStatFailureChart.java
  uristat/uristat-web/src/main/java/com/navercorp/pinpoint/uristat/web/chart/UriStatLatencyChart.java
  uristat/uristat-web/src/main/java/com/navercorp/pinpoint/uristat/web/chart/UriStatTotalChart.java
  uristat/uristat-web/src/main/java/com/navercorp/pinpoint/uristat/web/config/UriStatChartTypeConfiguration.java
  uristat/uristat-web/src/main/java/com/navercorp/pinpoint/uristat/web/controller/UriStatController.java
  uristat/uristat-web/src/main/java/com/navercorp/pinpoint/uristat/web/model/UriStatChartValue.java
  uristat/uristat-web/src/main/java/com/navercorp/pinpoint/uristat/web/model/UriStatGroup.java
  uristat/uristat-web/src/main/java/com/navercorp/pinpoint/uristat/web/util/UriStatSummaryQueryParameter.java
Labels: cleanup, module:metric

#10228 [#noissue] Cleanup InspectorWebApp
  inspector-module/inspector-web/src/main/java/com/navercorp/pinpoint/inspector/web/InspectorWebApp.java
  inspector-module/inspector-web/src/main/java/com/navercorp/pinpoint/inspector/web/model/InspectorMetricValue.java
Labels: cleanup

#10229 [#noissue] Cleanup UriStat Module
  uristat/uristat-web/src/main/java/com/navercorp/pinpoint/uristat/web/controller/UriStatController.java
  uristat/uristat-web/src/main/java/com/navercorp/pinpoint/uristat/web/util/UriStatChartQueryParameter.java
  uristat/uristat-web/src/main/java/com/navercorp/pinpoint/uristat/web/util/UriStatSummaryQueryParameter.java
Labels: module:metric

#10238 [#10237] Bump ASM from 9.4 to 9.5 for JDK21
  pom.xml
Labels: module:agent, dependencies

#10241 [#10240] Backport: Bump ASM from 9.4 to 9.5 for JDK21
  pom.xml
Labels: module:agent, dependencies

#10247 [#10246] Fix missing leave() of ScopedInterceptor when an exception occurs
  bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/interceptor/scope/ScopedInterceptor.java
  bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/interceptor/scope/ScopedInterceptor0.java
  bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/interceptor/scope/ScopedInterceptor1.java
  bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/interceptor/scope/ScopedInterceptor2.java
  bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/interceptor/scope/ScopedInterceptor3.java
  bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/interceptor/scope/ScopedInterceptor4.java
  bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/interceptor/scope/ScopedInterceptor5.java
  profiler/src/test/java/com/navercorp/pinpoint/profiler/interceptor/scope/ScopedInterceptorTest.java
Labels: bug, module:agent

#10250 [#noissue] Cleanup
  commons/src/main/java/com/navercorp/pinpoint/common/util/BytesUtils.java
  commons/src/main/java/com/navercorp/pinpoint/common/util/StringUtils.java
Labels: cleanup

#10251 [#noissue] Cleanup
  batch/pom.xml
  batch/src/test/java/com/navercorp/pinpoint/batch/alarm/AlarmJobTest.java
  batch/src/test/java/com/navercorp/pinpoint/batch/alarm/MainCategoryTest.java
  batch/src/test/java/com/navercorp/pinpoint/batch/alarm/checker/ApdexScoreCheckerTest.java
  batch/src/test/java/com/navercorp/pinpoint/batch/alarm/checker/DataSourceConnectionUsageRateCheckerTest.java
  batch/src/test/java/com/navercorp/pinpoint/batch/alarm/checker/DeadlockCheckerTest.java
  batch/src/test/java/com/navercorp/pinpoint/batch/alarm/checker/ErrorCountCheckerTest.java
  batch/src/test/java/com/navercorp/pinpoint/batch/alarm/checker/ErrorRateCheckerTest.java
  batch/src/test/java/com/navercorp/pinpoint/batch/alarm/checker/GcCountCheckerTest.java
  batch/src/test/java/com/navercorp/pinpoint/batch/alarm/checker/ResponseCountCheckerTest.java
  batch/src/test/java/com/navercorp/pinpoint/batch/alarm/checker/SlowCountCheckerTest.java
  batch/src/test/java/com/navercorp/pinpoint/batch/alarm/checker/SlowRateCheckerTest.java
  batch/src/test/java/com/navercorp/pinpoint/batch/alarm/collector/FileDescriptorDataCollectorTest.java
  batch/src/test/java/com/navercorp/pinpoint/batch/job/AgentCountPartitionerTest.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/config/LoggingEvent.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/util/AgentEventMessageDeserializer.java
  commons-server/src/test/java/com/navercorp/pinpoint/common/server/bo/SpanFactoryAssert.java
  flink/src/main/java/com/navercorp/pinpoint/flink/StatStreamingVer2Job.java
Labels: cleanup

#10253 [#10252] Improve Dynamic Registration of AlarmChecker
  batch/src/main/java/com/navercorp/pinpoint/batch/BatchModule.java
  batch/src/main/java/com/navercorp/pinpoint/batch/alarm/AlarmCheckerFactory.java
  batch/src/main/java/com/navercorp/pinpoint/batch/alarm/AlarmProcessor.java
  batch/src/main/java/com/navercorp/pinpoint/batch/alarm/CheckerRegistry.java
  batch/src/main/java/com/navercorp/pinpoint/batch/configuration/AlarmCheckerConfiguration.java
  batch/src/main/java/com/navercorp/pinpoint/batch/configuration/AlarmJobModule.java
  batch/src/main/resources/job/applicationContext-alarmJob.xml
  batch/src/test/java/com/navercorp/pinpoint/batch/alarm/AlarmProcessorTest.java
  batch/src/test/java/com/navercorp/pinpoint/batch/alarm/CheckerCategoryTest.java
Labels: configuration

#10258 [#10244] Change serviceTypeCode type
  web/src/main/java/com/navercorp/pinpoint/web/view/NodeSerializer.java
Labels: module:web

#10257 [#10256] Removed rule of finalizing path for API with .pinpoint
  web/src/main/java/com/navercorp/pinpoint/web/servlet/RewriteForV2Filter.java
  web/src/test/java/com/navercorp/pinpoint/web/servlet/RewriteForV2FilterTest.java
Labels: module:web
