Repository pinpoint-apm/pinpoint, pull requests merged in 2024-10, with the labels that each got.

#11537 [#11497] Cleanup error log when closing ActiveThreadCount
  agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/receiver/grpc/ActiveThreadCountStreamSocket.java
Labels: cleanup

#11538 [#11497] Cleanup
  realtime/realtime-collector/src/main/java/com/navercorp/pinpoint/realtime/collector/receiver/grpc/ActiveThreadCountResponseStreamObserver.java
  realtime/realtime-collector/src/main/java/com/navercorp/pinpoint/realtime/collector/receiver/grpc/GrpcCommandService.java
Labels: cleanup

#11542 [#noissue] Remove unnecessary protobuf-maven-plugin version
  agent-module/plugins-it/google-grpc-it/google-grpc-1-42-it/pom.xml
  agent-module/plugins-it/google-grpc-it/google-grpc-1-8-it/pom.xml
Labels: cleanup

#11544 [#11543] Remove unnecessary EnumerationFilter
  agent-module/bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/context/Header.java
  commons/src/main/java/com/navercorp/pinpoint/common/util/DelegateEnumeration.java
  commons/src/main/java/com/navercorp/pinpoint/common/util/EmptyEnumeration.java
  commons/src/main/java/com/navercorp/pinpoint/common/util/Predicates.java
  commons/src/test/java/com/navercorp/pinpoint/common/util/DelegateEnumerationTest.java
  commons/src/test/java/com/navercorp/pinpoint/common/util/PredicatesTest.java
Labels: cleanup

#11548 [#11543] Improve debuggability
  commons/src/main/java/com/navercorp/pinpoint/common/util/Predicates.java
Labels: cleanup

#11549 [#11497] Fix potential NPE
  agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/receiver/grpc/ActiveThreadCountStreamSocket.java
  agent-module/profiler/src/test/java/com/navercorp/pinpoint/profiler/receiver/grpc/ActiveThreadCountStreamSocketTest.java
Labels: bug

#11551 [#10776] Adding property to fieldClusterList in the metric properties API
  otlpmetric/otlpmetric-common/src/main/java/com/navercorp/pinpoint/otlp/common/web/definition/property/FieldCluster.java
Labels: module:otlpmetric

#11552 [#10776] Clean up the Metrics Data API
  otlpmetric/otlpmetric-web/src/main/java/com/navercorp/pinpoint/otlp/web/controller/OpenTelemetryMetricController.java
Labels: module:otlpmetric

#11554 [#11553] Update mongodb-plugin backward compatibility for 5.2.x
  agent-module/plugins/mongodb/src/main/java/com/navercorp/pinpoint/plugin/mongo/MongoPlugin.java
Labels: module:plugin

#11557 [#noissue] Improved maven-failsafe-plugin to only work with it-modules
  agent-module/plugins-it/pom.xml
  pom.xml
Labels: cleanup

#11555 [#11497] Refactor ActiveThreadCountStreamSocket
  agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/context/provider/grpc/AgentGrpcDataSenderProvider.java
  agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/receiver/grpc/ActiveThreadCountStreamSocket.java
  agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/receiver/grpc/GrpcActiveThreadCountService.java
  agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/receiver/grpc/GrpcCommandDispatcher.java
  agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/receiver/grpc/GrpcCommandService.java
  agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/receiver/grpc/GrpcProfilerStreamSocket.java
  agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/receiver/grpc/GrpcStreamService.java
  agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/receiver/grpc/PinpointClientResponseObserver.java
  agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/sender/grpc/PingStreamContext.java
  agent-module/profiler/src/test/java/com/navercorp/pinpoint/profiler/receiver/grpc/ActiveThreadCountStreamSocketTest.java
  agent-module/profiler/src/test/java/com/navercorp/pinpoint/profiler/receiver/grpc/GrpcStreamServiceTest.java
  agent-module/profiler/src/test/java/com/navercorp/pinpoint/profiler/receiver/grpc/PinpointClientResponseObserverTest.java
  grpc/src/main/java/com/navercorp/pinpoint/grpc/stream/ClientCallStateStreamObserver.java
  grpc/src/main/java/com/navercorp/pinpoint/grpc/stream/ObserverState.java
  grpc/src/main/java/com/navercorp/pinpoint/grpc/stream/StreamUtils.java
  grpc/src/test/java/com/navercorp/pinpoint/grpc/stream/ClientCallStateStreamObserverTest.java
Labels: cleanup

#11566 [#NOISSUE] Rename the method for consistency.
  batch/src/main/java/com/navercorp/pinpoint/batch/alarm/dao/pinot/PinotAlarmDao.java
  batch/src/main/java/com/navercorp/pinpoint/batch/common/BatchProperties.java
Labels: module:batch

#11567 [#11497] Improve atomicity and performance of Redis call in ActiveThread
  realtime/realtime-collector/src/main/java/com/navercorp/pinpoint/realtime/collector/service/state/RedisCollectorStatePublisherService.java
  realtime/realtime-collector/src/test/java/com/navercorp/pinpoint/realtime/collector/service/state/RedisCollectorStatePublisherServiceTest.java
  redis/src/main/java/com/navercorp/pinpoint/channel/redis/kv/RedisKVPubChannel.java
Labels: module:collector

#11569 [#noissue] Cleanup
  agent-module/plugins-it/cassandra-it/cassandra-2-it/src/test/java/com/navercorp/pinpoint/it/plugin/cassandra/CassandraServer.java
  agent-module/plugins-it/cassandra-it/cassandra-4-it/src/test/java/com/navercorp/pinpoint/it/plugin/cassandra/CassandraServer.java
  agent-module/plugins-it/elasticsearch-it/elasticsearch-6-it/src/test/java/com/navercorp/pinpoint/it/plugin/elasticsearch/ESServer.java
  agent-module/plugins-it/elasticsearch-it/elasticsearch-7-16-it/src/test/java/com/navercorp/pinpoint/it/plugin/elasticsearch/ESServer.java
  agent-module/plugins-it/informix-jdbc-it/src/test/java/com/navercorp/pinpoint/it/plugin/jdbc/informix/InformixServer.java
  agent-module/plugins-it/kafka-it/kafka-2-it/src/test/java/test/pinpoint/plugin/kafka/Kafka2UnitServer.java
  agent-module/plugins-it/kafka-it/kafka-3-it/src/test/java/test/pinpoint/plugin/kafka/Kafka3UnitServer.java
  agent-module/plugins-it/kafka-it/kafka-3-it/src/test/java/test/pinpoint/plugin/kafka/KafkaStreamsUnitServer.java
  agent-module/plugins-it/rabbitmq-it/src/test/java/com/navercorp/pinpoint/it/plugin/rabbitmq/TestBrokerServer.java
  agent-module/plugins-it/redis-lettuce-it/src/test/java/com/navercorp/pinpoint/it/plugin/lettuce/RedisServer.java
Labels: cleanup

#11570 [#10776] Sort metric property data.
  otlpmetric/otlpmetric-common/src/main/java/com/navercorp/pinpoint/otlp/common/web/definition/property/FieldCluster.java
  otlpmetric/otlpmetric-common/src/main/java/com/navercorp/pinpoint/otlp/common/web/definition/property/Metric.java
  otlpmetric/otlpmetric-common/src/main/java/com/navercorp/pinpoint/otlp/common/web/definition/property/MetricGroup.java
  otlpmetric/otlpmetric-common/src/main/java/com/navercorp/pinpoint/otlp/common/web/definition/property/TagCluster.java
  otlpmetric/otlpmetric-web/src/main/java/com/navercorp/pinpoint/otlp/web/dao/pinot/PinotMetricMetaDataDao.java
Labels: module:otlpmetric

#11575 [#noissue] Rename activeAgentService to Validator
  batch/src/main/java/com/navercorp/pinpoint/batch/service/BatchAgentServiceImpl.java
Labels: module:batch

#11574 [#noissue] Cleanup fastjson
  agent-module/plugins-it/fastjson-it/src/test/java/com/navercorp/pinpoint/it/plugin/fastjson/FastjsonIT.java
  agent-module/plugins-it/fastjson-it/src/test/java/com/navercorp/pinpoint/it/plugin/fastjson/FastjsonJDK8IT.java
  pom.xml
Labels: cleanup

#11578 [#11577] Update mariadb-plugin to support mariadb java client 3.x
  agent-module/agent-testweb/mariadb-jdbc-plugin-testweb/README.md
  agent-module/agent-testweb/mariadb-jdbc-plugin-testweb/pom.xml
  agent-module/agent-testweb/mariadb-jdbc-plugin-testweb/src/main/java/com/pinpoint/test/plugin/MariaDBPluginController.java
  agent-module/agent-testweb/mariadb-jdbc-plugin-testweb/src/main/java/com/pinpoint/test/plugin/MariaDBPluginTestStarter.java
  agent-module/agent-testweb/mariadb-jdbc-plugin-testweb/src/main/java/com/pinpoint/test/plugin/MariaDBServer.java
  agent-module/agent-testweb/mariadb-jdbc-plugin-testweb/src/main/resources/application.yml
  agent-module/agent-testweb/mariadb-jdbc-plugin-testweb/src/main/resources/init.sql
  agent-module/agent-testweb/mariadb-jdbc-plugin-testweb/src/test/java/com/pinpoint/test/plugin/mongo/MariaDBTest.java
  agent-module/agent-testweb/pom.xml
  agent-module/bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/util/InstrumentUtils.java
  agent-module/bootstraps/bootstrap-core/src/test/java/com/navercorp/pinpoint/bootstrap/plugin/util/InstrumentUtilsTest.java
  agent-module/plugins-it/mariadb-jdbc-it/src/test/java/com/navercorp/pinpoint/it/plugin/jdbc/MariaDB_3_x_DriverClass.java
  agent-module/plugins-it/mariadb-jdbc-it/src/test/java/com/navercorp/pinpoint/it/plugin/jdbc/MariaDB_3_x_IT.java
  agent-module/plugins/mariadb-jdbc/src/main/java/com/navercorp/pinpoint/plugin/jdbc/mariadb/MariaDBPlugin.java
  agent-module/plugins/mariadb-jdbc/src/main/java/com/navercorp/pinpoint/plugin/jdbc/mariadb/interceptor/PreparedStatementConstructorInterceptor.java
Labels: enhancement, module:plugin

#11582 [#10776] Improved API to store stackDetails and samplingInterval values
  otlpmetric/otlpmetric-common/src/main/java/com/navercorp/pinpoint/otlp/common/web/defined/AppMetricDefinition.java
  otlpmetric/otlpmetric-common/src/main/java/com/navercorp/pinpoint/otlp/common/web/defined/StackDetails.java
  otlpmetric/otlpmetric-web/src/main/java/com/navercorp/pinpoint/otlp/web/controller/OpenTelemetryMetricController.java
Labels: module:otlpmetric

#11583 [#11579] Update httpclient5 plugin option - mark.error
  agent-module/agent-testweb/httpclient5-plugin-testweb/src/main/java/com/pinpoint/test/plugin/HttpClient5PluginController.java
  agent-module/agent/src/main/resources/profiles/local/pinpoint.config
  agent-module/agent/src/main/resources/profiles/release/pinpoint.config
  agent-module/plugins/httpclient5/src/main/java/com/navercorp/pinpoint/plugin/httpclient5/HttpClient5Plugin.java
  agent-module/plugins/httpclient5/src/main/java/com/navercorp/pinpoint/plugin/httpclient5/HttpClient5PluginConfig.java
  agent-module/plugins/httpclient5/src/main/java/com/navercorp/pinpoint/plugin/httpclient5/interceptor/AsyncClientConnectionManagerConnectInterceptor.java
  agent-module/plugins/httpclient5/src/main/java/com/navercorp/pinpoint/plugin/httpclient5/interceptor/AsyncExecCallbackHandleResponseInterceptor.java
  agent-module/plugins/httpclient5/src/main/java/com/navercorp/pinpoint/plugin/httpclient5/interceptor/BasicClientExchangeHandlerConsumeResponseInterceptor.java
  agent-module/plugins/httpclient5/src/main/java/com/navercorp/pinpoint/plugin/httpclient5/interceptor/ClientConnectionManagerConnectInterceptor.java
  agent-module/plugins/httpclient5/src/main/java/com/navercorp/pinpoint/plugin/httpclient5/interceptor/CloseableHttpAsyncClientDoExecuteInterceptor.java
  agent-module/plugins/httpclient5/src/main/java/com/navercorp/pinpoint/plugin/httpclient5/interceptor/CloseableHttpAsyncClientExecuteImmediateMethodInterceptor.java
  agent-module/plugins/httpclient5/src/main/java/com/navercorp/pinpoint/plugin/httpclient5/interceptor/DefaultAsyncClientConnectionOperatorConnectInterceptor.java
  agent-module/plugins/httpclient5/src/main/java/com/navercorp/pinpoint/plugin/httpclient5/interceptor/DefaultHttpClientConnectionOperatorConnectInterceptor.java
  agent-module/plugins/httpclient5/src/main/java/com/navercorp/pinpoint/plugin/httpclient5/interceptor/FutureCancelInterceptor.java
  agent-module/plugins/httpclient5/src/main/java/com/navercorp/pinpoint/plugin/httpclient5/interceptor/FutureCompletedInterceptor.java
  agent-module/plugins/httpclient5/src/main/java/com/navercorp/pinpoint/plugin/httpclient5/interceptor/FutureFailedInterceptor.java
  agent-module/plugins/httpclient5/src/main/java/com/navercorp/pinpoint/plugin/httpclient5/interceptor/InternalHttpClientDoExecuteInterceptor.java
  agent-module/plugins/httpclient5/src/main/java/com/navercorp/pinpoint/plugin/httpclient5/interceptor/MinimalHttpAsyncClientExecuteInterceptor.java
Labels: enhancement, module:plugin

#11590 [#11589] Disable OtlpMetricsExportAutoConfiguration.
  collector-starter/src/main/java/com/navercorp/pinpoint/collector/starter/multi/application/BasicCollectorApp.java
  collector-starter/src/main/java/com/navercorp/pinpoint/collector/starter/multi/application/PinpointCollectorStarter.java
Labels: module:otlpmetric

#11586 [#noissue] Fix intermittent object initialization issue
  agent-module/profiler/src/test/java/com/navercorp/pinpoint/profiler/metadata/DefaultExceptionRecorderTest.java
Labels: module:agent, module:test

#11593 [#11592] Update arcus-plugin to support arcus java client 1.13.4
  agent-module/agent-testweb/arcus-plugin-testweb/pom.xml
  agent-module/agent-testweb/arcus-plugin-testweb/src/main/java/com/pinpoint/test/plugin/ArcusClientConfiguration.java
  agent-module/agent-testweb/arcus-plugin-testweb/src/main/java/com/pinpoint/test/plugin/ArcusPluginController.java
  agent-module/agent-testweb/arcus-plugin-testweb/src/main/java/com/pinpoint/test/plugin/ArcusPluginTestStarter.java
  agent-module/agent-testweb/arcus-plugin-testweb/src/main/resources/application.yml
  agent-module/agent-testweb/pom.xml
  agent-module/plugins/arcus/src/main/java/com/navercorp/pinpoint/plugin/arcus/ArcusPlugin.java
  agent-module/plugins/arcus/src/main/java/com/navercorp/pinpoint/plugin/arcus/ServiceCodeGetter.java
  agent-module/plugins/arcus/src/main/java/com/navercorp/pinpoint/plugin/arcus/interceptor/FrontCacheGetFutureConstructInterceptor.java
  agent-module/plugins/arcus/src/main/java/com/navercorp/pinpoint/plugin/arcus/interceptor/LocalCacheManagerConstructorInterceptor.java
  agent-module/plugins/arcus/src/main/java/com/navercorp/pinpoint/plugin/arcus/interceptor/SetCacheManagerInterceptor.java
Labels: enhancement, module:plugin

#11602 [#10776] Remove the agentId from the tag data in the oltp data.
  otlpmetric/otlpmetric-collector/src/main/java/com/navercorp/pinpoint/otlp/collector/mapper/OtlpMetricMapper.java
Labels: enhancement, module:otlpmetric

#11610 [#10776] Adding sortkey for kafka partition distribution
  otlpmetric/otlpmetric-collector/src/main/java/com/navercorp/pinpoint/otlp/collector/dao/PinotOtlpMetricDao.java
  otlpmetric/otlpmetric-collector/src/main/java/com/navercorp/pinpoint/otlp/collector/model/PinotOtlpMetricDataRow.java
  otlpmetric/otlpmetric-collector/src/main/java/com/navercorp/pinpoint/otlp/collector/model/PinotOtlpMetricDoubleData.java
  otlpmetric/otlpmetric-collector/src/main/java/com/navercorp/pinpoint/otlp/collector/model/PinotOtlpMetricLongData.java
  otlpmetric/otlpmetric-collector/src/main/java/com/navercorp/pinpoint/otlp/collector/model/SortKeyUtils.java
  otlpmetric/otlpmetric-collector/src/main/java/com/navercorp/pinpoint/otlp/collector/service/PinotOtlpMetricCollectorService.java
  otlpmetric/pinot-tables/pinot-otlpmetric-double-realtime-table.json
  otlpmetric/pinot-tables/pinot-otlpmetric-long-realtime-table.json
Labels: enhancement, module:otlpmetric

#11547 [#11433] Add Application agent list query options
  web/src/main/java/com/navercorp/pinpoint/web/authorization/controller/AgentListController.java
  web/src/main/java/com/navercorp/pinpoint/web/service/AgentInfoServiceImpl.java
  web/src/main/java/com/navercorp/pinpoint/web/service/ApplicationAgentInfoMapService.java
  web/src/main/java/com/navercorp/pinpoint/web/service/ApplicationAgentInfoMapServiceImpl.java
  web/src/main/java/com/navercorp/pinpoint/web/service/ApplicationAgentListQueryRule.java
  web/src/main/java/com/navercorp/pinpoint/web/service/ApplicationAgentListService.java
  web/src/main/java/com/navercorp/pinpoint/web/service/ApplicationAgentListServiceImpl.java
  web/src/main/java/com/navercorp/pinpoint/web/vo/ResponseTime.java
  web/src/main/java/com/navercorp/pinpoint/web/vo/agent/AgentInfoFilters.java
  web/src/main/java/com/navercorp/pinpoint/web/vo/agent/AgentStatusFilters.java
  web/src/test/java/com/navercorp/pinpoint/web/service/ApplicationAgentListServiceImplTest.java
Labels: module:web

#11616 [#noissue] Update README
  README.md
  doc/images/ss_error-analysis.png
  doc/images/ss_error-analysis1.png
  doc/images/ss_error-analysis3.gif
Labels: document

#11617 [#noissue] Bump actions/setup-java@v3 to actions/setup-java@v4
  .github/workflows/maven-central-deploy.yml
Labels: dependencies

#11618 [#noissue] Bump actions/setup-java@v3 to actions/setup-java@v4
  .github/workflows/maven-central-deploy.yml
Labels: dependencies

#11621 [#11620] Bump springframework from 6.1.5 to 6.1.14
  pom.xml
Labels: dependencies

#11624 [#11622] Bump spring-boot from 3.2.4 to 3.3.5
  pom.xml
Labels: dependencies

#11625 [#noissue] Cleanup springframework dependency
  agent-module/profiler/pom.xml
  otlpmetric/otlpmetric-collector/pom.xml
Labels: cleanup

#11632 [#10776] add test code
  otlpmetric/otlpmetric-collector/src/test/java/com/navercorp/pinpoint/otlp/collector/mapper/GaugeMapperTest.java
  otlpmetric/otlpmetric-web/src/main/java/com/navercorp/pinpoint/otlp/web/dao/pinot/PinotMetricMetaDataDao.java
Labels: enhancement, module:otlpmetric

#11633 [#10776] If metricGroup, metric, and field name are empty string, put the default value
  otlpmetric/otlpmetric-collector/src/main/java/com/navercorp/pinpoint/otlp/collector/mapper/GaugeMapper.java
  otlpmetric/otlpmetric-collector/src/test/java/com/navercorp/pinpoint/otlp/collector/mapper/GaugeMapperTest.java
  otlpmetric/otlpmetric-common/src/main/java/com/navercorp/pinpoint/otlp/common/model/MetricName.java
Labels: enhancement, module:otlpmetric

#11635 [#noissue] Update plugins url
  README.md
  agent-module/agent/src/main/resources/profiles/local/pinpoint.config
  agent-module/agent/src/main/resources/profiles/release/pinpoint.config
  agent-module/plugins/undertow-servlet/README.md
  doc/modules.md
Labels: document

#11629 [#11628] Bump spring-boot2 from 2.7.13 to 2.7.17 for plugin-test
  pom.xml
Labels: dependencies

#11627 [#11626] Bump springframework5 from 5.3.28 to 5.3.39 for plugin-test
  pom.xml
Labels: dependencies

#11639 [#11638] Bump spring-data from 3.2.2 to 3.3.3
  pom.xml
Labels: dependencies

#11637 [#noissue] Remove unnecessary zk cluster from web module
  web/pom.xml
  web/src/main/java/com/navercorp/pinpoint/web/PinpointWebModule.java
  web/src/main/java/com/navercorp/pinpoint/web/config/WebClusterProperties.java
  web/src/main/resources/pinpoint-web-root.properties
  web/src/test/java/com/navercorp/pinpoint/web/config/PropertiesVerificationTest.java
Labels: cleanup

#11644 [#11643] Bump spring-batch from 5.1.1 to 5.1.2
  pom.xml
Labels: dependencies

#11612 [#11611] Update mysql-jdbc-plugin support to mysql-connector-j 9.x
  agent-module/agent-testweb/mysql-jdbc-plugin-testweb/README.md
  agent-module/agent-testweb/mysql-jdbc-plugin-testweb/pom.xml
  agent-module/agent-testweb/mysql-jdbc-plugin-testweb/src/main/java/com/pinpoint/test/plugin/MysqlDBPluginController.java
  agent-module/agent-testweb/mysql-jdbc-plugin-testweb/src/main/java/com/pinpoint/test/plugin/MysqlDBPluginTestStarter.java
  agent-module/agent-testweb/mysql-jdbc-plugin-testweb/src/main/java/com/pinpoint/test/plugin/MysqlDBServer.java
  agent-module/agent-testweb/mysql-jdbc-plugin-testweb/src/main/resources/application.yml
  agent-module/agent-testweb/mysql-jdbc-plugin-testweb/src/main/resources/init.sql
  agent-module/agent-testweb/mysql-jdbc-plugin-testweb/src/test/java/com/pinpoint/test/plugin/mongo/MysqlDBTest.java
  agent-module/agent-testweb/pom.xml
  agent-module/plugins-it/mysql-jdbc-driver-plugin-it/pom.xml
  agent-module/plugins-it/mysql-jdbc-driver-plugin-it/src/test/java/com/navercorp/pinpoint/it/plugin/jdbc/mysql/MySql_9_X_IT.java
  agent-module/plugins/mysql-jdbc/src/main/java/com/navercorp/pinpoint/plugin/jdbc/mysql/MySqlPlugin.java
Labels: enhancement, module:plugin

#11650 [#noissue] Add docs on sql related configs
  agent-module/agent/src/main/resources/pinpoint-root.config
  agent-module/agent/src/main/resources/profiles/local/pinpoint.config
  agent-module/agent/src/main/resources/profiles/release/pinpoint.config
Labels: configuration

#11649 [#11647] Update httpclient5-plugin support to httpclient5 5.4
  agent-module/agent-testweb/httpclient5-plugin-testweb/pom.xml
  agent-module/agent-testweb/pom.xml
  agent-module/agent-testweb/spring-restclient-plugin-testweb/pom.xml
  agent-module/agent-testweb/spring-restclient-plugin-testweb/src/main/java/com/pinpoint/test/plugin/SpringRestClientPluginController.java
  agent-module/agent-testweb/spring-restclient-plugin-testweb/src/main/java/com/pinpoint/test/plugin/SpringRestClientPluginTestStarter.java
  agent-module/agent-testweb/spring-restclient-plugin-testweb/src/main/resources/application.yml
  agent-module/plugins-it/httpclient-it/httpclient-5-it/pom.xml
  agent-module/plugins-it/httpclient-it/httpclient-5-it/src/test/java/com/navercorp/pinpoint/it/plugin/httpclient5/CloaeableHttpClientIT.java
  agent-module/plugins-it/httpclient-it/httpclient-5-it/src/test/java/com/navercorp/pinpoint/it/plugin/httpclient5/CloaeableHttpClient_5_2_IT.java
  agent-module/plugins-it/httpclient-it/httpclient-5-it/src/test/java/com/navercorp/pinpoint/it/plugin/httpclient5/CloaeableHttpClient_5_4_IT.java
  agent-module/plugins-it/httpclient-it/httpclient-5-it/src/test/java/com/navercorp/pinpoint/it/plugin/httpclient5/ClosableAsyncHttpClientIT.java
  agent-module/plugins-it/httpclient-it/httpclient-5-it/src/test/java/com/navercorp/pinpoint/it/plugin/httpclient5/HttpClientITBase.java
  agent-module/plugins-it/httpclient-it/pom.xml
  agent-module/plugins/httpclient5/src/main/java/com/navercorp/pinpoint/plugin/httpclient5/HttpClient5Plugin.java
  agent-module/plugins/httpclient5/src/main/java/com/navercorp/pinpoint/plugin/httpclient5/interceptor/CloseableHttpAsyncClientExecuteImmediateMethodInterceptor.java
Labels: enhancement, module:plugin

#11645 [#11640] Introduce redis-timeseries module
  pom.xml
  redis-timeseries/pom.xml
  redis-timeseries/src/main/java/com/navercorp/pinpoint/redis/timeseries/ArrayTimestampValueOutput.java
  redis-timeseries/src/main/java/com/navercorp/pinpoint/redis/timeseries/MetricOutput.java
  redis-timeseries/src/main/java/com/navercorp/pinpoint/redis/timeseries/OutputFactory.java
  redis-timeseries/src/main/java/com/navercorp/pinpoint/redis/timeseries/RedisTimeseriesCommands.java
  redis-timeseries/src/main/java/com/navercorp/pinpoint/redis/timeseries/RedisTimeseriesCommandsImpl.java
  redis-timeseries/src/main/java/com/navercorp/pinpoint/redis/timeseries/TsAddArgs.java
  redis-timeseries/src/main/java/com/navercorp/pinpoint/redis/timeseries/model/TimestampValuePair.java
  redis-timeseries/src/main/java/com/navercorp/pinpoint/redis/timeseries/protocol/ChunkSize.java
  redis-timeseries/src/main/java/com/navercorp/pinpoint/redis/timeseries/protocol/Count.java
  redis-timeseries/src/main/java/com/navercorp/pinpoint/redis/timeseries/protocol/Duplicate.java
  redis-timeseries/src/main/java/com/navercorp/pinpoint/redis/timeseries/protocol/DuplicatePolicy.java
  redis-timeseries/src/main/java/com/navercorp/pinpoint/redis/timeseries/protocol/Encoding.java
  redis-timeseries/src/main/java/com/navercorp/pinpoint/redis/timeseries/protocol/Ignore.java
  redis-timeseries/src/main/java/com/navercorp/pinpoint/redis/timeseries/protocol/Label.java
  redis-timeseries/src/main/java/com/navercorp/pinpoint/redis/timeseries/protocol/Labels.java
  redis-timeseries/src/main/java/com/navercorp/pinpoint/redis/timeseries/protocol/Latest.java
  redis-timeseries/src/main/java/com/navercorp/pinpoint/redis/timeseries/protocol/OnDuplicate.java
  redis-timeseries/src/main/java/com/navercorp/pinpoint/redis/timeseries/protocol/Retention.java
  redis-timeseries/src/main/java/com/navercorp/pinpoint/redis/timeseries/protocol/TS.java
  redis-timeseries/src/test/java/com/navercorp/pinpoint/redis/timeseries/RedisServer.java
  redis-timeseries/src/test/java/com/navercorp/pinpoint/redis/timeseries/RedisTimeseriesCommandsTest.java
  redis-timeseries/src/test/resources/log4j2-test.xml
Labels: cleanup

#11654 [#11653] Bump kafka-client from 3.3.2 to 3.7.1
  agent-module/agent-testweb/kafka-plugin-testweb/pom.xml
  agent-module/agent-testweb/kafka-streams-testweb/pom.xml
  agent-module/plugins-it/kafka-it/kafka-2-it/pom.xml
  agent-module/plugins-it/kafka-it/kafka-3-it/pom.xml
  agent-module/plugins/bom/pom.xml
  pom.xml
Labels: dependencies

#11657 [#11433] Change servermap agent list condition
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/controller/MapController.java
  web/src/main/java/com/navercorp/pinpoint/web/authorization/controller/AgentListController.java
  web/src/main/java/com/navercorp/pinpoint/web/realtime/AgentLookupServiceImpl.java
  web/src/main/java/com/navercorp/pinpoint/web/realtime/RealtimeConfig.java
  web/src/main/java/com/navercorp/pinpoint/web/service/AgentInfoService.java
  web/src/main/java/com/navercorp/pinpoint/web/service/AgentInfoServiceImpl.java
  web/src/main/java/com/navercorp/pinpoint/web/service/ApplicationAgentInfoMapServiceImpl.java
  web/src/main/java/com/navercorp/pinpoint/web/service/ApplicationAgentListQueryRule.java
  web/src/main/java/com/navercorp/pinpoint/web/service/ApplicationAgentListService.java
  web/src/main/java/com/navercorp/pinpoint/web/service/ApplicationAgentListServiceImpl.java
  web/src/test/java/com/navercorp/pinpoint/web/service/ApplicationAgentListServiceImplTest.java
Labels: module:web

#11660 [#11659] Replaced log4 1.x with reload4j
  agent-module/plugins-it/hbase-it/pom.xml
  agent-module/plugins-it/log4j-it/pom.xml
  agent-module/plugins/hbase/pom.xml
  agent-module/plugins/log4j/pom.xml
  pom.xml
Labels: dependencies

#11667 [#10776] Add index to tables and schema of otlpmetric.
  otlpmetric/pinot-tables/pinot-otlpmetric-double-offline-table.json
  otlpmetric/pinot-tables/pinot-otlpmetric-double-realtime-table.json
  otlpmetric/pinot-tables/pinot-otlpmetric-double-schema.json
  otlpmetric/pinot-tables/pinot-otlpmetric-long-offline-table.json
  otlpmetric/pinot-tables/pinot-otlpmetric-long-realtime-table.json
  otlpmetric/pinot-tables/pinot-otlpmetric-long-schema.json
Labels: module:otlpmetric

#11664 [#11663] Update mark.error option of httpclient plugins
  agent-module/agent/src/main/resources/profiles/local/pinpoint.config
  agent-module/agent/src/main/resources/profiles/release/pinpoint.config
  agent-module/plugins/google-httpclient/src/main/java/com/navercorp/pinpoint/plugin/google/httpclient/HttpClientPlugin.java
  agent-module/plugins/google-httpclient/src/main/java/com/navercorp/pinpoint/plugin/google/httpclient/HttpClientPluginConfig.java
  agent-module/plugins/google-httpclient/src/main/java/com/navercorp/pinpoint/plugin/google/httpclient/interceptor/HttpRequestExecuteAsyncMethodInnerClassCallMethodInterceptor.java
  agent-module/plugins/google-httpclient/src/main/java/com/navercorp/pinpoint/plugin/google/httpclient/interceptor/HttpRequestExecuteAsyncMethodInterceptor.java
  agent-module/plugins/google-httpclient/src/main/java/com/navercorp/pinpoint/plugin/google/httpclient/interceptor/HttpRequestExecuteMethodInterceptor.java
  agent-module/plugins/httpclient3/src/main/java/com/navercorp/pinpoint/plugin/httpclient3/HttpClient3Plugin.java
  agent-module/plugins/httpclient3/src/main/java/com/navercorp/pinpoint/plugin/httpclient3/HttpClient3PluginConfig.java
  agent-module/plugins/httpclient3/src/main/java/com/navercorp/pinpoint/plugin/httpclient3/interceptor/ExecuteInterceptor.java
  agent-module/plugins/httpclient3/src/main/java/com/navercorp/pinpoint/plugin/httpclient3/interceptor/HttpConnectionOpenMethodInterceptor.java
  agent-module/plugins/httpclient3/src/main/java/com/navercorp/pinpoint/plugin/httpclient3/interceptor/HttpMethodBaseExecuteMethodInterceptor.java
  agent-module/plugins/httpclient3/src/main/java/com/navercorp/pinpoint/plugin/httpclient3/interceptor/RetryMethodInterceptor.java
  agent-module/plugins/httpclient4/src/main/java/com/navercorp/pinpoint/plugin/httpclient4/HttpClient4Plugin.java
  agent-module/plugins/httpclient4/src/main/java/com/navercorp/pinpoint/plugin/httpclient4/HttpClient4PluginConfig.java
  agent-module/plugins/httpclient4/src/main/java/com/navercorp/pinpoint/plugin/httpclient4/interceptor/AbstractHttpClientExecuteMethodInterceptor.java
  agent-module/plugins/httpclient4/src/main/java/com/navercorp/pinpoint/plugin/httpclient4/interceptor/BasicFutureFailedMethodInterceptor.java
  agent-module/plugins/httpclient4/src/main/java/com/navercorp/pinpoint/plugin/httpclient4/interceptor/BasicFutureMethodInterceptor.java
  agent-module/plugins/httpclient4/src/main/java/com/navercorp/pinpoint/plugin/httpclient4/interceptor/DefaultClientExchangeHandlerImplStartMethodInterceptor.java
  agent-module/plugins/httpclient4/src/main/java/com/navercorp/pinpoint/plugin/httpclient4/interceptor/DefaultHttpRequestRetryHandlerRetryRequestMethodInterceptor.java
  agent-module/plugins/httpclient4/src/main/java/com/navercorp/pinpoint/plugin/httpclient4/interceptor/HttpAsyncClientExecuteMethodInterceptor.java
  agent-module/plugins/httpclient4/src/main/java/com/navercorp/pinpoint/plugin/httpclient4/interceptor/HttpClientConnectionManagerConnectMethodInterceptor.java
  agent-module/plugins/httpclient4/src/main/java/com/navercorp/pinpoint/plugin/httpclient4/interceptor/HttpRequestExecutorExecuteMethodInterceptor.java
  agent-module/plugins/httpclient4/src/main/java/com/navercorp/pinpoint/plugin/httpclient4/interceptor/ManagedClientConnectionOpenMethodInterceptor.java
  agent-module/plugins/jdk-http/src/main/java/com/navercorp/pinpoint/plugin/jdk/http/JdkHttpPluginConfig.java
  agent-module/plugins/jdk-http/src/main/java/com/navercorp/pinpoint/plugin/jdk/http/interceptor/AbstractHttpURLConnectionInterceptor.java
  agent-module/plugins/jdk-http/src/main/java/com/navercorp/pinpoint/plugin/jdk/http/interceptor/HttpURLConnectionGetHeaderFieldInterceptor.java
  agent-module/plugins/jdk-http/src/main/java/com/navercorp/pinpoint/plugin/jdk/http/interceptor/HttpURLConnectionPlainConnect0Interceptor.java
  agent-module/plugins/jdk-httpclient/src/main/java/com/navercorp/pinpoint/plugin/jdk/httpclient/JdkHttpClientPluginConfig.java
  agent-module/plugins/jdk-httpclient/src/main/java/com/navercorp/pinpoint/plugin/jdk/httpclient/interceptor/HttpClientInterceptor.java
  agent-module/plugins/jdk-httpclient/src/main/java/com/navercorp/pinpoint/plugin/jdk/httpclient/interceptor/HttpResponseImplInterceptor.java
  agent-module/plugins/jdk-httpclient/src/main/java/com/navercorp/pinpoint/plugin/jdk/httpclient/interceptor/MultiExchangeResponseAsyncImplInterceptor.java
  agent-module/plugins/jdk-httpclient/src/main/java/com/navercorp/pinpoint/plugin/jdk/httpclient/interceptor/MultiExchangeResponseAsyncInterceptor.java
  agent-module/plugins/ning-asynchttpclient/src/main/java/com/navercorp/pinpoint/plugin/ning/asynchttpclient/NingAsyncHttpClientPluginConfig.java
  agent-module/plugins/ning-asynchttpclient/src/main/java/com/navercorp/pinpoint/plugin/ning/asynchttpclient/interceptor/ExecuteInterceptor.java
  agent-module/plugins/ning-asynchttpclient/src/main/java/com/navercorp/pinpoint/plugin/ning/asynchttpclient/interceptor/ExecuteRequestInterceptor.java
  agent-module/plugins/okhttp/src/main/java/com/navercorp/pinpoint/plugin/okhttp/OkHttpPluginConfig.java
  agent-module/plugins/okhttp/src/main/java/com/navercorp/pinpoint/plugin/okhttp/interceptor/AsyncCallExecuteMethodInterceptor.java
  agent-module/plugins/okhttp/src/main/java/com/navercorp/pinpoint/plugin/okhttp/interceptor/DispatcherEnqueueMethodInterceptor.java
  agent-module/plugins/okhttp/src/main/java/com/navercorp/pinpoint/plugin/okhttp/v2/OkHttpPlugin.java
  agent-module/plugins/okhttp/src/main/java/com/navercorp/pinpoint/plugin/okhttp/v2/interceptor/HttpEngineConnectMethodFromUserRequestInterceptor.java
  agent-module/plugins/okhttp/src/main/java/com/navercorp/pinpoint/plugin/okhttp/v2/interceptor/HttpEngineConnectMethodInterceptor.java
  agent-module/plugins/okhttp/src/main/java/com/navercorp/pinpoint/plugin/okhttp/v2/interceptor/HttpEngineReadResponseMethodInterceptor.java
  agent-module/plugins/okhttp/src/main/java/com/navercorp/pinpoint/plugin/okhttp/v2/interceptor/HttpEngineSendRequestMethodInterceptor.java
  agent-module/plugins/okhttp/src/main/java/com/navercorp/pinpoint/plugin/okhttp/v2/interceptor/RequestBuilderBuildMethodBackwardCompatibilityInterceptor.java
  agent-module/plugins/okhttp/src/main/java/com/navercorp/pinpoint/plugin/okhttp/v3/OkHttpPlugin.java
  agent-module/plugins/okhttp/src/main/java/com/navercorp/pinpoint/plugin/okhttp/v3/interceptor/BridgeInterceptorInterceptMethodInterceptor.java
  agent-module/plugins/okhttp/src/main/java/com/navercorp/pinpoint/plugin/okhttp/v3/interceptor/HttpEngineConnectMethodInterceptor.java
  agent-module/plugins/okhttp/src/main/java/com/navercorp/pinpoint/plugin/okhttp/v3/interceptor/HttpEngineReadResponseMethodInterceptor.java
  agent-module/plugins/okhttp/src/main/java/com/navercorp/pinpoint/plugin/okhttp/v3/interceptor/HttpEngineSendRequestMethodInterceptor.java
  agent-module/plugins/okhttp/src/main/java/com/navercorp/pinpoint/plugin/okhttp/v3/interceptor/RealConnectionConnectMethodInterceptor.java
  agent-module/plugins/okhttp/src/main/java/com/navercorp/pinpoint/plugin/okhttp/v3/interceptor/RequestBuilderBuildMethodInterceptor.java
Labels: enhancement, module:plugin

#11665 [#noissue] Fix support version range of vertx-plugin
  agent-module/plugins/vertx/src/main/java/com/navercorp/pinpoint/plugin/vertx/VertxPlugin.java
Labels: module:plugin

#11668 [#10776] Change id to name in the otlp logic.
  otlpmetric/otlpmetric-collector/src/main/java/com/navercorp/pinpoint/otlp/collector/dao/PinotOtlpMetricDao.java
  otlpmetric/otlpmetric-collector/src/main/java/com/navercorp/pinpoint/otlp/collector/model/PinotOtlpMetricDataRow.java
  otlpmetric/otlpmetric-collector/src/main/java/com/navercorp/pinpoint/otlp/collector/model/PinotOtlpMetricDoubleData.java
  otlpmetric/otlpmetric-collector/src/main/java/com/navercorp/pinpoint/otlp/collector/model/PinotOtlpMetricLongData.java
  otlpmetric/otlpmetric-collector/src/main/java/com/navercorp/pinpoint/otlp/collector/model/PinotOtlpMetricMetadata.java
  otlpmetric/otlpmetric-collector/src/main/java/com/navercorp/pinpoint/otlp/collector/service/PinotOtlpMetricCollectorService.java
  otlpmetric/otlpmetric-web/src/main/java/com/navercorp/pinpoint/otlp/web/controller/OpenTelemetryMetricController.java
  otlpmetric/otlpmetric-web/src/main/java/com/navercorp/pinpoint/otlp/web/dao/OtlpMetricDao.java
  otlpmetric/otlpmetric-web/src/main/java/com/navercorp/pinpoint/otlp/web/dao/pinot/PinotOtlpMetricDao.java
  otlpmetric/otlpmetric-web/src/main/java/com/navercorp/pinpoint/otlp/web/service/OtlpMetricWebService.java
  otlpmetric/otlpmetric-web/src/main/java/com/navercorp/pinpoint/otlp/web/service/OtlpMetricWebServiceImpl.java
  otlpmetric/otlpmetric-web/src/main/java/com/navercorp/pinpoint/otlp/web/vo/OtlpMetricChartQueryParameter.java
  otlpmetric/otlpmetric-web/src/main/java/com/navercorp/pinpoint/otlp/web/vo/OtlpMetricDataQueryParameter.java
  otlpmetric/otlpmetric-web/src/main/java/com/navercorp/pinpoint/otlp/web/vo/OtlpMetricDetailsQueryParam.java
  otlpmetric/otlpmetric-web/src/main/java/com/navercorp/pinpoint/otlp/web/vo/OtlpMetricGroupsQueryParam.java
  otlpmetric/otlpmetric-web/src/main/java/com/navercorp/pinpoint/otlp/web/vo/OtlpMetricNamesQueryParam.java
  otlpmetric/otlpmetric-web/src/main/resources/otlpmetric/web/mapper/pinot/MetricDefinitionMapper.xml
  otlpmetric/otlpmetric-web/src/main/resources/otlpmetric/web/mapper/pinot/OtlpMetricMapper.xml
Labels: enhancement, module:otlpmetric
