Repository pinpoint-apm/pinpoint, pull requests merged in 2024-11, with the labels that each got.

#11671 [#11670] Bump spring-cloud from 4.1.2 to 4.1.4
  pom.xml
Labels: dependencies

#11673 [#11672] Bump spring-cloud from 3.1.8 to 3.1.9
  pom.xml
Labels: dependencies

#11669 [#noissue] Improve compatibility with thrift 0.21
  agent-module/plugins/thrift/src/main/java/com/navercorp/pinpoint/plugin/thrift/interceptor/server/ProcessFunctionProcessInterceptor.java
Labels: module:plugin, cleanup

#11675 [#11674] Bump guava from 32.1.2-jre to 33.3.1-jre
  pom.xml
Labels: dependencies

#11678 [#11677] Bump gson from Gson 2.10.1 to Gson 2.11.0
  pom.xml
Labels: dependencies

#11680 [#11679] Bump grpc from 1.64.1 to 1.68.1
  pom.xml
Labels: dependencies

#11685 [#NOISSUE] reserved ports for use by OpenTelemetry data collection.
  collector-starter/src/main/java/com/navercorp/pinpoint/collector/starter/multi/application/type/CollectorType.java
  collector/src/main/resources/profiles/local/pinpoint-collector-grpc.properties
  collector/src/main/resources/profiles/release/pinpoint-collector-grpc.properties
Labels: module:collector

#11689 [#noissue] Add network metrics
  collector-monitor/pom.xml
  collector-monitor/src/main/java/com/navercorp/pinpoint/collector/monitor/config/MicrometerConfiguration.java
  collector-monitor/src/main/java/com/navercorp/pinpoint/collector/monitor/micrometer/binder/NetworkMetricsBinder.java
Labels: module:collector

#11696 [#noissue] Bump jna from 5.14.0 to 5.15.0
  pom.xml
Labels: dependencies

#11701 [#noissue] Add allOfAsync to FutureUtils
  commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/util/FutureUtils.java
  commons-hbase/src/test/java/com/navercorp/pinpoint/common/hbase/util/FutureUtilsTest.java
Labels: dependencies

#11704 [#11703] Bump mockito-junit-jupiter from 4.8.1 to 4.11.0
  pom.xml
Labels: dependencies

#11706 [#11705] Bump junit-jupiter 5.10.2 from to 5.11.3
  pom.xml
Labels: dependencies

#11707 [#noissue] Remove unnecessary pinpoint-pugins-test-utils
  pom.xml
Labels: cleanup

#11711 [#noissue] Generalize CachingSqlNormalizer
  agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/cache/UidCache.java
  agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/context/provider/metadata/SqlMetadataServiceProvider.java
  agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/metadata/DefaultCachingSqlNormalizer.java
  agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/metadata/SimpleCachingSqlNormalizer.java
  agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/metadata/SqlCacheService.java
  agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/metadata/UidCachingSqlNormalizer.java
  agent-module/profiler/src/test/java/com/navercorp/pinpoint/profiler/metadata/DefaultCachingSqlNormalizerTest.java
  agent-module/profiler/src/test/java/com/navercorp/pinpoint/profiler/metadata/SqlCacheServiceTest.java
  agent-module/profiler/src/test/java/com/navercorp/pinpoint/profiler/metadata/SqlUidMetaDataServiceTest.java
Labels: module:agent

#11715 [#noissue] Optimize hashing by reusing hasher instance
  agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/cache/SimpleCache.java
  agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/cache/UidCache.java
  agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/cache/UidGenerator.java
  agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/context/provider/metadata/SqlMetadataServiceProvider.java
  agent-module/profiler/src/test/java/com/navercorp/pinpoint/profiler/metadata/SqlUidMetaDataServiceTest.java
Labels: module:agent

#11716 [#11503] Delegate cache creation to SimpleCacheFactory
  agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/context/provider/metadata/SimpleCacheFactory.java
  agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/context/provider/metadata/SimpleCacheFactoryProvider.java
  agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/context/provider/metadata/SqlMetadataServiceProvider.java
Labels: module:agent

#11719 [#11705] Improve compatibility of Junit with It tests
  agent-module/plugins-test-module/plugins-test/src/main/java/com/navercorp/pinpoint/test/plugin/junit5/descriptor/DescriptorUtils.java
  agent-module/plugins-test-module/plugins-test/src/main/java/com/navercorp/pinpoint/test/plugin/junit5/descriptor/PluginForkedTestDependencyTestDescriptor.java
  agent-module/plugins-test-module/plugins-test/src/main/java/com/navercorp/pinpoint/test/plugin/junit5/descriptor/PluginForkedTestUnitTestDescriptor.java
  agent-module/plugins-test-module/plugins-test/src/main/java/com/navercorp/pinpoint/test/plugin/junit5/descriptor/PluginTestDescriptor.java
  agent-module/plugins-test-module/plugins-test/src/main/java/com/navercorp/pinpoint/test/plugin/junit5/descriptor/PluginTestUnitTestDescriptor.java
  agent-module/plugins-test-module/plugins-test/src/main/java/org/junit/jupiter/engine/descriptor/ExtensionContextFactory.java
Labels: cleanup

#11725 [#noissue] Remove deprecated PLogger API
  agent-module/bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/logging/PLogger.java
  agent-module/bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/logging/PLoggerFactory.java
  agent-module/plugins/agentsdk-async/src/main/java/com/navercorp/pinpoint/plugin/sdk/AgentSdkAsyncPlugin.java
  agent-module/plugins/agentsdk-async/src/main/java/com/navercorp/pinpoint/plugin/sdk/interceptor/CommandInterceptor.java
  agent-module/profiler-logging/src/main/java/com/navercorp/pinpoint/profiler/logging/Log4J2PluginLoggerAdapter.java
  agent-module/profiler-logging/src/main/java/com/navercorp/pinpoint/profiler/logging/Log4j2LoggingSystem.java
Labels: cleanup

#11724 [#noissue] Fix deprecated API
  agent-module/agent-testweb/cassandra3-plugin-testweb/src/test/java/com/pinpoint/test/plugin/cassandra/CassandraTest.java
  agent-module/agent-testweb/cassandra4-plugin-testweb/src/main/java/com/pinpoint/test/plugin/Cassandra4PluginController.java
  agent-module/agent-testweb/kafka-plugin-testweb/src/test/java/com/pinpoint/test/plugin/kafka/KafkaTest.java
  agent-module/plugins-it/cassandra-it/cassandra-2-it/src/test/java/com/navercorp/pinpoint/it/plugin/cassandra/CassandraServer.java
  agent-module/plugins-it/cassandra-it/cassandra-4-it/src/test/java/com/navercorp/pinpoint/it/plugin/cassandra/CassandraServer.java
  agent-module/plugins-it/kafka-it/kafka-2-it/src/test/java/com/navercorp/pinpoint/it/plugin/kafka/KafkaClient2ITBase.java
  agent-module/plugins-it/kafka-it/kafka-2-it/src/test/java/test/pinpoint/plugin/kafka/Kafka3UnitServer.java
  agent-module/plugins-it/kafka-it/kafka-3-it/src/test/java/com/navercorp/pinpoint/it/plugin/kafka/KafkaClient3ITBase.java
  agent-module/plugins-it/kafka-it/kafka-3-it/src/test/java/com/navercorp/pinpoint/it/plugin/kafka/KafkaStreamsIT.java
  agent-module/plugins-it/kafka-it/kafka-3-it/src/test/java/test/pinpoint/plugin/kafka/Kafka3UnitServer.java
  agent-module/plugins-it/kafka-it/kafka-3-it/src/test/java/test/pinpoint/plugin/kafka/KafkaStreamsUnitServer.java
  agent-module/plugins-it/kafka-it/kafka-3-it/src/test/java/test/pinpoint/plugin/kafka/TestConsumer.java
  agent-module/plugins/cxf/src/main/java/com/navercorp/pinpoint/plugin/cxf/CxfPlugin.java
  agent-module/plugins/cxf/src/main/java/com/navercorp/pinpoint/plugin/cxf/CxfPluginTraceMetadataProvider.java
  agent-module/plugins/cxf/src/test/java/com/navercorp/pinpoint/plugin/cxf/interceptor/CxfClientInvokeSyncMethodInterceptorTest.java
  agent-module/plugins/hbase/src/test/java/com/navercorp/pinpoint/plugin/hbase/interceptor/HbaseTableMethodInterceptorTest.java
  commons-server/src/test/java/com/navercorp/pinpoint/common/server/scatter/FuzzyRowKeyBuilderTest.java
  grpc/src/test/java/com/navercorp/pinpoint/grpc/StatusErrorsTest.java
Labels: cleanup

#11727 [#11726] Bump maven-surefire-plugin from 3.1.2 to 3.5.2
  pom.xml
Labels: dependencies

#11728 [#noissue] Cleanup protobuf-maven-plugin
  agent-module/agent-testweb/grpc-plugin-testweb/pom.xml
  agent-module/plugins-it/google-grpc-it/google-grpc-1-42-it/pom.xml
  agent-module/plugins-it/google-grpc-it/google-grpc-1-8-it/pom.xml
  grpc/pom.xml
  pom.xml
Labels: dependencies

#11732 [#noissue] Fix deprecated API
  agent-module/agent-testweb/cassandra3-plugin-testweb/src/test/java/com/pinpoint/test/plugin/cassandra/CassandraTest.java
  agent-module/agent-testweb/cassandra4-plugin-testweb/src/test/java/com/pinpoint/test/plugin/cassandra/CassandraTest.java
  agent-module/plugins-it/activemq-it/activemq-5-15-it/src/test/java/com/navercorp/pinpoint/it/plugin/activemq/client/ActiveMQClientITBase.java
  agent-module/plugins-it/activemq-it/activemq-5-17-it/src/test/java/com/navercorp/pinpoint/it/plugin/activemq/client/ActiveMQClientITBase.java
  agent-module/plugins-it/cassandra-it/cassandra-2-it/src/test/java/com/navercorp/pinpoint/it/plugin/cassandra/CassandraServer.java
  agent-module/plugins-it/clickhouse-jdbc-it/src/test/java/com/navercorp/pinpoint/it/plugin/jdbc/clickhouse/ClickHouseITBase.java
  agent-module/plugins-it/gson-it/src/test/java/com/navercorp/pinpoint/it/plugin/gson/GsonIT.java
  agent-module/plugins-it/hbase-it/src/test/java/com/navercorp/pinpoint/it/plugin/hbase/HbaseClientIT.java
  agent-module/plugins-it/httpclient-it/httpclient-5-it/src/test/java/com/navercorp/pinpoint/it/plugin/httpclient5/ClosableAsyncHttpClientIT.java
  agent-module/plugins-it/kafka-it/kafka-2-it/src/test/java/test/pinpoint/plugin/kafka/TestConsumer.java
  agent-module/plugins-it/kafka-it/kafka-3-it/src/test/java/test/pinpoint/plugin/kafka/TestConsumer.java
  agent-module/plugins-it/netty-it/src/test/java/com/navercorp/pinpoint/it/plugin/netty/NettyIT.java
  agent-module/plugins-it/oracledb-it/oracledb-19-it/src/test/java/com/navercorp/pinpoint/it/plugin/jdbc/oracle/Oracle_IT_Base.java
  agent-module/plugins-test-module/plugins-it-utils-jdbc/src/main/java/com/navercorp/pinpoint/it/plugin/utils/jdbc/DataBaseTestCase.java
  agent-module/plugins/httpclient3/src/main/java/com/navercorp/pinpoint/plugin/httpclient3/HttpClient3EntityExtractor.java
  agent-module/plugins/ktor/src/main/java/com/navercorp/pinpoint/plugin/ktor/interceptor/HttpRequestAdaptor.java
  agent-module/plugins/ktor/src/main/java/com/navercorp/pinpoint/plugin/ktor/interceptor/MethodFilterExtractor.java
  agent-module/plugins/netty/src/main/java/com/navercorp/pinpoint/plugin/netty/NettyClientRequestWrapper.java
  agent-module/plugins/vertx/src/main/java/com/navercorp/pinpoint/plugin/vertx/VertxHttpClientRequestWrapper.java
Labels: cleanup

#11733 [#noissue] Cleanup
  agent-module/agent-testweb/httpclient5-plugin-testweb/src/main/java/com/pinpoint/test/plugin/HttpClient5PluginController.java
  collector/src/main/java/com/navercorp/pinpoint/collector/receiver/grpc/GrpcReceiver.java
  commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/parallel/ScanTask.java
  commons-server-cluster/pom.xml
  commons-server-cluster/src/main/java/com/navercorp/pinpoint/common/server/cluster/zookeeper/CreateNodeMessage.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/codec/stat/join/ActiveTraceCodec.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/codec/stat/join/CpuLoadCodec.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/codec/stat/join/DataSourceCodec.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/codec/stat/join/DirectBufferCodec.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/codec/stat/join/FileDescriptorCodec.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/codec/stat/join/LoadedClassCodec.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/codec/stat/join/MemoryCodec.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/codec/stat/join/ResponseTimeCodec.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/codec/stat/join/TotalThreadCountCodec.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/codec/stat/join/TransactionCodec.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/codec/stat/v2/AgentStatCodecV2.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/codec/stat/v2/DataSourceCodecV2.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/codec/stat/v2/JvmGcCodecV2.java
  hbase/hbase-schema/src/main/java/com/navercorp/pinpoint/hbase/schema/reader/xml/mapper/ColumnFamilyChangeMapper.java
  hbase/hbase-schema/src/main/java/com/navercorp/pinpoint/hbase/schema/service/HbaseSchemaServiceImpl.java
Labels: cleanup

#11736 [#noissue] Fix visibility of node histogram during concurrent execution
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/ApplicationMapBuilder.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/appender/histogram/DefaultNodeHistogramAppender.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/util/CancellableHistogramFactory.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/util/TimeoutWatcher.java
  web/src/test/java/com/navercorp/pinpoint/web/applicationmap/ApplicationMapBuilderTest.java
  web/src/test/java/com/navercorp/pinpoint/web/applicationmap/util/TimeoutWatcherTest.java
Labels: cleanup

#11734 [#noissue] Remove Thrift serializer
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/event/AgentEventBo.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/util/AgentEventMessageDeserializer.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/util/AgentEventMessageDeserializerV1.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/util/AgentEventMessageSerializer.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/util/AgentEventType.java
  commons-server/src/test/java/com/navercorp/pinpoint/common/server/util/AgentEventMessageSerDesTest.java
  web/src/main/java/com/navercorp/pinpoint/web/WebServiceConfig.java
  web/src/main/java/com/navercorp/pinpoint/web/mapper/AgentEventMapper.java
  web/src/main/java/com/navercorp/pinpoint/web/service/AgentEventServiceImpl.java
  web/src/main/java/com/navercorp/pinpoint/web/view/AgentEventSerializer.java
Labels: cleanup

#11735 [#noissue] Use general character to mark replaced tokens
  exceptiontrace/exceptiontrace-web/src/main/java/com/navercorp/pinpoint/exceptiontrace/web/mapper/CLPMapper.java
Labels: module:web

#11742 [#11729] Update agent's realipheader value to the list type.
  agent-module/agent/src/main/resources/profiles/local/pinpoint.config
  agent-module/agent/src/main/resources/profiles/release/pinpoint.config
  agent-module/bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/request/util/RealIpHeaderResolver.java
  agent-module/plugins/common-servlet/src/test/java/com/navercorp/pinpoint/plugin/common/servlet/RemoteAddressResolverFactoryTest.java
Labels: enhancement, module:plugin

#11743 [#noissue] Cleanup kafka test
  agent-module/plugins-it/kafka-it/kafka-2-it/src/test/java/com/navercorp/pinpoint/it/plugin/kafka/KafkaClient_0_11_x_IT.java
  agent-module/plugins-it/kafka-it/kafka-2-it/src/test/java/com/navercorp/pinpoint/it/plugin/kafka/KafkaClient_1_0_x_IT.java
  agent-module/plugins-it/kafka-it/kafka-2-it/src/test/java/com/navercorp/pinpoint/it/plugin/kafka/KafkaClient_1_1_x_IT.java
  agent-module/plugins-it/kafka-it/kafka-2-it/src/test/java/com/navercorp/pinpoint/it/plugin/kafka/KafkaClient_2_0_x_IT.java
  agent-module/plugins-it/kafka-it/kafka-2-it/src/test/java/com/navercorp/pinpoint/it/plugin/kafka/KafkaClient_2_2_x_IT.java
  agent-module/plugins-it/kafka-it/kafka-2-it/src/test/java/com/navercorp/pinpoint/it/plugin/kafka/KafkaClient_2_3_0_IT.java
  agent-module/plugins-it/kafka-it/kafka-2-it/src/test/java/com/navercorp/pinpoint/it/plugin/kafka/KafkaClient_2_3_1_to_max_IT.java
  agent-module/plugins-it/kafka-it/kafka-2-it/src/test/java/com/navercorp/pinpoint/it/plugin/kafka/KafkaClient_2_4_x_IT.java
  agent-module/plugins-it/kafka-it/kafka-2-it/src/test/java/com/navercorp/pinpoint/it/plugin/kafka/KafkaClient_2_5_x_IT.java
  agent-module/plugins-it/kafka-it/kafka-2-it/src/test/java/com/navercorp/pinpoint/it/plugin/kafka/KafkaClient_2_6_x_IT.java
  agent-module/plugins-it/kafka-it/kafka-2-it/src/test/java/com/navercorp/pinpoint/it/plugin/kafka/KafkaClient_2_7_x_IT.java
  agent-module/plugins-it/kafka-it/kafka-2-it/src/test/java/test/pinpoint/plugin/kafka/TestConsumer.java
  agent-module/plugins-it/kafka-it/kafka-2-it/src/test/java/test/pinpoint/plugin/kafka/TestProducer.java
  agent-module/plugins-it/kafka-it/kafka-3-it/src/test/java/com/navercorp/pinpoint/it/plugin/kafka/KafkaClient_2_8_x_3_IT.java
  agent-module/plugins-it/kafka-it/kafka-3-it/src/test/java/com/navercorp/pinpoint/it/plugin/kafka/KafkaClient_3_0_x_3_IT.java
  agent-module/plugins-it/kafka-it/kafka-3-it/src/test/java/com/navercorp/pinpoint/it/plugin/kafka/KafkaClient_3_1_x_3_IT.java
  agent-module/plugins-it/kafka-it/kafka-3-it/src/test/java/com/navercorp/pinpoint/it/plugin/kafka/KafkaClient_3_2_x_3_IT.java
  agent-module/plugins-it/kafka-it/kafka-3-it/src/test/java/com/navercorp/pinpoint/it/plugin/kafka/KafkaStreams_2_5_x_IT.java
  agent-module/plugins-it/kafka-it/kafka-3-it/src/test/java/com/navercorp/pinpoint/it/plugin/kafka/KafkaStreams_2_6_2_x_IT.java
  agent-module/plugins-it/kafka-it/kafka-3-it/src/test/java/com/navercorp/pinpoint/it/plugin/kafka/KafkaStreams_2_6_x_IT.java
  agent-module/plugins-it/kafka-it/kafka-3-it/src/test/java/com/navercorp/pinpoint/it/plugin/kafka/KafkaStreams_2_7_x_IT.java
  agent-module/plugins-it/kafka-it/kafka-3-it/src/test/java/com/navercorp/pinpoint/it/plugin/kafka/KafkaStreams_2_8_x_IT.java
  agent-module/plugins-it/kafka-it/kafka-3-it/src/test/java/com/navercorp/pinpoint/it/plugin/kafka/KafkaStreams_3_0_x_IT.java
  agent-module/plugins-it/kafka-it/kafka-3-it/src/test/java/com/navercorp/pinpoint/it/plugin/kafka/KafkaStreams_3_1_x_IT.java
  agent-module/plugins-it/kafka-it/kafka-3-it/src/test/java/com/navercorp/pinpoint/it/plugin/kafka/KafkaStreams_3_2_x_IT.java
  agent-module/plugins-it/kafka-it/kafka-3-it/src/test/java/com/navercorp/pinpoint/it/plugin/kafka/KafkaStreams_3_3_x_IT.java
  agent-module/plugins-it/kafka-it/kafka-3-it/src/test/java/com/navercorp/pinpoint/it/plugin/kafka/KafkaStreams_3_4_x_IT.java
  agent-module/plugins-it/kafka-it/kafka-3-it/src/test/java/test/pinpoint/plugin/kafka/TestProducer.java
Labels: cleanup

#11750 [#noissue] Remove deprecated Charsets.java
  commons/src/main/java/com/navercorp/pinpoint/common/Charsets.java
Labels: cleanup

#11749 [#noissue] Move commons.task package to commons-server module
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/task/TimerTaskDecorator.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/task/TimerTaskDecoratorFactory.java
  realtime/realtime-web/src/main/java/com/navercorp/pinpoint/web/realtime/activethread/count/service/ActiveThreadCountServiceImpl.java
  web/src/main/java/com/navercorp/pinpoint/web/realtime/RealtimeConfig.java
  web/src/main/java/com/navercorp/pinpoint/web/websocket/PinpointWebSocketTimerTaskDecoratorFactory.java
  web/src/test/java/com/navercorp/pinpoint/web/websocket/PinpointWebSocketTimerTaskDecoratorTest.java
Labels: cleanup

#11748 [#noissue] Fix `testRecordNotChainedException` test failure
  agent-module/profiler/src/test/java/com/navercorp/pinpoint/profiler/metadata/DefaultExceptionRecorderTest.java
Labels: module:agent, module:test

#11759 [#11758] Separate banner into module
  agent-module/bootstraps/bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/PinpointStarter.java
  agent-module/bootstraps/bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/banner/PinpointBannerImpl.java
  agent-module/profiler/pom.xml
  agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/DefaultAgent.java
  banner/README.md
  banner/pom.xml
  banner/src/main/java-templates/com/navercorp/pinpoint/banner/BannerVersionTemplate.java
  banner/src/main/java/com/navercorp/pinpoint/banner/Banner.java
  banner/src/main/java/com/navercorp/pinpoint/banner/BannerUtils.java
  banner/src/main/java/com/navercorp/pinpoint/banner/Mode.java
  banner/src/main/java/com/navercorp/pinpoint/banner/PinpointBanner.java
  banner/src/main/resources/pinpoint-banner/banner.txt
  banner/src/test/java/com/navercorp/pinpoint/banner/BannerUtilsTest.java
  banner/src/test/java/com/navercorp/pinpoint/banner/PinpointBannerTest.java
  banner/src/test/resources/log4j2-test.xml
  commons-server/pom.xml
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/banner/PinpointSpringBanner.java
  commons/src/main/java/com/navercorp/pinpoint/common/banner/PinpointBanner.java
  pom.xml
Labels: cleanup

#11760 [#noissue] Delete testcase directory
  testcase/pom.xml
  testcase/src/main/java/com/navercorp/pinpoint/testcase/util/SocketUtils.java
  testcase/src/main/resources/log4j2-test.xml
Labels: cleanup

#11761 [#noissue] Memory Optimization for ChainedTaskDecorator
  web/src/main/java/com/navercorp/pinpoint/web/task/ChainedTaskDecorator.java
Labels: cleanup

#11762 [#noissue] Apply junit AutoClose
  agent-module/profiler/src/test/java/com/navercorp/pinpoint/profiler/context/DefaultServerMetaDataRegistryServiceTest.java
  agent-module/profiler/src/test/java/com/navercorp/pinpoint/profiler/sender/grpc/stream/StreamExecutorTest.java
  web/src/test/java/com/navercorp/pinpoint/web/applicationmap/ApplicationMapBuilderTest.java
  web/src/test/java/com/navercorp/pinpoint/web/applicationmap/appender/histogram/NodeHistogramAppenderTest.java
  web/src/test/java/com/navercorp/pinpoint/web/applicationmap/service/FilteredMapServiceImplTest.java
  web/src/test/java/com/navercorp/pinpoint/web/task/ChainedTaskDecoratorTest.java
  web/src/test/java/com/navercorp/pinpoint/web/task/RequestContextPropagatingTaskDecoratorTest.java
  web/src/test/java/com/navercorp/pinpoint/web/task/SecurityContextPropagatingTaskDecoratorTest.java
Labels: cleanup

#11764 [#11763] Bump maven-compiler-plugin from 3.11.0 to 3.13.0
  pom.xml
Labels: dependencies

#11766 [#noissue] Bump slash-command-dispatch from v2 to v4
  .github/workflows/slash-command-dispatch.yml
Labels: dependencies

#11767 [#noissue] Replace ChainedTaskDecorator with CompositeTaskDecorator
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/config/ApplicationMapModule.java
  web/src/main/java/com/navercorp/pinpoint/web/task/ChainedTaskDecorator.java
  web/src/test/java/com/navercorp/pinpoint/web/task/ChainedTaskDecoratorTest.java
Labels: cleanup

#11769 [#11768] Migrate TimerTaskDecorator to TaskDecorator
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/task/TaskDecoratorFactory.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/task/TimerTaskDecorator.java
  realtime/realtime-web/src/main/java/com/navercorp/pinpoint/web/realtime/activethread/count/service/ActiveThreadCountServiceImpl.java
  web/src/main/java/com/navercorp/pinpoint/web/realtime/RealtimeConfig.java
  web/src/main/java/com/navercorp/pinpoint/web/websocket/WebSocketTaskDecoratorFactory.java
  web/src/test/java/com/navercorp/pinpoint/web/websocket/WebSocketTaskDecoratorFactoryTest.java
Labels: cleanup

#11770 [#11745] Apply Version templating to plugin-test module
  agent-module/plugins-test-module/plugins-test/pom.xml
  agent-module/plugins-test-module/plugins-test/src/main/java-templates/com/navercorp/pinpoint/test/plugin/Log4j2VersionTemplate.java
  agent-module/plugins-test-module/plugins-test/src/main/java-templates/com/navercorp/pinpoint/test/plugin/PluginEngineTemplate.java
  agent-module/plugins-test-module/plugins-test/src/main/java/com/navercorp/pinpoint/test/plugin/DefaultPluginTestSuite.java
  agent-module/plugins-test-module/plugins-test/src/main/java/com/navercorp/pinpoint/test/plugin/LibraryFilter.java
  agent-module/plugins-test-module/plugins-test/src/main/java/com/navercorp/pinpoint/test/plugin/PluginClassLoading.java
  agent-module/plugins-test-module/plugins-test/src/main/java/com/navercorp/pinpoint/test/plugin/util/StringUtils.java
  agent-module/plugins-test-module/plugins-test/src/main/java/com/navercorp/pinpoint/test/plugin/util/TestPluginVersion.java
  agent-module/plugins-test-module/plugins-test/src/main/java/com/navercorp/pinpoint/test/plugin/util/VersionUtils.java
  agent-module/plugins-test-module/plugins-test/src/main/resources/testplugin-version.properties
  agent-module/plugins-test-module/plugins-test/src/test/java/com/navercorp/pinpoint/test/plugin/LibraryFinderTest.java
Labels: cleanup

#11771 [#noissue] Reduce commons dependency of test-plugin
  agent-module/plugins-test-module/plugins-test/src/main/java/com/navercorp/pinpoint/test/plugin/AbstractPluginForkedTestSuite.java
  agent-module/plugins-test-module/plugins-test/src/main/java/com/navercorp/pinpoint/test/plugin/AbstractPluginTestSuite.java
  agent-module/plugins-test-module/plugins-test/src/main/java/com/navercorp/pinpoint/test/plugin/DefaultPluginForkedTestSuite.java
  agent-module/plugins-test-module/plugins-test/src/main/java/com/navercorp/pinpoint/test/plugin/DefaultPluginTestSuite.java
  agent-module/plugins-test-module/plugins-test/src/main/java/com/navercorp/pinpoint/test/plugin/PluginClassLoading.java
  agent-module/plugins-test-module/plugins-test/src/main/java/com/navercorp/pinpoint/test/plugin/agent/classloader/MockInstrumentor.java
  agent-module/plugins-test-module/plugins-test/src/main/java/com/navercorp/pinpoint/test/plugin/classloader/PluginTestJunitTestClassLoader.java
  agent-module/plugins-test-module/plugins-test/src/main/java/com/navercorp/pinpoint/test/plugin/classloader/predicates/IsJdkPackage.java
  agent-module/plugins-test-module/plugins-test/src/main/java/com/navercorp/pinpoint/test/plugin/maven/DependencyResolver.java
  agent-module/plugins-test-module/plugins-test/src/main/java/com/navercorp/pinpoint/test/plugin/maven/DependencyResolverFactory.java
  agent-module/plugins-test-module/plugins-test/src/main/java/com/navercorp/pinpoint/test/plugin/maven/DependencyVersionFilter.java
  agent-module/plugins-test-module/plugins-test/src/main/java/com/navercorp/pinpoint/test/plugin/maven/MavenCentral.java
  agent-module/plugins-test-module/plugins-test/src/main/java/com/navercorp/pinpoint/test/plugin/shared/ReflectionDependencyResolver.java
  agent-module/plugins-test-module/plugins-test/src/main/java/com/navercorp/pinpoint/test/plugin/util/ArrayUtils.java
  agent-module/plugins-test-module/plugins-test/src/main/java/com/navercorp/pinpoint/test/plugin/util/ClassPath.java
  agent-module/plugins-test-module/plugins-test/src/main/java/com/navercorp/pinpoint/test/plugin/util/IOUtils.java
  agent-module/plugins-test-module/plugins-test/src/main/java/com/navercorp/pinpoint/test/plugin/util/JvmUtils.java
  agent-module/plugins-test-module/plugins-test/src/main/java/com/navercorp/pinpoint/test/plugin/util/MapUtils.java
  agent-module/plugins-test-module/plugins-test/src/main/java/com/navercorp/pinpoint/test/plugin/util/OsUtils.java
  agent-module/plugins-test-module/plugins-test/src/test/java/com/navercorp/pinpoint/test/plugin/DependencyVersionFilterTest.java
  agent-module/plugins-test-module/plugins-test/src/test/java/com/navercorp/pinpoint/test/plugin/maven/DependencyResolverTest.java
  agent-module/plugins-test-module/plugins-test/src/test/java/com/navercorp/pinpoint/test/plugin/maven/DependencyVersionFilterTest.java
  agent-module/plugins-test-module/plugins-test/src/test/java/com/navercorp/pinpoint/test/plugin/maven/MavenCentralTest.java
  agent-module/plugins-test-module/plugins-test/src/test/java/com/navercorp/pinpoint/test/plugin/util/JvmUtilsTest.java
Labels: cleanup

#11772 [#11768] Cleanup
  web/src/test/java/com/navercorp/pinpoint/web/websocket/WebSocketTaskDecoratorFactoryTest.java
Labels: cleanup

#11774 [#noissue] Cleanup plugins-test
  agent-module/plugins-test-module/plugins-test/src/main/java/com/navercorp/pinpoint/test/plugin/AbstractPluginForkedTestSuite.java
  agent-module/plugins-test-module/plugins-test/src/main/java/com/navercorp/pinpoint/test/plugin/AbstractPluginTestSuite.java
  agent-module/plugins-test-module/plugins-test/src/main/java/com/navercorp/pinpoint/test/plugin/LibraryFilter.java
  agent-module/plugins-test-module/plugins-test/src/main/java/com/navercorp/pinpoint/test/plugin/PluginClassLoading.java
  agent-module/plugins-test-module/plugins-test/src/main/java/com/navercorp/pinpoint/test/plugin/util/JavaHomeResolver.java
  agent-module/plugins-test-module/plugins-test/src/main/java/com/navercorp/pinpoint/test/plugin/util/PathUtils.java
  agent-module/plugins-test-module/plugins-test/src/test/java/com/navercorp/pinpoint/test/plugin/LibraryFinderTest.java
  agent-module/plugins-test-module/plugins-test/src/test/java/com/navercorp/pinpoint/test/plugin/util/PathUtilsTest.java
Labels: cleanup
