Repository pinpoint-apm/pinpoint, pull requests merged in 2024-09, with the labels that each got.

#11444 [#11379] Remove unnecessary Math.abs
  commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/async/AsyncPollingPutWriter.java
  commons-hbase/src/test/java/com/navercorp/pinpoint/common/hbase/async/AsyncPollingPutWriterTest.java
Labels: cleanup

#11445 [#11431] Striping span connection
  collector/src/main/java/com/navercorp/pinpoint/collector/CollectorHbaseModule.java
  collector/src/main/resources/hbase-root.properties
  commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/async/AsyncConnectionFactoryBean.java
  commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/async/AsyncPollerOption.java
  commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/async/AsyncTableWriterSelectorFactory.java
  commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/async/ConnectionSelector.java
  commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/async/RoundRobinSelector.java
  commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/async/SimpleConnectionSelector.java
  commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/config/HbasePutWriterConfiguration.java
  commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/config/HbaseTemplateConfiguration.java
  commons-hbase/src/test/java/com/navercorp/pinpoint/common/hbase/async/RoundRobinSelectorTest.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/hbase/config/HbaseClientConfiguration.java
Labels: module:collector

#11451 [#noissue] Return original object when pattern does not match
  exceptiontrace/exceptiontrace-web/src/main/java/com/navercorp/pinpoint/exceptiontrace/web/mapper/CLPMapper.java
  exceptiontrace/exceptiontrace-web/src/test/java/com/navercorp/pinpoint/exceptiontrace/web/mapper/CLPMapperTest.java
Labels: module:web

#11455 [#11414] Update exceptionTrace table configuration
  exceptiontrace/exceptiontrace-common/src/main/pinot/pinot-exceptionTrace-offline-table.json
  exceptiontrace/exceptiontrace-common/src/main/pinot/pinot-exceptionTrace-realtime-table.json
Labels: configuration

#11456 [#noissue] Cleanup
  exceptiontrace/exceptiontrace-web/src/main/java/com/navercorp/pinpoint/exceptiontrace/web/mapper/CLPMapper.java
Labels: module:web

#11450 [#11449] Trim long sql from agent
  agent-module/bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/config/DefaultProfilerConfig.java
  agent-module/bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/config/ProfilerConfig.java
  agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/context/provider/metadata/SqlMetadataServiceProvider.java
  agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/metadata/SqlCacheService.java
  agent-module/profiler/src/test/java/com/navercorp/pinpoint/profiler/metadata/SqlCacheServiceTest.java
  agent-module/profiler/src/test/java/com/navercorp/pinpoint/profiler/metadata/SqlUidMetaDataServiceTest.java
Labels: module:agent

#11458 [#noissue] Cleanup SqlUidMetaDataServiceTest
  agent-module/profiler/src/test/java/com/navercorp/pinpoint/profiler/metadata/SqlUidMetaDataServiceTest.java
Labels: test

#11460 [#10776] Rename chart type. Change keyname of response format of metric data api
  otlpmetric/otlpmetric-common/src/main/java/com/navercorp/pinpoint/otlp/common/web/definition/property/ChartType.java
  otlpmetric/otlpmetric-web/src/main/java/com/navercorp/pinpoint/otlp/web/view/MetricDataView.java
  otlpmetric/otlpmetric-web/src/main/java/com/navercorp/pinpoint/otlp/web/view/legacy/OtlpChartViewBuilder.java
Labels: enhancement, module:otlpmetric

#11461 [#10776] Add a setting to allow the metric to represent data as a stack.
  otlpmetric/otlpmetric-common/src/main/java/com/navercorp/pinpoint/otlp/common/web/defined/AppMetricDefinition.java
Labels: module:otlpmetric

#11418 [#11417] Add telelgraf proctstat fd metric
  metric-module/metric/src/main/resources/pinot-web/telegraf-metric.yml
  metric-module/metric/src/main/telegraf/pinpoint-telegraf.conf
Labels: module:metric

#11452 [#noissue] Cleanup Kafka-It
  agent-module/plugins-it/kafka-it/kafka-2-it/pom.xml
  agent-module/plugins-it/kafka-it/kafka-2-it/src/test/java/com/navercorp/pinpoint/it/plugin/kafka/KafkaClient_0_11_x_IT.java
  agent-module/plugins-it/kafka-it/kafka-2-it/src/test/java/com/navercorp/pinpoint/it/plugin/kafka/KafkaClient_1_0_x_IT.java
  agent-module/plugins-it/kafka-it/kafka-2-it/src/test/java/com/navercorp/pinpoint/it/plugin/kafka/KafkaClient_1_1_x_IT.java
  agent-module/plugins-it/kafka-it/kafka-2-it/src/test/java/com/navercorp/pinpoint/it/plugin/kafka/KafkaClient_2_0_x_IT.java
  agent-module/plugins-it/kafka-it/kafka-2-it/src/test/java/com/navercorp/pinpoint/it/plugin/kafka/KafkaClient_2_2_x_IT.java
  agent-module/plugins-it/kafka-it/kafka-2-it/src/test/java/com/navercorp/pinpoint/it/plugin/kafka/KafkaClient_2_3_0_IT.java
  agent-module/plugins-it/kafka-it/kafka-2-it/src/test/java/com/navercorp/pinpoint/it/plugin/kafka/KafkaClient_2_3_1_to_max_IT.java
  agent-module/plugins-it/kafka-it/kafka-2-it/src/test/java/com/navercorp/pinpoint/it/plugin/kafka/KafkaClient_2_4_x_IT.java
  agent-module/plugins-it/kafka-it/kafka-2-it/src/test/java/com/navercorp/pinpoint/it/plugin/kafka/KafkaClient_2_5_x_IT.java
  agent-module/plugins-it/kafka-it/kafka-2-it/src/test/java/com/navercorp/pinpoint/it/plugin/kafka/KafkaClient_2_6_x_IT.java
  agent-module/plugins-it/kafka-it/kafka-2-it/src/test/java/com/navercorp/pinpoint/it/plugin/kafka/KafkaClient_2_7_x_IT.java
  agent-module/plugins-it/kafka-it/kafka-2-it/src/test/java/com/navercorp/pinpoint/it/plugin/kafka/util/TempDirectory.java
  agent-module/plugins-it/kafka-it/kafka-2-it/src/test/java/test/pinpoint/plugin/kafka/Kafka2UnitServer.java
  agent-module/plugins-it/kafka-it/kafka-2-it/src/test/java/test/pinpoint/plugin/kafka/KafkaUnitServer.java
  agent-module/plugins-it/kafka-it/kafka-2-it/src/test/java/test/pinpoint/plugin/kafka/ZookeeperUnitServer.java
  agent-module/plugins-it/kafka-it/kafka-3-it/pom.xml
  agent-module/plugins-it/kafka-it/kafka-3-it/src/test/java/com/navercorp/pinpoint/it/plugin/kafka/KafkaClient_2_8_x_3_IT.java
  agent-module/plugins-it/kafka-it/kafka-3-it/src/test/java/com/navercorp/pinpoint/it/plugin/kafka/KafkaClient_3_0_x_3_IT.java
  agent-module/plugins-it/kafka-it/kafka-3-it/src/test/java/com/navercorp/pinpoint/it/plugin/kafka/KafkaClient_3_1_x_3_IT.java
  agent-module/plugins-it/kafka-it/kafka-3-it/src/test/java/com/navercorp/pinpoint/it/plugin/kafka/KafkaClient_3_2_x_3_IT.java
  agent-module/plugins-it/kafka-it/kafka-3-it/src/test/java/com/navercorp/pinpoint/it/plugin/kafka/KafkaStreams_2_5_x_IT.java
  agent-module/plugins-it/kafka-it/kafka-3-it/src/test/java/com/navercorp/pinpoint/it/plugin/kafka/KafkaStreams_2_6_2_x_IT.java
  agent-module/plugins-it/kafka-it/kafka-3-it/src/test/java/com/navercorp/pinpoint/it/plugin/kafka/KafkaStreams_2_6_x_IT.java
  agent-module/plugins-it/kafka-it/kafka-3-it/src/test/java/com/navercorp/pinpoint/it/plugin/kafka/KafkaStreams_2_7_x_IT.java
  agent-module/plugins-it/kafka-it/kafka-3-it/src/test/java/com/navercorp/pinpoint/it/plugin/kafka/KafkaStreams_2_8_x_IT.java
  agent-module/plugins-it/kafka-it/kafka-3-it/src/test/java/com/navercorp/pinpoint/it/plugin/kafka/KafkaStreams_3_0_x_IT.java
  agent-module/plugins-it/kafka-it/kafka-3-it/src/test/java/com/navercorp/pinpoint/it/plugin/kafka/KafkaStreams_3_1_x_IT.java
  agent-module/plugins-it/kafka-it/kafka-3-it/src/test/java/com/navercorp/pinpoint/it/plugin/kafka/KafkaStreams_3_2_x_IT.java
  agent-module/plugins-it/kafka-it/kafka-3-it/src/test/java/com/navercorp/pinpoint/it/plugin/kafka/KafkaStreams_3_3_x_IT.java
  agent-module/plugins-it/kafka-it/kafka-3-it/src/test/java/com/navercorp/pinpoint/it/plugin/kafka/KafkaStreams_3_4_x_IT.java
  agent-module/plugins-it/kafka-it/kafka-3-it/src/test/java/test/pinpoint/plugin/kafka/Kafka3UnitServer.java
  agent-module/plugins-it/kafka-it/kafka-3-it/src/test/java/test/pinpoint/plugin/kafka/KafkaUnitServer.java
  agent-module/plugins-it/kafka-it/kafka-3-it/src/test/java/test/pinpoint/plugin/kafka/TestConsumer.java
  agent-module/plugins-it/kafka-it/kafka-3-it/src/test/java/test/pinpoint/plugin/kafka/ZookeeperUnitServer.java
Labels: cleanup

#11453 [#issue] Cleaneup filter in plugin test
  agent-module/plugins-test-module/plugins-test/src/main/java/com/navercorp/pinpoint/test/plugin/classloader/PluginTestClassLoader.java
  agent-module/plugins-test-module/plugins-test/src/main/java/com/navercorp/pinpoint/test/plugin/classloader/PluginTestJunitTestClassLoader.java
  agent-module/plugins-test-module/plugins-test/src/main/java/com/navercorp/pinpoint/test/plugin/classloader/predicates/IsFastXmlPackage.java
  agent-module/plugins-test-module/plugins-test/src/main/java/com/navercorp/pinpoint/test/plugin/classloader/predicates/IsJdkPackage.java
  agent-module/plugins-test-module/plugins-test/src/main/java/com/navercorp/pinpoint/test/plugin/classloader/predicates/IsJunitPackage.java
  agent-module/plugins-test-module/plugins-test/src/main/java/com/navercorp/pinpoint/test/plugin/classloader/predicates/IsLogPackage.java
  agent-module/plugins-test-module/plugins-test/src/main/java/com/navercorp/pinpoint/test/plugin/classloader/predicates/IsPinpointBootstrapPluginTestPackage.java
  agent-module/plugins-test-module/plugins-test/src/main/java/com/navercorp/pinpoint/test/plugin/classloader/predicates/IsPinpointCommonPackage.java
  agent-module/plugins-test-module/plugins-test/src/main/java/com/navercorp/pinpoint/test/plugin/classloader/predicates/IsPinpointPackage.java
  agent-module/plugins-test-module/plugins-test/src/main/java/com/navercorp/pinpoint/test/plugin/classloader/predicates/IsPinpointTestAgentPackage.java
  agent-module/plugins-test-module/plugins-test/src/main/java/com/navercorp/pinpoint/test/plugin/classloader/predicates/IsPinpointTestPackage.java
  agent-module/plugins-test-module/plugins-test/src/main/java/com/navercorp/pinpoint/test/plugin/classloader/predicates/PackageFilter.java
  agent-module/plugins-test-module/plugins-test/src/test/java/com/navercorp/pinpoint/test/plugin/classloader/predicates/IsPinpointPackageTest.java
Labels: cleanup

#11465 [#noissue] Remove unnecessary log4j dependency
  agent-module/plugins-it/clickhouse-jdbc-it/src/test/java/com/navercorp/pinpoint/it/plugin/jdbc/clickhouse/ClickHouse_0_3_2_IT.java
  agent-module/plugins-it/clickhouse-jdbc-it/src/test/java/com/navercorp/pinpoint/it/plugin/jdbc/clickhouse/ClickHouse_0_4_x_IT.java
  agent-module/plugins-it/kotlin-coroutines-it/src/test/java/com/navercorp/pinpoint/it/plugin/kotlinx/coroutines/CoroutinesIT.java
  agent-module/plugins-it/kotlin-coroutines-it/src/test/java/com/navercorp/pinpoint/it/plugin/kotlinx/coroutines/Coroutines_1_6_IT.java
  agent-module/plugins-it/mysql-jdbc-driver-plugin-it/src/test/java/com/navercorp/pinpoint/it/plugin/jdbc/mysql/MySqlConnection_6_X_IT.java
  agent-module/plugins-it/mysql-jdbc-driver-plugin-it/src/test/java/com/navercorp/pinpoint/it/plugin/jdbc/mysql/MySqlLoadBalance_5_X_IT.java
  agent-module/plugins-it/mysql-jdbc-driver-plugin-it/src/test/java/com/navercorp/pinpoint/it/plugin/jdbc/mysql/MySqlLoadBalance_6_X_IT.java
  agent-module/plugins-it/mysql-jdbc-driver-plugin-it/src/test/java/com/navercorp/pinpoint/it/plugin/jdbc/mysql/MySql_8_X_IT.java
  agent-module/plugins-it/paho-mqtt-it/src/test/java/com/navercorp/pinpoint/it/plugin/paho/mqtt/PahoMqttV3ClientIT.java
  agent-module/plugins-it/paho-mqtt-it/src/test/java/com/navercorp/pinpoint/it/plugin/paho/mqtt/PahoMqttV5ClientIT.java
  agent-module/plugins-it/postgresql-jdbc-it/src/test/java/com/navercorp/pinpoint/it/plugin/jdbc/postgresql/PostgreSql_9_4_1207_IT.java
  agent-module/plugins-it/postgresql-jdbc-it/src/test/java/com/navercorp/pinpoint/it/plugin/jdbc/postgresql/PostgreSql_9_x_to_9_4_1207_IT.java
Labels: cleanup

#11467 [#11468] Bump jsonassert to 1.5.3
  pom.xml
  web/pom.xml
Labels: cleanup

#11470 [#11469] Bump HdrHistogram to 2.2.2
  pom.xml
Labels: dependencies

#11472 [#11471] Bump commons-logging from 1.2.0 to 1.3.4
  agent-module/plugins-it/paho-mqtt-it/pom.xml
  pom.xml
Labels: dependencies

#11474 [#11473] Bump commons-cli to 1.9.0
  pom.xml
Labels: dependencies

#11476 [#11475] Bump perfmark-api to 0.27.0
  pom.xml
Labels: dependencies

#11477 [#noissue] Cleanup log4j dependency
  pom.xml
Labels: dependencies

#11478 [#noissue] Cleanup it test
  agent-module/agent-testweb/grpc-plugin-testweb/src/main/java/com/pinpoint/test/plugin/HelloWorldStreamClient.java
  agent-module/plugins-it/cassandra-it/cassandra-2-it/src/test/java/com/navercorp/pinpoint/it/plugin/cassandra/CassandraDatastaxITBase.java
  agent-module/plugins-it/cassandra-it/cassandra-4-it/src/test/java/com/navercorp/pinpoint/it/plugin/cassandra/CassandraDatastaxITBase.java
  agent-module/plugins-it/druid-it/src/test/java/com/navercorp/pinpoint/it/plugin/druid/DruidIT.java
  agent-module/plugins-it/dubbo-it/src/test/java/com/navercorp/pinpoint/it/plugin/dubbo/consumer/DubboConsumerIT.java
  agent-module/plugins-it/dubbo-it/src/test/java/com/navercorp/pinpoint/it/plugin/dubbo/provider/DubboProviderIT.java
  agent-module/plugins-it/google-grpc-it/google-grpc-1-42-it/src/test/java/com/navercorp/pinpoint/it/plugin/grpc/BuilderUtils.java
  agent-module/plugins-it/google-grpc-it/google-grpc-1-42-it/src/test/java/com/navercorp/pinpoint/it/plugin/grpc/HelloWorldStreamClient.java
  agent-module/plugins-it/google-grpc-it/google-grpc-1-8-it/src/test/java/com/navercorp/pinpoint/it/plugin/grpc/BuilderUtils.java
  agent-module/plugins-it/google-grpc-it/google-grpc-1-8-it/src/test/java/com/navercorp/pinpoint/it/plugin/grpc/GrpcITBase.java
  agent-module/plugins-it/google-grpc-it/google-grpc-1-8-it/src/test/java/com/navercorp/pinpoint/it/plugin/grpc/HelloWorldStreamClient.java
  agent-module/plugins-it/httpclient-it/httpclient-3-it/src/test/java/com/navercorp/pinpoint/it/plugin/httpclient3/HttpClientIT.java
  agent-module/plugins-it/hystrix-it/src/test/java/com/navercorp/pinpoint/it/plugin/hystrix/HystrixTestHelper.java
  agent-module/plugins-it/hystrix-it/src/test/java/com/navercorp/pinpoint/it/plugin/hystrix/commands/SayHelloCommand.java
  agent-module/plugins-it/hystrix-it/src/test/java/com/navercorp/pinpoint/it/plugin/hystrix/commands/SayHelloObservableCommand.java
  agent-module/plugins-it/informix-jdbc-it/src/test/java/com/navercorp/pinpoint/it/plugin/jdbc/informix/InformixConnectionIT.java
  agent-module/plugins-it/informix-jdbc-it/src/test/java/com/navercorp/pinpoint/it/plugin/jdbc/informix/InformixServer.java
  agent-module/plugins-it/jtds-it/src/test/java/com/navercorp/pinpoint/it/plugin/jdbc/jtds/JtdsIT.java
  agent-module/plugins-it/kafka-it/kafka-2-it/src/test/java/test/pinpoint/plugin/kafka/KafkaITConstants.java
  agent-module/plugins-it/kafka-it/kafka-3-it/src/test/java/test/pinpoint/plugin/kafka/KafkaITConstants.java
  agent-module/plugins-it/kotlin-coroutines-it/src/test/java/com/navercorp/pinpoint/it/plugin/kotlinx/coroutines/CoroutinesIT.java
  agent-module/plugins-it/kotlin-coroutines-it/src/test/java/com/navercorp/pinpoint/it/plugin/kotlinx/coroutines/Coroutines_1_6_IT.java
  agent-module/plugins-it/lambda-it/src/test/java/com/navercorp/pinpoint/it/plugin/lambda/LambdaIT.java
  agent-module/plugins-it/mariadb-jdbc-it/src/test/java/com/navercorp/pinpoint/it/plugin/jdbc/PreparedStatementType.java
  agent-module/plugins-it/mongodb-it/mongodb-4-it/src/test/java/com/navercorp/pinpoint/it/plugin/mongodb4/MongoDBITHelper.java
  agent-module/plugins-it/okhttp-it/src/test/java/com/navercorp/pinpoint/it/plugin/okhttp/OkHttpClient_3_0_0_to_3_3_x_IT.java
  agent-module/plugins-it/okhttp-it/src/test/java/com/navercorp/pinpoint/it/plugin/okhttp/OkHttpClient_3_4_0_BaseIT.java
  agent-module/plugins-it/rabbitmq-it/src/test/java/test/pinpoint/plugin/rabbitmq/MessageConverter.java
  agent-module/plugins-it/thread-it/src/test/java/test/one/MockCallable.java
  agent-module/plugins-it/thread-it/src/test/java/test/one/MockRunnable.java
  agent-module/plugins-it/thread-it/src/test/java/test/two/MockRunnable.java
  agent-module/plugins-it/thrift-it/thrift-0-10-it/src/test/java/com/navercorp/pinpoint/it/plugin/thrift/common/client/EchoTestClient.java
  agent-module/plugins-it/thrift-it/thrift-0-14-it/src/test/java/com/navercorp/pinpoint/it/plugin/thrift/common/client/EchoTestClient.java
Labels: cleanup

#11480 [#9631] Fix query error when a specific agentId is provided
  exceptiontrace/exceptiontrace-web/src/main/resources/exceptiontrace/mapper/ExceptionGroupMapper.xml
Labels: module:web

#11483 [#11481] Fix DirectByteBuffer leak in ActiveThreadCount
  agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/receiver/grpc/ActiveThreadCountStreamSocket.java
  agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/receiver/grpc/GrpcActiveThreadCountService.java
  agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/receiver/grpc/GrpcProfilerStreamSocket.java
  agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/receiver/grpc/GrpcStreamService.java
  agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/receiver/grpc/PinpointClientResponseObserver.java
  agent-module/profiler/src/test/java/com/navercorp/pinpoint/profiler/receiver/grpc/PinpointClientResponseObserverTest.java
Labels: bug, module:agent

#11485 [#11328] remove ping event check
  web/src/main/java/com/navercorp/pinpoint/web/controller/ApplicationController.java
  web/src/main/java/com/navercorp/pinpoint/web/service/AgentInfoService.java
  web/src/main/java/com/navercorp/pinpoint/web/service/AgentInfoServiceImpl.java
Labels: module:web

#11490 [#11489] Bump reactor-bom to 2023.0.9
  agent-module/agent-testweb/reactor-netty-plugin-testweb/pom.xml
  agent-module/agent-testweb/spring-data-r2dbc-plugin-testweb/pom.xml
  agent-module/plugins-it/spring-data-r2dbc-it/pom.xml
  pom.xml
Labels: dependencies

#11495 [#11489] Cleanup reactor dependency
  agent-module/agent-testweb/reactor-netty-plugin-testweb/pom.xml
  agent-module/plugins-it/spring-data-r2dbc-it/pom.xml
  agent-module/plugins/bom/pom.xml
  agent-module/plugins/reactor-netty/pom.xml
Labels: dependencies

#11505 [#noissue] Cleanup
  agent-module/plugins-test-module/plugins-test/src/main/java/com/navercorp/pinpoint/test/plugin/DependencyResolver.java
Labels: cleanup

#11507 [#11506] Update MSSQL docker images
  agent-module/agent-testweb/spring-data-r2dbc-plugin-testweb/src/test/java/com/pinpoint/test/plugin/spring/data/r2dbc/R2dbcMssqlTest.java
  agent-module/agent-testweb/spring-data-r2dbc-plugin-testweb/src/test/resources/container-license-acceptance.txt
  agent-module/plugins-it/jtds-it/src/test/java/com/navercorp/pinpoint/it/plugin/jdbc/jtds/JtdsConnectionIT.java
  agent-module/plugins-it/jtds-it/src/test/java/com/navercorp/pinpoint/it/plugin/jdbc/jtds/MsSqlServer.java
  agent-module/plugins-it/mssql-jdbc-it/src/test/java/com/navercorp/pinpoint/it/plugin/jdbc/mssql/MSSQLServerContainerFactory.java
  agent-module/plugins-it/spring-data-r2dbc-it/src/test/java/com/navercorp/pinpoint/it/plugin/jdbc/r2dbc/MssqlServer.java
Labels: cleanup

#11500 [#11267] Add Hbase client side metrics
  collector-monitor/pom.xml
  collector-monitor/src/main/java/com/navercorp/pinpoint/collector/monitor/config/HbaseConnectionReflects.java
  collector-monitor/src/main/java/com/navercorp/pinpoint/collector/monitor/config/HbaseMetricsConfiguration.java
  collector-monitor/src/main/java/com/navercorp/pinpoint/collector/monitor/dao/hbase/HBaseMetricsAdapter.java
  collector-monitor/src/main/java/com/navercorp/pinpoint/collector/monitor/dao/hbase/MetricNameExtractor.java
  collector-monitor/src/test/java/com/navercorp/pinpoint/collector/monitor/dao/hbase/MetricNameExtractorTest.java
  collector/src/main/java/com/navercorp/pinpoint/collector/grpc/CollectorGrpcConfiguration.java
Labels: module:collector

#11514 [#noissue] Cleanup
  inspector-module/inspector-commons/src/test/java/com/navercorp/pinpoint/common/dao/pinot/MultiValueTagTypeHandlerTest.java
  metric-module/metric-commons/src/main/java/com/navercorp/pinpoint/metric/common/model/Tags.java
  metric-module/metric-commons/src/main/java/com/navercorp/pinpoint/metric/common/mybatis/typehandler/TagListSerializer.java
  metric-module/metric-commons/src/main/java/com/navercorp/pinpoint/metric/common/mybatis/typehandler/TagListTypeHandler.java
  metric-module/metric-commons/src/main/java/com/navercorp/pinpoint/metric/common/mybatis/typehandler/TagSerializer.java
  metric-module/metric-commons/src/test/java/com/navercorp/pinpoint/metric/common/mybatis/typehandler/TagListSerializerTest.java
  metric-module/metric-commons/src/test/java/com/navercorp/pinpoint/metric/common/mybatis/typehandler/TagListTypeHandlerTest.java
Labels: cleanup

#11516 [#noissue] Update mongo docker images
  agent-module/agent-testweb/mongodb-plugin-testweb/src/test/java/com/pinpoint/test/plugin/mongo/MongodbTest.java
  agent-module/agent-testweb/mongodb-reactive-plugin-testweb/src/test/java/com/pinpoint/test/plugin/mongo/MongodbTest.java
  agent-module/plugins-it/mongodb-it/mongodb-3-it/src/test/java/com/navercorp/pinpoint/it/plugin/mongodb/MongodbServer.java
  agent-module/plugins-it/mongodb-it/mongodb-4-it/src/test/java/com/navercorp/pinpoint/it/plugin/mongodb4/MongodbServer.java
Labels: cleanup

#11520 [#noissue] Cleanup ActiveMQClientIT
  agent-module/plugins-it/activemq-it/activemq-5-15-it/src/test/java/com/navercorp/pinpoint/it/plugin/activemq/client/ActiveMQClientITBase.java
  agent-module/plugins-it/activemq-it/activemq-5-15-it/src/test/java/com/navercorp/test/pinpoint/plugin/activemq/MessageReceiver.java
  agent-module/plugins-it/activemq-it/activemq-5-17-it/src/test/java/com/navercorp/pinpoint/it/plugin/activemq/client/ActiveMQClientITBase.java
  agent-module/plugins-it/activemq-it/activemq-5-17-it/src/test/java/com/navercorp/test/pinpoint/plugin/activemq/MessageReceiver.java
Labels: cleanup

#11521 [#noissue] Cleanup elasticsearch-rest-high-level-client dependency
  agent-module/plugins/bom/pom.xml
Labels: cleanup

#11522 [#noissue] Update README.md
  README.md
  doc/images/ss_error-analysis.png
Labels: document

#11524 [#noissue] Update README.md
  doc/images/ss_error-analysis.png
Labels: document

#11532 [#11531] Add websocket options to web module
  web-starter/src/main/resources/application.yml
  web/src/main/java/com/navercorp/pinpoint/web/WebSocketConfig.java
  web/src/main/resources/application.yml
Labels: module:web
