Repository pinpoint-apm/pinpoint, pull requests merged in 2024-07, with the labels that each got.

#11196 [#11195] Update reactor onNext
  agent-module/bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/reactor/CoreSubscriberOnNextInterceptor.java
  agent-module/bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/reactor/CoreSubscriberOnSubscribeInterceptor.java
  agent-module/plugins/reactor/src/main/java/com/navercorp/pinpoint/plugin/reactor/ReactorPlugin.java
Labels: enhancement, module:plugin

#11200 [#11158] Refactor GrpcDataSender
  agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/context/provider/grpc/MetadataGrpcDataSenderProvider.java
  agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/sender/grpc/AbstractGrpcDataSender.java
  agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/sender/grpc/GrpcDataSender.java
  agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/sender/grpc/LogResponseStreamObserver.java
  agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/sender/grpc/MetadataGrpcDataSender.java
  agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/sender/grpc/MetadataGrpcHedgingDataSender.java
  agent-module/profiler/src/test/java/com/navercorp/pinpoint/profiler/sender/grpc/MetadataGrpcDataSenderTest.java
Labels: cleanup

#11201 [#noissue] Cleanup
  agent-module/plugins-it/google-grpc-it/google-grpc-1-42-it/src/test/java/com/navercorp/pinpoint/it/plugin/grpc/GrpcITBase.java
  agent-module/plugins-it/google-grpc-it/google-grpc-1-42-it/src/test/java/com/navercorp/pinpoint/it/plugin/grpc/HelloWorldClient.java
  agent-module/plugins-it/google-grpc-it/google-grpc-1-42-it/src/test/java/com/navercorp/pinpoint/it/plugin/grpc/HelloWorldServer.java
  agent-module/plugins-it/google-grpc-it/google-grpc-1-42-it/src/test/java/com/navercorp/pinpoint/it/plugin/grpc/HelloWorldSimpleClient.java
  agent-module/plugins-it/google-grpc-it/google-grpc-1-42-it/src/test/java/com/navercorp/pinpoint/it/plugin/grpc/HelloWorldSimpleServer.java
  agent-module/plugins-it/google-grpc-it/google-grpc-1-42-it/src/test/java/com/navercorp/pinpoint/it/plugin/grpc/HelloWorldStreamClient.java
  agent-module/plugins-it/google-grpc-it/google-grpc-1-42-it/src/test/java/com/navercorp/pinpoint/it/plugin/grpc/HelloWorldStreamServer.java
  agent-module/plugins-it/google-grpc-it/google-grpc-1-42-it/src/test/java/com/navercorp/pinpoint/it/plugin/grpc/ShutdownUtils.java
  agent-module/plugins-it/google-grpc-it/google-grpc-1-8-it/src/test/java/com/navercorp/pinpoint/it/plugin/grpc/GrpcITBase.java
  agent-module/plugins-it/google-grpc-it/google-grpc-1-8-it/src/test/java/com/navercorp/pinpoint/it/plugin/grpc/HelloWorldClient.java
  agent-module/plugins-it/google-grpc-it/google-grpc-1-8-it/src/test/java/com/navercorp/pinpoint/it/plugin/grpc/HelloWorldServer.java
  agent-module/plugins-it/google-grpc-it/google-grpc-1-8-it/src/test/java/com/navercorp/pinpoint/it/plugin/grpc/HelloWorldSimpleClient.java
  agent-module/plugins-it/google-grpc-it/google-grpc-1-8-it/src/test/java/com/navercorp/pinpoint/it/plugin/grpc/HelloWorldSimpleServer.java
  agent-module/plugins-it/google-grpc-it/google-grpc-1-8-it/src/test/java/com/navercorp/pinpoint/it/plugin/grpc/HelloWorldStreamClient.java
  agent-module/plugins-it/google-grpc-it/google-grpc-1-8-it/src/test/java/com/navercorp/pinpoint/it/plugin/grpc/HelloWorldStreamServer.java
  agent-module/plugins-it/google-grpc-it/google-grpc-1-8-it/src/test/java/com/navercorp/pinpoint/it/plugin/grpc/ShutdownUtils.java
  agent-module/plugins-test-module/plugins-it-utils/src/main/java/com/navercorp/pinpoint/it/plugin/utils/ExecutorUtils.java
Labels: cleanup

#11177 [#11166] Bypass cache for long SQL queries
  agent-module/bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/config/DefaultProfilerConfig.java
  agent-module/bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/config/ProfilerConfig.java
  agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/cache/UidCache.java
  agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/context/provider/metadata/SqlMetadataServiceProvider.java
  agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/metadata/DefaultSqlMetaDataService.java
  agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/metadata/SimpleCachingSqlNormalizer.java
  agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/metadata/SqlUidMetaDataService.java
  agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/metadata/UidCachingSqlNormalizer.java
  agent-module/profiler/src/test/java/com/navercorp/pinpoint/profiler/cache/UidCacheTest.java
  agent-module/profiler/src/test/java/com/navercorp/pinpoint/profiler/metadata/SimpleCachingSqlNormalizerTest.java
  agent-module/profiler/src/test/java/com/navercorp/pinpoint/profiler/metadata/SqlCacheServiceTest.java
  agent-module/profiler/src/test/java/com/navercorp/pinpoint/profiler/metadata/SqlUidMetaDataServiceTest.java
Labels: module:agent

#11207 [#noissue] Delete unnecessary dbunit
  pom.xml
Labels: cleanup

#11206 [#11205] Update CacheManager constructor args of arcus plugin
  agent-module/plugins/arcus/src/main/java/com/navercorp/pinpoint/plugin/arcus/ArcusPlugin.java
Labels: enhancement, module:plugin

#11209 [#noissue] Cleanup
  agent-module/bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/rxjava/interceptor/WorkerScheduleInterceptor.java
  agent-module/plugins-test-module/plugins-test/src/main/java/com/navercorp/pinpoint/test/plugin/DefaultPluginTestSuite.java
  agent-module/plugins/spring/src/main/java/com/navercorp/pinpoint/plugin/spring/beans/SpringBeansTargetScope.java
  agent-module/plugins/spring/src/test/java/com/navercorp/pinpoint/plugin/spring/beans/SpringBeansTargetScopeTest.java
  agent-module/plugins/vertx/src/main/java/com/navercorp/pinpoint/plugin/vertx/interceptor/RouteStateInterceptor.java
  grpc/src/main/java/com/navercorp/pinpoint/grpc/client/retry/HedgingServiceConfigBuilder.java
Labels: cleanup

#11208 [#noissue] Add ErrorMockController for error page testing
  web/src/main/java/com/navercorp/pinpoint/web/controller/ErrorMockController.java
Labels: module:web

#11211 [#11210] Update DispatcherHandler.handleResult() of spring webflux 6
  agent-module/plugins/spring-webflux/src/main/java/com/navercorp/pinpoint/plugin/spring/webflux/SpringWebFluxPlugin.java
Labels: enhancement, module:plugin

#11215 [#11186] Change gRPC UNARY response based on header value
  agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/context/provider/grpc/MetadataGrpcDataSenderProvider.java
  agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/sender/grpc/LogResponseStreamObserver.java
  collector/src/main/java/com/navercorp/pinpoint/collector/receiver/grpc/retry/GrpcRetryFriendlyServerResponse.java
  collector/src/main/java/com/navercorp/pinpoint/collector/receiver/grpc/service/SimpleRequestHandlerAdaptor.java
  grpc/src/main/java/com/navercorp/pinpoint/grpc/Header.java
  grpc/src/main/java/com/navercorp/pinpoint/grpc/client/retry/RetryHeaderFactory.java
  grpc/src/main/java/com/navercorp/pinpoint/grpc/server/AgentHeaderReader.java
Labels: module:agent, module:collector

#11218 [#11217] Update NULL pattern of uri template
  agent-module/plugins/tomcat/src/main/java/com/navercorp/pinpoint/plugin/tomcat/jakarta/interceptor/StandardHostValveInvokeInterceptor.java
  agent-module/plugins/tomcat/src/main/java/com/navercorp/pinpoint/plugin/tomcat/javax/interceptor/StandardHostValveInvokeInterceptor.java
  agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/context/recorder/DefaultSpanRecorder.java
  agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/context/recorder/DisableSpanRecorder.java
  agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/context/recorder/TraceRootSpanRecorder.java
  agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/context/recorder/uri/UriTemplateFilter.java
  agent-module/profiler/src/test/java/com/navercorp/pinpoint/profiler/context/recorder/uri/UriTemplateFilterTest.java
Labels: enhancement, module:plugin

#11220 [#11219] Bump netty.io from 4.1.100.Final to 4.1.111.Final
  pom.xml
Labels: configuration

#11228 [#noissue] Replace servlet-context-collector.xml with JavaConfig
  collector/src/main/java/com/navercorp/pinpoint/collector/CollectorMvcConfig.java
  collector/src/main/java/com/navercorp/pinpoint/collector/PinpointCollectorModule.java
  collector/src/main/java/com/navercorp/pinpoint/collector/controller/ServerTimeController.java
  collector/src/main/java/com/navercorp/pinpoint/collector/manage/AdminMvcConfigure.java
  collector/src/main/java/com/navercorp/pinpoint/collector/manage/CollectorAdminConfiguration.java
  collector/src/main/java/com/navercorp/pinpoint/collector/manage/controller/AuthInterceptor.java
  collector/src/main/java/com/navercorp/pinpoint/collector/manage/controller/ControllerUtils.java
  collector/src/main/java/com/navercorp/pinpoint/collector/manage/controller/HandlerManagerController.java
  collector/src/main/java/com/navercorp/pinpoint/collector/manage/controller/SimpleResponse.java
  collector/src/main/resources/servlet-context-collector.xml
Labels: module:collector

#11230 [#11140] Increase max limit to align with new default value
  agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/monitor/DefaultAgentStatMonitor.java
Labels: module:agent, configuration

#11233 [#noissue] Cleanup Response
  collector/src/main/java/com/navercorp/pinpoint/collector/manage/controller/AuthInterceptor.java
  collector/src/main/java/com/navercorp/pinpoint/collector/manage/controller/HandlerManagerController.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/response/MapResponse.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/response/Response.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/response/Result.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/response/SimpleResponse.java
  web/src/main/java/com/navercorp/pinpoint/web/authorization/controller/AlarmController.java
  web/src/main/java/com/navercorp/pinpoint/web/authorization/controller/UserController.java
  web/src/main/java/com/navercorp/pinpoint/web/authorization/controller/UserGroupController.java
  web/src/main/java/com/navercorp/pinpoint/web/authorization/controller/WebhookAlarmController.java
  web/src/main/java/com/navercorp/pinpoint/web/controller/AgentStatisticsController.java
  web/src/main/java/com/navercorp/pinpoint/web/response/AlarmResponse.java
  web/src/main/java/com/navercorp/pinpoint/web/response/CreateUserGroupResponse.java
  web/src/test/java/com/navercorp/pinpoint/web/response/AlarmResponseTest.java
  web/src/test/java/com/navercorp/pinpoint/web/response/CreateUserGroupResponseTest.java
  web/src/test/java/com/navercorp/pinpoint/web/response/SimpleResponseTest.java
  web/src/test/java/com/navercorp/pinpoint/web/response/WebhookResponseTest.java
  web/src/test/java/com/navercorp/pinpoint/web/response/WebhookSendInfoResponseTest.java
  webhook/src/main/java/com/navercorp/pinpoint/web/webhook/controller/WebhookController.java
  webhook/src/main/java/com/navercorp/pinpoint/web/webhook/controller/WebhookSendInfoController.java
  webhook/src/main/java/com/navercorp/pinpoint/web/webhook/model/WebhookResponse.java
  webhook/src/main/java/com/navercorp/pinpoint/web/webhook/model/WebhookSendInfoResponse.java
Labels: cleanup

#11234 [#noissue] Cleanup
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/stat/DirectBufferBo.java
  commons-server/src/test/java/com/navercorp/pinpoint/common/server/util/CallerUtilsTest.java
  inspector-module/inspector-collector/src/main/java/com/navercorp/pinpoint/inspector/collector/model/kafka/AgentStat.java
  metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/web/model/MetricValueGroup.java
  otlpmetric/otlpmetric-collector/src/main/java/com/navercorp/pinpoint/otlp/collector/mapper/HistogramMapper.java
  otlpmetric/otlpmetric-web/src/main/java/com/navercorp/pinpoint/otlp/web/view/OtlpChartHistogramViewBuilder.java
  otlpmetric/otlpmetric-web/src/main/java/com/navercorp/pinpoint/otlp/web/vo/OtlpMetricDetailsQueryParam.java
  pinot/pinot-batch/src/main/java/com/navercorp/pinpoint/pinot/alarm/vo/PinotAlarmKey.java
  pinot/pinot-datasource/src/main/java/com/navercorp/pinpoint/pinot/datasource/WrappedPinotPreparedStatement.java
Labels: cleanup

#11236 [#11235] Bump grpc from 1.62.2 to 1.64.1 due to compatibility
  pom.xml
Labels: dependencies

#11242 [#noissue] Cleanup PMD warning
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/dao/hbase/mapper/AgentInfoBoResultsExtractor.java
  flink/src/main/java/com/navercorp/pinpoint/flink/mapper/thrift/stat/JoinAgentStatBoMapper.java
  web/src/main/java/com/navercorp/pinpoint/web/mapper/AgentInfoResultsExtractor.java
  web/src/main/java/com/navercorp/pinpoint/web/mapper/DetailedAgentInfoResultsExtractor.java
Labels: cleanup

#11226 [#noissue] Replace XML in GRPC with java config
  collector/src/main/java/com/navercorp/pinpoint/collector/PinpointCollectorModule.java
  collector/src/main/java/com/navercorp/pinpoint/collector/config/CollectorCommonConfiguration.java
  collector/src/main/java/com/navercorp/pinpoint/collector/grpc/CollectorGrpcConfiguration.java
  collector/src/main/java/com/navercorp/pinpoint/collector/grpc/config/GrpcAgentDataReceiverConfiguration.java
  collector/src/main/java/com/navercorp/pinpoint/collector/grpc/config/GrpcComponentConfiguration.java
  collector/src/main/java/com/navercorp/pinpoint/collector/grpc/config/GrpcKeepAliveScheduler.java
  collector/src/main/java/com/navercorp/pinpoint/collector/grpc/config/GrpcSpanReceiverConfiguration.java
  collector/src/main/java/com/navercorp/pinpoint/collector/grpc/config/GrpcStatReceiverConfiguration.java
  collector/src/main/java/com/navercorp/pinpoint/collector/grpc/ssl/GrpcSslModule.java
  collector/src/main/java/com/navercorp/pinpoint/collector/receiver/grpc/GrpcReceiver.java
  collector/src/main/java/com/navercorp/pinpoint/collector/receiver/grpc/HeaderServerInterceptorFactory.java
  collector/src/main/java/com/navercorp/pinpoint/collector/receiver/grpc/ServerInterceptorFactory.java
  collector/src/main/resources/applicationContext-collector-grpc.xml
  collector/src/main/resources/applicationContext-collector.xml
  collector/src/test/java/com/navercorp/pinpoint/collector/grpc/config/GrpcAgentDataReceiverConfigurationTest.java
  collector/src/test/java/com/navercorp/pinpoint/collector/grpc/config/GrpcSpanReceiverConfigurationTest.java
  collector/src/test/java/com/navercorp/pinpoint/collector/grpc/config/GrpcStatReceiverConfigurationTest.java
  collector/src/test/java/com/navercorp/pinpoint/collector/receiver/grpc/AgentServerTestMain.java
  collector/src/test/java/com/navercorp/pinpoint/collector/receiver/grpc/SpanServerTestMain.java
  collector/src/test/java/com/navercorp/pinpoint/collector/receiver/grpc/StatServerTestMain.java
  grpc/src/main/java/com/navercorp/pinpoint/grpc/server/AgentHeaderReader.java
  grpc/src/main/java/com/navercorp/pinpoint/grpc/server/HeaderPropagationInterceptor.java
  grpc/src/main/java/com/navercorp/pinpoint/grpc/server/ServerFactory.java
  grpc/src/test/java/com/navercorp/pinpoint/grpc/ChannelFactoryTest.java
  log/log-collector/src/main/java/com/navercorp/pinpoint/log/collector/grpc/LogCollectorGrpcServerConfig.java
  realtime/realtime-collector/src/main/java/com/navercorp/pinpoint/realtime/collector/receiver/EmptyCommandService.java
Labels: module:collector, cleanup

#11243 [#noissue] Cleanup GrpcConfiguration
  collector/src/main/java/com/navercorp/pinpoint/collector/grpc/CollectorGrpcConfiguration.java
  collector/src/main/java/com/navercorp/pinpoint/collector/grpc/config/GrpcAgentConfiguration.java
  collector/src/main/java/com/navercorp/pinpoint/collector/grpc/config/GrpcAgentReceiverConfiguration.java
  collector/src/main/java/com/navercorp/pinpoint/collector/grpc/config/GrpcSpanConfiguration.java
  collector/src/main/java/com/navercorp/pinpoint/collector/grpc/config/GrpcSpanReceiverConfiguration.java
  collector/src/main/java/com/navercorp/pinpoint/collector/grpc/config/GrpcStatConfiguration.java
  collector/src/main/java/com/navercorp/pinpoint/collector/grpc/config/GrpcStatReceiverConfiguration.java
  collector/src/main/java/com/navercorp/pinpoint/collector/grpc/ssl/GrpcAgentSslConfiguration.java
  collector/src/main/java/com/navercorp/pinpoint/collector/grpc/ssl/GrpcSpanSslConfiguration.java
  collector/src/main/java/com/navercorp/pinpoint/collector/grpc/ssl/GrpcStatSslConfiguration.java
  collector/src/test/java/com/navercorp/pinpoint/collector/grpc/config/GrpcAgentConfigurationTest.java
  collector/src/test/java/com/navercorp/pinpoint/collector/grpc/config/GrpcSpanConfigurationTest.java
  collector/src/test/java/com/navercorp/pinpoint/collector/grpc/config/GrpcStatConfigurationTest.java
  collector/src/test/java/com/navercorp/pinpoint/collector/grpc/ssl/GrpcAgentSslConfigurationTest.java
  collector/src/test/java/com/navercorp/pinpoint/collector/grpc/ssl/GrpcSpanSslConfigurationTest.java
  collector/src/test/java/com/navercorp/pinpoint/collector/grpc/ssl/GrpcStatSslConfigurationTest.java
Labels: cleanup

#11246 [#noissue] Cleanup
  commons/src/main/java/com/navercorp/pinpoint/common/util/FileUtils.java
  commons/src/test/java/com/navercorp/pinpoint/common/util/FileUtilsTest.java
Labels: cleanup

#11247 [#noissue] Remove applicationContext-collector.xml
  collector/src/main/resources/applicationContext-collector.xml
Labels: cleanup

#11249 [#noissue] Cleanup
  web/src/test/java/com/navercorp/pinpoint/web/controller/AlarmControllerTest.java
  web/src/test/java/com/navercorp/pinpoint/web/controller/ConfigControllerTest.java
  web/src/test/java/com/navercorp/pinpoint/web/controller/UserControllerTest.java
  web/src/test/java/com/navercorp/pinpoint/web/controller/UserGroupControllerTest.java
Labels: cleanup

#11250 [#noissue] Replaced test.xml with java config
  commons-server/src/test/java/com/navercorp/pinpoint/common/server/bo/codec/stat/CodecTestConfig.java
  commons-server/src/test/java/com/navercorp/pinpoint/common/server/bo/codec/stat/v2/ActiveTraceCodecV2Test.java
  commons-server/src/test/java/com/navercorp/pinpoint/common/server/bo/codec/stat/v2/CpuLoadCodecV2Test.java
  commons-server/src/test/java/com/navercorp/pinpoint/common/server/bo/codec/stat/v2/DataSourceCodecV2Test.java
  commons-server/src/test/java/com/navercorp/pinpoint/common/server/bo/codec/stat/v2/DeadlockCodecV2Test.java
  commons-server/src/test/java/com/navercorp/pinpoint/common/server/bo/codec/stat/v2/DirectBufferCodecV2Test.java
  commons-server/src/test/java/com/navercorp/pinpoint/common/server/bo/codec/stat/v2/FileDescriptorCodecV2Test.java
  commons-server/src/test/java/com/navercorp/pinpoint/common/server/bo/codec/stat/v2/JvmGcCodecV2Test.java
  commons-server/src/test/java/com/navercorp/pinpoint/common/server/bo/codec/stat/v2/JvmGcDetailedCodecV2Test.java
  commons-server/src/test/java/com/navercorp/pinpoint/common/server/bo/codec/stat/v2/LoadedClassCodecV2Test.java
  commons-server/src/test/java/com/navercorp/pinpoint/common/server/bo/codec/stat/v2/ResponseTimeCodecV2Test.java
  commons-server/src/test/java/com/navercorp/pinpoint/common/server/bo/codec/stat/v2/TotalThreadCountCodecV2Test.java
  commons-server/src/test/java/com/navercorp/pinpoint/common/server/bo/codec/stat/v2/TransactionCodecV2Test.java
  commons-server/src/test/java/com/navercorp/pinpoint/common/server/bo/serializer/stat/AgentStatHbaseOperationFactoryTest.java
  commons-server/src/test/resources/applicationContext-test.xml
Labels: cleanup

#11248 [#noissue] Refactor `exceptiontrace-web` module
  exceptiontrace/exceptiontrace-web/src/main/java/com/navercorp/pinpoint/exceptiontrace/web/config/ExceptionTraceRegistryHandler.java
  exceptiontrace/exceptiontrace-web/src/main/java/com/navercorp/pinpoint/exceptiontrace/web/controller/ExceptionTraceController.java
  exceptiontrace/exceptiontrace-web/src/main/java/com/navercorp/pinpoint/exceptiontrace/web/dao/ExceptionTraceDao.java
  exceptiontrace/exceptiontrace-web/src/main/java/com/navercorp/pinpoint/exceptiontrace/web/dao/PinotExceptionTraceDao.java
  exceptiontrace/exceptiontrace-web/src/main/java/com/navercorp/pinpoint/exceptiontrace/web/entity/ExceptionChartValueViewEntity.java
  exceptiontrace/exceptiontrace-web/src/main/java/com/navercorp/pinpoint/exceptiontrace/web/entity/ExceptionGroupSummaryEntity.java
  exceptiontrace/exceptiontrace-web/src/main/java/com/navercorp/pinpoint/exceptiontrace/web/mapper/ExceptionEntityMapper.java
  exceptiontrace/exceptiontrace-web/src/main/java/com/navercorp/pinpoint/exceptiontrace/web/model/ExceptionChartGroup.java
  exceptiontrace/exceptiontrace-web/src/main/java/com/navercorp/pinpoint/exceptiontrace/web/model/ExceptionGroupSummary.java
  exceptiontrace/exceptiontrace-web/src/main/java/com/navercorp/pinpoint/exceptiontrace/web/model/Grouped.java
  exceptiontrace/exceptiontrace-web/src/main/java/com/navercorp/pinpoint/exceptiontrace/web/model/GroupedFieldName.java
  exceptiontrace/exceptiontrace-web/src/main/java/com/navercorp/pinpoint/exceptiontrace/web/model/params/GroupFilterParams.java
  exceptiontrace/exceptiontrace-web/src/main/java/com/navercorp/pinpoint/exceptiontrace/web/service/ExceptionTraceService.java
  exceptiontrace/exceptiontrace-web/src/main/java/com/navercorp/pinpoint/exceptiontrace/web/service/ExceptionTraceServiceImpl.java
  exceptiontrace/exceptiontrace-web/src/main/java/com/navercorp/pinpoint/exceptiontrace/web/util/TimeSeriesUtils.java
  exceptiontrace/exceptiontrace-web/src/main/java/com/navercorp/pinpoint/exceptiontrace/web/view/ExceptionChartValueView.java
  exceptiontrace/exceptiontrace-web/src/main/java/com/navercorp/pinpoint/exceptiontrace/web/view/ExceptionChartView.java
  exceptiontrace/exceptiontrace-web/src/main/java/com/navercorp/pinpoint/exceptiontrace/web/view/ExceptionDetailView.java
  exceptiontrace/exceptiontrace-web/src/main/resources/exceptiontrace/mapper/ExceptionGroupMapper.xml
  exceptiontrace/exceptiontrace-web/src/main/resources/exceptiontrace/mapper/ExceptionMetadataMapper.xml
  exceptiontrace/exceptiontrace-web/src/main/resources/exceptiontrace/mapper/ExceptionUtilMapper.xml
  exceptiontrace/exceptiontrace-web/src/test/java/com/navercorp/pinpoint/exceptiontrace/web/mapper/ExceptionEntityMapperTest.java
  exceptiontrace/exceptiontrace-web/src/test/java/com/navercorp/pinpoint/exceptiontrace/web/model/ExceptionChartGroupTest.java
  exceptiontrace/exceptiontrace-web/src/test/java/com/navercorp/pinpoint/exceptiontrace/web/model/ExceptionChartValueViewTest.java
Labels: module:web

#11255 [#noissue] Reduce Memory Usage
  commons-profiler/src/main/java/com/navercorp/pinpoint/common/profiler/logging/ThrottledLogger.java
Labels: cleanup

#11251 [#noissue] Replace Grpc Status conversion with build-in API
  grpc/src/main/java/com/navercorp/pinpoint/grpc/StatusErrors.java
Labels: cleanup

#11258 [#noissue] Cleanup Server.shutdown
  collector/src/main/java/com/navercorp/pinpoint/collector/receiver/grpc/GrpcReceiver.java
  grpc/src/main/java/com/navercorp/pinpoint/grpc/util/ServerUtils.java
Labels: cleanup

#11262 [#11261] Fix missing metadata trailer in ServerCall.close
  grpc/src/main/java/com/navercorp/pinpoint/grpc/server/flowcontrol/DefaultServerCallWrapper.java
Labels: module:collector, cleanup

#11257 [#11256] Apply RateLimiter to the server stream in gRPC
  collector/pom.xml
  collector/src/main/java/com/navercorp/pinpoint/collector/grpc/config/GrpcSpanReceiverConfiguration.java
  collector/src/main/java/com/navercorp/pinpoint/collector/grpc/config/GrpcStatReceiverConfiguration.java
  collector/src/main/java/com/navercorp/pinpoint/collector/receiver/grpc/flow/RateLimitClientStreamServerInterceptor.java
  collector/src/test/java/com/navercorp/pinpoint/collector/receiver/grpc/flow/StreamRateLimitServerInterceptorTest.java
  grpc/src/main/java/com/navercorp/pinpoint/grpc/server/flowcontrol/DefaultServerCallWrapper.java
  grpc/src/main/java/com/navercorp/pinpoint/grpc/server/flowcontrol/ServerCallWrapper.java
Labels: module:collector

#11277 [#noissue] Cleanup
  grpc/src/main/java/com/navercorp/pinpoint/grpc/server/NettyStatsOptions.java
  grpc/src/main/java/com/navercorp/pinpoint/grpc/server/ServerFactory.java
Labels: cleanup

#11279 [#11278] Add gRPC transport and stream monitoring
  collector/src/main/java/com/navercorp/pinpoint/collector/receiver/grpc/GrpcReceiver.java
  collector/src/main/java/com/navercorp/pinpoint/collector/receiver/grpc/monitor/BasicMonitor.java
  collector/src/main/java/com/navercorp/pinpoint/collector/receiver/grpc/monitor/EmptyMonitor.java
  collector/src/main/java/com/navercorp/pinpoint/collector/receiver/grpc/monitor/Monitor.java
  grpc/src/main/java/com/navercorp/pinpoint/grpc/server/ConnectionCountServerTransportFilter.java
  grpc/src/main/java/com/navercorp/pinpoint/grpc/server/StreamCountInterceptor.java
Labels: module:collector

#11283 [#11282] Bump hbase-client from 2.5.5 to 2.5.9
  pom.xml
Labels: dependencies

#11284 [#10776] Add api to get defined Metric list
  otlpmetric/otlpmetric-web/src/main/java/com/navercorp/pinpoint/otlp/web/controller/MetricDefinitionController.java
  otlpmetric/otlpmetric-web/src/main/java/com/navercorp/pinpoint/otlp/web/dao/AppMetricDefinitionDao.java
  otlpmetric/otlpmetric-web/src/main/java/com/navercorp/pinpoint/otlp/web/dao/model/AppMetricDefDto.java
  otlpmetric/otlpmetric-web/src/main/java/com/navercorp/pinpoint/otlp/web/dao/mysql/MysqlAppMetricDefinitionDao.java
  otlpmetric/otlpmetric-web/src/main/java/com/navercorp/pinpoint/otlp/web/service/AppMetricDefinitionService.java
  otlpmetric/otlpmetric-web/src/main/java/com/navercorp/pinpoint/otlp/web/service/AppMetricDefinitionServiceImpl.java
  otlpmetric/otlpmetric-web/src/main/resources/otlp/web/mapper/mysql/AppMetricDefinitionMapper.xml
Labels: module:web, module:otlpmetric

#11280 [#noissue] change inspector minimal time slot
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/util/timewindow/TimeWindowSlotCentricSampler.java
  inspector-module/inspector-web/src/main/java/com/navercorp/pinpoint/inspector/web/controller/AgentInspectorStatController.java
  web/src/main/java/com/navercorp/pinpoint/web/authorization/controller/AgentStatController.java
  web/src/main/java/com/navercorp/pinpoint/web/authorization/controller/ApplicationDataSourceController.java
  web/src/main/java/com/navercorp/pinpoint/web/authorization/controller/ApplicationStatController.java
Labels: module:web

#11285 [#11278] Cleanup
  collector/src/main/java/com/navercorp/pinpoint/collector/grpc/config/GrpcAgentConfiguration.java
  collector/src/main/java/com/navercorp/pinpoint/collector/grpc/config/GrpcComponentConfiguration.java
  collector/src/main/java/com/navercorp/pinpoint/collector/grpc/config/GrpcSpanReceiverConfiguration.java
  collector/src/main/java/com/navercorp/pinpoint/collector/grpc/config/GrpcStatReceiverConfiguration.java
  collector/src/main/java/com/navercorp/pinpoint/collector/receiver/grpc/GrpcReceiver.java
  collector/src/main/java/com/navercorp/pinpoint/collector/receiver/grpc/monitor/Monitor.java
Labels: cleanup

#11273 [#11252] Limit query to one row for faster response
  web/src/main/java/com/navercorp/pinpoint/web/dao/hbase/stat/HbaseAgentStatDaoOperations.java
Labels: module:web

#11292 [#10776] Add api to update defined Metric list
  otlpmetric/otlpmetric-web/src/main/java/com/navercorp/pinpoint/otlp/web/controller/MetricDefinitionController.java
  otlpmetric/otlpmetric-web/src/main/java/com/navercorp/pinpoint/otlp/web/dao/AppMetricDefinitionDao.java
  otlpmetric/otlpmetric-web/src/main/java/com/navercorp/pinpoint/otlp/web/dao/mysql/MysqlAppMetricDefinitionDao.java
  otlpmetric/otlpmetric-web/src/main/java/com/navercorp/pinpoint/otlp/web/service/AppMetricDefinitionService.java
  otlpmetric/otlpmetric-web/src/main/java/com/navercorp/pinpoint/otlp/web/service/AppMetricDefinitionServiceImpl.java
  otlpmetric/otlpmetric-web/src/main/resources/otlp/web/mapper/mysql/AppMetricDefinitionMapper.xml
Labels: module:otlpmetric

#11297 [#noissue] Fix typo bitField
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/serializer/trace/v2/SpanDecoderV0.java
Labels: cleanup, module:project-common

#11294 [#11276] Align `exceptionTrace` tableName with manual
  exceptiontrace/exceptiontrace-web/src/main/resources/profiles/local/pinpoint-web-exceptiontrace.properties
  exceptiontrace/exceptiontrace-web/src/main/resources/profiles/release/pinpoint-web-exceptiontrace.properties
Labels: module:web, configuration

#11299 [#11298] Fix concurrency bug in GrpcAgentConnectionRepository
  realtime/realtime-collector/src/main/java/com/navercorp/pinpoint/realtime/collector/receiver/grpc/GrpcAgentConnectionRepository.java
  realtime/realtime-collector/src/test/java/com/navercorp/pinpoint/realtime/collector/receiver/grpc/GrpcAgentConnectionRepositoryTest.java
Labels: bug

#11304 [#10776] Create an ID to distinguish between metric definitions
  otlpmetric/otlpmetric-common/src/main/java/com/navercorp/pinpoint/otlp/common/defined/AppMetricDefinition.java
  otlpmetric/otlpmetric-web/src/main/java/com/navercorp/pinpoint/otlp/web/service/AppMetricDefinitionServiceImpl.java
Labels: module:otlpmetric

#11307 [#noissue] Cleanup
  web/src/main/java/com/navercorp/pinpoint/web/metric/common/model/Tag.java
Labels: cleanup

#11309 [#11308] Apply gRPC MAX_CONNECTION_AGE
  collector/src/main/java/com/navercorp/pinpoint/collector/grpc/config/GrpcPropertiesServerOptionBuilder.java
  collector/src/main/resources/pinpoint-collector-grpc-root.properties
  collector/src/test/java/com/navercorp/pinpoint/collector/grpc/config/GrpcStatConfigurationTest.java
  grpc/src/main/java/com/navercorp/pinpoint/grpc/server/ServerOption.java
  grpc/src/main/java/com/navercorp/pinpoint/grpc/server/flowcontrol/StreamExecutorServerInterceptor.java
Labels: enhancement
