Repository pinpoint-apm/pinpoint, pull requests merged in 2024-03, with the labels that each got.

#10731 [#NOISSUE] edit Copyright format
  batch/src/main/java/com/navercorp/pinpoint/batch/alarm/collector/DataSourceDataGetter.java
  batch/src/main/java/com/navercorp/pinpoint/batch/alarm/collector/FileDescriptorDataGetter.java
  batch/src/main/java/com/navercorp/pinpoint/batch/alarm/collector/HeapDataGetter.java
  batch/src/main/java/com/navercorp/pinpoint/batch/alarm/collector/JvmCpuDataGetter.java
  batch/src/main/java/com/navercorp/pinpoint/batch/alarm/collector/SystemCpuDataGetter.java
  batch/src/main/java/com/navercorp/pinpoint/batch/alarm/collector/pinot/DataSourceDataCollector.java
  batch/src/main/java/com/navercorp/pinpoint/batch/alarm/collector/pinot/FileDescriptorDataCollector.java
  batch/src/main/java/com/navercorp/pinpoint/batch/alarm/collector/pinot/HeapDataCollector.java
  batch/src/main/java/com/navercorp/pinpoint/batch/alarm/collector/pinot/JvmCpuDataCollector.java
  batch/src/main/java/com/navercorp/pinpoint/batch/alarm/collector/pinot/SystemCpuDataCollector.java
  batch/src/main/java/com/navercorp/pinpoint/batch/alarm/dao/AlarmDao.java
  batch/src/main/java/com/navercorp/pinpoint/batch/alarm/dao/model/BatchQueryParameter.java
  batch/src/main/java/com/navercorp/pinpoint/batch/alarm/dao/pinot/PinotAlarmDao.java
  batch/src/main/java/com/navercorp/pinpoint/batch/alarm/vo/AgentFieldUsage.java
  batch/src/main/java/com/navercorp/pinpoint/batch/alarm/vo/AgentUsage.java
  batch/src/main/java/com/navercorp/pinpoint/batch/alarm/vo/AgentUsageCount.java
  batch/src/main/java/com/navercorp/pinpoint/batch/configuration/BatchPinotDaoConfiguration.java
  batch/src/main/java/com/navercorp/pinpoint/batch/configuration/BatchRegistryHandler.java
  inspector-module/inspector-commons/src/main/java/com/navercorp/pinpoint/common/dao/pinot/MultiValueTagTypeHandler.java
  inspector-module/inspector-commons/src/main/java/com/navercorp/pinpoint/common/model/TagInformation.java
  inspector-module/inspector-web/src/main/java/com/navercorp/pinpoint/inspector/web/dao/ApplicationStatDao.java
  inspector-module/inspector-web/src/main/java/com/navercorp/pinpoint/inspector/web/dao/pinot/PinotApplicationStatDao.java
  inspector-module/inspector-web/src/main/java/com/navercorp/pinpoint/inspector/web/definition/metric/AvgUsingIntervalForTotalCountPostProcessor.java
  inspector-module/inspector-web/src/main/java/com/navercorp/pinpoint/inspector/web/definition/metric/UsingDataSourceTagForApplicationPreProcessor.java
  inspector-module/inspector-web/src/main/java/com/navercorp/pinpoint/inspector/web/service/ApdexStatService.java
  inspector-module/inspector-web/src/main/java/com/navercorp/pinpoint/inspector/web/service/DefaultApdexStatService.java
  metric-module/metric-commons/src/main/java/com/navercorp/pinpoint/metric/common/model/Range.java
  metric-module/metric-commons/src/main/java/com/navercorp/pinpoint/metric/common/model/TimeWindow.java
  metric-module/metric-commons/src/main/java/com/navercorp/pinpoint/metric/common/model/chart/AvgMinMaxMetricPoint.java
  metric-module/metric-commons/src/main/java/com/navercorp/pinpoint/metric/common/model/chart/AvgMinMetricPoint.java
  metric-module/metric-commons/src/main/java/com/navercorp/pinpoint/metric/common/model/chart/MinMaxMetricPoint.java
  metric-module/metric-commons/src/main/java/com/navercorp/pinpoint/metric/common/model/chart/Point.java
  metric-module/metric-commons/src/main/java/com/navercorp/pinpoint/metric/common/model/chart/SystemMetricPoint.java
  metric-module/metric-commons/src/main/java/com/navercorp/pinpoint/metric/common/mybatis/typehandler/TagTypeHandler.java
  metric-module/metric-commons/src/main/java/com/navercorp/pinpoint/metric/common/util/DoubleUncollectedDataCreator.java
  metric-module/metric-commons/src/main/java/com/navercorp/pinpoint/metric/common/util/LongUncollectedDataCreator.java
  metric-module/metric-commons/src/main/java/com/navercorp/pinpoint/metric/common/util/TagUtils.java
  metric-module/metric-commons/src/main/java/com/navercorp/pinpoint/metric/common/util/TimeSeriesBuilder.java
  metric-module/metric-commons/src/main/java/com/navercorp/pinpoint/metric/common/util/TimeUtils.java
  metric-module/metric-commons/src/main/java/com/navercorp/pinpoint/metric/common/util/TimeWindowDownSampler.java
  metric-module/metric-commons/src/main/java/com/navercorp/pinpoint/metric/common/util/TimeWindowSampler.java
  metric-module/metric-commons/src/main/java/com/navercorp/pinpoint/metric/common/util/TimeWindowSlotCentricSampler.java
  metric-module/metric-commons/src/main/java/com/navercorp/pinpoint/metric/common/util/UncollectedDataCreator.java
  metric-module/metric-commons/src/test/java/com/navercorp/pinpoint/metric/common/model/TagUtilsTest.java
  metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/web/mybatis/typehandler/TagListTypeHandler.java
Labels: module:batch, module:inspector

#10729 [#noissue] Cleanup
  batch/src/main/java/com/navercorp/pinpoint/batch/alarm/collector/pinot/DataSourceDataCollector.java
  batch/src/main/java/com/navercorp/pinpoint/batch/alarm/collector/pinot/HeapDataCollector.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/JvmInfoBo.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/SimpleAgentKey.java
  inspector-module/inspector-commons/src/main/java/com/navercorp/pinpoint/common/model/TagInformation.java
  inspector-module/inspector-web/src/main/java/com/navercorp/pinpoint/inspector/web/controller/AgentStatV2Controller.java
  inspector-module/inspector-web/src/main/java/com/navercorp/pinpoint/inspector/web/controller/ApplicationStatV2Controller.java
  inspector-module/inspector-web/src/main/java/com/navercorp/pinpoint/inspector/web/definition/metric/UsingDataSourceTagForAgentPreProcessor.java
  inspector-module/inspector-web/src/main/java/com/navercorp/pinpoint/inspector/web/definition/metric/UsingDataSourceTagForApplicationPreProcessor.java
  inspector-module/inspector-web/src/main/java/com/navercorp/pinpoint/inspector/web/model/InspectorMetricData.java
  inspector-module/inspector-web/src/main/java/com/navercorp/pinpoint/inspector/web/model/InspectorMetricGroupData.java
  inspector-module/inspector-web/src/main/java/com/navercorp/pinpoint/inspector/web/view/InspectorMetricGroupDataView.java
  inspector-module/inspector-web/src/main/java/com/navercorp/pinpoint/inspector/web/view/InspectorMetricView.java
  web/src/main/java/com/navercorp/pinpoint/web/authorization/controller/HeatMapController.java
  web/src/main/java/com/navercorp/pinpoint/web/controller/MainController.java
  web/src/main/java/com/navercorp/pinpoint/web/dao/hbase/HbaseAgentLifeCycleDao.java
  web/src/main/java/com/navercorp/pinpoint/web/query/model/BindSqlView.java
  web/src/main/java/com/navercorp/pinpoint/web/scatter/Coordinates.java
  web/src/main/java/com/navercorp/pinpoint/web/scatter/DotGroup.java
  web/src/main/java/com/navercorp/pinpoint/web/scatter/DotGroups.java
  web/src/main/java/com/navercorp/pinpoint/web/scatter/ScatterDataBuilder.java
  web/src/main/java/com/navercorp/pinpoint/web/scatter/Status.java
  web/src/main/java/com/navercorp/pinpoint/web/scatter/heatmap/HeatMapBuilder.java
  web/src/main/java/com/navercorp/pinpoint/web/scatter/heatmap/Point.java
  web/src/main/java/com/navercorp/pinpoint/web/service/AgentEventServiceImpl.java
  web/src/main/java/com/navercorp/pinpoint/web/util/etag/ETag.java
  web/src/main/java/com/navercorp/pinpoint/web/vo/AgentEvent.java
  web/src/main/java/com/navercorp/pinpoint/web/vo/DurationalAgentEvent.java
  web/src/main/java/com/navercorp/pinpoint/web/vo/scatter/Dot.java
  web/src/test/java/com/navercorp/pinpoint/web/applicationmap/ApplicationMapBuilderTest.java
  web/src/test/java/com/navercorp/pinpoint/web/scatter/heatmap/HeatMapBuilderTest.java
  web/src/test/java/com/navercorp/pinpoint/web/util/etag/ETagUtilsTest.java
  web/src/test/java/com/navercorp/pinpoint/web/view/AgentEventMarkerSerializerTest.java
  web/src/test/java/com/navercorp/pinpoint/web/vo/AgentEventTest.java
  web/src/test/java/com/navercorp/pinpoint/web/vo/timeline/inspector/AgentEventTimelineTest.java
  web/src/test/java/com/navercorp/pinpoint/web/vo/timeline/inspector/AgentStatusTimelineTest.java
Labels: cleanup

#10734 [#10704] Increase query speed by adding the applicationName parameter to the agent API.
  inspector-module/inspector-web/src/main/java/com/navercorp/pinpoint/inspector/web/controller/AgentStatV2Controller.java
  inspector-module/inspector-web/src/main/resources/inspector/web/mapper/pinot/agentInspectorMapper.xml
Labels: module:web, module:inspector

#10733 [#noissue] Cleanup
  batch/src/main/java/com/navercorp/pinpoint/batch/alarm/collector/pinot/DataSourceDataCollector.java
  batch/src/main/java/com/navercorp/pinpoint/batch/alarm/collector/pinot/HeapDataCollector.java
Labels: cleanup

#10735 Revert "[#NotAssigned] Removed getRawStatusCode() method for removal …
  plugins/resttemplate/src/main/java/com/navercorp/pinpoint/plugin/resttemplate/interceptor/ClientHttpResponseInterceptor.java
  plugins/resttemplate/src/main/java/com/navercorp/pinpoint/plugin/resttemplate/interceptor/HttpRequestInterceptor.java
  plugins/spring-webflux/src/main/java/com/navercorp/pinpoint/plugin/spring/webflux/interceptor/ClientResponseFunctionInterceptor.java
Labels: module:plugin

#10732 [#10693] Add enable option for grpc client reties
  grpc/src/main/java/com/navercorp/pinpoint/grpc/client/ChannelFactoryBuilder.java
  grpc/src/main/java/com/navercorp/pinpoint/grpc/client/DefaultChannelFactory.java
  grpc/src/main/java/com/navercorp/pinpoint/grpc/client/DefaultChannelFactoryBuilder.java
  grpc/src/main/java/com/navercorp/pinpoint/grpc/client/config/ClientRetryOption.java
  grpc/src/main/java/com/navercorp/pinpoint/grpc/client/retry/HedgingServiceConfigBuilder.java
  grpc/src/main/java/com/navercorp/pinpoint/grpc/client/retry/RetryServiceConfigBuilder.java
  grpc/src/main/java/com/navercorp/pinpoint/grpc/client/retry/ServiceConfigBuilder.java
  grpc/src/test/java/com/navercorp/pinpoint/grpc/client/config/RetryConfigTest.java
  grpc/src/test/resources/client/example/hedging_service_config.json
  grpc/src/test/resources/client/example/retry_service_config.json
  profiler/src/main/java/com/navercorp/pinpoint/profiler/context/grpc/config/GrpcTransportConfig.java
  profiler/src/main/java/com/navercorp/pinpoint/profiler/context/provider/grpc/MetadataGrpcDataSenderProvider.java
  profiler/src/main/java/com/navercorp/pinpoint/profiler/sender/grpc/LogResponseStreamObserver.java
  profiler/src/main/java/com/navercorp/pinpoint/profiler/sender/grpc/MetadataGrpcDataSender.java
Labels: module:agent

#10724 [#10723] Add ScanMetrics for Scan Performance Measurements
  collector/src/test/resources/log4j2-test.xml
  commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/HbaseTemplate.java
  commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/config/HbaseTemplateConfiguration.java
  commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/parallel/ScanUtils.java
  commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/util/DefaultScanMetricReporter.java
  commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/util/EmptyScanMetricReporter.java
  commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/util/ScanMetricReporter.java
  commons-hbase/src/test/java/com/navercorp/pinpoint/common/hbase/HbaseTemplateExtractDataIT.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/config/MapHbaseConfiguration.java
  web/src/main/resources/application.yml
Labels: enhancement

#10736 [#NotAssigned] Removed getRawStatusCode() method for removal in Sprin…
  agent-testweb/spring-boot3-webflux-plugin-testweb/src/main/java/com/pinpoint/test/plugin/SpringBoot3WebfluxPluginController.java
  plugins/resttemplate/pom.xml
  plugins/resttemplate/src/main/java/com/navercorp/pinpoint/plugin/resttemplate/RestTemplatePlugin.java
  plugins/resttemplate/src/main/java/com/navercorp/pinpoint/plugin/resttemplate/SpringVersion.java
  plugins/resttemplate/src/main/java/com/navercorp/pinpoint/plugin/resttemplate/interceptor/ClientHttpResponseInterceptor.java
  plugins/resttemplate/src/main/java/com/navercorp/pinpoint/plugin/resttemplate/interceptor/HttpRequestInterceptor.java
  plugins/resttemplate/src/main/java/com/navercorp/pinpoint/plugin/resttemplate/interceptor/ListenableFutureInterceptor.java
  plugins/resttemplate/src/main/java/com/navercorp/pinpoint/plugin/resttemplate/interceptor/util/HttpStatusProvider.java
  plugins/resttemplate/src/main/java/com/navercorp/pinpoint/plugin/resttemplate/interceptor/util/HttpStatusProviderFactory.java
  plugins/resttemplate/src/main/java/com/navercorp/pinpoint/plugin/resttemplate/interceptor/util/Spring5HttpStatusProvider.java
  plugins/resttemplate/src/main/java/com/navercorp/pinpoint/plugin/resttemplate/interceptor/util/Spring6HttpStatusProvider.java
  plugins/resttemplate/src/main/java/com/navercorp/pinpoint/plugin/resttemplate/interceptor/util/UnsupportedHttpStatusProvider.java
  plugins/resttemplate/src/main/java/org/springframework/http/HttpStatusCode.java
  plugins/resttemplate/src/main/java/org/springframework/http/client/ClientHttpResponse.java
  plugins/spring-webflux/pom.xml
  plugins/spring-webflux/src/main/java/com/navercorp/pinpoint/plugin/spring/webflux/SpringVersion.java
  plugins/spring-webflux/src/main/java/com/navercorp/pinpoint/plugin/spring/webflux/SpringWebFluxPlugin.java
  plugins/spring-webflux/src/main/java/com/navercorp/pinpoint/plugin/spring/webflux/interceptor/ClientResponseFunctionInterceptor.java
  plugins/spring-webflux/src/main/java/com/navercorp/pinpoint/plugin/spring/webflux/interceptor/util/HttpStatusProvider.java
  plugins/spring-webflux/src/main/java/com/navercorp/pinpoint/plugin/spring/webflux/interceptor/util/HttpStatusProviderFactory.java
  plugins/spring-webflux/src/main/java/com/navercorp/pinpoint/plugin/spring/webflux/interceptor/util/Spring5HttpStatusProvider.java
  plugins/spring-webflux/src/main/java/com/navercorp/pinpoint/plugin/spring/webflux/interceptor/util/Spring6HttpStatusProvider.java
  plugins/spring-webflux/src/main/java/com/navercorp/pinpoint/plugin/spring/webflux/interceptor/util/UnsupportedHttpStatusProvider.java
  plugins/spring-webflux/src/main/java/org/springframework/http/HttpStatusCode.java
  plugins/spring-webflux/src/main/java/org/springframework/http/client/reactive/ClientHttpResponse.java
Labels: module:plugin

#10748 [#10747] Replaced deprecated spring security methods
  basic-login/src/main/java/com/navercorp/pinpoint/login/basic/PinpointBasicLoginConfig.java
Labels: module:collector, module:web

#10752 [#10736] Separate dummy java class not to disturb spring-web dependency
  plugins/resttemplate/pom.xml
  plugins/resttemplate/src/main/java-spring/org/springframework/http/HttpStatusCode.java
  plugins/resttemplate/src/main/java-spring/org/springframework/http/client/ClientHttpResponse.java
  plugins/spring-webflux/pom.xml
  plugins/spring-webflux/src/main/java-spring/org/springframework/http/HttpStatusCode.java
  plugins/spring-webflux/src/main/java-spring/org/springframework/http/client/reactive/ClientHttpResponse.java
Labels: bug, module:plugin

#10753 [#10736] Remove dummy classes after install the plugin
  plugins/resttemplate/pom.xml
  plugins/spring-webflux/pom.xml
Labels: bug, module:plugin, configuration

#10754 [#10736] Use maven-clean-plugin instead of exec
  plugins/resttemplate/pom.xml
  plugins/spring-webflux/pom.xml
Labels: module:plugin, configuration

#10761 [#noissue] Cleanup
  agent-module/plugins/jetty/pom.xml
Labels: cleanup

#10764 [#noissue] Update plugin-it path
  agent-module/plugins-test/src/main/java/com/navercorp/pinpoint/test/plugin/DefaultPluginTestSuite.java
  agent-module/plugins-test/src/main/java/com/navercorp/pinpoint/test/plugin/PluginClassLoading.java
Labels: Continuous Integration

#10760 [#10701] Add io.vavr dependency for resilience4j
  agent-module/bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/classloader/ProfilerLibs.java
Labels: cleanup

#10769 [#10704] Added per-table performance measurement and comparison logic to improve read speeds.
  inspector-module/inspector-collector/src/main/java/com/navercorp/pinpoint/inspector/collector/model/kafka/AgentStat.java
  inspector-module/inspector-collector/src/main/java/com/navercorp/pinpoint/inspector/collector/model/kafka/AgentStatModelConverter.java
Labels: module:inspector

#10771 [#noissue] Fix plugin-it cassandra shared class
  agent-module/plugins-it/cassandra-it/cassandra-2-it/src/test/java/com/navercorp/pinpoint/it/plugin/cassandra/CassandraDatastaxITBase.java
  agent-module/plugins-it/cassandra-it/cassandra-2-it/src/test/java/com/navercorp/pinpoint/it/plugin/cassandra/CassandraServer.java
Labels: Continuous Integration

#10773 [#10772] Fix interceptor option in resttemplate plugin
  agent-module/plugins/resttemplate/src/main/java/com/navercorp/pinpoint/plugin/resttemplate/RestTemplatePlugin.java
  agent-module/plugins/resttemplate/src/main/java/com/navercorp/pinpoint/plugin/resttemplate/interceptor/ListenableFutureInterceptor.java
Labels: module:plugin

#10763 [#noissue] Cleanup dependencies
  agent-module/plugins-it/clickhouse-jdbc-it/pom.xml
Labels: module:plugin, dependencies

#10777 [#noissue] Cleanup maven
  agent-module/agent/src/assembly/component/core.xml
  agent-module/plugins/jboss/pom.xml
  agent-module/plugins/jetty/pom.xml
  agent-module/plugins/resin/pom.xml
  agent-module/plugins/tomcat/pom.xml
  agent-module/plugins/undertow-servlet/pom.xml
  agent-module/plugins/undertow/pom.xml
  agent-module/plugins/weblogic/pom.xml
  agent-module/plugins/websphere/pom.xml
  pom.xml
Labels: cleanup

#10778 [#noissue] Fix HBase2 compatibility
  commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/HbaseVersionCheckBean.java
Labels: cleanup

#10784 [#10783] Bump tiny-log from 2.1.1 to 2.7.0
  agent-module/plugins-test/pom.xml
Labels: dependencies

#10787 [#10786] Bump testcontainer from 1.17.6 to 1.19.7
  agent-module/plugins-it/plugins-it-utils/src/main/java/com/navercorp/pinpoint/it/plugin/utils/TestcontainersOption.java
  pom.xml
Labels: dependencies

#10789 [#noissue] Fix maven build errors
  agent-module/plugins-it/pom.xml
  agent-testweb/bom/pom.xml
Labels: bug, configuration

#10790 [#noissue] Improve ARM64 compatibility of mysql-server-8
  agent-module/plugins-it/mysql-jdbc-driver-plugin-it/src/test/java/com/navercorp/pinpoint/it/plugin/jdbc/mysql/MySqlConnection_5_X_IT.java
  agent-module/plugins-it/mysql-jdbc-driver-plugin-it/src/test/java/com/navercorp/pinpoint/it/plugin/jdbc/mysql/MySqlConnection_6_X_IT.java
  agent-module/plugins-it/mysql-jdbc-driver-plugin-it/src/test/java/com/navercorp/pinpoint/it/plugin/jdbc/mysql/MySqlLoadBalance_5_X_IT.java
  agent-module/plugins-it/mysql-jdbc-driver-plugin-it/src/test/java/com/navercorp/pinpoint/it/plugin/jdbc/mysql/MySqlLoadBalance_6_X_IT.java
  agent-module/plugins-it/mysql-jdbc-driver-plugin-it/src/test/java/com/navercorp/pinpoint/it/plugin/jdbc/mysql/MySqlServer.java
  agent-module/plugins-it/mysql-jdbc-driver-plugin-it/src/test/java/com/navercorp/pinpoint/it/plugin/jdbc/mysql/MySqlServer5.java
  agent-module/plugins-it/mysql-jdbc-driver-plugin-it/src/test/java/com/navercorp/pinpoint/it/plugin/jdbc/mysql/MySqlServer8.java
  agent-module/plugins-it/mysql-jdbc-driver-plugin-it/src/test/java/com/navercorp/pinpoint/it/plugin/jdbc/mysql/MySql_5_X_IT.java
  agent-module/plugins-it/mysql-jdbc-driver-plugin-it/src/test/java/com/navercorp/pinpoint/it/plugin/jdbc/mysql/MySql_6_X_IT.java
  agent-module/plugins-it/mysql-jdbc-driver-plugin-it/src/test/java/com/navercorp/pinpoint/it/plugin/jdbc/mysql/MySql_8_X_IT.java
Labels: cleanup

#10791 [#noissue] Improved ARM compatibility of integration tests
  agent-module/plugins-it/cassandra-it/cassandra-2-it/src/test/java/com/navercorp/pinpoint/it/plugin/cassandra/CassandraITConstants.java
  agent-module/plugins-it/cassandra-it/cassandra-2-it/src/test/java/com/navercorp/pinpoint/it/plugin/cassandra/CassandraServer.java
  agent-module/plugins-it/cassandra-it/cassandra-4-it/src/test/java/com/navercorp/pinpoint/it/plugin/cassandra/CassandraITConstants.java
  agent-module/plugins-it/cassandra-it/cassandra-4-it/src/test/java/com/navercorp/pinpoint/it/plugin/cassandra/CassandraServer.java
  agent-module/plugins-it/elasticsearch-it/elasticsearch-7-16-it/src/test/java/com/navercorp/pinpoint/it/plugin/elasticsearch/ESServerContainerFactory.java
  agent-module/plugins-it/mariadb-jdbc-it/src/test/java/com/navercorp/pinpoint/it/plugin/jdbc/MariaDBServer.java
  agent-module/plugins-it/mongodb-it/mongodb-3-it/src/test/java/com/navercorp/pinpoint/it/plugin/mongodb/MongodbServer.java
  agent-module/plugins-it/mongodb-it/mongodb-4-it/src/test/java/com/navercorp/pinpoint/it/plugin/mongodb4/MongodbServer.java
Labels: cleanup

#10796 [#10795] Bump commons-compress from 1.21 to 1.26.1
  pom.xml
Labels: dependencies

#10794 [#noissue] Improved ARM64 compatibility
  agent-module/plugins-it/postgresql-jdbc-it/src/test/java/com/navercorp/pinpoint/it/plugin/jdbc/postgresql/PostgreSQLContainerFactory.java
  agent-module/plugins-it/spring-data-r2dbc-it/src/test/java/com/navercorp/pinpoint/it/plugin/jdbc/r2dbc/PostgreSqlServer.java
  agent-testweb/spring-data-r2dbc-plugin-testweb/src/main/java/com/pinpoint/test/plugin/MariadbR2dbcDatabase.java
  agent-testweb/spring-data-r2dbc-plugin-testweb/src/test/java/com/pinpoint/test/plugin/spring/data/r2dbc/R2dbcH2Test.java
  agent-testweb/spring-data-r2dbc-plugin-testweb/src/test/java/com/pinpoint/test/plugin/spring/data/r2dbc/R2dbcMariadbTest.java
  agent-testweb/spring-data-r2dbc-plugin-testweb/src/test/java/com/pinpoint/test/plugin/spring/data/r2dbc/R2dbcMssqlTest.java
  agent-testweb/spring-data-r2dbc-plugin-testweb/src/test/java/com/pinpoint/test/plugin/spring/data/r2dbc/R2dbcMysqlTest.java
  agent-testweb/spring-data-r2dbc-plugin-testweb/src/test/java/com/pinpoint/test/plugin/spring/data/r2dbc/R2dbcPostgresqlTest.java
Labels: cleanup

#10782 [#noissue] Cleanup Deprecated Api
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/SpanEventBo.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/SpanEventComparator.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/serializer/trace/v2/SpanDecoderV0.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/serializer/trace/v2/SpanEncoderV0.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/serializer/trace/v2/bitfield/SpanEventBitField.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/serializer/trace/v2/bitfield/SpanEventQualifierBitField.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/thrift/SpanFactory.java
  commons-server/src/test/java/com/navercorp/pinpoint/common/server/bo/RandomTSpan.java
  commons-server/src/test/java/com/navercorp/pinpoint/common/server/bo/SpanFactoryAssert.java
  commons-server/src/test/java/com/navercorp/pinpoint/common/server/bo/serializer/trace/v2/bitfield/SpanEventBitFieldTest.java
  commons-server/src/test/java/com/navercorp/pinpoint/common/server/bo/thrift/SpanFactoryTest.java
  web/src/test/java/com/navercorp/pinpoint/web/calltree/span/CallTreeIteratorTest.java
  web/src/test/java/com/navercorp/pinpoint/web/calltree/span/CallTreeTest.java
Labels: cleanup

#10801 [#noissue] Improve ARM64 compatibility of JNA and JNR
  pom.xml
Labels: cleanup

#10802 [#noissue] Improve ARM64 compatibility of zstd-jni
  metric-module/metric/pom.xml
  pom.xml
Labels: cleanup

#10803 [#noissue] Fix plugin-it classloading and dependency
  agent-module/plugins-test/src/main/java/com/navercorp/pinpoint/test/plugin/DefaultPluginForkedTestSuite.java
  agent-module/plugins-test/src/main/java/com/navercorp/pinpoint/test/plugin/PluginClassLoading.java
Labels: Continuous Integration

#10799 [#noissue] Cleanup testcontainers dependency
  agent-module/plugins-it/cassandra-it/cassandra-2-it/pom.xml
  agent-module/plugins-it/cassandra-it/cassandra-4-it/pom.xml
  agent-module/plugins-it/clickhouse-jdbc-it/pom.xml
  agent-module/plugins-it/elasticsearch-it/elasticsearch-6-it/pom.xml
  agent-module/plugins-it/elasticsearch-it/elasticsearch-6-it/src/test/java/com/navercorp/pinpoint/it/plugin/elasticsearch/ESServerContainerFactory.java
  agent-module/plugins-it/elasticsearch-it/elasticsearch-7-16-it/pom.xml
  agent-module/plugins-it/elasticsearch-it/elasticsearch-7-16-it/src/test/java/com/navercorp/pinpoint/it/plugin/elasticsearch/ESServerContainerFactory.java
  agent-module/plugins-it/informix-jdbc-it/pom.xml
  agent-module/plugins-it/informix-jdbc-it/src/test/java/com/navercorp/pinpoint/it/plugin/jdbc/informix/InformixServer.java
  agent-module/plugins-it/jtds-it/pom.xml
  agent-module/plugins-it/jtds-it/src/test/java/com/navercorp/pinpoint/it/plugin/jdbc/jtds/JtdsConnectionIT.java
  agent-module/plugins-it/jtds-it/src/test/java/com/navercorp/pinpoint/it/plugin/jdbc/jtds/MsSqlServer.java
  agent-module/plugins-it/kafka-it/kafka-3-it/pom.xml
  agent-module/plugins-it/mariadb-jdbc-it/pom.xml
  agent-module/plugins-it/mariadb-jdbc-it/src/test/java/com/navercorp/pinpoint/it/plugin/jdbc/MariaDBServer.java
  agent-module/plugins-it/mongodb-it/mongodb-3-it/pom.xml
  agent-module/plugins-it/mongodb-it/mongodb-4-it/pom.xml
  agent-module/plugins-it/mssql-jdbc-it/pom.xml
  agent-module/plugins-it/mssql-jdbc-it/src/test/java/com/navercorp/pinpoint/it/plugin/jdbc/mssql/MSSQLServerContainerFactory.java
  agent-module/plugins-it/mysql-jdbc-driver-plugin-it/pom.xml
  agent-module/plugins-it/mysql-jdbc-driver-plugin-it/src/test/java/com/navercorp/pinpoint/it/plugin/jdbc/mysql/MySqlServer.java
  agent-module/plugins-it/oracledb-it/oracledb-11-it/pom.xml
  agent-module/plugins-it/oracledb-it/oracledb-19-it/pom.xml
  agent-module/plugins-it/paho-mqtt-it/pom.xml
  agent-module/plugins-it/plugins-it-utils-jdbc/pom.xml
  agent-module/plugins-it/plugins-it-utils/pom.xml
  agent-module/plugins-it/plugins-it-utils/src/main/java/com/navercorp/pinpoint/it/plugin/utils/LogOutputStream.java
  agent-module/plugins-it/plugins-it-utils/src/main/java/com/navercorp/pinpoint/it/plugin/utils/LogUtils.java
  agent-module/plugins-it/pom.xml
  agent-module/plugins-it/postgresql-jdbc-it/pom.xml
  agent-module/plugins-it/postgresql-jdbc-it/src/test/java/com/navercorp/pinpoint/it/plugin/jdbc/postgresql/PostgreSQLContainerFactory.java
  agent-module/plugins-it/rabbitmq-it/pom.xml
  agent-module/plugins-it/redis-lettuce-it/pom.xml
  agent-module/plugins-it/spring-data-r2dbc-it/pom.xml
  agent-module/pom.xml
  agent-testweb/elasticsearch-8-plugin-testweb/src/main/java/com/pinpoint/test/plugin/ElasticSearchServer.java
  agent-testweb/elasticsearch-plugin-testweb/src/main/java/com/pinpoint/test/plugin/ElasticSearchServer.java
Labels: cleanup

#10806 [#noissue] Improve ARM64 compatibility of elasticsearch plugin test
  agent-module/plugins-it/elasticsearch-it/elasticsearch-6-it/pom.xml
Labels: cleanup

#10808 [#noissue] Fix plugin-it forked required libs
  agent-module/plugins-it/mssql-jdbc-it/src/test/java/com/navercorp/pinpoint/it/plugin/jdbc/mssql/MSSSqlConnectionIT.java
  agent-module/plugins-test/src/main/java/com/navercorp/pinpoint/test/plugin/AbstractPluginForkedTestSuite.java
  agent-module/plugins-test/src/main/java/com/navercorp/pinpoint/test/plugin/PluginClassLoading.java
Labels: Continuous Integration

#10810 [#noissue] Fix SpotBug Warning
  pinot/pinot-datasource/src/main/java/com/navercorp/pinpoint/pinot/mybatis/PinotAsyncTemplate.java
Labels: cleanup

#10807 [#noissue] Return the empty string as is
  exceptiontrace/exceptiontrace-web/src/main/java/com/navercorp/pinpoint/exceptiontrace/web/model/ExceptionTraceValueView.java
  exceptiontrace/exceptiontrace-web/src/test/java/com/navercorp/pinpoint/exceptiontrace/web/model/ExceptionTraceValueViewTest.java
Labels: module:web

#10815 [#10704] Improved to operate with inspectorStatV2 table using sortkey.
  batch/src/main/java/com/navercorp/pinpoint/batch/alarm/collector/pinot/DataSourceDataCollector.java
  batch/src/main/java/com/navercorp/pinpoint/batch/alarm/dao/model/BatchQueryParameter.java
  batch/src/main/java/com/navercorp/pinpoint/batch/alarm/dao/pinot/PinotAlarmDao.java
  batch/src/main/resources/job/applicationContext-alarmJob.xml
  batch/src/main/resources/mapper/batch/BatchAlarmForPinotMapper.xml
Labels: module:inspector

#10818 [#10817] Bump micrometer to 1.12.4
  pom.xml
Labels: dependencies

#10821 [#10819] Bump junit from 5.9.3 to 5.10.2
  agent-module/plugins-test-module/plugins-test/pom.xml
  pom.xml
Labels: dependencies

#10822 [#10820] Bump jackson from 2.15.2 to 1.16.2
  pom.xml
Labels: dependencies

#10823 [#noissue] Replace commons-logging with log4j2
  commons-mybatis/src/main/java/com/navercorp/pinpoint/mybatis/plugin/DefaultBindingLogFormatter.java
Labels: cleanup
