Repository pinpoint-apm/pinpoint, pull requests merged in 2024-04, with the labels that each got.

#10825 [#noissue] Cleanup
  agent-module/plugins/log4j2/src/main/java/com/navercorp/pinpoint/plugin/log4j2/interceptor/PatternLayoutInterceptor.java
Labels: cleanup

#10816 [#10814] Prevent NPE when grpc status error message is null
  commons/src/main/java/com/navercorp/pinpoint/common/util/StringUtils.java
  grpc/src/main/java/com/navercorp/pinpoint/grpc/StatusErrors.java
  grpc/src/test/java/com/navercorp/pinpoint/grpc/StatusErrorsTest.java
Labels: bug, module:agent

#10812 [#noissue] Handle PinotResultSet implicitly convert "null" to null
  exceptiontrace/exceptiontrace-common/src/main/java/com/navercorp/pinpoint/exceptiontrace/common/model/ExceptionMetaData.java
  exceptiontrace/exceptiontrace-web/src/main/java/com/navercorp/pinpoint/exceptiontrace/web/dao/PinotExceptionTraceDao.java
  exceptiontrace/exceptiontrace-web/src/main/java/com/navercorp/pinpoint/exceptiontrace/web/mapper/ExceptionMetaDataEntityMapper.java
  exceptiontrace/exceptiontrace-web/src/main/java/com/navercorp/pinpoint/exceptiontrace/web/model/ExceptionTraceSummary.java
  exceptiontrace/exceptiontrace-web/src/main/java/com/navercorp/pinpoint/exceptiontrace/web/model/ExceptionTraceValueView.java
  exceptiontrace/exceptiontrace-web/src/main/java/com/navercorp/pinpoint/exceptiontrace/web/model/Grouped.java
  exceptiontrace/exceptiontrace-web/src/main/java/com/navercorp/pinpoint/exceptiontrace/web/util/ExceptionTraceQueryParameter.java
  exceptiontrace/exceptiontrace-web/src/test/java/com/navercorp/pinpoint/exceptiontrace/web/mapper/ExceptionMetaDataEntityMapperTest.java
  exceptiontrace/exceptiontrace-web/src/test/java/com/navercorp/pinpoint/exceptiontrace/web/model/ExceptionTraceValueViewTest.java
Labels: module:collector, module:web

#10839 [#noissue] Cleanup GrpcSqlMetaDataHandler
  collector/src/main/java/com/navercorp/pinpoint/collector/handler/grpc/GrpcSqlMetaDataHandler.java
  collector/src/main/java/com/navercorp/pinpoint/collector/handler/grpc/GrpcSqlUidMetaDataHandler.java
Labels: module:collector, cleanup

#10834 [#10828] Backport: Resolve issue for rewritten launcher on spring-boot 3.2
  plugins/spring-boot/src/main/java/com/navercorp/pinpoint/plugin/spring/boot/SpringBootPlugin.java
  plugins/spring-boot/src/main/java/com/navercorp/pinpoint/plugin/spring/boot/interceptor/LauncherLaunchInterceptor.java
Labels: module:plugin

#10843 [#noissue] Cleanup
  exceptiontrace/exceptiontrace-collector/src/main/java/com/navercorp/pinpoint/exceptiontrace/collector/dao/PinotExceptionTraceDao.java
  exceptiontrace/exceptiontrace-web/src/test/java/com/navercorp/pinpoint/exceptiontrace/web/model/ExceptionTraceValueViewTest.java
Labels: module:collector, module:test

#10842 [#noissue] Fix intermittent testcase failure
  agent-module/plugins-test-module/plugins-test/src/test/java/com/navercorp/pinpoint/test/plugin/DependencyResolverTest.java
Labels: cleanup

#10841 [#10840] Java Security is deprecated in java17
  agent-module/bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/classloader/ParallelClassLoaderFactory.java
  agent-module/bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/classloader/URLClassLoaderFactory.java
  agent-module/bootstraps/bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/PinpointStarter.java
  agent-module/profiler-test/src/main/java/com/navercorp/pinpoint/profiler/test/classloader/TransformClassLoader.java
  agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/context/provider/plugin/PluginClassLoaderProvider.java
Labels: cleanup

#10847 [#noissue] Resolve MapStruct warning due to protobuf unmapped target
  agent-module/profiler/pom.xml
  agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/context/grpc/mapper/AgentInfoMapper.java
  agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/context/grpc/mapper/AgentStatMapper.java
  agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/context/grpc/mapper/AnnotationValueMapper.java
  agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/context/grpc/mapper/CustomMetricMapper.java
  agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/context/grpc/mapper/ExceptionMetaDataMapper.java
  agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/context/grpc/mapper/MetaDataMapper.java
  agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/context/grpc/mapper/SpanMessageMapper.java
  agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/context/grpc/mapper/ThreadDumpMapper.java
  agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/context/grpc/mapper/UriStatMapper.java
  commons-mapstruct-spi/pom.xml
  commons-mapstruct-spi/src/main/java/com/navercorp/pinpoint/mapstruct/spi/ProcessingEnvOptionsHolder.java
  commons-mapstruct-spi/src/main/java/com/navercorp/pinpoint/mapstruct/spi/ProtobufAccessorNamingStrategy.java
  commons-mapstruct-spi/src/main/resources/META-INF/services/javax.annotation.processing.Processor
  commons-mapstruct-spi/src/main/resources/META-INF/services/org.mapstruct.ap.spi.AccessorNamingStrategy
  pom.xml
Labels: module:agent

#10848 [#10846] Bump lettuce from 6.2.3 to 6.3.2
  agent-module/plugins-it/redis-lettuce-it/pom.xml
  agent-module/plugins-it/redis-lettuce-it/src/test/java/com/navercorp/pinpoint/it/plugin/lettuce/RedisServer.java
  agent-module/plugins/bom/pom.xml
  pom.xml
  realtime/realtime-common/pom.xml
  redis/pom.xml
Labels: dependencies

#10849 [#10757] Cleanup
  agent-module/pom.xml
Labels: cleanup

#10836 [#noissue] Linked application list cache
  collector/src/main/resources/hbase-root.properties
  web/src/main/java/com/navercorp/pinpoint/web/service/CacheServiceImpl.java
Labels: module:web

#10850 [#noissue] Fix SpotBugs warnings
  agent-module/plugins-test-module/plugins-test/src/main/java/com/navercorp/pinpoint/test/plugin/DefaultPluginJunitTestInstance.java
  agent-module/profiler-test/src/main/java/com/navercorp/pinpoint/profiler/test/classloader/TestClassLoader.java
  agent-module/profiler-test/src/main/java/com/navercorp/pinpoint/profiler/test/classloader/TestClassLoaderFactory.java
  agent-module/profiler-test/src/main/java/com/navercorp/pinpoint/profiler/test/junit5/TestContext.java
Labels: cleanup

#10851 [#10704] add segmentPruning function in application table config
  inspector-module/inspector-collector/src/main/pinot/pinot-inspector-stat-application-realtime-table.json
Labels: module:inspector

#10855 [#noissue] Cleanup
  agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/instrument/ASMAspectWeaver.java
  web/src/main/java/com/navercorp/pinpoint/web/mapper/SpanMapperV2.java
Labels: cleanup

#10856 [#noissue] Cleanup
  agent-module/plugins-test-module/plugins-test/src/main/java/com/navercorp/pinpoint/test/plugin/DefaultPluginTestSuite.java
  agent-module/plugins-test-module/plugins-test/src/main/java/com/navercorp/pinpoint/test/plugin/shared/PluginSharedInstanceFactory.java
  agent-module/plugins-test-module/plugins-test/src/main/java/com/navercorp/pinpoint/test/plugin/util/ClassLoaderUtils.java
  agent-module/plugins-test-module/plugins-test/src/test/java/com/navercorp/pinpoint/test/plugin/shared/ReflectionDependencyResolverTest.java
Labels: cleanup

#10861 [#10844] Backport: Add new Main classes to SpringBootDetector
  agent/src/main/resources/profiles/local/pinpoint.config
  agent/src/main/resources/profiles/release/pinpoint.config
  plugins-it/activemq-it/src/test/resources/activemq/client/pinpoint-activemq-client.config
  plugins-it/cxf-it/src/test/resources/cxf/pinpoint-cxf-test.config
  plugins-it/druid-it/src/test/resources/druid/pinpoint-druid-test.config
  plugins-it/fastjson-it/src/test/resources/fastjson/pinpoint-fastjson-test.config
  plugins-it/google-grpc-it/src/test/resources/pinpoint-grpc-plugin-test.config
  plugins-it/google-grpc-it2/src/test/resources/pinpoint-grpc-plugin-test.config
  plugins-it/hbase-it/src/test/resources/hbase/pinpoint-hbase-test.config
  plugins-it/hystrix-it/src/test/resources/hystrix/pinpoint-hystrix.config
  plugins-it/jtds-it/src/test/resources/pinpoint.config
  plugins-it/lambda-it/src/test/resources/pinpoint-lambda-test.config
  plugins-it/log4j-it/src/test/resources/pinpoint-spring-bean-test.config
  plugins-it/log4j2-it/src/test/resources/pinpoint-spring-bean-test.config
  plugins-it/logback-it/src/test/resources/pinpoint-spring-bean-test.config
  plugins-it/netty-it/src/test/resources/pinpoint-netty-plugin-test.config
  plugins-it/process-it/src/test/resources/pinpoint-process-test.config
  plugins-it/rxjava-it/src/test/resources/rxjava/pinpoint-rxjava.config
  plugins-it/spring-it/src/test/resources/pinpoint-disabled-plugin-test.config
  plugins-it/spring-it/src/test/resources/pinpoint-spring-bean-test.config
  plugins-it/thread-it/src/test/resources/pinpoint-thread-test-multiple-pkg.config
  plugins-it/thread-it/src/test/resources/pinpoint-thread-test.config
  plugins/akka-http/src/test/resources/pinpoint.config
  plugins/google-httpclient/src/test/resources/pinpoint.config
  plugins/httpclient3/src/test/resources/pinpoint.config
  plugins/httpclient4/src/test/resources/pinpoint.config
  plugins/jboss/src/test/resources/pinpoint.config
  plugins/jsp/src/test/resources/pinpoint.config
  plugins/redis/src/test/resources/pinpoint.config
  plugins/spring-boot/README.md
  plugins/spring-boot/src/main/java/com/navercorp/pinpoint/plugin/spring/boot/SpringBootDetector.java
  plugins/tomcat/src/test/resources/pinpoint.config
  plugins/user/src/test/resources/pinpoint.config
  plugins/vertx/src/test/resources/pinpoint.config
  plugins/weblogic/src/test/resources/pinpoint.config
  profiler/src/test/resources/pinpoint.config
Labels: module:plugin

#10860 [#noissue] Simplify OnClassLoader state
  agent-module/plugins-test-module/plugins-test/src/main/java/com/navercorp/pinpoint/test/plugin/ClassLoding.java
  agent-module/plugins-test-module/plugins-test/src/main/java/com/navercorp/pinpoint/test/plugin/DefaultPluginForkedTestInstance.java
  agent-module/plugins-test-module/plugins-test/src/main/java/com/navercorp/pinpoint/test/plugin/DefaultPluginForkedTestSuite.java
  agent-module/plugins-test-module/plugins-test/src/main/java/com/navercorp/pinpoint/test/plugin/DefaultPluginTestSuite.java
  agent-module/plugins-test-module/plugins-test/src/main/java/com/navercorp/pinpoint/test/plugin/OnClassLoader.java
  agent-module/plugins-test-module/plugins-test/src/main/java/com/navercorp/pinpoint/test/plugin/PluginTestInstanceFactory.java
Labels: cleanup

#10863 [#10704] Cleanup of code added to compare performance
  inspector-module/inspector-web/src/main/java/com/navercorp/pinpoint/inspector/web/config/InspectorRegistryHandler.java
  inspector-module/inspector-web/src/main/java/com/navercorp/pinpoint/inspector/web/controller/AgentStatV2Controller.java
  inspector-module/inspector-web/src/main/java/com/navercorp/pinpoint/inspector/web/controller/ApplicationStatV2Controller.java
  inspector-module/inspector-web/src/main/java/com/navercorp/pinpoint/inspector/web/dao/model/InspectorQueryParameter.java
  inspector-module/inspector-web/src/main/java/com/navercorp/pinpoint/inspector/web/dao/model/InspectorQueryParameterV2.java
  inspector-module/inspector-web/src/main/java/com/navercorp/pinpoint/inspector/web/dao/pinot/PinotAgentStatDao.java
  inspector-module/inspector-web/src/main/java/com/navercorp/pinpoint/inspector/web/dao/pinot/PinotApplicationStatDao.java
  inspector-module/inspector-web/src/main/java/com/navercorp/pinpoint/inspector/web/definition/metric/UsingDataSourceTagForAgentPreProcessor.java
  inspector-module/inspector-web/src/main/java/com/navercorp/pinpoint/inspector/web/definition/metric/UsingDataSourceTagForApplicationPreProcessor.java
  inspector-module/inspector-web/src/main/java/com/navercorp/pinpoint/inspector/web/model/InspectorDataSearchKey.java
  inspector-module/inspector-web/src/main/java/com/navercorp/pinpoint/inspector/web/service/DefaultAgentStatService.java
  inspector-module/inspector-web/src/main/java/com/navercorp/pinpoint/inspector/web/service/DefaultApplicationStatService.java
  inspector-module/inspector-web/src/main/resources/inspector/web/mapper/pinot/agentInspectorV2Mapper.xml
  inspector-module/inspector-web/src/main/resources/inspector/web/mapper/pinot/applicationInspectorV2Mapper.xml
Labels: module:inspector

#10862 [#noissue] Cleanup
  agent-module/plugins-test-module/plugins-test/src/main/java/com/navercorp/pinpoint/test/plugin/junit5/descriptor/PluginJunitTestClassTestDescriptor.java
  agent-module/plugins-test-module/plugins-test/src/main/java/com/navercorp/pinpoint/test/plugin/junit5/descriptor/PluginJunitTestMethodTestDescriptor.java
  agent-module/plugins-test-module/plugins-test/src/main/java/com/navercorp/pinpoint/test/plugin/shared/PluginSharedInstance.java
  agent-module/plugins-test-module/plugins-test/src/main/java/com/navercorp/pinpoint/test/plugin/util/ThreadContextExecutor.java
Labels: cleanup

#10864 [#noissue] Fix NPE of PluginTestClassLoader
  agent-module/plugins-test-module/plugins-test/src/main/java/com/navercorp/pinpoint/test/plugin/DefaultPluginTestInstance.java
  agent-module/plugins-test-module/plugins-test/src/main/java/com/navercorp/pinpoint/test/plugin/classloader/PluginTestClassLoader.java
  agent-module/plugins-test-module/plugins-test/src/main/java/com/navercorp/pinpoint/test/plugin/shared/SharedProcessManager.java
  agent-module/plugins-test-module/plugins-test/src/main/java/com/navercorp/pinpoint/test/plugin/shared/SharedTestExecutor.java
Labels: cleanup

#10871 [#10704] Attempts to improve performance and reduce disk utilization
  inspector-module/inspector-collector/src/main/java/com/navercorp/pinpoint/inspector/collector/config/InspectorKafkaConfiguration.java
  inspector-module/inspector-collector/src/main/java/com/navercorp/pinpoint/inspector/collector/dao/pinot/DefaultAgentStatDao.java
  inspector-module/inspector-collector/src/main/java/com/navercorp/pinpoint/inspector/collector/dao/pinot/PinotDaoConfiguration.java
  inspector-module/inspector-collector/src/main/java/com/navercorp/pinpoint/inspector/collector/model/kafka/AgentStatV2.java
  pinot/pinot-kafka/src/main/java/com/navercorp/pinpoint/pinot/kafka/KafkaConfiguration.java
  pinot/pinot-kafka/src/main/java/com/navercorp/pinpoint/pinot/kafka/KafkaProperties.java
Labels: module:inspector

#10870 [#noissue] Cleanup LocalDate API
  web/src/main/java/com/navercorp/pinpoint/web/util/DateTimeUtils.java
Labels: cleanup

#10869 [#noissue] Cleanup Job&Process management
  agent-module/plugins-test-module/plugins-test/src/main/java/com/navercorp/pinpoint/test/plugin/DefaultPluginTestInstance.java
  agent-module/plugins-test-module/plugins-test/src/main/java/com/navercorp/pinpoint/test/plugin/DefaultProcessManager.java
  agent-module/plugins-test-module/plugins-test/src/main/java/com/navercorp/pinpoint/test/plugin/classloader/PluginTestClassLoader.java
  agent-module/plugins-test-module/plugins-test/src/main/java/com/navercorp/pinpoint/test/plugin/shared/SharedTestExecutor.java
Labels: cleanup

#10873 [#noissue] Eliminate unnecessary delay
  web/src/test/java/com/navercorp/pinpoint/web/websocket/PinpointWebSocketTimerTaskDecoratorTest.java
Labels: cleanup

#10874 [#10859] Fix interceptorHolder on bootstrap classloader
  agent-module/bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/interceptor/registry/DefaultInterceptorRegistryAdaptor.java
  agent-module/bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/interceptor/registry/EmptyRegistryAdaptor.java
  agent-module/bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/interceptor/registry/InterceptorRegistry.java
  agent-module/bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/interceptor/registry/InterceptorRegistryAdaptor.java
  agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/instrument/ASMMethod.java
  agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/instrument/ASMMethodVariables.java
Labels: enhancement, module:plugin, module:agent

#10876 [#10704] fit test fail
  pinot/pinot-kafka/src/test/java/com/navercorp/pinpoint/pinot/kafka/KafkaConfigurationTest.java
Labels: module:inspector

#10877 [#noissue] Remove unnecessary threads
  realtime/realtime-common/src/test/java/com/navercorp/pinpoint/util/ThrottleTest.java
Labels: cleanup

#10878 [#noissue] Remove duplicate code
  agent-module/plugins-test-module/plugins-test/src/main/java/com/navercorp/pinpoint/test/plugin/DefaultProcessManager.java
  agent-module/plugins-test-module/plugins-test/src/main/java/com/navercorp/pinpoint/test/plugin/ProcessTerminator.java
  agent-module/plugins-test-module/plugins-test/src/main/java/com/navercorp/pinpoint/test/plugin/shared/SharedProcessManager.java
Labels: cleanup

#10868 [#10865] Added param `serviceTypeName`
  web/src/main/java/com/navercorp/pinpoint/web/authorization/controller/AgentInfoController.java
  web/src/main/java/com/navercorp/pinpoint/web/authorization/controller/AgentListController.java
  web/src/main/java/com/navercorp/pinpoint/web/realtime/AgentLookupServiceImpl.java
  web/src/main/java/com/navercorp/pinpoint/web/service/AgentInfoService.java
  web/src/main/java/com/navercorp/pinpoint/web/service/AgentInfoServiceImpl.java
  web/src/main/java/com/navercorp/pinpoint/web/vo/agent/AgentInfoFilter.java
  web/src/main/java/com/navercorp/pinpoint/web/vo/agent/AgentInfoFilters.java
  web/src/main/java/com/navercorp/pinpoint/web/vo/agent/AgentStatusFilter.java
  web/src/main/java/com/navercorp/pinpoint/web/vo/agent/AgentStatusFilterChain.java
  web/src/main/java/com/navercorp/pinpoint/web/vo/agent/AgentStatusFilters.java
  web/src/main/java/com/navercorp/pinpoint/web/vo/agent/DefaultAgentStatusFilter.java
  web/src/main/java/com/navercorp/pinpoint/web/vo/tree/AgentsMapByApplication.java
  web/src/main/java/com/navercorp/pinpoint/web/vo/tree/AgentsMapByHost.java
  web/src/main/java/com/navercorp/pinpoint/web/vo/tree/InstancesListMapBuilder.java
  web/src/test/java/com/navercorp/pinpoint/web/vo/AgentsMapByApplicationTest.java
  web/src/test/java/com/navercorp/pinpoint/web/vo/AgentsMapByHostTest.java
  web/src/test/java/com/navercorp/pinpoint/web/vo/agent/AgentStatusFilterChainTest.java
Labels: module:web

#10886 [#10885] Bump springframework from 6.0.16 to 6.1.5
  pom.xml
Labels: dependencies

#10888 [#10887] Bump spring-boot from 3.1.8 to 3.2.4
  agent-module/agent-testweb/mongodb-plugin-testweb/pom.xml
  agent-module/agent-testweb/mongodb-reactive-plugin-testweb/pom.xml
  agent-module/agent-testweb/pom.xml
  agent-module/agent-testweb/redis-lettuce-plugin-testweb/pom.xml
  agent-module/agent-testweb/spring-boot3-testweb/pom.xml
  agent-module/agent-testweb/spring-boot3-webflux-plugin-testweb/pom.xml
  agent-module/agent-testweb/spring-cloud-gateway-plugin-testweb/pom.xml
  agent-module/plugins/spring/pom.xml
  channel/pom.xml
  collector-starter/pom.xml
  hbase/hbase-schema-manager/pom.xml
  pom.xml
  quickstart/testapp/pom.xml
  realtime/realtime-common/pom.xml
  redis/pom.xml
  web/pom.xml
Labels: dependencies

#10891 [#10704] Modify the logic so that the long type sortkey is properly assigned a partition.
  inspector-module/inspector-collector/pom.xml
  inspector-module/inspector-collector/src/main/java/com/navercorp/pinpoint/inspector/collector/config/InspectorKafkaConfiguration.java
  inspector-module/inspector-collector/src/main/java/com/navercorp/pinpoint/inspector/collector/dao/pinot/DefaultAgentStatDao.java
  inspector-module/inspector-collector/src/main/java/com/navercorp/pinpoint/inspector/collector/dao/pinot/PinotDaoConfiguration.java
  inspector-module/inspector-collector/src/test/java/com/navercorp/pinpoint/inspector/collector/dao/pinot/DefaultAgentStatDaoTest.java
  pinot/pinot-kafka/src/main/java/com/navercorp/pinpoint/pinot/kafka/KafkaConfiguration.java
  pinot/pinot-kafka/src/main/java/com/navercorp/pinpoint/pinot/kafka/KafkaProperties.java
Labels: module:inspector

#10890 [#10889] Bump spring-cloud to 4.1.2
  agent-module/agent-testweb/pom.xml
  agent-module/agent-testweb/rocketmq-plugin-testweb/rocketmq-springcloud-stream/pom.xml
  agent-module/agent-testweb/spring-cloud-gateway-plugin-testweb/pom.xml
  pom.xml
Labels: dependencies

#10895 [#10894] Bump spring-security from 6.1.4 to 6.1.8
  pom.xml
Labels: dependencies

#10897 [#10896] Bump spring-data to 3.2.4
  agent-module/plugins/bom/pom.xml
  pom.xml
  realtime/realtime-common/pom.xml
  redis/pom.xml
Labels: dependencies

#10899 [#10898] Bump grpc from 1.59.0 to 1.62.2
  agent-module/plugins-it/google-grpc-it/google-grpc-1-42-it/pom.xml
  agent-module/plugins-it/google-grpc-it/google-grpc-1-8-it/pom.xml
  agent-module/plugins-it/kafka-it/kafka-3-it/src/test/java/test/pinpoint/plugin/kafka/ZookeeperUnitServer.java
  pom.xml
Labels: dependencies

#10902 [#noissue] Cleanup
  agent-module/plugins-it/google-grpc-it/google-grpc-1-8-it/src/test/java/com/navercorp/pinpoint/it/plugin/grpc/HelloWorldSimpleServer.java
  agent-module/plugins-it/kafka-it/kafka-2-it/src/test/java/test/pinpoint/plugin/kafka/ZookeeperUnitServer.java
Labels: cleanup

#10903 [#noissue] Add Java8 Date/Time type to PluginLoggerAdapter
  agent-module/profiler-logging/src/main/java/com/navercorp/pinpoint/profiler/logging/AbstractLoggerAdapter.java
  agent-module/profiler-logging/src/test/java/com/navercorp/pinpoint/profiler/logging/Log4J2PluginLoggerAdapterTest.java
Labels: enhancement

#10905 [#noissue] Apply Java8 Date API
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/util/time/DateTimeUtils.java
  web/src/main/java/com/navercorp/pinpoint/web/controller/ApplicationController.java
  web/src/main/java/com/navercorp/pinpoint/web/service/AgentInfoService.java
  web/src/main/java/com/navercorp/pinpoint/web/service/AgentInfoServiceImpl.java
Labels: cleanup

#10906 [#noissue] Apply Java8 Date API
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/util/time/DateTimeUtils.java
  commons-server/src/test/java/com/navercorp/pinpoint/common/server/util/time/DateTimeUtilsTest.java
  metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/collector/service/SystemMetricDataTypeServiceImpl.java
  metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/collector/service/SystemMetricTagServiceImpl.java
  metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/common/model/MetricDataName.java
  metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/web/service/SystemMetricHostInfoServiceImpl.java
  metric-module/metric/src/test/java/com/navercorp/pinpoint/metric/collector/service/SystemMetricTagServiceImplTest.java
Labels: cleanup

#10914 [#noissue] Update plugin-it method name
  agent-module/plugins-test-module/plugins-test/src/main/java/com/navercorp/pinpoint/test/plugin/junit5/descriptor/PluginForkedTestMethodTestDescriptor.java
  agent-module/plugins-test-module/plugins-test/src/main/java/com/navercorp/pinpoint/test/plugin/junit5/descriptor/PluginTestMethodTestDescriptor.java
  agent-module/plugins-test-module/plugins-test/src/main/java/com/navercorp/pinpoint/test/plugin/junit5/engine/PluginForkedTestEngine.java
  agent-module/plugins-test-module/plugins-test/src/main/java/com/navercorp/pinpoint/test/plugin/junit5/engine/PluginTestEngine.java
Labels: Continuous Integration

#10904 [#10859] Fix interceptor holder log NPE
  agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/instrument/ASMMethod.java
Labels: module:agent

#10913 [#10912] Bump mybatis from 3.5.13 to 3.5.16
  pom.xml
Labels: dependencies

#10910 [#noissue] Add limit to String.split
  log/log-common/src/main/java/com/navercorp/pinpoint/log/vo/FileKey.java
  log/log-common/src/main/java/com/navercorp/pinpoint/log/vo/HostKey.java
  log/log-common/src/test/java/com/navercorp/pinpoint/log/vo/FileKeyTest.java
  log/log-web/src/main/java/com/navercorp/pinpoint/log/web/service/LiveTailServiceImpl.java
  log/log-web/src/main/java/com/navercorp/pinpoint/log/web/service/LogFileKeyMapSupplier.java
  log/log-web/src/main/java/com/navercorp/pinpoint/log/web/vo/LogHostGroupInfo.java
Labels: cleanup

#10917 [#noissue] Add custom hbase-schema-path
  hbase/hbase-schema-manager/src/main/java/com/navercorp/pinpoint/hbase/manager/config/AppConfig.java
  hbase/hbase-schema-manager/src/main/resources/application.properties
  hbase/hbase-schema-manager/src/main/resources/application.yml
  hbase/hbase-schema/src/main/java/com/navercorp/pinpoint/hbase/schema/reader/xml/XmlHbaseSchemaReader.java
Labels: cleanup

#10926 [#noissue] Fix oracle 19 GssCredential
  agent-module/plugins-it/oracledb-it/oracledb-11-it/src/test/java/com/navercorp/pinpoint/it/plugin/jdbc/oracle/OracleItHelper.java
  agent-module/plugins-it/oracledb-it/oracledb-19-it/src/test/java/com/navercorp/pinpoint/it/plugin/jdbc/oracle/OracleItHelper.java
Labels: Continuous Integration

#10927 [#10704] Create a minute unit statistical data table for agent
  inspector-module/inspector-collector/src/main/java/com/navercorp/pinpoint/inspector/collector/model/kafka/AgentStat.java
  inspector-module/inspector-collector/src/main/java/com/navercorp/pinpoint/inspector/collector/model/kafka/AgentStatModelConverter.java
  metric-module/metric-commons/src/main/java/com/navercorp/pinpoint/metric/common/model/Tags.java
  metric-module/metric-commons/src/main/java/com/navercorp/pinpoint/metric/common/mybatis/typehandler/TagListSerializer.java
  metric-module/metric-commons/src/main/java/com/navercorp/pinpoint/metric/common/mybatis/typehandler/TagListTypeHandler.java
  metric-module/metric-commons/src/main/java/com/navercorp/pinpoint/metric/common/mybatis/typehandler/TagMySqlSerializer.java
  metric-module/metric-commons/src/test/java/com/navercorp/pinpoint/metric/common/mybatis/typehandler/TagListTypeHandlerTest.java
  metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/collector/dao/pinot/PinotMetricTagDao.java
  metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/collector/model/TelegrafMetric.java
  metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/collector/service/SystemMetricTagServiceImpl.java
  metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/common/config/CommonRegistryHandler.java
  metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/common/model/json/Tags.java
  metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/common/model/mybatis/TagMySqlSerializer.java
Labels: module:inspector

#10932 [#10925] 2.5.4 Update README.md
  README.md
Labels: release

#10945 [#10944] Improve RangeValidator
  batch/src/main/java/com/navercorp/pinpoint/batch/alarm/collector/AgentEventDataCollector.java
  batch/src/main/java/com/navercorp/pinpoint/batch/alarm/collector/AgentStatDataCollector.java
  batch/src/main/java/com/navercorp/pinpoint/batch/alarm/collector/DataSourceDataCollector.java
  batch/src/main/java/com/navercorp/pinpoint/batch/alarm/collector/FileDescriptorDataCollector.java
  batch/src/main/java/com/navercorp/pinpoint/batch/alarm/collector/ResponseTimeDataCollector.java
  batch/src/main/java/com/navercorp/pinpoint/batch/alarm/collector/pinot/DataSourceDataCollector.java
  batch/src/main/java/com/navercorp/pinpoint/batch/alarm/collector/pinot/FileDescriptorDataCollector.java
  batch/src/main/java/com/navercorp/pinpoint/batch/alarm/collector/pinot/HeapDataCollector.java
  batch/src/main/java/com/navercorp/pinpoint/batch/alarm/collector/pinot/JvmCpuDataCollector.java
  batch/src/main/java/com/navercorp/pinpoint/batch/alarm/collector/pinot/SystemCpuDataCollector.java
  batch/src/test/java/com/navercorp/pinpoint/batch/alarm/checker/DataSourceConnectionUsageRateCheckerTest.java
  batch/src/test/java/com/navercorp/pinpoint/batch/alarm/checker/DeadlockCheckerTest.java
  batch/src/test/java/com/navercorp/pinpoint/batch/alarm/collector/FileDescriptorDataCollectorTest.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/util/time/ForwardRangeValidator.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/util/time/Range.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/util/time/RangeValidator.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/util/time/RangeValidatorConfiguration.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/util/time/ReverseRangeValidator.java
  commons-server/src/test/java/com/navercorp/pinpoint/common/server/util/time/ForwardRangeValidatorTest.java
  commons-server/src/test/java/com/navercorp/pinpoint/common/server/util/time/RangeTest.java
  commons-server/src/test/java/com/navercorp/pinpoint/common/server/util/time/ReverseRangeValidatorTest.java
  pinot/pinot-batch/src/main/java/com/navercorp/pinpoint/pinot/alarm/checker/PinotAlarmChecker.java
  web/src/main/java/com/navercorp/pinpoint/web/PinpointWebModule.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/controller/MapController.java
  web/src/main/java/com/navercorp/pinpoint/web/authorization/controller/HeatMapController.java
  web/src/main/java/com/navercorp/pinpoint/web/authorization/controller/ResponseTimeController.java
  web/src/main/java/com/navercorp/pinpoint/web/authorization/controller/ScatterChartController.java
  web/src/main/java/com/navercorp/pinpoint/web/dao/hbase/HbaseApplicationTraceIndexDao.java
  web/src/main/java/com/navercorp/pinpoint/web/vo/RangeFactory.java
  web/src/test/java/com/navercorp/pinpoint/web/util/DateLimiterTest.java
Labels: cleanup

#10941 [#10940] Fix mongodb reactive streams driver interceptor
  agent-module/agent-testweb/mongodb-plugin-testweb/pom.xml
  agent-module/agent-testweb/mongodb-plugin-testweb/src/main/java/com/pinpoint/test/plugin/MongoConfig.java
  agent-module/agent-testweb/mongodb-plugin-testweb/src/main/java/com/pinpoint/test/plugin/MongoPluginController.java
  agent-module/agent-testweb/mongodb-plugin-testweb/src/test/java/com/pinpoint/test/plugin/mongo/MongodbTest.java
  agent-module/bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/jdbc/UnKnownDatabaseInfo.java
  agent-module/plugins/mongodb/src/main/java/com/navercorp/pinpoint/plugin/mongo/MongoConstants.java
  agent-module/plugins/mongodb/src/main/java/com/navercorp/pinpoint/plugin/mongo/MongoPlugin.java
  agent-module/plugins/mongodb/src/main/java/com/navercorp/pinpoint/plugin/mongo/interceptor/DatabaseInfoUtils.java
  agent-module/plugins/mongodb/src/main/java/com/navercorp/pinpoint/plugin/mongo/interceptor/MongoClientConstructorInterceptor.java
  agent-module/plugins/mongodb/src/main/java/com/navercorp/pinpoint/plugin/mongo/interceptor/MongoCollectionImplReadOperationInterceptor.java
  agent-module/plugins/mongodb/src/main/java/com/navercorp/pinpoint/plugin/mongo/interceptor/MongoCollectionImplWriteOperationInterceptor.java
  agent-module/plugins/mongodb/src/test/java/com/navercorp/pinpoint/plugin/mongo/interceptor/DatabaseInfoUtilsTest.java
Labels: bug, module:plugin

#10950 [#10944] Use RangeValidator to check the search time.
  inspector-module/inspector-web/src/main/java/com/navercorp/pinpoint/inspector/web/controller/AgentStatV2Controller.java
  inspector-module/inspector-web/src/main/java/com/navercorp/pinpoint/inspector/web/controller/ApplicationStatV2Controller.java
  metric-module/metric-commons/src/main/java/com/navercorp/pinpoint/metric/common/model/Range.java
  metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/web/controller/SystemMetricController.java
Labels: module:web, module:metric, module:inspector

#10952 [#10948] Backport: Fix mongodb reactive streams driver interceptor
  bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/jdbc/UnKnownDatabaseInfo.java
  plugins/mongodb/src/main/java/com/navercorp/pinpoint/plugin/mongo/MongoConstants.java
  plugins/mongodb/src/main/java/com/navercorp/pinpoint/plugin/mongo/MongoPlugin.java
  plugins/mongodb/src/main/java/com/navercorp/pinpoint/plugin/mongo/interceptor/DatabaseInfoUtils.java
  plugins/mongodb/src/main/java/com/navercorp/pinpoint/plugin/mongo/interceptor/MongoClientConstructorInterceptor.java
  plugins/mongodb/src/main/java/com/navercorp/pinpoint/plugin/mongo/interceptor/MongoCollectionImplReadOperationInterceptor.java
  plugins/mongodb/src/main/java/com/navercorp/pinpoint/plugin/mongo/interceptor/MongoCollectionImplWriteOperationInterceptor.java
  plugins/mongodb/src/test/java/com/navercorp/pinpoint/plugin/mongo/interceptor/DatabaseInfoUtilsTest.java
Labels: bug, module:plugin

#10953 [#10944] Cleanup
  batch/src/main/java/com/navercorp/pinpoint/batch/alarm/collector/AgentEventDataCollector.java
  batch/src/main/java/com/navercorp/pinpoint/batch/alarm/collector/AgentStatDataCollector.java
  batch/src/main/java/com/navercorp/pinpoint/batch/alarm/collector/DataSourceDataCollector.java
  batch/src/main/java/com/navercorp/pinpoint/batch/alarm/collector/FileDescriptorDataCollector.java
  batch/src/main/java/com/navercorp/pinpoint/batch/alarm/collector/ResponseTimeDataCollector.java
  batch/src/main/java/com/navercorp/pinpoint/batch/alarm/collector/pinot/DataSourceDataCollector.java
  batch/src/main/java/com/navercorp/pinpoint/batch/alarm/collector/pinot/FileDescriptorDataCollector.java
  batch/src/main/java/com/navercorp/pinpoint/batch/alarm/collector/pinot/HeapDataCollector.java
  batch/src/main/java/com/navercorp/pinpoint/batch/alarm/collector/pinot/JvmCpuDataCollector.java
  batch/src/main/java/com/navercorp/pinpoint/batch/alarm/collector/pinot/SystemCpuDataCollector.java
  batch/src/test/java/com/navercorp/pinpoint/batch/alarm/checker/DataSourceConnectionUsageRateCheckerTest.java
  batch/src/test/java/com/navercorp/pinpoint/batch/alarm/checker/DeadlockCheckerTest.java
  batch/src/test/java/com/navercorp/pinpoint/batch/alarm/collector/FileDescriptorDataCollectorTest.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/util/time/Range.java
  commons-server/src/test/java/com/navercorp/pinpoint/common/server/util/time/RangeTest.java
  commons-server/src/test/java/com/navercorp/pinpoint/common/server/util/time/ReverseRangeValidatorTest.java
  pinot/pinot-batch/src/main/java/com/navercorp/pinpoint/pinot/alarm/checker/PinotAlarmChecker.java
  web/src/main/java/com/navercorp/pinpoint/web/authorization/controller/HeatMapController.java
  web/src/main/java/com/navercorp/pinpoint/web/authorization/controller/ScatterChartController.java
  web/src/main/java/com/navercorp/pinpoint/web/dao/hbase/HbaseApplicationTraceIndexDao.java
  web/src/main/java/com/navercorp/pinpoint/web/vo/RangeFactory.java
Labels: cleanup

#10951 [#10940] Move the class location to avoid loading the class in web to…
  agent-module/bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/jdbc/MongoDatabaseInfo.java
  agent-module/plugins/mongodb/src/main/java/com/navercorp/pinpoint/plugin/mongo/MongoConstants.java
  agent-module/plugins/mongodb/src/main/java/com/navercorp/pinpoint/plugin/mongo/interceptor/MongoCollectionImplReadOperationInterceptor.java
  agent-module/plugins/mongodb/src/main/java/com/navercorp/pinpoint/plugin/mongo/interceptor/MongoCollectionImplWriteOperationInterceptor.java
  agent-module/plugins/mongodb/src/test/java/com/navercorp/pinpoint/plugin/mongo/interceptor/DatabaseInfoUtilsTest.java
Labels: module:plugin

#10963 [#10704] stored data separately in multiple tables to improve reading speed
  inspector-module/inspector-collector/src/main/java/com/navercorp/pinpoint/inspector/collector/config/InspectorKafkaConfiguration.java
  inspector-module/inspector-collector/src/main/java/com/navercorp/pinpoint/inspector/collector/config/InspectorPropertySources.java
  inspector-module/inspector-collector/src/main/java/com/navercorp/pinpoint/inspector/collector/dao/AgentStatDao.java
  inspector-module/inspector-collector/src/main/java/com/navercorp/pinpoint/inspector/collector/dao/pinot/DefaultAgentStatDao.java
  inspector-module/inspector-collector/src/main/java/com/navercorp/pinpoint/inspector/collector/dao/pinot/PinotDaoConfiguration.java
  inspector-module/inspector-collector/src/main/java/com/navercorp/pinpoint/inspector/collector/model/kafka/AgentStat.java
  inspector-module/inspector-collector/src/main/java/com/navercorp/pinpoint/inspector/collector/model/kafka/AgentStatModelConverter.java
  inspector-module/inspector-collector/src/main/java/com/navercorp/pinpoint/inspector/collector/model/kafka/AgentStatV2.java
  inspector-module/inspector-collector/src/main/resources/inspector/collector/kafka-topic-inspector.properties
  inspector-module/inspector-collector/src/main/resources/inspector/collector/profiles/local/inspector-collector.properties
  inspector-module/inspector-collector/src/main/resources/inspector/collector/profiles/release/inspector-collector.properties
  inspector-module/inspector-commons/src/main/java/com/navercorp/pinpoint/common/dao/pinot/AgentStatTopicNameManager.java
  pinot/pinot-kafka/src/main/java/com/navercorp/pinpoint/pinot/kafka/KafkaConfiguration.java
Labels: module:inspector

#10961 [#noissue] Unify `Range` class across common-server and metric-module
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/util/time/Range.java
  exceptiontrace/exceptiontrace-web/src/main/java/com/navercorp/pinpoint/exceptiontrace/web/controller/ExceptionTraceController.java
  inspector-module/inspector-web/src/main/java/com/navercorp/pinpoint/inspector/web/controller/AgentStatV2Controller.java
  inspector-module/inspector-web/src/main/java/com/navercorp/pinpoint/inspector/web/controller/ApplicationStatV2Controller.java
  inspector-module/inspector-web/src/main/java/com/navercorp/pinpoint/inspector/web/dao/model/InspectorQueryParameter.java
  inspector-module/inspector-web/src/main/java/com/navercorp/pinpoint/inspector/web/dao/model/InspectorQueryParameterV2.java
  inspector-module/inspector-web/src/main/java/com/navercorp/pinpoint/inspector/web/model/InspectorDataSearchKey.java
  metric-module/metric-commons/src/main/java/com/navercorp/pinpoint/metric/common/model/Range.java
  metric-module/metric-commons/src/main/java/com/navercorp/pinpoint/metric/common/model/TimeWindow.java
  metric-module/metric-commons/src/main/java/com/navercorp/pinpoint/metric/common/util/TimeWindowDownSampler.java
  metric-module/metric-commons/src/main/java/com/navercorp/pinpoint/metric/common/util/TimeWindowSampler.java
  metric-module/metric-commons/src/main/java/com/navercorp/pinpoint/metric/common/util/TimeWindowSlotCentricSampler.java
  metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/web/config/WebRegistryHandler.java
  metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/web/controller/SystemMetricController.java
  metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/web/dao/model/SystemMetricDataSearchKey.java
  metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/web/model/MetricDataSearchKey.java
  metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/web/util/QueryParameter.java
  metric-module/metric/src/test/java/com/navercorp/pinpoint/metric/web/model/chart/SystemMetricChartTest.java
  uristat/uristat-web/src/main/java/com/navercorp/pinpoint/uristat/web/controller/UriStatController.java
Labels: cleanup

#10965 [#10944] Cleanup
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/util/time/Range.java
  web/src/main/java/com/navercorp/pinpoint/web/service/AgentInfoServiceImpl.java
  web/src/test/java/com/navercorp/pinpoint/web/service/ApdexScoreServiceImplTest.java
Labels: cleanup

#10971 [#noissue] Fix plugin-it fork shared dependency
  agent-module/plugins-it/mongodb-it/mongodb-4-it/src/test/java/com/navercorp/pinpoint/it/plugin/mongodb4/ReactiveMongoDBIT_4_2_x_IT.java
  agent-module/plugins-it/mssql-jdbc-it/src/test/java/com/navercorp/pinpoint/it/plugin/jdbc/mssql/MSSSqlConnectionIT.java
  agent-module/plugins-it/mssql-jdbc-it/src/test/java/com/navercorp/pinpoint/it/plugin/jdbc/mssql/MSSqlIT.java
  agent-module/plugins-it/mybatis-it/src/test/java/com/navercorp/pinpoint/it/plugin/mybatis/DefaultSqlSessionIT.java
  agent-module/plugins-it/mybatis-it/src/test/java/com/navercorp/pinpoint/it/plugin/mybatis/SqlSessionTemplate_1_1_x_IT.java
  agent-module/plugins-it/mybatis-it/src/test/java/com/navercorp/pinpoint/it/plugin/mybatis/SqlSessionTemplate_1_2_x_IT.java
  agent-module/plugins-it/mybatis-it/src/test/java/com/navercorp/pinpoint/it/plugin/mybatis/SqlSessionTemplate_1_3_x_IT.java
  agent-module/plugins-it/oracledb-it/oracledb-11-it/src/test/java/com/navercorp/pinpoint/it/plugin/jdbc/oracle/Oracle19_Ojdbc8_ConnectWithGssCredential_IT.java
  agent-module/plugins-it/oracledb-it/oracledb-11-it/src/test/java/com/navercorp/pinpoint/it/plugin/jdbc/oracle/OracleItHelper.java
  agent-module/plugins-it/oracledb-it/oracledb-19-it/src/test/java/com/navercorp/pinpoint/it/plugin/jdbc/oracle/Oracle19_Ojdbc10_IT_ConnectWithGssCredential_IT.java
  agent-module/plugins-it/oracledb-it/oracledb-19-it/src/test/java/com/navercorp/pinpoint/it/plugin/jdbc/oracle/OracleItHelper.java
  agent-module/plugins-it/oracledb-it/oracledb-19-it/src/test/java/com/navercorp/pinpoint/it/plugin/jdbc/oracle/OracleServer.java
  agent-module/plugins-it/thrift-it/thrift-0-10-it/src/test/java/com/navercorp/pinpoint/it/plugin/thrift/it/asynchronous/ThriftHalfSyncHalfAsyncServerAsyncIT.java
  agent-module/plugins-it/thrift-it/thrift-0-10-it/src/test/java/com/navercorp/pinpoint/it/plugin/thrift/it/asynchronous/ThriftNonblockingServerAsyncIT.java
  agent-module/plugins-it/thrift-it/thrift-0-10-it/src/test/java/com/navercorp/pinpoint/it/plugin/thrift/it/asynchronous/ThriftThreadedSelectorServerAsyncIT.java
  agent-module/plugins-it/thrift-it/thrift-0-10-it/src/test/java/com/navercorp/pinpoint/it/plugin/thrift/it/http/ThriftHttpIT.java
  agent-module/plugins-it/thrift-it/thrift-0-10-it/src/test/java/com/navercorp/pinpoint/it/plugin/thrift/it/synchronous/ThriftHalfSyncHalfAsyncServerIT.java
  agent-module/plugins-it/thrift-it/thrift-0-10-it/src/test/java/com/navercorp/pinpoint/it/plugin/thrift/it/synchronous/ThriftNonblockingServerIT.java
  agent-module/plugins-it/thrift-it/thrift-0-10-it/src/test/java/com/navercorp/pinpoint/it/plugin/thrift/it/synchronous/ThriftSimpleServerIT.java
  agent-module/plugins-it/thrift-it/thrift-0-10-it/src/test/java/com/navercorp/pinpoint/it/plugin/thrift/it/synchronous/ThriftThreadPoolServerIT.java
  agent-module/plugins-it/thrift-it/thrift-0-10-it/src/test/java/com/navercorp/pinpoint/it/plugin/thrift/it/synchronous/ThriftThreadedSelectorServerIT.java
  agent-module/plugins-test-module/plugins-test/src/main/java/com/navercorp/pinpoint/test/plugin/AbstractPluginForkedTestSuite.java
  agent-module/plugins-test-module/plugins-test/src/main/java/com/navercorp/pinpoint/test/plugin/DefaultPluginForkedTestInstance.java
  agent-module/plugins-test-module/plugins-test/src/main/java/com/navercorp/pinpoint/test/plugin/DefaultPluginForkedTestSuite.java
  agent-module/plugins-test-module/plugins-test/src/main/java/com/navercorp/pinpoint/test/plugin/DefaultPluginJunitTestInstance.java
  agent-module/plugins-test-module/plugins-test/src/main/java/com/navercorp/pinpoint/test/plugin/DefaultPluginJunitTestSuite.java
  agent-module/plugins-test-module/plugins-test/src/main/java/com/navercorp/pinpoint/test/plugin/PluginClassLoading.java
  agent-module/plugins-test-module/plugins-test/src/main/java/com/navercorp/pinpoint/test/plugin/PluginForkedTestContext.java
  agent-module/plugins-test-module/plugins-test/src/main/java/com/navercorp/pinpoint/test/plugin/PluginForkedTestInstance.java
  agent-module/plugins-test-module/plugins-test/src/main/java/com/navercorp/pinpoint/test/plugin/PluginJunitTestInstance.java
  agent-module/plugins-test-module/plugins-test/src/main/java/com/navercorp/pinpoint/test/plugin/PluginTestInstanceContext.java
  agent-module/plugins-test-module/plugins-test/src/main/java/com/navercorp/pinpoint/test/plugin/junit5/engine/PluginForkedTestEngine.java
  agent-module/plugins-test-module/plugins-test/src/main/java/com/navercorp/pinpoint/test/plugin/junit5/launcher/SharedPluginForkedTestLauncher.java
  agent-module/plugins-test-module/plugins-test/src/main/java/com/navercorp/pinpoint/test/plugin/shared/SharedPluginTestConstants.java
  agent-module/plugins-test-module/plugins-test/src/main/java/com/navercorp/pinpoint/test/plugin/shared/SharedProcessManager.java
  agent-module/plugins-test-module/plugins-test/src/main/java/com/navercorp/pinpoint/test/plugin/shared/SharedTestExecutor.java
  agent-module/plugins-test-module/plugins-test/src/main/java/com/navercorp/pinpoint/test/plugin/shared/SharedTestLifeCycleWrapper.java
Labels: Continuous Integration

#10947 [#noissue] Replace class with record
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/histogram/ApdexScore.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/map/processor/RpcCallProcessor.java
  web/src/main/java/com/navercorp/pinpoint/web/authorization/controller/HeatMapController.java
  web/src/main/java/com/navercorp/pinpoint/web/scatter/ScatterView.java
  web/src/main/java/com/navercorp/pinpoint/web/view/ResponseTimeViewModel.java
  web/src/main/java/com/navercorp/pinpoint/web/view/TimeCountSerializer.java
  web/src/main/java/com/navercorp/pinpoint/web/vo/tree/ApplicationAgentHostList.java
  web/src/test/java/com/navercorp/pinpoint/web/applicationmap/service/FilteredMapServiceImplTest.java
Labels: cleanup

#10973 [#noissue] Fix oracle19 ojdbc8 forked test
  agent-module/plugins-it/oracledb-it/oracledb-11-it/src/test/java/com/navercorp/pinpoint/it/plugin/jdbc/oracle/Oracle19_Ojdbc8_ConnectWithGssCredential_IT.java
Labels: Continuous Integration
