Repository pinpoint-apm/pinpoint, pull requests merged in 2024-08, with the labels that each got.

#11314 [#11256] Fix a bug that incorrectly assigned bucket to interceptor
  collector/src/main/java/com/navercorp/pinpoint/collector/grpc/config/GrpcSpanReceiverConfiguration.java
  collector/src/main/java/com/navercorp/pinpoint/collector/grpc/config/GrpcStatReceiverConfiguration.java
  collector/src/main/java/com/navercorp/pinpoint/collector/receiver/grpc/flow/RateLimitClientStreamServerInterceptor.java
Labels: bug

#11316 [#11267] Fix test failures and Configurations
  collector/src/main/java/com/navercorp/pinpoint/collector/PinpointCollectorModule.java
  collector/src/main/java/com/navercorp/pinpoint/collector/grpc/CollectorGrpcConfiguration.java
  collector/src/main/java/com/navercorp/pinpoint/collector/grpc/config/GrpcAgentReceiverConfiguration.java
  collector/src/main/java/com/navercorp/pinpoint/collector/grpc/config/GrpcSpanConfiguration.java
  collector/src/main/java/com/navercorp/pinpoint/collector/grpc/config/GrpcStatConfiguration.java
  collector/src/main/java/com/navercorp/pinpoint/collector/monitor/config/DropwizardConfiguration.java
  collector/src/main/java/com/navercorp/pinpoint/collector/monitor/config/MicrometerConfiguration.java
  collector/src/test/java/com/navercorp/pinpoint/collector/grpc/config/TestReceiverConfig.java
Labels: module:collector

#11319 [#11318] Bump hbase-client from 2.5.9 to 2.5.10
  pom.xml
Labels: dependencies

#11311 [#11310] Abbreviate sql in sql metadata if sql is too long
  collector/src/main/java/com/navercorp/pinpoint/collector/config/CollectorProperties.java
  collector/src/main/java/com/navercorp/pinpoint/collector/service/HbaseSqlMetaDataService.java
  collector/src/main/java/com/navercorp/pinpoint/collector/service/HbaseSqlUidMetaDataService.java
Labels: module:collector

#11324 [#11256] Remove Deprecated legacy StreamRateLimiter
  collector-starter/src/main/resources/profiles/local/pinpoint-collector-grpc.properties
  collector-starter/src/main/resources/profiles/release/pinpoint-collector-grpc.properties
  collector/src/main/java/com/navercorp/pinpoint/collector/grpc/config/GrpcSpanReceiverConfiguration.java
  collector/src/main/java/com/navercorp/pinpoint/collector/grpc/config/GrpcStatReceiverConfiguration.java
  collector/src/main/java/com/navercorp/pinpoint/collector/grpc/config/GrpcStreamProperties.java
  collector/src/main/java/com/navercorp/pinpoint/collector/grpc/config/GrpcStreamReceiverProperties.java
  collector/src/main/java/com/navercorp/pinpoint/collector/receiver/grpc/flow/RateLimitClientStreamServerInterceptor.java
  collector/src/main/java/com/navercorp/pinpoint/collector/receiver/grpc/service/StreamExecutorServerInterceptorFactory.java
  collector/src/main/resources/profiles/local/pinpoint-collector-grpc.properties
  collector/src/main/resources/profiles/release/pinpoint-collector-grpc.properties
  collector/src/test/java/com/navercorp/pinpoint/collector/grpc/config/GrpcSpanConfigurationTest.java
  collector/src/test/java/com/navercorp/pinpoint/collector/grpc/config/GrpcStatConfigurationTest.java
  collector/src/test/java/com/navercorp/pinpoint/collector/receiver/grpc/SpanServerTestMain.java
  collector/src/test/java/com/navercorp/pinpoint/collector/receiver/grpc/StatServerTestMain.java
  grpc/src/main/java/com/navercorp/pinpoint/grpc/server/flowcontrol/DefaultIdleTimeout.java
  grpc/src/main/java/com/navercorp/pinpoint/grpc/server/flowcontrol/DisableIdleTimeout.java
  grpc/src/main/java/com/navercorp/pinpoint/grpc/server/flowcontrol/FlowControlRejectExecutionListener.java
  grpc/src/main/java/com/navercorp/pinpoint/grpc/server/flowcontrol/IdleTimeout.java
  grpc/src/main/java/com/navercorp/pinpoint/grpc/server/flowcontrol/IdleTimeoutFactory.java
  grpc/src/main/java/com/navercorp/pinpoint/grpc/server/flowcontrol/RejectedExecutionListener.java
  grpc/src/main/java/com/navercorp/pinpoint/grpc/server/flowcontrol/RejectedExecutionListenerFactory.java
  grpc/src/main/java/com/navercorp/pinpoint/grpc/server/flowcontrol/ScheduledExecutor.java
  grpc/src/main/java/com/navercorp/pinpoint/grpc/server/flowcontrol/SimpleRejectedExecutionListener.java
  grpc/src/main/java/com/navercorp/pinpoint/grpc/server/flowcontrol/StreamExecutorRejectedExecutionRequestScheduler.java
  grpc/src/main/java/com/navercorp/pinpoint/grpc/server/flowcontrol/StreamExecutorServerInterceptor.java
  grpc/src/test/java/com/navercorp/pinpoint/grpc/server/flowcontrol/DefaultIdleTimeoutTest.java
  grpc/src/test/java/com/navercorp/pinpoint/grpc/server/flowcontrol/DirectScheduledExecutor.java
  grpc/src/test/java/com/navercorp/pinpoint/grpc/server/flowcontrol/StreamExecutorRejectedExecutionRequestSchedulerTest.java
Labels: cleanup

#11325 [#11256] Remove unused properties
  collector/src/main/java/com/navercorp/pinpoint/collector/grpc/config/GrpcStreamReceiverProperties.java
  collector/src/test/java/com/navercorp/pinpoint/collector/grpc/config/GrpcSpanConfigurationTest.java
  collector/src/test/java/com/navercorp/pinpoint/collector/grpc/config/GrpcStatConfigurationTest.java
Labels: cleanup

#11326 [#11267] Add gRPC metric interceptors
  collector/src/main/java/com/navercorp/pinpoint/collector/grpc/config/GrpcAgentConfiguration.java
  collector/src/main/java/com/navercorp/pinpoint/collector/grpc/config/GrpcSpanReceiverConfiguration.java
  collector/src/main/java/com/navercorp/pinpoint/collector/grpc/config/GrpcStatReceiverConfiguration.java
  collector/src/main/java/com/navercorp/pinpoint/collector/grpc/ssl/GrpcSslModule.java
  collector/src/main/java/com/navercorp/pinpoint/collector/monitor/config/MicrometerConfiguration.java
Labels: module:collector

#11321 [#11320] Add validation of parentApplicationName
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/grpc/GrpcSpanBinder.java
  commons-server/src/test/java/com/navercorp/pinpoint/common/server/bo/grpc/GrpcSpanBinderTest.java
Labels: bug, module:collector

#11329 [#11267] Add netty ByteBufAllocator metrics
  collector/src/main/java/com/navercorp/pinpoint/collector/grpc/config/GrpcAgentConfiguration.java
  collector/src/main/java/com/navercorp/pinpoint/collector/grpc/config/GrpcPropertiesServerOptionBuilder.java
  collector/src/main/java/com/navercorp/pinpoint/collector/grpc/config/GrpcSpanReceiverConfiguration.java
  collector/src/main/java/com/navercorp/pinpoint/collector/grpc/config/GrpcStatReceiverConfiguration.java
  collector/src/main/java/com/navercorp/pinpoint/collector/grpc/ssl/GrpcSslModule.java
  collector/src/main/java/com/navercorp/pinpoint/collector/monitor/config/MicrometerConfiguration.java
  collector/src/main/java/com/navercorp/pinpoint/collector/receiver/grpc/GrpcReceiver.java
  grpc/src/main/java/com/navercorp/pinpoint/grpc/server/ServerFactory.java
  grpc/src/main/java/com/navercorp/pinpoint/grpc/server/ServerOption.java
  grpc/src/test/java/com/navercorp/pinpoint/grpc/ChannelFactoryTest.java
Labels: module:collector

#11331 [#11328] improve getApplicationHostinfo api
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/util/time/BackwardRangeSplitter.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/util/time/RangeSplitter.java
  commons-server/src/test/java/com/navercorp/pinpoint/common/server/util/time/RangeSplitterTest.java
  web/src/main/java/com/navercorp/pinpoint/web/controller/ApplicationController.java
  web/src/main/java/com/navercorp/pinpoint/web/controller/MainController.java
  web/src/main/java/com/navercorp/pinpoint/web/service/AgentInfoService.java
  web/src/main/java/com/navercorp/pinpoint/web/service/AgentInfoServiceImpl.java
  web/src/main/java/com/navercorp/pinpoint/web/util/TagApplicationsUtils.java
  web/src/main/java/com/navercorp/pinpoint/web/vo/agent/AgentInfoFilters.java
Labels: module:web

#11334 [#noissue] Cleanup micrometer dependency
  agent-module/agent-testweb/spring-boot3-testweb/pom.xml
  pom.xml
Labels: dependencies

#11335 [#noissue] Add service type
  commons/src/main/java/com/navercorp/pinpoint/common/trace/ServiceType.java
Labels: module:plugin

#11338 [#10776] Change property name for layout
  otlpmetric/otlpmetric-common/src/main/java/com/navercorp/pinpoint/otlp/common/defined/Layout.java
Labels: module:otlpmetric

#11339 [#noissue] Increase http max header size
  web-starter/src/main/resources/application.yml
  web/src/main/resources/application.yml
Labels: module:web, configuration

#11340 [#11267] Add log4j2 metrics
  collector/src/main/java/com/navercorp/pinpoint/collector/monitor/config/MicrometerConfiguration.java
Labels: module:collector

#11343 [#nossiue] Add Agent Count to AgentMapByHost
  web/src/main/java/com/navercorp/pinpoint/web/service/AgentInfoServiceImpl.java
  web/src/main/java/com/navercorp/pinpoint/web/vo/tree/AgentsMapByHost.java
  web/src/main/java/com/navercorp/pinpoint/web/vo/tree/InstancesListMap.java
Labels: module:web

#11345 [#10693] enable grpc built-in retry by default
  agent-module/agent/src/main/resources/pinpoint-root.config
  grpc/src/main/java/com/navercorp/pinpoint/grpc/Header.java
Labels: module:agent

#11344 [#nossiue] Cleanup
  collector/src/main/java/com/navercorp/pinpoint/collector/CollectorHbaseModule.java
  collector/src/main/java/com/navercorp/pinpoint/collector/dao/hbase/HbaseTraceDaoV2.java
Labels: module:collector

#11342 [#11337] Improve performance for Active Agent
  batch/src/main/java/com/navercorp/pinpoint/batch/alarm/AlarmProcessor.java
  batch/src/main/java/com/navercorp/pinpoint/batch/job/AgentCountProcessor.java
  batch/src/main/java/com/navercorp/pinpoint/batch/service/BatchAgentServiceImpl.java
  batch/src/test/java/com/navercorp/pinpoint/batch/alarm/AlarmProcessorTest.java
  web/pom.xml
  web/src/main/java/com/navercorp/pinpoint/web/service/AdminServiceImpl.java
  web/src/main/java/com/navercorp/pinpoint/web/service/AgentInfoService.java
  web/src/main/java/com/navercorp/pinpoint/web/service/AgentInfoServiceImpl.java
  web/src/main/java/com/navercorp/pinpoint/web/service/component/ActiveAgentValidator.java
  web/src/main/java/com/navercorp/pinpoint/web/service/component/DefaultActiveAgentValidator.java
  web/src/main/java/com/navercorp/pinpoint/web/service/component/DefaultLegacyAgentCompatibility.java
  web/src/main/java/com/navercorp/pinpoint/web/service/component/DisableAgentCompatibility.java
  web/src/main/java/com/navercorp/pinpoint/web/service/component/LegacyAgent.java
  web/src/main/java/com/navercorp/pinpoint/web/service/component/LegacyAgentCompatibility.java
  web/src/main/java/com/navercorp/pinpoint/web/service/component/LegacySupportConfiguration.java
  web/src/main/resources/application.yml
  web/src/test/java/com/navercorp/pinpoint/web/service/AdminServiceImplTest.java
  web/src/test/java/com/navercorp/pinpoint/web/service/component/DefaultActiveAgentValidatorTest.java
  web/src/test/java/com/navercorp/pinpoint/web/service/component/DefaultLegacyAgentCompatibilityTest.java
Labels: module:web

#11347 [#11346] Optimize agent lookup for agent compatibility
  collector/src/main/java/com/navercorp/pinpoint/collector/dao/AgentInfoDao.java
  collector/src/main/java/com/navercorp/pinpoint/collector/dao/hbase/HbaseAgentInfoDao.java
  collector/src/main/java/com/navercorp/pinpoint/collector/receiver/grpc/service/AgentLifecycleListener.java
  collector/src/main/java/com/navercorp/pinpoint/collector/service/AgentInfoService.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/dao/hbase/mapper/SingleResultsExtractor.java
  grpc/src/main/java/com/navercorp/pinpoint/grpc/server/lifecycle/PingSession.java
  grpc/src/test/java/com/navercorp/pinpoint/grpc/server/lifecycle/PingSessionTest.java
Labels: module:collector

#11352 [#noissue] Fix Runtime error
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/dao/hbase/mapper/SingleResultsExtractor.java
Labels: module:web

#11351 [#11350] Add write option to AsyncBufferedMutatorBuilder
  collector/src/main/resources/hbase-root.properties
  commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/async/AsyncBufferedMutatorCustomizer.java
  commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/async/AsyncBufferedMutatorFactory.java
  commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/async/AsyncTableCustomizer.java
  commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/async/AsyncTableFactory.java
  commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/async/BatchAsyncHbasePutWriter.java
  commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/async/DefaultAsyncBufferedMutatorCustomizer.java
  commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/async/DefaultAsyncTableCustomizer.java
  commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/async/HbaseAsyncBufferedMutatorFactory.java
  commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/async/HbaseAsyncTableFactory.java
  commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/config/HbaseTemplateConfiguration.java
Labels: enhancement, module:collector

#11354 [#11320] Add debug information when validation fail
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/grpc/GrpcSpanBinder.java
  commons-server/src/test/java/com/navercorp/pinpoint/common/server/bo/grpc/GrpcSpanBinderTest.java
Labels: module:collector, cleanup

#11355 [#noissue] Memory optimization for PingSession
  grpc/src/main/java/com/navercorp/pinpoint/grpc/server/lifecycle/PingSession.java
  grpc/src/test/java/com/navercorp/pinpoint/grpc/server/lifecycle/PingSessionTest.java
Labels: cleanup

#11353 [#10776] Add the aggregation function attribute to the metric definition
  otlpmetric/otlpmetric-common/src/main/java/com/navercorp/pinpoint/otlp/common/defined/AppMetricDefinition.java
Labels: module:otlpmetric

#11356 [#noissue] Refactor PingSession
  collector/src/main/java/com/navercorp/pinpoint/collector/receiver/grpc/service/AgentLifecycleListener.java
  collector/src/main/java/com/navercorp/pinpoint/collector/receiver/grpc/service/KeepAliveService.java
  collector/src/main/java/com/navercorp/pinpoint/collector/service/async/AgentLifeCycleAsyncTaskService.java
  collector/src/main/java/com/navercorp/pinpoint/collector/service/async/DefaultAgentProperty.java
  grpc/src/main/java/com/navercorp/pinpoint/grpc/server/lifecycle/DefaultPingEventHandler.java
  grpc/src/main/java/com/navercorp/pinpoint/grpc/server/lifecycle/PingSession.java
  grpc/src/test/java/com/navercorp/pinpoint/grpc/server/lifecycle/PingSessionTest.java
Labels: cleanup

#11360 [#11320] Root node has no parent information
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/grpc/GrpcSpanBinder.java
  commons-server/src/test/java/com/navercorp/pinpoint/common/server/bo/grpc/GrpcSpanBinderTest.java
Labels: bug, module:collector

#11357 [#11328] cleanup getApplicationHostinfoV2 ActiveAgent
  web/src/main/java/com/navercorp/pinpoint/web/controller/ApplicationController.java
  web/src/main/java/com/navercorp/pinpoint/web/service/AgentInfoService.java
  web/src/main/java/com/navercorp/pinpoint/web/service/AgentInfoServiceImpl.java
Labels: module:web

#11367 [#noissue] Fix SpotBug Warning
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/appender/server/DefaultServerInfoAppender.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/nodes/ServerGroupList.java
Labels: cleanup

#11369 [#noissue] Cleanup
  web/src/main/java/com/navercorp/pinpoint/web/dao/hbase/HbaseAgentLifeCycleDao.java
Labels: cleanup

#11371 [#noissue] Refactor AgentInfoQuery
  web/src/main/java/com/navercorp/pinpoint/web/dao/AgentInfoDao.java
  web/src/main/java/com/navercorp/pinpoint/web/dao/AgentInfoQuery.java
  web/src/main/java/com/navercorp/pinpoint/web/dao/hbase/HbaseAgentInfoDao.java
  web/src/main/java/com/navercorp/pinpoint/web/mapper/AgentLifeCycleMapper.java
  web/src/main/java/com/navercorp/pinpoint/web/service/AgentInfoServiceImpl.java
  web/src/main/java/com/navercorp/pinpoint/web/vo/agent/AgentStatus.java
Labels: cleanup

#11373 [#noissue] Add EnableScheduling annotation
  collector/src/main/java/com/navercorp/pinpoint/collector/grpc/CollectorGrpcConfiguration.java
  collector/src/main/java/com/navercorp/pinpoint/collector/grpc/config/GrpcKeepAliveScheduler.java
Labels: module:collector

#11375 [#11267] Separate `collector-monitor` module
  collector-monitor/pom.xml
  collector-monitor/src/main/java/com/navercorp/pinpoint/collector/monitor/BypassRunnableDecorator.java
  collector-monitor/src/main/java/com/navercorp/pinpoint/collector/monitor/LoggingRejectedExecutionHandler.java
  collector-monitor/src/main/java/com/navercorp/pinpoint/collector/monitor/MonitoredThreadPoolExecutor.java
  collector-monitor/src/main/java/com/navercorp/pinpoint/collector/monitor/MonitoredThreadPoolExecutorFactory.java
  collector-monitor/src/main/java/com/navercorp/pinpoint/collector/monitor/MonitoredThreadPoolExecutorFactoryProvider.java
  collector-monitor/src/main/java/com/navercorp/pinpoint/collector/monitor/MonitoringExecutors.java
  collector-monitor/src/main/java/com/navercorp/pinpoint/collector/monitor/RejectedExecutionHandlerChain.java
  collector-monitor/src/main/java/com/navercorp/pinpoint/collector/monitor/RunnableDecorator.java
  collector-monitor/src/main/java/com/navercorp/pinpoint/collector/monitor/config/MicrometerConfiguration.java
  collector-monitor/src/main/java/com/navercorp/pinpoint/collector/monitor/dao/hbase/BulkOperationReporter.java
  collector-monitor/src/main/java/com/navercorp/pinpoint/collector/monitor/micrometer/BulkOperationMetrics.java
  collector-monitor/src/main/java/com/navercorp/pinpoint/collector/monitor/micrometer/CounterRejectedExecutionHandler.java
  collector-monitor/src/main/java/com/navercorp/pinpoint/collector/monitor/micrometer/HBaseAsyncOperationMetrics.java
  collector-monitor/src/main/java/com/navercorp/pinpoint/collector/monitor/micrometer/MicrometerThreadPoolExecutorFactory.java
  collector-monitor/src/main/java/com/navercorp/pinpoint/collector/monitor/micrometer/MicrometerThreadPoolExecutorFactoryProvider.java
  collector-monitor/src/main/java/com/navercorp/pinpoint/collector/monitor/receiver/ExecutorFactoryBean.java
  collector/pom.xml
  collector/src/main/java/com/navercorp/pinpoint/collector/dao/hbase/statistics/BulkFactory.java
  collector/src/main/java/com/navercorp/pinpoint/collector/dao/hbase/statistics/BulkIncrementerFactory.java
  collector/src/main/java/com/navercorp/pinpoint/collector/dao/hbase/statistics/BulkOperationReporterFactory.java
  collector/src/main/java/com/navercorp/pinpoint/collector/dao/hbase/statistics/SizeLimitedBulkIncrementer.java
  collector/src/main/java/com/navercorp/pinpoint/collector/dao/hbase/statistics/SizeLimitedBulkUpdater.java
  collector/src/test/java/com/navercorp/pinpoint/collector/dao/hbase/statistics/DefaultBulkUpdaterTest.java
  collector/src/test/java/com/navercorp/pinpoint/collector/dao/hbase/statistics/SizeLimitedBulkIncrementerTest.java
  flink/pom.xml
  pom.xml
Labels: module:collector

#11378 [#11377] Fix Pinpoint jboss plugin build failure
  agent-module/plugins/jboss/pom.xml
Labels: bug

#11382 [#noissue] Cleanup
  agent-module/plugins-it/kafka-it/kafka-2-it/src/test/java/com/navercorp/pinpoint/it/plugin/kafka/KafkaClient_0_11_x_IT.java
  agent-module/plugins-it/kafka-it/kafka-2-it/src/test/java/com/navercorp/pinpoint/it/plugin/kafka/KafkaClient_1_0_x_IT.java
  agent-module/plugins-it/kafka-it/kafka-2-it/src/test/java/com/navercorp/pinpoint/it/plugin/kafka/KafkaClient_1_1_x_IT.java
  agent-module/plugins-it/kafka-it/kafka-2-it/src/test/java/com/navercorp/pinpoint/it/plugin/kafka/KafkaClient_2_0_x_IT.java
  agent-module/plugins-it/kafka-it/kafka-2-it/src/test/java/com/navercorp/pinpoint/it/plugin/kafka/KafkaClient_2_2_x_IT.java
  agent-module/plugins-it/kafka-it/kafka-2-it/src/test/java/com/navercorp/pinpoint/it/plugin/kafka/KafkaClient_2_3_0_IT.java
  agent-module/plugins-it/kafka-it/kafka-2-it/src/test/java/com/navercorp/pinpoint/it/plugin/kafka/KafkaClient_2_3_1_to_max_IT.java
  agent-module/plugins-it/kafka-it/kafka-2-it/src/test/java/com/navercorp/pinpoint/it/plugin/kafka/KafkaClient_2_4_x_IT.java
  agent-module/plugins-it/kafka-it/kafka-2-it/src/test/java/com/navercorp/pinpoint/it/plugin/kafka/KafkaClient_2_5_x_IT.java
  agent-module/plugins-it/kafka-it/kafka-2-it/src/test/java/com/navercorp/pinpoint/it/plugin/kafka/KafkaClient_2_6_x_IT.java
  agent-module/plugins-it/kafka-it/kafka-2-it/src/test/java/com/navercorp/pinpoint/it/plugin/kafka/KafkaClient_2_7_x_IT.java
  agent-module/plugins-it/kafka-it/kafka-3-it/src/test/java/com/navercorp/pinpoint/it/plugin/kafka/KafkaClient_2_8_x_3_IT.java
  agent-module/plugins-it/kafka-it/kafka-3-it/src/test/java/com/navercorp/pinpoint/it/plugin/kafka/KafkaClient_3_0_x_3_IT.java
  agent-module/plugins-it/kafka-it/kafka-3-it/src/test/java/com/navercorp/pinpoint/it/plugin/kafka/KafkaClient_3_1_x_3_IT.java
  agent-module/plugins-it/kafka-it/kafka-3-it/src/test/java/com/navercorp/pinpoint/it/plugin/kafka/KafkaClient_3_2_x_3_IT.java
  agent-module/plugins-it/kafka-it/kafka-3-it/src/test/java/com/navercorp/pinpoint/it/plugin/kafka/KafkaStreams_2_5_x_IT.java
  agent-module/plugins-it/kafka-it/kafka-3-it/src/test/java/com/navercorp/pinpoint/it/plugin/kafka/KafkaStreams_2_6_2_x_IT.java
  agent-module/plugins-it/kafka-it/kafka-3-it/src/test/java/com/navercorp/pinpoint/it/plugin/kafka/KafkaStreams_2_6_x_IT.java
  agent-module/plugins-it/kafka-it/kafka-3-it/src/test/java/com/navercorp/pinpoint/it/plugin/kafka/KafkaStreams_2_7_x_IT.java
  agent-module/plugins-it/kafka-it/kafka-3-it/src/test/java/com/navercorp/pinpoint/it/plugin/kafka/KafkaStreams_2_8_x_IT.java
  agent-module/plugins-it/kafka-it/kafka-3-it/src/test/java/com/navercorp/pinpoint/it/plugin/kafka/KafkaStreams_3_0_x_IT.java
  agent-module/plugins-it/kafka-it/kafka-3-it/src/test/java/com/navercorp/pinpoint/it/plugin/kafka/KafkaStreams_3_1_x_IT.java
  agent-module/plugins-it/kafka-it/kafka-3-it/src/test/java/com/navercorp/pinpoint/it/plugin/kafka/KafkaStreams_3_2_x_IT.java
  agent-module/plugins-it/kafka-it/kafka-3-it/src/test/java/com/navercorp/pinpoint/it/plugin/kafka/KafkaStreams_3_3_x_IT.java
  agent-module/plugins-it/kafka-it/kafka-3-it/src/test/java/com/navercorp/pinpoint/it/plugin/kafka/KafkaStreams_3_4_x_IT.java
  channel/src/test/java/com/navercorp/pinpoint/channel/serde/JacksonSerdeTest.java
  collector/src/test/java/com/navercorp/pinpoint/collector/dao/hbase/statistics/BulkIncrementerTestClazz.java
  commons-buffer/src/test/java/com/navercorp/pinpoint/common/buffer/FixedBufferTest.java
Labels: cleanup

#11380 [#11379] Add AsyncPollingPutWriter
  collector/src/main/resources/hbase-root.properties
  commons-hbase/pom.xml
  commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/async/AsyncPollerOption.java
  commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/async/AsyncPollerThread.java
  commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/async/AsyncPollingPutWriter.java
  commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/async/AsyncTableWriterFactory.java
  commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/async/TableWriterFactory.java
  commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/async/WriteRequest.java
  commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/config/HbaseTemplateConfiguration.java
  commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/util/FutureUtils.java
  commons-hbase/src/test/java/com/navercorp/pinpoint/common/hbase/async/AsyncPollerOptionTest.java
  commons-hbase/src/test/java/com/navercorp/pinpoint/common/hbase/async/AsyncPollerThreadTest.java
  commons-hbase/src/test/java/com/navercorp/pinpoint/common/hbase/async/AsyncPollingPutWriterTest.java
  commons-hbase/src/test/resources/log4j2-test.xml
Labels: module:collector

#11241 [#9631] Add ErrorSummary for improved analytic insights
  exceptiontrace/exceptiontrace-web/src/main/java/com/navercorp/pinpoint/exceptiontrace/web/config/ExceptionTraceRegistryHandler.java
  exceptiontrace/exceptiontrace-web/src/main/java/com/navercorp/pinpoint/exceptiontrace/web/controller/ExceptionTraceController.java
  exceptiontrace/exceptiontrace-web/src/main/java/com/navercorp/pinpoint/exceptiontrace/web/dao/ExceptionTraceDao.java
  exceptiontrace/exceptiontrace-web/src/main/java/com/navercorp/pinpoint/exceptiontrace/web/dao/PinotExceptionTraceDao.java
  exceptiontrace/exceptiontrace-web/src/main/java/com/navercorp/pinpoint/exceptiontrace/web/entity/ErrorSummaryEntity.java
  exceptiontrace/exceptiontrace-web/src/main/java/com/navercorp/pinpoint/exceptiontrace/web/mapper/ExceptionEntityMapper.java
  exceptiontrace/exceptiontrace-web/src/main/java/com/navercorp/pinpoint/exceptiontrace/web/model/ErrorSummary.java
  exceptiontrace/exceptiontrace-web/src/main/java/com/navercorp/pinpoint/exceptiontrace/web/model/params/GroupFilterParams.java
  exceptiontrace/exceptiontrace-web/src/main/java/com/navercorp/pinpoint/exceptiontrace/web/model/params/Params.java
  exceptiontrace/exceptiontrace-web/src/main/java/com/navercorp/pinpoint/exceptiontrace/web/model/params/TransactionSearchParams.java
  exceptiontrace/exceptiontrace-web/src/main/java/com/navercorp/pinpoint/exceptiontrace/web/service/ExceptionTraceService.java
  exceptiontrace/exceptiontrace-web/src/main/java/com/navercorp/pinpoint/exceptiontrace/web/service/ExceptionTraceServiceImpl.java
  exceptiontrace/exceptiontrace-web/src/main/java/com/navercorp/pinpoint/exceptiontrace/web/util/ExceptionTraceQueryParameter.java
  exceptiontrace/exceptiontrace-web/src/main/java/com/navercorp/pinpoint/exceptiontrace/web/view/ErrorSummaryView.java
  exceptiontrace/exceptiontrace-web/src/main/resources/exceptiontrace/mapper/ErrorSummaryMapper.xml
  exceptiontrace/exceptiontrace-web/src/main/resources/exceptiontrace/mapper/ExceptionGroupMapper.xml
  exceptiontrace/exceptiontrace-web/src/main/resources/exceptiontrace/mapper/ExceptionUtilMapper.xml
Labels: enhancement, module:web

#11387 [#11350] Allow default property
  commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/async/DefaultAsyncBufferedMutatorCustomizer.java
  commons-hbase/src/test/java/com/navercorp/pinpoint/common/hbase/async/DefaultAsyncBufferedMutatorCustomizerTest.java
Labels: cleanup

#11389 [#11388] Optimize Async call chain of maxColumnValue
  commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/CasResult.java
  commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/HbaseTemplate.java
Labels: module:collector

#11330 [#noissue] Validate SqlUidMetaDataBo
  collector/src/main/java/com/navercorp/pinpoint/collector/service/HbaseSqlUidMetaDataService.java
  collector/src/main/java/com/navercorp/pinpoint/collector/service/SqlUidMetaDataService.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/SqlUidMetaDataBo.java
Labels: module:collector

#11395 [#11394] Bump commons-io from 2.11.0 to 2.16.1
  pom.xml
Labels: dependencies

#11391 [#11390] Update reactor lift of spring-cloud-sleuth plugin
  agent-module/plugins/spring-cloud-sleuth/src/main/java/com/navercorp/pinpoint/plugin/spring/cloud/sleuth/SpringCloudSleuthPlugin.java
  agent-module/plugins/spring-cloud-sleuth/src/main/java/com/navercorp/pinpoint/plugin/spring/cloud/sleuth/interceptor/ParallelFluxSubscribeInterceptor.java
Labels: enhancement, module:plugin

#11407 [#11406] Bump commons-validator to 1.9.0
  pom.xml
Labels: dependencies

#11398 [#11396] Bump commons-lang3 from 3.12.0 to 3.16.0
  pom.xml
Labels: dependencies

#11409 [#11408] Bump commons-codec from 1.15 to 1.17.1
  pom.xml
Labels: dependencies

#11405 [#11397] Bump commons-compress from 1.26.1 to 1.27.1
  pom.xml
Labels: dependencies

#11410 [#noissue] Cleanup IOUtils
  commons-hbase/pom.xml
  commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/async/AsyncPollingPutWriter.java
  commons-server-cluster/src/test/java/com/navercorp/pinpoint/common/server/cluster/zookeeper/ConnectionTest.java
  commons-server-cluster/src/test/java/com/navercorp/pinpoint/common/server/cluster/zookeeper/CuratorZookeeperClientTest.java
  commons-server-cluster/src/test/java/com/navercorp/pinpoint/common/server/cluster/zookeeper/ZKUtils.java
  commons/src/main/java/com/navercorp/pinpoint/common/util/IOUtils.java
Labels: cleanup

#11393 [#11388] Add HbaseAsyncTemplate
  collector/src/main/java/com/navercorp/pinpoint/collector/dao/hbase/statistics/BulkFactory.java
  collector/src/main/java/com/navercorp/pinpoint/collector/dao/hbase/statistics/DefaultBulkWriter.java
  collector/src/main/java/com/navercorp/pinpoint/collector/dao/hbase/statistics/SyncWriter.java
  commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/CheckAndMax.java
  commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/HbaseAccessor.java
  commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/HbaseOperations.java
  commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/HbaseTemplate.java
  commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/async/AsyncHbaseOperations.java
  commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/async/HbaseAsyncTemplate.java
  commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/config/HbaseTemplateConfiguration.java
  commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/util/CheckAndMutates.java
  commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/util/FutureUtils.java
  commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/util/HBaseExceptionUtils.java
  commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/util/MutationType.java
  hbase/hbase-schema-manager/src/main/java/com/navercorp/pinpoint/hbase/manager/config/HbaseConfig.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/config/MapHbaseConfiguration.java
Labels: module:collector

#11412 [#11411] Improve performance of ServerMap Link
  collector/src/main/java/com/navercorp/pinpoint/collector/dao/hbase/statistics/DefaultBulkWriter.java
  collector/src/main/java/com/navercorp/pinpoint/collector/dao/hbase/statistics/RowKeyMerge.java
  collector/src/main/java/com/navercorp/pinpoint/collector/dao/hbase/statistics/SyncWriter.java
Labels: module:collector

#11400 [#11399] Add ktor plugin
  agent-module/agent-testweb/ktor-plugin-testweb/pom.xml
  agent-module/agent-testweb/ktor-plugin-testweb/src/main/java/com/pinpoint/test/plugin/Application.kt
  agent-module/agent-testweb/ktor-plugin-testweb/src/main/java/com/pinpoint/test/plugin/Routing.kt
  agent-module/agent-testweb/pom.xml
  agent-module/agent/src/main/resources/profiles/local/pinpoint.config
  agent-module/agent/src/main/resources/profiles/release/pinpoint.config
  agent-module/plugins/assembly/pom.xml
  agent-module/plugins/ktor/README.md
  agent-module/plugins/ktor/pom.xml
  agent-module/plugins/ktor/src/main/java/com/navercorp/pinpoint/plugin/ktor/CoroutineContextGetter.java
  agent-module/plugins/ktor/src/main/java/com/navercorp/pinpoint/plugin/ktor/KtorConstants.java
  agent-module/plugins/ktor/src/main/java/com/navercorp/pinpoint/plugin/ktor/KtorDetector.java
  agent-module/plugins/ktor/src/main/java/com/navercorp/pinpoint/plugin/ktor/KtorPlugin.java
  agent-module/plugins/ktor/src/main/java/com/navercorp/pinpoint/plugin/ktor/KtorPluginConfig.java
  agent-module/plugins/ktor/src/main/java/com/navercorp/pinpoint/plugin/ktor/RouteMethodTransformer.java
  agent-module/plugins/ktor/src/main/java/com/navercorp/pinpoint/plugin/ktor/interceptor/ConfigureRoutingFactoryInterceptor.java
  agent-module/plugins/ktor/src/main/java/com/navercorp/pinpoint/plugin/ktor/interceptor/HttpRequestAdaptor.java
  agent-module/plugins/ktor/src/main/java/com/navercorp/pinpoint/plugin/ktor/interceptor/HttpRequestAndContext.java
  agent-module/plugins/ktor/src/main/java/com/navercorp/pinpoint/plugin/ktor/interceptor/HttpRequestParameterExtractor.java
  agent-module/plugins/ktor/src/main/java/com/navercorp/pinpoint/plugin/ktor/interceptor/MethodFilterExtractor.java
  agent-module/plugins/ktor/src/main/java/com/navercorp/pinpoint/plugin/ktor/interceptor/NettyApplicationCallHandlerInterceptor.java
  agent-module/plugins/ktor/src/main/java/com/navercorp/pinpoint/plugin/ktor/interceptor/NettyHttp1HandlerHandleRequestInterceptor.java
  agent-module/plugins/ktor/src/main/java/com/navercorp/pinpoint/plugin/ktor/interceptor/NettyHttp1HandlerPrepareCallFromRequestInterceptor.java
  agent-module/plugins/ktor/src/main/java/com/navercorp/pinpoint/plugin/ktor/interceptor/ParameterRecorderFactory.java
  agent-module/plugins/ktor/src/main/java/com/navercorp/pinpoint/plugin/ktor/interceptor/RouteMethodInterceptor.java
  agent-module/plugins/ktor/src/main/java/com/navercorp/pinpoint/plugin/ktor/interceptor/SuspendFunctionGunInterceptor.java
  agent-module/plugins/ktor/src/main/java/com/navercorp/pinpoint/plugin/ktor/interceptor/UriUtils.java
  agent-module/plugins/ktor/src/main/resources/META-INF/pinpoint/type-provider.yml
  agent-module/plugins/ktor/src/main/resources/META-INF/services/com.navercorp.pinpoint.bootstrap.plugin.ProfilerPlugin
  agent-module/plugins/pom.xml
  commons/src/main/java/com/navercorp/pinpoint/common/trace/ServiceType.java
Labels: enhancement, module:plugin

#11420 [#11419] Adjust flush interval for node and link information
  collector/src/main/java/com/navercorp/pinpoint/collector/scheduler/AvgMaxLinkScheduler.java
  collector/src/main/java/com/navercorp/pinpoint/collector/scheduler/StatisticsLinkScheduler.java
  collector/src/main/resources/pinpoint-collector-root.properties
Labels: module:collector

#11430 [#11392] Cleanup
  commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/async/HbaseAsyncTemplate.java
Labels: cleanup

#11425 [#9631] Merge ErrorSummary into ExceptionGroupSummary
  exceptiontrace/exceptiontrace-web/src/main/java/com/navercorp/pinpoint/exceptiontrace/web/config/ExceptionTraceRegistryHandler.java
  exceptiontrace/exceptiontrace-web/src/main/java/com/navercorp/pinpoint/exceptiontrace/web/controller/ExceptionTraceController.java
  exceptiontrace/exceptiontrace-web/src/main/java/com/navercorp/pinpoint/exceptiontrace/web/dao/ExceptionTraceDao.java
  exceptiontrace/exceptiontrace-web/src/main/java/com/navercorp/pinpoint/exceptiontrace/web/dao/PinotExceptionTraceDao.java
  exceptiontrace/exceptiontrace-web/src/main/java/com/navercorp/pinpoint/exceptiontrace/web/entity/ErrorSummaryEntity.java
  exceptiontrace/exceptiontrace-web/src/main/java/com/navercorp/pinpoint/exceptiontrace/web/entity/ExceptionGroupSummaryEntity.java
  exceptiontrace/exceptiontrace-web/src/main/java/com/navercorp/pinpoint/exceptiontrace/web/mapper/ExceptionEntityMapper.java
  exceptiontrace/exceptiontrace-web/src/main/java/com/navercorp/pinpoint/exceptiontrace/web/model/ErrorSummary.java
  exceptiontrace/exceptiontrace-web/src/main/java/com/navercorp/pinpoint/exceptiontrace/web/model/ExceptionGroupSummary.java
  exceptiontrace/exceptiontrace-web/src/main/java/com/navercorp/pinpoint/exceptiontrace/web/model/GroupedFieldName.java
  exceptiontrace/exceptiontrace-web/src/main/java/com/navercorp/pinpoint/exceptiontrace/web/service/ExceptionTraceService.java
  exceptiontrace/exceptiontrace-web/src/main/java/com/navercorp/pinpoint/exceptiontrace/web/service/ExceptionTraceServiceImpl.java
  exceptiontrace/exceptiontrace-web/src/main/java/com/navercorp/pinpoint/exceptiontrace/web/view/ErrorSummaryView.java
  exceptiontrace/exceptiontrace-web/src/main/resources/exceptiontrace/mapper/ErrorSummaryMapper.xml
  exceptiontrace/exceptiontrace-web/src/main/resources/exceptiontrace/mapper/ExceptionGroupMapper.xml
  exceptiontrace/exceptiontrace-web/src/test/java/com/navercorp/pinpoint/exceptiontrace/web/model/ExceptionChartValueViewTest.java
Labels: module:web

#11426 [#noissue] Precompile regex in replacePlaceHolders
  exceptiontrace/exceptiontrace-web/src/main/java/com/navercorp/pinpoint/exceptiontrace/web/mapper/CLPMapper.java
  exceptiontrace/exceptiontrace-web/src/test/java/com/navercorp/pinpoint/exceptiontrace/web/mapper/CLPMapperTest.java
  exceptiontrace/exceptiontrace-web/src/test/java/com/navercorp/pinpoint/exceptiontrace/web/mapper/ExceptionEntityMapperTest.java
Labels: module:web

#11432 [#11431] Separate AsyncConnections for Span
  commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/async/AsyncPollerThread.java
  commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/async/AsyncTableWriterFactory.java
  commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/config/HbaseTemplateConfiguration.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/hbase/config/HbaseClientConfiguration.java
Labels: module:collector

#11436 [#11435] Bump jacoco from 0.8.10 to 0.8.12
  pom.xml
Labels: dependencies

#11441 [#11440] Bump commons-lang3 from 3.16.0 to 3.17.0
  commons-server/src/test/java/com/navercorp/pinpoint/common/server/bo/RandomTSpan.java
  pom.xml
  thrift-datasender/src/test/java/com/navercorp/pinpoint/thrift/sender/UdpDataSenderTest.java
  web/src/test/java/com/navercorp/pinpoint/web/mapper/FilteringSpanDecoderTest.java
Labels: dependencies
