Repository pinpoint-apm/pinpoint, pull requests merged in 2025-05, with the labels that each got.

#12406 [#noissue] Cleanup down sampling
  batch/src/main/java/com/navercorp/pinpoint/batch/alarm/collector/MapOutLinkDataCollector.java
  batch/src/test/java/com/navercorp/pinpoint/batch/alarm/checker/ErrorCountToCalleCheckerTest.java
  batch/src/test/java/com/navercorp/pinpoint/batch/alarm/checker/ErrorRateToCalleCheckerTest.java
  batch/src/test/java/com/navercorp/pinpoint/batch/alarm/checker/SlowCountToCalleCheckerTest.java
  batch/src/test/java/com/navercorp/pinpoint/batch/alarm/checker/SlowRateToCalleCheckerTest.java
  batch/src/test/java/com/navercorp/pinpoint/batch/alarm/checker/TotalCountToCalleeCheckerTest.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/controller/MapController.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/controller/MapHistogramController.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/dao/MapInLinkDao.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/dao/MapOutLinkDao.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/dao/hbase/HbaseMapInLinkDao.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/dao/hbase/HbaseMapOutLinkDao.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/map/BidirectionalLinkSelector.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/map/DefaultApplicationMapCreator.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/map/LinkSelectContext.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/map/LinkSelector.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/map/UnidirectionalLinkSelector.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/map/VirtualLinkHandler.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/map/processor/ApplicationFilter.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/map/processor/ApplicationLimiterProcessor.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/map/processor/DestinationApplicationFilter.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/map/processor/LinkDataMapProcessor.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/map/processor/LinkDataMapProcessors.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/map/processor/RpcCallProcessor.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/map/processor/SourceApplicationFilter.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/map/processor/WasOnlyProcessor.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/service/LinkDataMapService.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/service/LinkDataMapServiceImpl.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/service/MapServiceImpl.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/service/MapServiceOption.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/service/ResponseTimeHistogramService.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/service/ResponseTimeHistogramServiceImpl.java
  web/src/main/java/com/navercorp/pinpoint/web/authorization/controller/ResponseTimeController.java
  web/src/test/java/com/navercorp/pinpoint/web/applicationmap/map/BidirectionalLinkSelectorTest.java
  web/src/test/java/com/navercorp/pinpoint/web/applicationmap/map/FilteredMapBuilderTest.java
  web/src/test/java/com/navercorp/pinpoint/web/applicationmap/map/LinkSelectorTestBase.java
  web/src/test/java/com/navercorp/pinpoint/web/applicationmap/map/UnidirectionalLinkSelectorTest.java
  web/src/test/java/com/navercorp/pinpoint/web/applicationmap/map/processor/ApplicationLimiterProcessorTest.java
  web/src/test/java/com/navercorp/pinpoint/web/applicationmap/map/processor/RpcCallProcessorTest.java
  web/src/test/java/com/navercorp/pinpoint/web/applicationmap/map/processor/WasOnlyProcessorTest.java
  web/src/test/java/com/navercorp/pinpoint/web/applicationmap/service/ResponseTimeHistogramServiceImplTest.java
Labels: cleanup

#12407 [#noissue] Refactor FilteredMap
  batch/src/test/java/com/navercorp/pinpoint/batch/alarm/checker/ApdexScoreCheckerTest.java
  batch/src/test/java/com/navercorp/pinpoint/batch/alarm/checker/ErrorCountCheckerTest.java
  batch/src/test/java/com/navercorp/pinpoint/batch/alarm/checker/ErrorRateCheckerTest.java
  batch/src/test/java/com/navercorp/pinpoint/batch/alarm/checker/ResponseCountCheckerTest.java
  batch/src/test/java/com/navercorp/pinpoint/batch/alarm/checker/SlowCountCheckerTest.java
  batch/src/test/java/com/navercorp/pinpoint/batch/alarm/checker/SlowRateCheckerTest.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/dao/mapper/ResponseTimeMapper.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/map/FilteredMapBuilder.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/service/FilteredMapServiceImpl.java
  web/src/main/java/com/navercorp/pinpoint/web/vo/ResponseHistograms.java
  web/src/main/java/com/navercorp/pinpoint/web/vo/ResponseTime.java
  web/src/test/java/com/navercorp/pinpoint/web/applicationmap/ApplicationMapBuilderTest.java
  web/src/test/java/com/navercorp/pinpoint/web/applicationmap/dao/mapper/ResponseTimeMapperTest.java
  web/src/test/java/com/navercorp/pinpoint/web/applicationmap/histogram/AgentTimeHistogramTest.java
  web/src/test/java/com/navercorp/pinpoint/web/applicationmap/histogram/ApplicationTimeHistogramTest.java
  web/src/test/java/com/navercorp/pinpoint/web/applicationmap/map/FilteredMapBuilderTest.java
  web/src/test/java/com/navercorp/pinpoint/web/applicationmap/service/FilteredMapServiceImplTest.java
  web/src/test/java/com/navercorp/pinpoint/web/applicationmap/service/ResponseTimeHistogramServiceImplTest.java
  web/src/test/java/com/navercorp/pinpoint/web/service/ApdexScoreServiceImplTest.java
  web/src/test/java/com/navercorp/pinpoint/web/service/ApplicationAgentListServiceImplTest.java
  web/src/test/java/com/navercorp/pinpoint/web/vo/ResponseHistogramsTest.java
Labels: cleanup

#12411 [#12410] Fix NPE of elasticsearch plugin
  agent-module/plugins/elasticsearch/src/main/java/com/navercorp/pinpoint/plugin/elasticsearch/interceptor/ElasticsearchExecutorInterceptor.java
  agent-module/plugins/elasticsearch/src/main/java/com/navercorp/pinpoint/plugin/elasticsearch/interceptor/HighLevelConnectInterceptor.java
  agent-module/plugins/elasticsearch/src/main/java/com/navercorp/pinpoint/plugin/elasticsearch/interceptor/RestClientConnectInterceptor.java
  agent-module/plugins/elasticsearch8/src/main/java/com/navercorp/pinpoint/plugin/elasticsearch8/interceptor/ElasticsearchClientConstructorInterceptor.java
  agent-module/plugins/elasticsearch8/src/main/java/com/navercorp/pinpoint/plugin/elasticsearch8/interceptor/ElasticsearchClientMethodInterceptor.java
Labels: enhancement, module:plugin

#12414 [#12413] Backport: Fix NPE of elasticsearch plugin
  agent-module/plugins/elasticsearch/src/main/java/com/navercorp/pinpoint/plugin/elasticsearch/interceptor/ElasticsearchExecutorInterceptor.java
  agent-module/plugins/elasticsearch/src/main/java/com/navercorp/pinpoint/plugin/elasticsearch/interceptor/HighLevelConnectInterceptor.java
  agent-module/plugins/elasticsearch/src/main/java/com/navercorp/pinpoint/plugin/elasticsearch/interceptor/RestClientConnectInterceptor.java
  agent-module/plugins/elasticsearch8/src/main/java/com/navercorp/pinpoint/plugin/elasticsearch8/interceptor/ElasticsearchClientConstructorInterceptor.java
  agent-module/plugins/elasticsearch8/src/main/java/com/navercorp/pinpoint/plugin/elasticsearch8/interceptor/ElasticsearchClientMethodInterceptor.java
Labels: enhancement, module:plugin

#12418 [#12159] Change heatmap eventTime from startTime to CollectorAcceptTime
  collector/src/main/java/com/navercorp/pinpoint/collector/heatmap/service/HeatmapService.java
Labels: module:collector

#12412 [#noissue] Reduced memory usage in ResponseTime
  batch/src/test/java/com/navercorp/pinpoint/batch/alarm/checker/ApdexScoreCheckerTest.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/appender/histogram/datasource/MapApplicationResponseNodeHistogramDataSource.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/config/MapHbaseConfiguration.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/config/MapMapperConfiguration.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/dao/MapResponseDao.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/dao/hbase/HbaseMapResponseTimeDao.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/dao/mapper/ApplicationResponseTimeResultExtractor.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/histogram/ApplicationHistogram.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/histogram/NodeHistogram.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/service/MapServiceImpl.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/view/NodeView.java
Labels: cleanup

#12416 [#noissue] Cleanup
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/ApplicationMapBuilder.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/appender/server/DefaultServerInfoAppender.java
Labels: cleanup

#12420 [#12419] Cleanup duplicate Agent field in ServerMap
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/view/LinkView.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/view/NodeView.java
Labels: cleanup

#12422 [#noissue] Refactor ApplicationTimeHistogramBuilder
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/appender/histogram/datasource/MapApplicationResponseNodeHistogramDataSource.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/histogram/ApplicationTimeHistogramBuilder.java
Labels: cleanup

#12427 [#noissue] Cleanup ResponseTimeResultExtractor
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/dao/mapper/ResponseTimeResultExtractor.java
Labels: cleanup

#12428 [#noissue] Cleanup
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/rawdata/AgentHistogram.java
  web/src/test/java/com/navercorp/pinpoint/web/applicationmap/rawdata/AgentHistogramTest.java
Labels: cleanup

#12426 [#noissue] Refactor ApplicationResponse
  batch/src/main/java/com/navercorp/pinpoint/batch/alarm/collector/ResponseTimeDataCollector.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/appender/histogram/datasource/MapApplicationResponseNodeHistogramDataSource.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/config/MapHbaseConfiguration.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/config/MapMapperConfiguration.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/dao/ApplicationResponse.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/dao/MapResponseDao.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/dao/hbase/HbaseMapResponseTimeDao.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/dao/mapper/ApplicationResponseTimeResultExtractor.java
  web/src/main/java/com/navercorp/pinpoint/web/service/ApdexScoreServiceImpl.java
  web/src/test/java/com/navercorp/pinpoint/web/service/ApdexScoreServiceImplTest.java
Labels: cleanup

#12431 [#12419] Fix agents field in NodeView
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/view/NodeView.java
Labels: cleanup

#12433 [#12419] Remove unused json field in ServerMap
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/view/LinkView.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/view/NodeView.java
Labels: cleanup

#12439 [#12434] Cleanup
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/dao/hbase/HbaseMapInLinkDao.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/dao/hbase/HbaseMapOutLinkDao.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/dao/mapper/InLinkMapper.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/dao/mapper/OutLinkMapper.java
Labels: cleanup

#12441 [#12440] Improved reuse of ObjectMapper in Agent
  agent-module/plugins-loader/src/main/java/com/navercorp/pinpoint/loader/plugins/trace/yaml/TraceMetadataProviderYamlParser.java
Labels: enhancement, module:agent

#12444 [#12434] Move HostApplicationMapDao to servermap package
  collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/dao/HostApplicationMapDao.java
  collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/dao/hbase/HbaseHostApplicationMapDao.java
  collector/src/main/java/com/navercorp/pinpoint/collector/service/HbaseTraceService.java
  collector/src/test/java/com/navercorp/pinpoint/collector/applicationmap/dao/hbase/HbaseHostApplicationMapDaoTest.java
Labels: cleanup

#12443 [#12434] Changed Link stat to Application stat
  collector/src/main/java/com/navercorp/pinpoint/collector/service/HbaseTraceService.java
Labels: enhancement, module:collector

#12445 [#12419] Fix agents field in LinkView
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/view/LinkView.java
Labels: bug, module:web

#12446 [#12434] Cleanup
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/dao/hbase/HbaseMapInLinkDao.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/dao/hbase/HbaseMapOutLinkDao.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/dao/mapper/InLinkMapper.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/dao/mapper/OutLinkMapper.java
Labels: cleanup

#12454 [#12159] Enable all configurations for heatmap support
  collector-starter/src/main/resources/application.yml
  web-starter/src/main/resources/application.yml
  web/src/main/resources/pinpoint-web-root.properties
Labels: module:collector, module:web

#12456 [#12455] Add S3(Simple Storage Service) client plugin
  agent-module/agent-testweb/aws-sdk-s3-plugin-testweb/pom.xml
  agent-module/agent-testweb/aws-sdk-s3-plugin-testweb/src/main/java/com/pinpoint/test/plugin/AwsSdkS3PluginController.java
  agent-module/agent-testweb/aws-sdk-s3-plugin-testweb/src/main/java/com/pinpoint/test/plugin/AwsSdkS3PluginTestStarter.java
  agent-module/agent-testweb/aws-sdk-s3-plugin-testweb/src/main/resources/application.yml
  agent-module/agent-testweb/aws-sdk-s3-plugin-testweb/src/main/resources/test.txt
  agent-module/agent-testweb/aws-sdk-s3-plugin-testweb/src/test/java/com/pinpoint/test/plugin/LocalStackContainerTest.java
  agent-module/agent-testweb/pom.xml
  agent-module/agent/src/main/resources/profiles/local/pinpoint.config
  agent-module/agent/src/main/resources/profiles/release/pinpoint.config
  agent-module/bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/request/ClientDatabaseRequestAdaptor.java
  agent-module/bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/request/ClientDatabaseRequestRecorder.java
  agent-module/bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/request/ClientDatabaseRequestWrapper.java
  agent-module/bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/request/ClientDatabaseRequestWrapperAdaptor.java
  agent-module/plugins/assembly/pom.xml
  agent-module/plugins/aws-sdk-s3/README.md
  agent-module/plugins/aws-sdk-s3/pom.xml
  agent-module/plugins/aws-sdk-s3/src/main/java/com/navercorp/pinpoint/plugin/aws/sdk/s3/AwsSdkS3Constants.java
  agent-module/plugins/aws-sdk-s3/src/main/java/com/navercorp/pinpoint/plugin/aws/sdk/s3/AwsSdkS3Plugin.java
  agent-module/plugins/aws-sdk-s3/src/main/java/com/navercorp/pinpoint/plugin/aws/sdk/s3/AwsSdkS3PluginConfig.java
  agent-module/plugins/aws-sdk-s3/src/main/java/com/navercorp/pinpoint/plugin/aws/sdk/s3/RequestBuilderGetter.java
  agent-module/plugins/aws-sdk-s3/src/main/java/com/navercorp/pinpoint/plugin/aws/sdk/s3/URIGetter.java
  agent-module/plugins/aws-sdk-s3/src/main/java/com/navercorp/pinpoint/plugin/aws/sdk/s3/interceptor/AsyncResponseHandlerOnErrorInterceptor.java
  agent-module/plugins/aws-sdk-s3/src/main/java/com/navercorp/pinpoint/plugin/aws/sdk/s3/interceptor/AsyncResponseHandlerOnHeadersInterceptor.java
  agent-module/plugins/aws-sdk-s3/src/main/java/com/navercorp/pinpoint/plugin/aws/sdk/s3/interceptor/BaseClientHandlerInterceptor.java
  agent-module/plugins/aws-sdk-s3/src/main/java/com/navercorp/pinpoint/plugin/aws/sdk/s3/interceptor/HttpResponseHandlerInterceptor.java
  agent-module/plugins/aws-sdk-s3/src/main/java/com/navercorp/pinpoint/plugin/aws/sdk/s3/interceptor/S3ClientDatabaseRequestWrapper.java
  agent-module/plugins/aws-sdk-s3/src/main/java/com/navercorp/pinpoint/plugin/aws/sdk/s3/interceptor/S3ClientInterceptor.java
  agent-module/plugins/aws-sdk-s3/src/main/java/com/navercorp/pinpoint/plugin/aws/sdk/s3/interceptor/SdkHttpFullRequestHeaderAdaptor.java
  agent-module/plugins/aws-sdk-s3/src/main/java/com/navercorp/pinpoint/plugin/aws/sdk/s3/interceptor/XmlProtocolMarshallerInterceptor.java
  agent-module/plugins/aws-sdk-s3/src/main/resources/META-INF/pinpoint/type-provider.yml
  agent-module/plugins/aws-sdk-s3/src/main/resources/META-INF/services/com.navercorp.pinpoint.bootstrap.plugin.ProfilerPlugin
  agent-module/plugins/pom.xml
  commons/src/main/java/com/navercorp/pinpoint/common/trace/ServiceType.java
  web-frontend/src/main/v3/apps/web/public/img/icons/S3.png
  web-frontend/src/main/v3/apps/web/public/img/servers/S3.png
Labels: enhancement, module:plugin

#12458 [#12457] Backport: Add S3(Simple Storage Service) client plugin
  agent-module/agent/src/main/resources/profiles/local/pinpoint.config
  agent-module/agent/src/main/resources/profiles/release/pinpoint.config
  agent-module/bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/request/ClientDatabaseRequestAdaptor.java
  agent-module/bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/request/ClientDatabaseRequestRecorder.java
  agent-module/bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/request/ClientDatabaseRequestWrapper.java
  agent-module/bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/request/ClientDatabaseRequestWrapperAdaptor.java
  agent-module/plugins/assembly/pom.xml
  agent-module/plugins/aws-sdk-s3/README.md
  agent-module/plugins/aws-sdk-s3/pom.xml
  agent-module/plugins/aws-sdk-s3/src/main/java/com/navercorp/pinpoint/plugin/aws/sdk/s3/AwsSdkS3Constants.java
  agent-module/plugins/aws-sdk-s3/src/main/java/com/navercorp/pinpoint/plugin/aws/sdk/s3/AwsSdkS3Plugin.java
  agent-module/plugins/aws-sdk-s3/src/main/java/com/navercorp/pinpoint/plugin/aws/sdk/s3/AwsSdkS3PluginConfig.java
  agent-module/plugins/aws-sdk-s3/src/main/java/com/navercorp/pinpoint/plugin/aws/sdk/s3/RequestBuilderGetter.java
  agent-module/plugins/aws-sdk-s3/src/main/java/com/navercorp/pinpoint/plugin/aws/sdk/s3/URIGetter.java
  agent-module/plugins/aws-sdk-s3/src/main/java/com/navercorp/pinpoint/plugin/aws/sdk/s3/interceptor/AsyncResponseHandlerOnErrorInterceptor.java
  agent-module/plugins/aws-sdk-s3/src/main/java/com/navercorp/pinpoint/plugin/aws/sdk/s3/interceptor/AsyncResponseHandlerOnHeadersInterceptor.java
  agent-module/plugins/aws-sdk-s3/src/main/java/com/navercorp/pinpoint/plugin/aws/sdk/s3/interceptor/BaseClientHandlerInterceptor.java
  agent-module/plugins/aws-sdk-s3/src/main/java/com/navercorp/pinpoint/plugin/aws/sdk/s3/interceptor/HttpResponseHandlerInterceptor.java
  agent-module/plugins/aws-sdk-s3/src/main/java/com/navercorp/pinpoint/plugin/aws/sdk/s3/interceptor/S3ClientDatabaseRequestWrapper.java
  agent-module/plugins/aws-sdk-s3/src/main/java/com/navercorp/pinpoint/plugin/aws/sdk/s3/interceptor/S3ClientInterceptor.java
  agent-module/plugins/aws-sdk-s3/src/main/java/com/navercorp/pinpoint/plugin/aws/sdk/s3/interceptor/SdkHttpFullRequestHeaderAdaptor.java
  agent-module/plugins/aws-sdk-s3/src/main/java/com/navercorp/pinpoint/plugin/aws/sdk/s3/interceptor/XmlProtocolMarshallerInterceptor.java
  agent-module/plugins/aws-sdk-s3/src/main/resources/META-INF/pinpoint/type-provider.yml
  agent-module/plugins/aws-sdk-s3/src/main/resources/META-INF/services/com.navercorp.pinpoint.bootstrap.plugin.ProfilerPlugin
  agent-module/plugins/pom.xml
  commons/src/main/java/com/navercorp/pinpoint/common/trace/ServiceType.java
  web-frontend/src/main/v3/apps/web/public/img/icons/S3.png
  web-frontend/src/main/v3/apps/web/public/img/servers/S3.png
Labels: enhancement, module:plugin

#12459 [#noissue] Cleanup
  agent-module/profiler/src/test/java/com/navercorp/pinpoint/profiler/instrument/transformer/MatchableTransformerRegistryTest.java
  commons-server/src/test/java/com/navercorp/pinpoint/common/server/util/CallerUtilsTest.java
  commons/src/test/java/com/navercorp/pinpoint/common/trace/ServiceTypeCategoryTest.java
  redis-timeseries/src/test/java/com/navercorp/pinpoint/redis/timeseries/RedisTimeseriesAsyncCommandsTest.java
  web/src/test/java/com/navercorp/pinpoint/web/applicationmap/controller/MapControllerTest.java
Labels: cleanup

#12460 [#12434] Change InLink stats to Application stats
  collector/src/main/java/com/navercorp/pinpoint/collector/service/HbaseTraceService.java
Labels: enhancement

#12461 [#12434] Optimize scanner caching
  commons-timeseries/src/main/java/com/navercorp/pinpoint/common/timeseries/window/DefaultTimeSlot.java
  commons-timeseries/src/main/java/com/navercorp/pinpoint/common/timeseries/window/TimeWindow.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/dao/hbase/MapScanFactory.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/nodes/ServerBuilder.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/service/MapServiceImpl.java
Labels: enhancement

#12463 [#12434] Refactor HostApplicationDao
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/config/ApplicationMapModule.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/config/MapHbaseConfiguration.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/config/MapMapperConfiguration.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/dao/HostApplicationMapDao.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/dao/hbase/HbaseHostApplicationMapDao.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/dao/mapper/HostApplicationMapper.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/map/LinkSelectorFactory.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/map/processor/RpcCallProcessor.java
  web/src/test/java/com/navercorp/pinpoint/web/applicationmap/map/LinkSelectorTestBase.java
  web/src/test/java/com/navercorp/pinpoint/web/applicationmap/map/processor/RpcCallProcessorTest.java
Labels: enhancement

#12464 [#12434] Remove unnecessary agent interpolation
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/appender/server/StatisticsServerGroupListFactory.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/appender/server/datasource/AgentInfoServerGroupListDataSource.java
Labels: enhancement

#12465 [#12434] Reduce Memory usage in InLinkMapper
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/dao/mapper/InLinkMapper.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/dao/mapper/OutLinkMapper.java
Labels: enhancement

#12462 [#12434] Change node limit of servermap from 100 to 200
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/config/ApplicationMapModule.java
Labels: cleanup

#12467 [#12466] Upgrade spring boot from 3.3.7 to 3.3.11
  pom.xml
Labels: security, dependencies

#12468 [#12466] Bump springboot3 from 3.3.7 to 3.3.11
  pom.xml
Labels: security, dependencies

#12471 [#12469] Bump springframework from 6.1.16 to 6.1.20
  pom.xml
Labels: dependencies

#12472 [#12470] Bump springsecurity from 6.4.2 to 6.4.6
  pom.xml
Labels: dependencies

#12474 [#12473] Bump springdata from 3.3.7 to 3.3.12
  pom.xml
Labels: dependencies

#12475 [#noissue] Cleanup
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/map/VirtualLinkHandler.java
  web/src/main/java/com/navercorp/pinpoint/web/calltree/span/CallTreeIterator.java
  web/src/main/java/com/navercorp/pinpoint/web/calltree/span/MetaSpanCallTreeFactory.java
  web/src/main/java/com/navercorp/pinpoint/web/calltree/span/Node.java
  web/src/main/java/com/navercorp/pinpoint/web/service/ProxyRequestTypeRegistryServiceImpl.java
Labels: cleanup

#12476 [#noissue] Reduced netty3 dependency for future removal
  agent-module/plugins-it/ning-asyncclient-it/pom.xml
  agent-module/plugins/ning-asynchttpclient/pom.xml
  pom.xml
Labels: cleanup

#12365 [#12364] Bump pinot jdbc client from 1.2.0 to 1.3.0
  README.md
  pom.xml
Labels: dependencies

#12478 [#12477] Bump maven-wrapper from 3.9.7 to 3.9.9
  .mvn/wrapper/maven-wrapper.properties
  quickstart/testapp/.mvn/wrapper/MavenWrapperDownloader.java
  quickstart/testapp/.mvn/wrapper/maven-wrapper.jar
  quickstart/testapp/.mvn/wrapper/maven-wrapper.properties
  quickstart/testapp/mvnw
  quickstart/testapp/mvnw.cmd
  quickstart/testapp/pom.xml
Labels: cleanup

#12479 [#noissue] Remove antrun plugin from pom.xml
  pom.xml
Labels: cleanup

#12481 [#12480] Bump maven-enforce-plugin from 3.3.0 to 3.5.0
  pom.xml
Labels: dependencies

#12484 [#12483] Bump maven-release-plugin from 3.0.0-M1 to 3.1.1
  pom.xml
Labels: dependencies

#12485 [#12455] Update s3 client error mark
  agent-module/agent/src/main/resources/profiles/local/pinpoint.config
  agent-module/agent/src/main/resources/profiles/release/pinpoint.config
  agent-module/plugins/aws-sdk-s3/src/main/java/com/navercorp/pinpoint/plugin/aws/sdk/s3/AwsSdkS3PluginConfig.java
Labels: enhancement, module:plugin

#12486 [#12457] Backport: Update s3 client error mark
  agent-module/agent/src/main/resources/profiles/local/pinpoint.config
  agent-module/agent/src/main/resources/profiles/release/pinpoint.config
  agent-module/plugins/aws-sdk-s3/src/main/java/com/navercorp/pinpoint/plugin/aws/sdk/s3/AwsSdkS3PluginConfig.java
Labels: enhancement, module:plugin

#12488 [#noissue] Replace StringUtils.defaultString with Objects.toString for null handling
  agent-module/plugins/cubrid-jdbc/src/main/java/com/navercorp/pinpoint/plugin/jdbc/cubrid/CubridJdbcUrlParser.java
  agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/context/provider/ClassFileTransformerProvider.java
  agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/instrument/ASMMethodInsnNodeRemapper.java
  agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/jdbc/BindValueUtils.java
  collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/dao/hbase/HbaseMapInLinkDao.java
  collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/dao/hbase/HbaseMapOutLinkDao.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/util/ApplicationMapStatisticsUtils.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/util/TransactionIdParser.java
  commons/src/main/java/com/navercorp/pinpoint/common/util/StringUtils.java
  commons/src/test/java/com/navercorp/pinpoint/common/util/StringUtilsTest.java
  exceptiontrace/exceptiontrace-common/src/main/java/com/navercorp/pinpoint/exceptiontrace/common/model/ExceptionMetaData.java
  exceptiontrace/exceptiontrace-web/src/main/java/com/navercorp/pinpoint/exceptiontrace/web/mapper/ExceptionEntityMapper.java
  exceptiontrace/exceptiontrace-web/src/main/java/com/navercorp/pinpoint/exceptiontrace/web/view/ExceptionChartValueView.java
  inspector-module/inspector-web/src/main/java/com/navercorp/pinpoint/inspector/web/definition/MetricDefinition.java
  inspector-module/inspector-web/src/main/java/com/navercorp/pinpoint/inspector/web/definition/metric/field/Field.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/dao/mapper/InLinkMapper.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/map/FilteredMapBuilder.java
  web/src/main/java/com/navercorp/pinpoint/web/vo/activethread/AgentActiveThreadCountList.java
  web/src/main/java/com/navercorp/pinpoint/web/vo/callstacks/ExceptionRecord.java
  web/src/main/java/com/navercorp/pinpoint/web/vo/callstacks/ParameterRecord.java
  web/src/main/java/com/navercorp/pinpoint/web/vo/tree/ApplicationAgentHostList.java
Labels: cleanup

#12491 [#noissue] Replace deprecated API
  web/src/main/java/com/navercorp/pinpoint/web/util/DefaultCellTracker.java
Labels: cleanup

#12490 [#noissue] Extract ExceptionInfo
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/ExceptionInfo.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/SpanBo.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/SpanEventBo.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/grpc/GrpcSpanBinder.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/serializer/trace/v2/SpanDecoderV0.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/serializer/trace/v2/SpanEncoderV0.java
  commons-server/src/test/java/com/navercorp/pinpoint/common/server/bo/SpanFactoryAssert.java
  commons-server/src/test/java/com/navercorp/pinpoint/common/server/bo/serializer/trace/v2/bitfield/SpanBitFieldTest.java
  commons-server/src/test/java/com/navercorp/pinpoint/common/server/bo/serializer/trace/v2/bitfield/SpanEventBitFieldTest.java
  web/src/main/java/com/navercorp/pinpoint/web/calltree/span/Align.java
  web/src/main/java/com/navercorp/pinpoint/web/calltree/span/SpanAlign.java
  web/src/main/java/com/navercorp/pinpoint/web/calltree/span/SpanEventAlign.java
  web/src/main/java/com/navercorp/pinpoint/web/service/SpanServiceImpl.java
  web/src/main/java/com/navercorp/pinpoint/web/vo/callstacks/ExceptionRecord.java
  web/src/test/java/com/navercorp/pinpoint/web/mapper/SpanMapperV2Test.java
  web/src/test/java/com/navercorp/pinpoint/web/vo/callstacks/RecordFactoryTest.java
Labels: cleanup

#12489 [#noissue] Add Separate api to get response histogram
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/config/ApplicationMapModule.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/controller/MapHistogramController.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/rawdata/LinkDataMap.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/service/HistogramService.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/service/HistogramServiceImpl.java
Labels: module:web

#12498 [#noissue] Remove JsonViewUtils
  web/src/main/java/com/navercorp/pinpoint/web/util/json/JsonViewUtils.java
Labels: cleanup

#12497 [#noissue] Cleanup ObjectMapper
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/mapper/MapStructUtils.java
  commons-server/src/test/java/com/navercorp/pinpoint/common/server/mapper/MapStructUtilsTest.java
  exceptiontrace/exceptiontrace-web/src/main/java/com/navercorp/pinpoint/exceptiontrace/web/mapper/StackTraceMapper.java
  exceptiontrace/exceptiontrace-web/src/test/java/com/navercorp/pinpoint/exceptiontrace/web/mapper/ExceptionEntityMapperTest.java
  metric-module/metric-commons/src/main/java/com/navercorp/pinpoint/metric/common/mybatis/typehandler/TagListSerializer.java
  metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/collector/model/serialize/TelegrafJsonDeserializer.java
  otlpmetric/otlpmetric-web/src/main/java/com/navercorp/pinpoint/otlp/web/dao/mysql/MysqlAppMetricDefinitionDao.java
  realtime/realtime-common/src/main/java/com/navercorp/pinpoint/realtime/serde/ClusterKeyDeserializer.java
  web/src/main/java/com/navercorp/pinpoint/web/filter/DefaultFilterBuilder.java
Labels: cleanup

#12506 [#12434] Add Node Interpolation
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/service/MapServiceImpl.java
Labels: enhancement

#12504 [#12503] Do not allow the HttpClient to run in an nested
  agent-module/agent-testweb/spring-webflux-plugin-testweb/src/main/java/com/pinpoint/test/plugin/SpringWebfluxPluginController.java
  agent-module/bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/context/StackOperation.java
  agent-module/bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/context/TraceBlock.java
  agent-module/bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/interceptor/AsyncContextSpanEventBlockSimpleAroundInterceptor.java
  agent-module/bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/interceptor/AsyncContextSpanEventNestedBlockApiIdAwareAroundInterceptor.java
  agent-module/bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/interceptor/SpanEventBlockApiIdAwareAroundInterceptorForPlugin.java
  agent-module/bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/interceptor/SpanEventBlockSimpleAroundInterceptorForPlugin.java
  agent-module/bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/reactor/CoreSubscriberOnNextInterceptor.java
  agent-module/bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/request/ClientHeaderAdaptor.java
  agent-module/bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/request/DefaultRequestTraceWriter.java
  agent-module/bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/request/RequestTraceWriter.java
  agent-module/plugins/aws-sdk-s3/src/main/java/com/navercorp/pinpoint/plugin/aws/sdk/s3/interceptor/SdkHttpFullRequestHeaderAdaptor.java
  agent-module/plugins/aws-sdk-s3/src/main/java/com/navercorp/pinpoint/plugin/aws/sdk/s3/interceptor/XmlProtocolMarshallerInterceptor.java
  agent-module/plugins/grpc/src/main/java/com/navercorp/pinpoint/plugin/grpc/interceptor/client/ClientCallStartInterceptor.java
  agent-module/plugins/grpc/src/main/java/com/navercorp/pinpoint/plugin/grpc/interceptor/client/GrpcClientHeaderAdaptor.java
  agent-module/plugins/grpc/src/main/java/com/navercorp/pinpoint/plugin/grpc/interceptor/client/GrpcClientRequestWrapper.java
  agent-module/plugins/httpclient3/src/main/java/com/navercorp/pinpoint/plugin/httpclient3/HttpMethodClientHeaderAdaptor.java
  agent-module/plugins/httpclient3/src/main/java/com/navercorp/pinpoint/plugin/httpclient3/interceptor/HttpMethodBaseExecuteMethodInterceptor.java
  agent-module/plugins/httpclient4/src/main/java/com/navercorp/pinpoint/plugin/httpclient4/HttpRequest4ClientHeaderAdaptor.java
  agent-module/plugins/httpclient4/src/main/java/com/navercorp/pinpoint/plugin/httpclient4/interceptor/DefaultClientExchangeHandlerImplStartMethodInterceptor.java
  agent-module/plugins/httpclient4/src/main/java/com/navercorp/pinpoint/plugin/httpclient4/interceptor/HttpRequestExecutorExecuteMethodInterceptor.java
  agent-module/plugins/httpclient5/src/main/java/com/navercorp/pinpoint/plugin/httpclient5/HttpRequest5ClientHeaderAdaptor.java
  agent-module/plugins/httpclient5/src/main/java/com/navercorp/pinpoint/plugin/httpclient5/interceptor/CloseableHttpAsyncClientDoExecuteInterceptor.java
  agent-module/plugins/httpclient5/src/main/java/com/navercorp/pinpoint/plugin/httpclient5/interceptor/InternalHttpClientDoExecuteInterceptor.java
  agent-module/plugins/jdk-http/src/main/java/com/navercorp/pinpoint/plugin/jdk/http/HttpURLConnectionClientHeaderAdaptor.java
  agent-module/plugins/jdk-http/src/main/java/com/navercorp/pinpoint/plugin/jdk/http/interceptor/AbstractHttpURLConnectionInterceptor.java
  agent-module/plugins/jdk-http/src/main/java/com/navercorp/pinpoint/plugin/jdk/http/interceptor/HttpURLConnectionInterceptor.java
  agent-module/plugins/jdk-http/src/main/java/com/navercorp/pinpoint/plugin/jdk/http/interceptor/HttpsURLConnectionImplInterceptor.java
  agent-module/plugins/jdk-httpclient/src/main/java/com/navercorp/pinpoint/plugin/jdk/httpclient/HttpRequestImplClientHeaderAdaptor.java
  agent-module/plugins/jdk-httpclient/src/main/java/com/navercorp/pinpoint/plugin/jdk/httpclient/interceptor/MultiExchangeResponseAsyncImplInterceptor.java
  agent-module/plugins/netty/src/main/java/com/navercorp/pinpoint/plugin/netty/interceptor/http/HttpMessageClientHeaderAdaptor.java
  agent-module/plugins/ning-asynchttpclient/src/main/java/com/navercorp/pinpoint/plugin/ning/asynchttpclient/RequestHeaderAdaptorV1.java
  agent-module/plugins/ning-asynchttpclient/src/main/java/com/navercorp/pinpoint/plugin/ning/asynchttpclient/RequestHeaderAdaptorV2.java
  agent-module/plugins/ning-asynchttpclient/src/main/java/com/navercorp/pinpoint/plugin/ning/asynchttpclient/interceptor/ExecuteInterceptor.java
  agent-module/plugins/ning-asynchttpclient/src/main/java/com/navercorp/pinpoint/plugin/ning/asynchttpclient/interceptor/ExecuteRequestInterceptor.java
  agent-module/plugins/okhttp/src/main/java/com/navercorp/pinpoint/plugin/okhttp/v2/RequestBuilder2ClientHeaderAdaptor.java
  agent-module/plugins/okhttp/src/main/java/com/navercorp/pinpoint/plugin/okhttp/v3/RequestBuilder3ClientHeaderAdaptor.java
  agent-module/plugins/okhttp/src/main/java/com/navercorp/pinpoint/plugin/okhttp/v3/interceptor/RequestBuilderBuildMethodInterceptor.java
  agent-module/plugins/reactor-netty/src/main/java/com/navercorp/pinpoint/plugin/reactor/netty/interceptor/HttpClientOperationsSendInterceptor.java
  agent-module/plugins/reactor-netty/src/main/java/com/navercorp/pinpoint/plugin/reactor/netty/interceptor/HttpClientRequestHeaderAdaptor.java
  agent-module/plugins/reactor/src/main/java/com/navercorp/pinpoint/plugin/reactor/interceptor/FluxAndMonoSubscribeMethodInterceptor.java
  agent-module/plugins/spring-webflux/src/main/java/com/navercorp/pinpoint/plugin/spring/webflux/interceptor/BodyInserterRequestBuilderWriteToInterceptor.java
  agent-module/plugins/spring-webflux/src/main/java/com/navercorp/pinpoint/plugin/spring/webflux/interceptor/ClientHttpRequestClientHeaderAdaptor.java
  agent-module/plugins/spring-webflux/src/main/java/com/navercorp/pinpoint/plugin/spring/webflux/interceptor/HttpHeadersClientHeaderAdaptor.java
  agent-module/plugins/vertx/src/main/java/com/navercorp/pinpoint/plugin/vertx/HttpClientRequestClientHeaderAdaptor.java
  agent-module/plugins/vertx/src/main/java/com/navercorp/pinpoint/plugin/vertx/HttpRequestClientHeaderAdaptor.java
  agent-module/plugins/vertx/src/main/java/com/navercorp/pinpoint/plugin/vertx/interceptor/Http1xClientConnectionCreateRequestInterceptor.java
  agent-module/plugins/vertx/src/main/java/com/navercorp/pinpoint/plugin/vertx/interceptor/HttpClientStreamInterceptor.java
  agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/context/ChildTrace.java
  agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DefaultTrace.java
  agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DefaultTraceBlock.java
  agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DisableChildTrace.java
  agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DisableTrace.java
  agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DisableTraceBlock.java
Labels: enhancement, module:plugin

#12509 [#noissue] Optimize TagUtils
  inspector-module/inspector-commons/src/main/java/com/navercorp/pinpoint/common/dao/pinot/MultiValueTagTypeHandler.java
  metric-module/metric-commons/src/main/java/com/navercorp/pinpoint/metric/common/util/TagUtils.java
Labels: cleanup

#12505 [#12502] Add alias support for agent profiles
  agent-module/agent/src/main/resources/pinpoint-root.config
  agent-module/bootstraps/bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/config/ProfilePropertyLoader.java
  agent-module/bootstraps/bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/util/ProfileConstants.java
Labels: module:agent

#12510 [#noissue] Refactor SystemMetric
  metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/collector/controller/TelegrafMetricController.java
  metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/collector/model/TelegrafMetric.java
  metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/collector/service/SystemMetricDataTypeService.java
  metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/collector/service/SystemMetricDataTypeServiceImpl.java
  metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/collector/service/SystemMetricService.java
  metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/collector/service/SystemMetricTagServiceImpl.java
  metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/common/model/DoubleMetric.java
  metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/common/model/MetricDataName.java
  metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/common/model/MetricTagKey.java
  metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/common/model/Metrics.java
  metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/common/model/SystemMetric.java
  metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/web/service/SystemMetricDataServiceImpl.java
  metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/web/service/SystemMetricHostInfoServiceImpl.java
  metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/web/util/TagListUtils.java
  metric-module/metric/src/test/java/com/navercorp/pinpoint/metric/collector/controller/TelegrafMetricControllerTest.java
  metric-module/metric/src/test/java/com/navercorp/pinpoint/metric/collector/service/SystemMetricDataTypeServiceImplTest.java
  metric-module/metric/src/test/java/com/navercorp/pinpoint/metric/collector/service/SystemMetricFilterTest.java
  metric-module/metric/src/test/java/com/navercorp/pinpoint/metric/collector/service/SystemMetricTagServiceImplTest.java
  metric-module/metric/src/test/java/com/navercorp/pinpoint/metric/common/model/validation/TelegrafMetricsValidatorTest.java
  metric-module/metric/src/test/java/com/navercorp/pinpoint/metric/web/util/TagListUtilsTest.java
Labels: cleanup
