Repository pinpoint-apm/pinpoint, pull requests merged in 2025-03, with the labels that each got.

#12116 [#12115] Fix java.lang.NoClassDefFoundError: java/sql/Date in spring …
  agent-module/plugins/spring-data-r2dbc/src/main/java/com/navercorp/pinpoint/plugin/spring/r2dbc/interceptor/StatementBindInterceptor.java
  agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/jdbc/BindValueConverter.java
Labels: bug, module:plugin

#12108 [#12107] Update pubsub to lettuce plugin
  agent-module/agent-testweb/redis-lettuce-plugin-testweb/pom.xml
  agent-module/agent-testweb/redis-lettuce-plugin-testweb/src/main/java/com/pinpoint/test/plugin/RedisLettuceEventListenerCommandLineRunner.java
  agent-module/agent-testweb/redis-lettuce-plugin-testweb/src/main/java/com/pinpoint/test/plugin/RedisLettucePluginController.java
  agent-module/agent-testweb/redis-lettuce-plugin-testweb/src/main/java/com/pinpoint/test/plugin/RedisTemplateConfig.java
  agent-module/agent-testweb/redis-lettuce-plugin-testweb/src/test/java/com/pinpoint/test/plugin/RedisServerTest.java
  agent-module/agent-testweb/spring-cloud-gateway-plugin-testweb/src/main/java/com/pinpoint/test/plugin/ConfigManager.java
  agent-module/agent-testweb/spring-cloud-gateway-plugin-testweb/src/main/java/com/pinpoint/test/plugin/RedisLettuceEventListenerCommandLineRunner.java
  agent-module/agent-testweb/spring-cloud-gateway-plugin-testweb/src/main/java/com/pinpoint/test/plugin/RedisLettucePublisherCommandLineRunner.java
  agent-module/agent-testweb/spring-cloud-gateway-plugin-testweb/src/main/java/com/pinpoint/test/plugin/SimpleEvent.java
  agent-module/agent-testweb/spring-cloud-gateway-plugin-testweb/src/main/java/com/pinpoint/test/plugin/SpringCloudGatewayPluginTestStarter.java
  agent-module/agent-testweb/spring-cloud-gateway-plugin-testweb/src/main/resources/application.yml
  agent-module/agent/src/main/resources/profiles/local/pinpoint.config
  agent-module/agent/src/main/resources/profiles/release/pinpoint.config
  agent-module/plugins/redis-lettuce/src/main/java/com/navercorp/pinpoint/plugin/redis/lettuce/LettucePlugin.java
  agent-module/plugins/redis-lettuce/src/main/java/com/navercorp/pinpoint/plugin/redis/lettuce/LettucePluginConfig.java
  agent-module/plugins/redis-lettuce/src/main/java/com/navercorp/pinpoint/plugin/redis/lettuce/interceptor/RedisPubSubListenerInterceptor.java
  agent-module/plugins/redis-lettuce/src/main/java/com/navercorp/pinpoint/plugin/redis/lettuce/interceptor/RedisPubSubListenerMethodDescriptor.java
  agent-module/plugins/redis-lettuce/src/main/java/com/navercorp/pinpoint/plugin/redis/lettuce/interceptor/RunnableRunInterceptor.java
Labels: enhancement, module:plugin

#12118 [#12117] Backport: Fix java.lang.NoClassDefFoundError: java/sql/Date …
  agent-module/plugins/spring-data-r2dbc/src/main/java/com/navercorp/pinpoint/plugin/spring/r2dbc/interceptor/StatementBindInterceptor.java
  agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/jdbc/BindValueConverter.java
Labels: bug, module:plugin

#12130 [#12064] Rename package with id as uid
  collector/src/main/java/com/navercorp/pinpoint/collector/config/CollectorPinpointIdConfiguration.java
  collector/src/main/java/com/navercorp/pinpoint/collector/dao/ApplicationNameDao.java
  collector/src/main/java/com/navercorp/pinpoint/collector/dao/ApplicationUidDao.java
  collector/src/main/java/com/navercorp/pinpoint/collector/dao/ServiceUidDao.java
  collector/src/main/java/com/navercorp/pinpoint/collector/dao/hbase/HbaseApplicationNameDao.java
  collector/src/main/java/com/navercorp/pinpoint/collector/dao/hbase/HbaseApplicationUidDao.java
  collector/src/main/java/com/navercorp/pinpoint/collector/dao/hbase/HbaseServiceUidDao.java
  collector/src/main/java/com/navercorp/pinpoint/collector/receiver/grpc/cache/LevelUidCache.java
  collector/src/main/java/com/navercorp/pinpoint/collector/receiver/grpc/cache/SingleEntryUidCacheV1.java
  collector/src/main/java/com/navercorp/pinpoint/collector/receiver/grpc/cache/UidCache.java
  collector/src/main/java/com/navercorp/pinpoint/collector/service/ApplicationUidService.java
  collector/src/main/java/com/navercorp/pinpoint/collector/service/ApplicationUidServiceImpl.java
  collector/src/main/java/com/navercorp/pinpoint/collector/service/EmptyApplicationUidService.java
  collector/src/main/java/com/navercorp/pinpoint/collector/service/ServiceGroupService.java
  collector/src/main/java/com/navercorp/pinpoint/collector/service/ServiceGroupServiceImpl.java
  collector/src/main/java/com/navercorp/pinpoint/collector/service/StaticServiceGroupService.java
  collector/src/main/java/com/navercorp/pinpoint/io/request/GrpcServerHeaderV1.java
  collector/src/main/java/com/navercorp/pinpoint/io/request/ServerHeader.java
  collector/src/test/java/com/navercorp/pinpoint/io/request/GrpcServerHeaderV1Test.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/dao/hbase/mapper/ApplicationIdentifierMapper.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/dao/hbase/mapper/ApplicationUidMapper.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/dao/hbase/mapper/ServiceUidMapper.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/uid/ApplicationIdentifier.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/uid/ApplicationUid.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/uid/ServiceInfo.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/uid/ServiceUid.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/util/ApplicationUidRowKeyUtils.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/util/RandomApplicationUidGenerator.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/util/RandomServiceUidGenerator.java
  commons-server/src/test/java/com/navercorp/pinpoint/common/server/util/RandomServiceUidGeneratorTest.java
  web/src/main/java/com/navercorp/pinpoint/web/config/WebPinpointIdConfiguration.java
  web/src/main/java/com/navercorp/pinpoint/web/controller/ApplicationUidController.java
  web/src/main/java/com/navercorp/pinpoint/web/controller/ServiceGroupController.java
  web/src/main/java/com/navercorp/pinpoint/web/dao/ApplicationNameDao.java
  web/src/main/java/com/navercorp/pinpoint/web/dao/ApplicationUidDao.java
  web/src/main/java/com/navercorp/pinpoint/web/dao/ServiceNameDao.java
  web/src/main/java/com/navercorp/pinpoint/web/dao/ServiceUidDao.java
  web/src/main/java/com/navercorp/pinpoint/web/dao/hbase/HbaseApplicationNameDao.java
  web/src/main/java/com/navercorp/pinpoint/web/dao/hbase/HbaseApplicationUidDao.java
  web/src/main/java/com/navercorp/pinpoint/web/dao/hbase/HbaseServiceNameDao.java
  web/src/main/java/com/navercorp/pinpoint/web/dao/hbase/HbaseServiceUidDao.java
  web/src/main/java/com/navercorp/pinpoint/web/service/ApplicationUidService.java
  web/src/main/java/com/navercorp/pinpoint/web/service/ApplicationUidServiceImpl.java
  web/src/main/java/com/navercorp/pinpoint/web/service/ServiceGroupService.java
  web/src/main/java/com/navercorp/pinpoint/web/service/ServiceGroupServiceImpl.java
Labels: cleanup

#12132 [#noissue] Cleanup Boundary checking
  commons-buffer/src/main/java/com/navercorp/pinpoint/common/buffer/ByteArrayUtils.java
  commons-buffer/src/main/java/com/navercorp/pinpoint/common/buffer/StringCacheableBuffer.java
  commons-buffer/src/test/java/com/navercorp/pinpoint/common/buffer/ByteArrayUtilsTest.java
  commons-buffer/src/test/java/com/navercorp/pinpoint/common/buffer/StringCacheableBufferTest.java
  commons-buffer/src/test/java/com/navercorp/pinpoint/common/util/BytesUtilsTest.java
  commons/src/main/java/com/navercorp/pinpoint/common/util/BytesUtils.java
Labels: cleanup

#12127 [#12061] Backport: Remove comments from SQL queries
  agent-module/bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/config/DefaultProfilerConfig.java
  agent-module/bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/config/ProfilerConfig.java
  agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/context/provider/metadata/SqlMetadataServiceProvider.java
  agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/metadata/UidCachingSqlNormalizer.java
  agent-module/profiler/src/test/java/com/navercorp/pinpoint/profiler/metadata/SqlUidMetaDataServiceTest.java
  commons-profiler/src/main/java/com/navercorp/pinpoint/common/profiler/sql/DefaultSqlNormalizer.java
  commons-profiler/src/test/java/com/navercorp/pinpoint/common/profiler/sql/DefaultSqlNormalizerTest.java
Labels: enhancement, module:agent

#12136 [#12135] Enable configuration of period interval list for data query
  exceptiontrace/exceptiontrace-web/src/main/java/com/navercorp/pinpoint/exceptiontrace/web/config/ExceptionTraceProperties.java
  exceptiontrace/exceptiontrace-web/src/main/java/com/navercorp/pinpoint/exceptiontrace/web/frontend/export/ExceptionTracePropertiesExporter.java
  exceptiontrace/exceptiontrace-web/src/main/resources/pinpoint-web-exceptiontrace-root.properties
  inspector-module/inspector-web/src/main/java/com/navercorp/pinpoint/inspector/web/config/InspectorWebProperties.java
  metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/web/config/SystemMetricProperties.java
  metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/web/frontend/export/SystemMetricPropertiesExporter.java
  metric-module/metric/src/main/resources/pinot-web/pinpoint-web-metric-root.properties
  otlpmetric/otlpmetric-web/src/main/java/com/navercorp/pinpoint/otlp/web/config/OtlpMetricProperties.java
  otlpmetric/otlpmetric-web/src/main/java/com/navercorp/pinpoint/otlp/web/frontend/export/OtlpMetricPropertiesExporter.java
  otlpmetric/otlpmetric-web/src/main/resources/otlpmetric/web/otlpmetric-web-root.properties
  uristat/uristat-web/src/main/java/com/navercorp/pinpoint/uristat/web/config/UriStatProperties.java
  uristat/uristat-web/src/main/java/com/navercorp/pinpoint/uristat/web/frontend/export/UriStatPropertiesExporter.java
  uristat/uristat-web/src/main/resources/pinpoint-web-uristat-root.properties
  web/src/main/java/com/navercorp/pinpoint/web/config/ConfigProperties.java
  web/src/main/java/com/navercorp/pinpoint/web/frontend/export/ConfigPropertiesExporter.java
  web/src/main/resources/pinpoint-web-root.properties
Labels: enhancement, module:web

#12143 [#12048] Fix datetime/time columns config for Ingestion Aggregations
  inspector-module/inspector-collector/src/main/pinot/pinot-inspector-stat-application-realtime-table.json
Labels: bug, module:inspector

#12150 [#12149] Update avoid tracking unnecessary subscribe method of reactor
  agent-module/plugins/reactor/src/main/java/com/navercorp/pinpoint/plugin/reactor/interceptor/FluxAndMonoSubscribeMethodInterceptor.java
Labels: enhancement, module:plugin

#12155 [#12025] Refactor applicationId to applicationName
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/SpanBo.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/SpanEventBo.java
  web/src/test/java/com/navercorp/pinpoint/web/vo/callstacks/RecordFactoryTest.java
Labels: cleanup

#12157 [#noissue] Remove redundant fields of AgentStatDataPoint
  collector/src/main/java/com/navercorp/pinpoint/collector/mapper/grpc/stat/GrpcAgentUriStatMapper.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/stat/ActiveTraceBo.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/stat/AgentStatDataBasePoint.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/stat/AgentStatDataPoint.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/stat/AgentUriStatBo.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/stat/CpuLoadBo.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/stat/DataSourceBo.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/stat/DataSourceListBo.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/stat/DeadlockThreadCountBo.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/stat/DirectBufferBo.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/stat/FileDescriptorBo.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/stat/JvmGcBo.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/stat/JvmGcDetailedBo.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/stat/LoadedClassBo.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/stat/ResponseTimeBo.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/stat/TotalThreadCountBo.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/stat/TransactionBo.java
Labels: cleanup

#12161 [#12025] Fix UidFetcher NPE
  collector/src/main/java/com/navercorp/pinpoint/collector/receiver/grpc/service/DefaultServerRequestFactory.java
Labels: bug

#12162 [#noissue] Remove unnecessary stacktrace from header validation
  grpc/src/main/java/com/navercorp/pinpoint/grpc/server/HeaderExtractor.java
  grpc/src/main/java/com/navercorp/pinpoint/grpc/server/HeaderPropagationInterceptor.java
  grpc/src/main/java/com/navercorp/pinpoint/grpc/server/InvalidGrpcHeaderException.java
  grpc/src/test/java/com/navercorp/pinpoint/grpc/server/ServerHeaderReaderTest.java
  log/log-collector/src/main/java/com/navercorp/pinpoint/log/collector/grpc/context/LogHeaderPropagationInterceptor.java
Labels: cleanup

#12163 [#12159] Store span response time in Pinot and aggregate it into statistical data during storage.
  batch/src/main/java/com/navercorp/pinpoint/batch/alarm/dao/pinot/PinotAlarmDao.java
  collector-starter/src/main/resources/application.yml
  collector/pom.xml
  collector/src/main/java/com/navercorp/pinpoint/collector/PinpointCollectorModule.java
  collector/src/main/java/com/navercorp/pinpoint/collector/heatmap/HeatmapCollectorModule.java
  collector/src/main/java/com/navercorp/pinpoint/collector/heatmap/config/HeatmapKafkaConfiguration.java
  collector/src/main/java/com/navercorp/pinpoint/collector/heatmap/config/HeatmapProperties.java
  collector/src/main/java/com/navercorp/pinpoint/collector/heatmap/config/HeatmapPropertySources.java
  collector/src/main/java/com/navercorp/pinpoint/collector/heatmap/dao/HeatmapDao.java
  collector/src/main/java/com/navercorp/pinpoint/collector/heatmap/dao/pinot/PinotHeatmapDao.java
  collector/src/main/java/com/navercorp/pinpoint/collector/heatmap/service/HeatmapService.java
  collector/src/main/java/com/navercorp/pinpoint/collector/heatmap/vo/HeatmapStat.java
  collector/src/main/java/com/navercorp/pinpoint/collector/heatmap/vo/SpanStat.java
  collector/src/main/pinot/pinot-heatmap-stat-agent-realtime-table.json
  collector/src/main/pinot/pinot-heatmap-stat-agent-schema.json
  collector/src/main/pinot/pinot-heatmap-stat-application-realtime-table.json
  collector/src/main/pinot/pinot-heatmap-stat-application-schema.json
  collector/src/main/resources/heatmap/collector/profiles/local/heatmap-collector.properties
  collector/src/main/resources/heatmap/collector/profiles/release/heatmap-collector.properties
  commons-server/pom.xml
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/metric/dao/TableNameManager.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/metric/dao/TopicNameManager.java
  commons-server/src/test/java/com/navercorp/pinpoint/common/server/metric/dao/AgentStatNameManagerTest.java
  commons-server/src/test/java/com/navercorp/pinpoint/common/server/metric/dao/TableNameManagerTest.java
  commons-server/src/test/java/com/navercorp/pinpoint/common/server/metric/dao/TopicNameManagerTest.java
  inspector-module/inspector-collector/src/main/java/com/navercorp/pinpoint/inspector/collector/dao/pinot/DefaultAgentStatDao.java
  inspector-module/inspector-web/src/main/java/com/navercorp/pinpoint/inspector/web/dao/pinot/PinotAgentStatDao.java
  metric-module/metric-commons/pom.xml
  otlpmetric/otlpmetric-collector/src/main/java/com/navercorp/pinpoint/otlp/collector/dao/PinotOtlpMetricDao.java
  otlpmetric/otlpmetric-web/src/main/java/com/navercorp/pinpoint/otlp/web/service/OtlpMetricWebServiceImpl.java
  otlpmetric/otlpmetric-web/src/main/java/com/navercorp/pinpoint/otlp/web/vo/OtlpMetricDataQueryParameter.java
Labels: module:collector

#12165 [#12159] Change kafka.heatmap.topic.prefix configuration value
  collector/src/main/resources/heatmap/collector/profiles/release/heatmap-collector.properties
Labels: module:collector

#12164 [#12025] Refactor AgentStatDataPoint interface
  collector/src/main/java/com/navercorp/pinpoint/collector/mapper/grpc/stat/GrpcActiveTraceBoMapper.java
  collector/src/main/java/com/navercorp/pinpoint/collector/mapper/grpc/stat/GrpcAgentStatBatchMapper.java
  collector/src/main/java/com/navercorp/pinpoint/collector/mapper/grpc/stat/GrpcCpuLoadBoMapper.java
  collector/src/main/java/com/navercorp/pinpoint/collector/mapper/grpc/stat/GrpcDataSourceBoMapper.java
  collector/src/main/java/com/navercorp/pinpoint/collector/mapper/grpc/stat/GrpcDeadlockThreadCountBoMapper.java
  collector/src/main/java/com/navercorp/pinpoint/collector/mapper/grpc/stat/GrpcDirectBufferBoMapper.java
  collector/src/main/java/com/navercorp/pinpoint/collector/mapper/grpc/stat/GrpcFileDescriptorBoMapper.java
  collector/src/main/java/com/navercorp/pinpoint/collector/mapper/grpc/stat/GrpcJvmGcBoMapper.java
  collector/src/main/java/com/navercorp/pinpoint/collector/mapper/grpc/stat/GrpcJvmGcDetailedBoMapper.java
  collector/src/main/java/com/navercorp/pinpoint/collector/mapper/grpc/stat/GrpcLoadedClassBoMapper.java
  collector/src/main/java/com/navercorp/pinpoint/collector/mapper/grpc/stat/GrpcResponseTimeBoMapper.java
  collector/src/main/java/com/navercorp/pinpoint/collector/mapper/grpc/stat/GrpcTotalThreadCountBoMapper.java
  collector/src/main/java/com/navercorp/pinpoint/collector/mapper/grpc/stat/GrpcTransactionBoMapper.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/stat/AbstractStatDataPoint.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/stat/ActiveTraceBo.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/stat/AgentStatBo.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/stat/AgentStatDataPoint.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/stat/AgentStatDataPointList.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/stat/CpuLoadBo.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/stat/DataPoint.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/stat/DataSourceBo.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/stat/DataSourceListBo.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/stat/DeadlockThreadCountBo.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/stat/DefaultDataPoint.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/stat/DirectBufferBo.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/stat/FileDescriptorBo.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/stat/JvmGcBo.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/stat/JvmGcDetailedBo.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/stat/LoadedClassBo.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/stat/ResponseTimeBo.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/stat/StatDataPoint.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/stat/TotalThreadCountBo.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/stat/TransactionBo.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/stat/UriStatHistogram.java
  commons-server/src/test/java/com/navercorp/pinpoint/common/server/bo/codec/stat/TestAgentStatFactory.java
  inspector-module/inspector-collector/src/main/java/com/navercorp/pinpoint/inspector/collector/dao/AgentStatDao.java
  inspector-module/inspector-collector/src/main/java/com/navercorp/pinpoint/inspector/collector/dao/pinot/DefaultAgentStatDao.java
  inspector-module/inspector-collector/src/main/java/com/navercorp/pinpoint/inspector/collector/dao/pinot/PinotDaoConfiguration.java
  inspector-module/inspector-collector/src/main/java/com/navercorp/pinpoint/inspector/collector/model/kafka/AgentStat.java
  inspector-module/inspector-collector/src/main/java/com/navercorp/pinpoint/inspector/collector/model/kafka/AgentStatBuilder.java
  inspector-module/inspector-collector/src/main/java/com/navercorp/pinpoint/inspector/collector/model/kafka/AgentStatModelConverter.java
  inspector-module/inspector-collector/src/main/java/com/navercorp/pinpoint/inspector/collector/model/kafka/ApplicationStat.java
  inspector-module/inspector-commons/src/main/java/com/navercorp/pinpoint/common/model/SortKeyUtils.java
  web/src/test/java/com/navercorp/pinpoint/web/test/util/DataSourceTestUtils.java
Labels: cleanup

#12170 [#noissue] Refactor ColumnName
  collector/src/main/java/com/navercorp/pinpoint/collector/dao/hbase/statistics/CalleeColumnName.java
  collector/src/main/java/com/navercorp/pinpoint/collector/dao/hbase/statistics/CallerColumnName.java
  collector/src/main/java/com/navercorp/pinpoint/collector/dao/hbase/statistics/ColumnName.java
  collector/src/main/java/com/navercorp/pinpoint/collector/dao/hbase/statistics/ResponseColumnName.java
  collector/src/main/java/com/navercorp/pinpoint/collector/dao/hbase/statistics/RowKeyMerge.java
  collector/src/test/java/com/navercorp/pinpoint/collector/dao/hbase/statistics/BulkIncrementerTestClazz.java
  collector/src/test/java/com/navercorp/pinpoint/collector/dao/hbase/statistics/CalleeColumnNameTest.java
  collector/src/test/java/com/navercorp/pinpoint/collector/dao/hbase/statistics/CallerColumnNameTest.java
  collector/src/test/java/com/navercorp/pinpoint/collector/dao/hbase/statistics/DefaultBulkUpdaterTest.java
  collector/src/test/java/com/navercorp/pinpoint/collector/dao/hbase/statistics/ResponseColumnNameTest.java
  collector/src/test/java/com/navercorp/pinpoint/collector/dao/hbase/statistics/SizeLimitedBulkIncrementerTest.java
  collector/src/test/java/com/navercorp/pinpoint/collector/dao/hbase/statistics/ThreadUtils.java
Labels: cleanup

#12167 [#noissue] Improve logging for stream errors
  collector/src/main/java/com/navercorp/pinpoint/collector/receiver/grpc/service/AgentService.java
  collector/src/main/java/com/navercorp/pinpoint/collector/receiver/grpc/service/ServerCallStream.java
Labels: module:collector

#12173 [#noissue] Deprecate getPingSlotNumber API
  collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/dao/hbase/HbaseMapResponseTimeDao.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/util/ApplicationMapStatisticsUtils.java
Labels: cleanup

#12174 [#noissue] Refactor ResponseColumnName
  collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/dao/hbase/HbaseMapResponseTimeDao.java
  collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/statistics/ResponseColumnName.java
Labels: cleanup

#12176 [#12025] Remove deprecated getApplicationId in TransactionInfoViewModel
  web/src/main/java/com/navercorp/pinpoint/web/view/TransactionInfoViewModel.java
Labels: cleanup

#12175 [#noissue] Improve naming conventions for ServerMap
  batch/src/main/java/com/navercorp/pinpoint/batch/alarm/DataCollectorFactory.java
  batch/src/main/java/com/navercorp/pinpoint/batch/alarm/checker/ErrorCountToCalleeChecker.java
  batch/src/main/java/com/navercorp/pinpoint/batch/alarm/checker/ErrorRateToCalleeChecker.java
  batch/src/main/java/com/navercorp/pinpoint/batch/alarm/checker/SlowCountToCalleeChecker.java
  batch/src/main/java/com/navercorp/pinpoint/batch/alarm/checker/SlowRateToCalleeChecker.java
  batch/src/main/java/com/navercorp/pinpoint/batch/alarm/checker/TotalCountToCalleeChecker.java
  batch/src/main/java/com/navercorp/pinpoint/batch/alarm/collector/MapOutLinkDataCollector.java
  batch/src/main/java/com/navercorp/pinpoint/batch/config/AlarmCheckerConfiguration.java
  batch/src/test/java/com/navercorp/pinpoint/batch/alarm/checker/ErrorCountToCalleCheckerTest.java
  batch/src/test/java/com/navercorp/pinpoint/batch/alarm/checker/ErrorRateToCalleCheckerTest.java
  batch/src/test/java/com/navercorp/pinpoint/batch/alarm/checker/SlowCountToCalleCheckerTest.java
  batch/src/test/java/com/navercorp/pinpoint/batch/alarm/checker/SlowRateToCalleCheckerTest.java
  batch/src/test/java/com/navercorp/pinpoint/batch/alarm/checker/TotalCountToCalleeCheckerTest.java
  collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/statistics/config/BulkFactory.java
  commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/config/DistributorConfiguration.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/config/MapHbaseConfiguration.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/config/MapMapperConfiguration.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/dao/MapInLinkDao.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/dao/MapOutLinkDao.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/dao/hbase/HbaseMapInLinkDao.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/dao/hbase/HbaseMapOutLinkDao.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/dao/mapper/InLinkMapper.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/dao/mapper/LinkTimeWindowReducer.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/dao/mapper/OutLinkMapper.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/map/DefaultApplicationMapCreator.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/map/VirtualLinkHandler.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/rawdata/LinkData.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/service/LinkDataMapService.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/service/LinkDataMapServiceImpl.java
  web/src/test/java/com/navercorp/pinpoint/web/applicationmap/map/BidirectionalLinkSelectorTest.java
  web/src/test/java/com/navercorp/pinpoint/web/applicationmap/map/LinkSelectorTestBase.java
  web/src/test/java/com/navercorp/pinpoint/web/applicationmap/map/UnidirectionalLinkSelectorTest.java
Labels: cleanup

#12178 [#noissue] Cleanup
  batch/src/main/java/com/navercorp/pinpoint/batch/alarm/collector/AgentEventDataCollector.java
  batch/src/main/java/com/navercorp/pinpoint/batch/alarm/collector/DataCollector.java
  batch/src/main/java/com/navercorp/pinpoint/batch/alarm/collector/MapOutLinkDataCollector.java
  batch/src/main/java/com/navercorp/pinpoint/batch/alarm/collector/ResponseTimeDataCollector.java
  batch/src/main/java/com/navercorp/pinpoint/batch/alarm/collector/pinot/DataSourceDataCollector.java
  batch/src/main/java/com/navercorp/pinpoint/batch/alarm/collector/pinot/FileDescriptorDataCollector.java
  batch/src/main/java/com/navercorp/pinpoint/batch/alarm/collector/pinot/HeapDataCollector.java
  batch/src/main/java/com/navercorp/pinpoint/batch/alarm/collector/pinot/JvmCpuDataCollector.java
  batch/src/main/java/com/navercorp/pinpoint/batch/alarm/collector/pinot/SystemCpuDataCollector.java
Labels: cleanup

#12181 [#12180] Backport: Fix datetime/time columns config for Ingestion Aggregations
  inspector-module/inspector-collector/src/main/pinot/pinot-inspector-stat-application-realtime-table.json
Labels: bug, module:inspector

#12182 [#noissue] Remove unnecessary histogramSlot check
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/dao/mapper/InLinkMapper.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/dao/mapper/OutLinkMapper.java
Labels: cleanup

#12185 [#12159] Change schema for heatmap table
  collector/src/main/java/com/navercorp/pinpoint/collector/heatmap/dao/pinot/PinotHeatmapDao.java
  collector/src/main/java/com/navercorp/pinpoint/collector/heatmap/vo/HeatmapStat.java
  collector/src/main/pinot/pinot-heatmap-stat-application-realtime-table.json
  collector/src/main/pinot/pinot-heatmap-stat-application-schema.json
Labels: enhancement, module:collector

#12187 [#noissue] Refactor ServiceTypeCategory
  commons/src/main/java/com/navercorp/pinpoint/common/trace/ServiceTypeCategory.java
  commons/src/test/java/com/navercorp/pinpoint/common/trace/ServiceTypeCategoryTest.java
Labels: cleanup

#12188 [#noissue] Refactor Histogram
  commons/src/main/java/com/navercorp/pinpoint/common/trace/BaseHistogramSchema.java
  commons/src/main/java/com/navercorp/pinpoint/common/trace/HistogramSchema.java
  commons/src/main/java/com/navercorp/pinpoint/common/trace/HistogramSlotGroup.java
  commons/src/main/java/com/navercorp/pinpoint/common/trace/Schema.java
  commons/src/test/java/com/navercorp/pinpoint/common/trace/BaseHistogramSchemaTest.java
  commons/src/test/java/com/navercorp/pinpoint/common/trace/HistogramSchemaTest.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/histogram/Histogram.java
  web/src/test/java/com/navercorp/pinpoint/web/applicationmap/histogram/HistogramTest.java
  web/src/test/java/com/navercorp/pinpoint/web/applicationmap/rawdata/AgentHistogramTest.java
Labels: cleanup

#12190 [#12159] Change default value for serviceName column
  collector/src/main/pinot/pinot-heatmap-stat-application-schema.json
Labels: module:collector

#12191 [#noissue] Cleanup
  web/src/test/java/com/navercorp/pinpoint/web/TestTraceUtils.java
  web/src/test/java/com/navercorp/pinpoint/web/filter/LinkFilterTest.java
  web/src/test/java/com/navercorp/pinpoint/web/util/ServiceTypeRegistryMockFactory.java
Labels: cleanup

#12194 [#12193] Bump ASM from 9.6 to 9.7.1
  pom.xml
Labels: module:agent

#12192 [#noissue] Refactor datatype of ServiceType in Server from short to int
  agent-module/plugins-loader/src/main/java/com/navercorp/pinpoint/loader/service/DefaultServiceTypeRegistryService.java
  agent-module/plugins-loader/src/main/java/com/navercorp/pinpoint/loader/service/ServiceTypeRegistryService.java
  agent-module/plugins/fastjson/src/test/java/com/navercorp/pinpoint/plugin/fastjson/FastjsonConstantsTest.java
  collector/src/main/java/com/navercorp/pinpoint/collector/dao/hbase/HbaseApplicationIndexDao.java
  collector/src/main/java/com/navercorp/pinpoint/collector/mapper/grpc/GrpcAgentInfoBoMapper.java
  collector/src/main/java/com/navercorp/pinpoint/collector/service/HbaseTraceService.java
  collector/src/main/java/com/navercorp/pinpoint/collector/service/async/AgentLifeCycleAsyncTaskService.java
  commons-profiler/src/main/java/com/navercorp/pinpoint/common/profiler/trace/AnnotationKeyMatcherRegistry.java
  commons-profiler/src/main/java/com/navercorp/pinpoint/common/profiler/trace/ServiceTypeRegistry.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/AgentInfoBo.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/Event.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/ServiceTypeUtils.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/SpanBo.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/SpanChunkBo.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/SpanEventBo.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/grpc/GrpcSpanBinder.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/serializer/trace/v2/SpanEncoderV0.java
  commons-server/src/test/java/com/navercorp/pinpoint/common/server/bo/SpanBoTes.java
  commons/src/main/java/com/navercorp/pinpoint/common/trace/AnnotationKeyMatcherLocator.java
  commons/src/main/java/com/navercorp/pinpoint/common/trace/DefaultServiceType.java
  commons/src/main/java/com/navercorp/pinpoint/common/trace/ServiceTypeLocator.java
  commons/src/main/java/com/navercorp/pinpoint/common/trace/ServiceTypeProvider.java
  commons/src/test/java/com/navercorp/pinpoint/common/trace/ServiceTypeCategoryTest.java
  inspector-module/inspector-web/src/main/java/com/navercorp/pinpoint/inspector/web/definition/metric/ServiceTypeMatchingPostProcessor.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/dao/hbase/MapScanFactory.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/map/FilteredMapBuilder.java
  web/src/main/java/com/navercorp/pinpoint/web/calltree/span/Align.java
  web/src/main/java/com/navercorp/pinpoint/web/calltree/span/LinkedCallTree.java
  web/src/main/java/com/navercorp/pinpoint/web/calltree/span/SpanAlign.java
  web/src/main/java/com/navercorp/pinpoint/web/calltree/span/SpanEventAlign.java
  web/src/main/java/com/navercorp/pinpoint/web/component/AnnotationKeyMatcherService.java
  web/src/main/java/com/navercorp/pinpoint/web/component/ApplicationFactory.java
  web/src/main/java/com/navercorp/pinpoint/web/component/DefaultAnnotationKeyMatcherService.java
  web/src/main/java/com/navercorp/pinpoint/web/component/DefaultApplicationFactory.java
  web/src/main/java/com/navercorp/pinpoint/web/dao/hbase/HbaseHostApplicationMapDao.java
  web/src/main/java/com/navercorp/pinpoint/web/filter/transaction/LinkContext.java
  web/src/main/java/com/navercorp/pinpoint/web/filter/transaction/SpanContext.java
  web/src/main/java/com/navercorp/pinpoint/web/service/component/DefaultLegacyAgentCompatibility.java
  web/src/main/java/com/navercorp/pinpoint/web/service/component/DisableAgentCompatibility.java
  web/src/main/java/com/navercorp/pinpoint/web/service/component/LegacyAgent.java
  web/src/main/java/com/navercorp/pinpoint/web/service/component/LegacyAgentCompatibility.java
  web/src/main/java/com/navercorp/pinpoint/web/vo/Application.java
  web/src/main/java/com/navercorp/pinpoint/web/vo/ResponseTime.java
  web/src/main/java/com/navercorp/pinpoint/web/vo/callstacks/RecordFactory.java
  web/src/test/java/com/navercorp/pinpoint/web/applicationmap/service/FilteredMapServiceImplTest.java
  web/src/test/java/com/navercorp/pinpoint/web/calltree/span/SpanAlignerTest.java
  web/src/test/java/com/navercorp/pinpoint/web/filter/LinkFilterTest.java
  web/src/test/java/com/navercorp/pinpoint/web/mapper/SpanMapperV2Test.java
  web/src/test/java/com/navercorp/pinpoint/web/util/ServiceTypeRegistryMockFactory.java
  web/src/test/java/com/navercorp/pinpoint/web/vo/callstacks/RecordFactoryTest.java
Labels: cleanup

#12196 [#noissue] Remove ServiceType field from SpanChunkBo
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/ServiceTypeUtils.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/SpanBo.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/SpanChunkBo.java
  web/src/test/java/com/navercorp/pinpoint/web/calltree/span/CallTreeTest.java
Labels: cleanup

#12199 [#12198] Fix potential class loading deadlock in HbaseColumnFamily
  collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/statistics/config/BulkFactory.java
  collector/src/main/java/com/navercorp/pinpoint/collector/dao/hbase/HbaseAgentEventDao.java
  collector/src/main/java/com/navercorp/pinpoint/collector/dao/hbase/HbaseAgentInfoDao.java
  collector/src/main/java/com/navercorp/pinpoint/collector/dao/hbase/HbaseAgentLifeCycleDao.java
  collector/src/main/java/com/navercorp/pinpoint/collector/dao/hbase/HbaseApiMetaDataDao.java
  collector/src/main/java/com/navercorp/pinpoint/collector/dao/hbase/HbaseApplicationIndexDao.java
  collector/src/main/java/com/navercorp/pinpoint/collector/dao/hbase/HbaseApplicationTraceIndexDao.java
  collector/src/main/java/com/navercorp/pinpoint/collector/dao/hbase/HbaseHostApplicationMapDao.java
  collector/src/main/java/com/navercorp/pinpoint/collector/dao/hbase/HbaseSqlMetaDataDao.java
  collector/src/main/java/com/navercorp/pinpoint/collector/dao/hbase/HbaseSqlUidMetaDataDao.java
  collector/src/main/java/com/navercorp/pinpoint/collector/dao/hbase/HbaseStringMetaDataDao.java
  collector/src/main/java/com/navercorp/pinpoint/collector/dao/hbase/HbaseTraceDaoV2.java
  collector/src/main/java/com/navercorp/pinpoint/collector/uid/dao/hbase/HbaseApplicationNameDao.java
  collector/src/main/java/com/navercorp/pinpoint/collector/uid/dao/hbase/HbaseApplicationUidDao.java
  collector/src/main/java/com/navercorp/pinpoint/collector/uid/dao/hbase/HbaseServiceUidDao.java
  collector/src/test/java/com/navercorp/pinpoint/collector/dao/hbase/HbaseApiMetaDataDaoTest.java
  commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/HbaseColumnFamily.java
  commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/HbaseTable.java
  commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/HbaseTables.java
  commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/config/AsyncWarmup.java
  commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/config/Warmup.java
  commons-hbase/src/test/java/com/navercorp/pinpoint/common/hbase/HbaseTableTest.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/serializer/trace/v2/SpanChunkSerializerV2.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/serializer/trace/v2/SpanSerializerV2.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/dao/hbase/mapper/AgentInfoBoMapper.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/scatter/FuzzyRowKeyBuilder.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/uid/mapper/ApplicationIdentifierMapper.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/uid/mapper/ApplicationUidMapper.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/uid/mapper/ApplicationUidNameMapper.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/uid/mapper/ServiceNameMapper.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/uid/mapper/ServiceUidMapper.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/dao/hbase/HbaseMapInLinkDao.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/dao/hbase/HbaseMapOutLinkDao.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/dao/hbase/HbaseMapResponseTimeDao.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/dao/mapper/ResponseTimeMapper.java
  web/src/main/java/com/navercorp/pinpoint/web/dao/hbase/HbaseAgentEventDao.java
  web/src/main/java/com/navercorp/pinpoint/web/dao/hbase/HbaseAgentInfoDao.java
  web/src/main/java/com/navercorp/pinpoint/web/dao/hbase/HbaseAgentLifeCycleDao.java
  web/src/main/java/com/navercorp/pinpoint/web/dao/hbase/HbaseApiMetaDataDao.java
  web/src/main/java/com/navercorp/pinpoint/web/dao/hbase/HbaseApplicationIndexDao.java
  web/src/main/java/com/navercorp/pinpoint/web/dao/hbase/HbaseApplicationTraceIndexDao.java
  web/src/main/java/com/navercorp/pinpoint/web/dao/hbase/HbaseSqlMetaDataDao.java
  web/src/main/java/com/navercorp/pinpoint/web/dao/hbase/HbaseSqlUidMetaDataDao.java
  web/src/main/java/com/navercorp/pinpoint/web/dao/hbase/HbaseStringMetaDataDao.java
  web/src/main/java/com/navercorp/pinpoint/web/dao/hbase/HbaseTraceDaoV2.java
  web/src/main/java/com/navercorp/pinpoint/web/mapper/AgentLifeCycleMapper.java
  web/src/main/java/com/navercorp/pinpoint/web/mapper/ApiMetaDataMapper.java
  web/src/main/java/com/navercorp/pinpoint/web/mapper/SpanMapperV2.java
  web/src/main/java/com/navercorp/pinpoint/web/mapper/SqlMetaDataMapper.java
  web/src/main/java/com/navercorp/pinpoint/web/mapper/SqlUidMetaDataMapper.java
  web/src/main/java/com/navercorp/pinpoint/web/mapper/StringMetaDataMapper.java
  web/src/main/java/com/navercorp/pinpoint/web/mapper/TraceIndexMetaScatterMapper.java
  web/src/main/java/com/navercorp/pinpoint/web/mapper/TraceIndexScatterMapper.java
  web/src/main/java/com/navercorp/pinpoint/web/mapper/TransactionIdMapper.java
  web/src/main/java/com/navercorp/pinpoint/web/uid/dao/hbase/HbaseApplicationNameDao.java
  web/src/main/java/com/navercorp/pinpoint/web/uid/dao/hbase/HbaseApplicationUidDao.java
  web/src/main/java/com/navercorp/pinpoint/web/uid/dao/hbase/HbaseServiceNameDao.java
  web/src/main/java/com/navercorp/pinpoint/web/uid/dao/hbase/HbaseServiceUidDao.java
Labels: cleanup

#12202 [#11906] Fix log4j2 configuration YAML
  agent-module/agent/src/main/resources/log4j2-agent.yaml
Labels: module:agent

#12204 [#noissue] Cleanup
  agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/context/active/DefaultActiveTraceRepository.java
  agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/context/exception/model/ExceptionWrapper.java
  agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/monitor/metric/uri/URIKey.java
  batch/src/main/java/com/navercorp/pinpoint/batch/alarm/vo/DataSourceAlarmVO.java
  collector/src/main/java/com/navercorp/pinpoint/collector/receiver/grpc/PermissionServerTransportFilter.java
  collector/src/main/java/com/navercorp/pinpoint/collector/util/MultipleAddress.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/stat/EachUriStatBo.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/util/CidrAddressFilter.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/util/IgnoreAddressFilter.java
  commons-server/src/test/java/com/navercorp/pinpoint/common/server/bo/SpanBoTest.java
  commons/src/main/java/com/navercorp/pinpoint/common/trace/DefaultAnnotationKey.java
  commons/src/main/java/com/navercorp/pinpoint/common/trace/HistogramSlot.java
  commons/src/main/java/com/navercorp/pinpoint/common/util/LongIntIntByteByteStringValue.java
  hbase/hbase-schema-manager/src/main/java/com/navercorp/pinpoint/hbase/manager/ProgramOptions.java
  hbase/hbase-schema/src/main/java/com/navercorp/pinpoint/hbase/schema/reader/core/ChangeSet.java
  hbase/hbase-schema/src/main/java/com/navercorp/pinpoint/hbase/schema/reader/core/ColumnFamilyConfiguration.java
  hbase/hbase-schema/src/main/java/com/navercorp/pinpoint/hbase/schema/reader/core/CreateColumnFamilyChange.java
  hbase/hbase-schema/src/main/java/com/navercorp/pinpoint/hbase/schema/reader/core/CreateTableChange.java
  hbase/hbase-schema/src/main/java/com/navercorp/pinpoint/hbase/schema/reader/core/ModifyTableChange.java
  hbase/hbase-schema/src/main/java/com/navercorp/pinpoint/hbase/schema/reader/core/TableConfiguration.java
  hbase/hbase-schema/src/main/java/com/navercorp/pinpoint/hbase/schema/reader/xml/XmlHbaseSchemaParseResult.java
  metric-module/metric-commons/src/main/java/com/navercorp/pinpoint/metric/common/model/chart/SystemMetricPoint.java
  metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/collector/model/TelegrafMetric.java
  metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/web/model/chart/AgentStatPoint.java
  web/src/main/java/com/navercorp/pinpoint/web/alarm/vo/Rule.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/map/AcceptApplication.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/map/processor/RpcApplication.java
  web/src/main/java/com/navercorp/pinpoint/web/config/ConfigProperties.java
  web/src/main/java/com/navercorp/pinpoint/web/filter/AcceptUrlFilter.java
  web/src/main/java/com/navercorp/pinpoint/web/filter/FilterChain.java
  web/src/main/java/com/navercorp/pinpoint/web/filter/FilterHint.java
  web/src/main/java/com/navercorp/pinpoint/web/filter/RpcHint.java
  web/src/main/java/com/navercorp/pinpoint/web/filter/RpcType.java
  web/src/main/java/com/navercorp/pinpoint/web/filter/agent/AgentFilterFactory.java
  web/src/main/java/com/navercorp/pinpoint/web/filter/agent/DefaultAgentFilter.java
  web/src/main/java/com/navercorp/pinpoint/web/filter/responsetime/DefaultExecutionTypeFilter.java
  web/src/main/java/com/navercorp/pinpoint/web/filter/responsetime/DefaultResponseTimeFilter.java
  web/src/main/java/com/navercorp/pinpoint/web/filter/responsetime/SpanResponseConditionFilter.java
  web/src/main/java/com/navercorp/pinpoint/web/install/model/AgentDownloadInfo.java
  web/src/main/java/com/navercorp/pinpoint/web/scatter/DotGroups.java
  web/src/main/java/com/navercorp/pinpoint/web/service/AgentIdStartTimeKey.java
  web/src/main/java/com/navercorp/pinpoint/web/vo/AgentEvent.java
  web/src/main/java/com/navercorp/pinpoint/web/vo/DurationalAgentEvent.java
  web/src/main/java/com/navercorp/pinpoint/web/vo/agent/AgentInfo.java
  web/src/main/java/com/navercorp/pinpoint/web/vo/chart/Chart.java
  web/src/main/java/com/navercorp/pinpoint/web/vo/scatter/DotAgentInfo.java
  web/src/main/java/com/navercorp/pinpoint/web/vo/stat/chart/agent/AgentStatPoint.java
  web/src/main/java/com/navercorp/pinpoint/web/vo/timeline/inspector/AgentEventMarker.java
  web/src/main/java/com/navercorp/pinpoint/web/vo/timeline/inspector/AgentEventTimeline.java
  web/src/main/java/com/navercorp/pinpoint/web/vo/timeline/inspector/AgentEventTimelineSegment.java
  web/src/main/java/com/navercorp/pinpoint/web/vo/timeline/inspector/AgentStatusTimeline.java
  web/src/main/java/com/navercorp/pinpoint/web/vo/timeline/inspector/AgentStatusTimelineBuilder.java
  web/src/main/java/com/navercorp/pinpoint/web/vo/timeline/inspector/AgentStatusTimelineSegment.java
  web/src/main/java/com/navercorp/pinpoint/web/vo/timeline/inspector/InspectorTimeline.java
Labels: cleanup

#12206 [#12025] Validate applicationName and agentId using StringPrecondition
  batch/src/main/java/com/navercorp/pinpoint/batch/alarm/vo/CheckerResult.java
  batch/src/main/java/com/navercorp/pinpoint/batch/service/AlarmServiceImpl.java
  batch/src/test/java/com/navercorp/pinpoint/batch/alarm/CheckerCategoryTest.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/AgentInfoBo.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/AgentKeyBo.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/SpanBo.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/SpanChunkBo.java
  exceptiontrace/exceptiontrace-collector/src/main/java/com/navercorp/pinpoint/exceptiontrace/collector/entity/ExceptionMetaDataEntity.java
  exceptiontrace/exceptiontrace-common/src/main/java/com/navercorp/pinpoint/exceptiontrace/common/model/ExceptionMetaData.java
  exceptiontrace/exceptiontrace-web/src/main/java/com/navercorp/pinpoint/exceptiontrace/web/entity/ExceptionGroupSummaryEntity.java
  exceptiontrace/exceptiontrace-web/src/main/java/com/navercorp/pinpoint/exceptiontrace/web/entity/ExceptionMetaDataEntity.java
  exceptiontrace/exceptiontrace-web/src/main/java/com/navercorp/pinpoint/exceptiontrace/web/util/ExceptionTraceQueryParameter.java
  exceptiontrace/exceptiontrace-web/src/main/java/com/navercorp/pinpoint/exceptiontrace/web/view/ExceptionDetailView.java
  otlpmetric/otlpmetric-collector/src/main/java/com/navercorp/pinpoint/otlp/collector/model/OtlpMetricData.java
  otlpmetric/otlpmetric-web/src/main/java/com/navercorp/pinpoint/otlp/web/service/OtlpMetricWebServiceImpl.java
  otlpmetric/otlpmetric-web/src/main/java/com/navercorp/pinpoint/otlp/web/vo/OtlpMetricChartQueryParameter.java
  otlpmetric/otlpmetric-web/src/main/java/com/navercorp/pinpoint/otlp/web/vo/OtlpMetricDataQueryParameter.java
  pinot/pinot-batch/src/main/java/com/navercorp/pinpoint/pinot/alarm/vo/PinotAlarmRule.java
  realtime/realtime-common/src/main/java/com/navercorp/pinpoint/realtime/dto/ATCDemand.java
  realtime/realtime-common/src/main/java/com/navercorp/pinpoint/realtime/dto/ATCSupply.java
  uristat/uristat-web/src/main/java/com/navercorp/pinpoint/uristat/web/util/UriStatSummaryQueryParameter.java
  web/src/main/java/com/navercorp/pinpoint/web/alarm/vo/Rule.java
  web/src/main/java/com/navercorp/pinpoint/web/vo/AgentParam.java
  web/src/main/java/com/navercorp/pinpoint/web/vo/ApplicationPair.java
  web/src/main/java/com/navercorp/pinpoint/web/vo/activethread/AgentActiveThreadCount.java
  web/src/main/java/com/navercorp/pinpoint/web/vo/agent/AgentInfo.java
  web/src/main/java/com/navercorp/pinpoint/web/vo/callstacks/RecordSet.java
  web/src/main/java/com/navercorp/pinpoint/web/websocket/WebSocketSessionContext.java
  web/src/test/java/com/navercorp/pinpoint/web/applicationmap/ServerGroupListTest.java
  web/src/test/java/com/navercorp/pinpoint/web/calltree/span/CallTreeTest.java
  webhook/src/main/java/com/navercorp/pinpoint/web/webhook/model/Webhook.java
Labels: cleanup

#12207 [#12159] Enhance heatmap data retrieval by adding min and max Y-axis parameters
  web/src/main/java/com/navercorp/pinpoint/web/authorization/controller/HeatmapChartController.java
  web/src/main/java/com/navercorp/pinpoint/web/heatmap/dao/HeatmapChartDao.java
  web/src/main/java/com/navercorp/pinpoint/web/heatmap/dao/pinot/PinotHeatmapChartDao.java
  web/src/main/java/com/navercorp/pinpoint/web/heatmap/service/EmptyHeatmapService.java
  web/src/main/java/com/navercorp/pinpoint/web/heatmap/service/HeatmapChartService.java
  web/src/main/java/com/navercorp/pinpoint/web/heatmap/service/HeatmapChartServiceImpl.java
  web/src/main/java/com/navercorp/pinpoint/web/heatmap/vo/HeatmapSearchKey.java
  web/src/main/resources/heatmap/web/mapper/pinot/HeatmapWebMapper.xml
  web/src/test/java/com/navercorp/pinpoint/web/heatmap/service/HeatmapChartServiceImplTest.java
Labels: module:web

#12203 [#noissue] Add spring kafka plugin testweb
  agent-module/agent-testweb/pom.xml
  agent-module/agent-testweb/spring-kafka-plugin-testweb/pom.xml
  agent-module/agent-testweb/spring-kafka-plugin-testweb/src/main/java/com/pinpoint/test/plugin/Farewell.java
  agent-module/agent-testweb/spring-kafka-plugin-testweb/src/main/java/com/pinpoint/test/plugin/Greeting.java
  agent-module/agent-testweb/spring-kafka-plugin-testweb/src/main/java/com/pinpoint/test/plugin/Payment.java
  agent-module/agent-testweb/spring-kafka-plugin-testweb/src/main/java/com/pinpoint/test/plugin/SpringKafkaApplication.java
  agent-module/agent-testweb/spring-kafka-plugin-testweb/src/main/java/com/pinpoint/test/plugin/SpringKafkaConsumerConfig.java
  agent-module/agent-testweb/spring-kafka-plugin-testweb/src/main/java/com/pinpoint/test/plugin/SpringKafkaErrorHandler.java
  agent-module/agent-testweb/spring-kafka-plugin-testweb/src/main/java/com/pinpoint/test/plugin/SpringKafkaMultiTypeListener.java
  agent-module/agent-testweb/spring-kafka-plugin-testweb/src/main/java/com/pinpoint/test/plugin/SpringKafkaPluginController.java
  agent-module/agent-testweb/spring-kafka-plugin-testweb/src/main/java/com/pinpoint/test/plugin/SpringKafkaPluginTestConstants.java
  agent-module/agent-testweb/spring-kafka-plugin-testweb/src/main/java/com/pinpoint/test/plugin/SpringKafkaProducerConfig.java
  agent-module/agent-testweb/spring-kafka-plugin-testweb/src/main/java/com/pinpoint/test/plugin/SpringKafkaTopicConfig.java
  agent-module/agent-testweb/spring-kafka-plugin-testweb/src/main/resources/application.yml
  agent-module/agent-testweb/spring-kafka-plugin-testweb/src/main/resources/logback.xml
  agent-module/agent-testweb/spring-kafka-plugin-testweb/src/test/java/com/pinpoint/test/plugin/kafka/SpringKafkaTest.java
Labels: module:test

#12209 [#12208] Add UnsignedByte Util
  collector/src/main/java/com/navercorp/pinpoint/collector/mapper/grpc/GrpcJvmInfoBoMapper.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/AgentLifeCycleBo.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/JvmInfoBo.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/SpanBo.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/SpanChunkBo.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/event/AgentEventBo.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/stat/AgentStatType.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/dao/hbase/mapper/AgentInfoBoMapper.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/util/ByteUtils.java
  commons-server/src/test/java/com/navercorp/pinpoint/common/server/bo/JvmInfoBoTest.java
  commons-server/src/test/java/com/navercorp/pinpoint/common/server/util/ByteUtilsTest.java
  inspector-module/inspector-collector/src/main/java/com/navercorp/pinpoint/inspector/collector/model/kafka/AgentStatField.java
Labels: cleanup

#12211 [#12210] Add size, lastmodified, rollover-strategy-max to logging opt
  agent-module/agent/src/main/resources/log4j2-agent.xml
  agent-module/agent/src/main/resources/log4j2-agent.yaml
Labels: enhancement, module:agent, configuration

#12205 [#noissue] Cleanup
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/util/DefaultTimeSlot.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/util/timewindow/TimePrecision.java
  commons-server/src/test/java/com/navercorp/pinpoint/common/server/util/DefaultTimeSlotTest.java
  commons-server/src/test/java/com/navercorp/pinpoint/common/server/util/timewindow/TimePrecisionTest.java
  exceptiontrace/exceptiontrace-web/src/main/java/com/navercorp/pinpoint/exceptiontrace/web/controller/ExceptionTraceController.java
  inspector-module/inspector-web/src/main/java/com/navercorp/pinpoint/inspector/web/model/InspectorDataSearchKey.java
  inspector-module/inspector-web/src/main/java/com/navercorp/pinpoint/inspector/web/service/DefaultAgentStatService.java
  inspector-module/inspector-web/src/main/java/com/navercorp/pinpoint/inspector/web/service/DefaultApdexStatService.java
  inspector-module/inspector-web/src/main/java/com/navercorp/pinpoint/inspector/web/service/DefaultApplicationStatService.java
  metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/web/util/QueryParameter.java
  otlpmetric/otlpmetric-web/src/main/java/com/navercorp/pinpoint/otlp/web/service/OtlpMetricWebServiceImpl.java
  otlpmetric/otlpmetric-web/src/main/java/com/navercorp/pinpoint/otlp/web/vo/OtlpMetricChartQueryParameter.java
  otlpmetric/otlpmetric-web/src/main/java/com/navercorp/pinpoint/otlp/web/vo/OtlpMetricDataQueryParameter.java
  uristat/uristat-web/src/main/java/com/navercorp/pinpoint/uristat/web/controller/UriStatController.java
  uristat/uristat-web/src/main/java/com/navercorp/pinpoint/uristat/web/util/UriStatSummaryQueryParameter.java
  web/src/main/java/com/navercorp/pinpoint/web/heatmap/vo/HeatmapSearchKey.java
Labels: cleanup

#12213 [#12159] Refactor HeatmapChartController constructor to remove TenantProvider parameter.
  web/src/main/java/com/navercorp/pinpoint/web/authorization/controller/HeatmapChartController.java
Labels: module:web

#12214 [#12159] Improve time range segmentation for elapsedTime in query
  web/src/main/java/com/navercorp/pinpoint/web/authorization/controller/HeatmapChartController.java
  web/src/main/java/com/navercorp/pinpoint/web/heatmap/service/HeatmapChartServiceImpl.java
  web/src/main/java/com/navercorp/pinpoint/web/heatmap/vo/HeatmapSearchKey.java
  web/src/main/resources/heatmap/web/mapper/pinot/HeatmapWebMapper.xml
  web/src/test/java/com/navercorp/pinpoint/web/heatmap/service/HeatmapChartServiceImplTest.java
Labels: module:web

#12219 [#12218] Backport: Update spring kafka container entry point of kafka…
  agent-module/agent/src/main/resources/profiles/local/pinpoint.config
  agent-module/agent/src/main/resources/profiles/release/pinpoint.config
  agent-module/plugins/kafka/README.md
  agent-module/plugins/kafka/src/main/java/com/navercorp/pinpoint/plugin/kafka/KafkaConfig.java
  agent-module/plugins/kafka/src/main/java/com/navercorp/pinpoint/plugin/kafka/KafkaPlugin.java
  agent-module/plugins/kafka/src/main/java/com/navercorp/pinpoint/plugin/kafka/interceptor/ListenerConsumerInvokeErrorHandlerInterceptor.java
Labels: enhancement, module:plugin

#12224 [#12220] Backport: Bump ASM from 9.6 to 9.7.1
  pom.xml
Labels: module:agent, dependencies

#12223 [#12159] Improve the operation of creating buckets from elapsedTime values using interval
  collector/src/main/java/com/navercorp/pinpoint/collector/heatmap/dao/pinot/PinotHeatmapDao.java
  collector/src/main/java/com/navercorp/pinpoint/collector/heatmap/vo/HeatmapStat.java
  collector/src/test/java/com/navercorp/pinpoint/collector/heatmap/vo/HeatmapStatTest.java
  web/src/main/java/com/navercorp/pinpoint/web/heatmap/service/HeatmapChartServiceImpl.java
  web/src/main/resources/heatmap/web/mapper/pinot/HeatmapWebMapper.xml
  web/src/test/java/com/navercorp/pinpoint/web/heatmap/service/HeatmapChartServiceImplTest.java
Labels: module:web

#12227 [#noissue] Add non-null check for agentId for ServerMap
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/util/ApplicationMapStatisticsUtils.java
Labels: cleanup

#12228 [#noissue] Fix long to int for hashBytes
  commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/distributor/RangeOneByteSimpleHash.java
Labels: cleanup

#12230 [#12229] Remove boxing from Annotation types
  agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/context/annotation/BooleanAnnotation.java
  agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/context/annotation/ByteAnnotation.java
  agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/context/annotation/DoubleAnnotation.java
  agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/context/annotation/IntAnnotation.java
  agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/context/annotation/LongAnnotation.java
  agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/context/annotation/ShortAnnotation.java
  agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/context/grpc/mapper/AnnotationValueMapper.java
Labels: enhancement, module:agent

#12232 [#noissue] Refactor ChartGroupBuilder
  web/src/main/java/com/navercorp/pinpoint/web/vo/stat/chart/ChartGroupBuilder.java
  web/src/test/java/com/navercorp/pinpoint/web/vo/stat/chart/ChartGroupBuilderTest.java
Labels: cleanup

#12236 [#12235] Improve windowRangeCount for TimeWindows to be precomputed
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/util/timewindow/TimeWindow.java
  commons-server/src/test/java/com/navercorp/pinpoint/common/server/util/timewindow/TimeWindowTest.java
  metric-module/metric-commons/src/main/java/com/navercorp/pinpoint/metric/common/util/TimeSeriesBuilder.java
  metric-module/metric-commons/src/main/java/com/navercorp/pinpoint/metric/common/util/TimeUtils.java
  metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/web/model/MetricDataSearchKey.java
  metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/web/model/chart/TimeSeriesChartBuilder.java
  metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/web/view/SystemMetricChartSerializer.java
  otlpmetric/otlpmetric-common/src/main/java/com/navercorp/pinpoint/otlp/common/util/TimeSeriesBuilder.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/histogram/AgentTimeHistogram.java
  web/src/main/java/com/navercorp/pinpoint/web/vo/chart/TimeSeriesChartBuilder.java
Labels: enhancement, cleanup

#12239 [#12238] Add virtual TimeseriesWindows to TimeWindow
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/util/timewindow/TimeSeriesIterator.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/util/timewindow/TimeSeriesVirtualList.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/util/timewindow/TimeWindow.java
  commons-server/src/test/java/com/navercorp/pinpoint/common/server/util/timewindow/TimeSeriesVirtualListTest.java
  commons-server/src/test/java/com/navercorp/pinpoint/common/server/util/timewindow/TimeWindowTest.java
  exceptiontrace/exceptiontrace-web/src/main/java/com/navercorp/pinpoint/exceptiontrace/web/util/TimeSeriesUtils.java
  inspector-module/inspector-web/src/main/java/com/navercorp/pinpoint/inspector/web/service/DefaultAgentStatService.java
  inspector-module/inspector-web/src/main/java/com/navercorp/pinpoint/inspector/web/service/DefaultApplicationStatService.java
  metric-module/metric-commons/src/main/java/com/navercorp/pinpoint/metric/common/util/TimeUtils.java
  metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/web/service/SystemMetricDataServiceImpl.java
  metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/web/view/SystemMetricChartSerializer.java
  otlpmetric/otlpmetric-web/src/main/java/com/navercorp/pinpoint/otlp/web/service/OtlpMetricWebServiceImpl.java
  uristat/uristat-web/src/main/java/com/navercorp/pinpoint/uristat/web/view/UriStatView.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/histogram/AgentTimeHistogram.java
  web/src/test/java/com/navercorp/pinpoint/web/vo/ResponseHistogramsTest.java
Labels: enhancement

#12242 [#12241] Apply Primitive Containers to optimize memory usage
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/scatter/OneByteFuzzyRowKeyFactory.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/util/array/DoubleArray.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/util/array/IntArray.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/util/array/LongArray.java
  commons-server/src/test/java/com/navercorp/pinpoint/common/server/util/array/DoubleArrayTest.java
  commons-server/src/test/java/com/navercorp/pinpoint/common/server/util/array/LongArrayTest.java
  exceptiontrace/exceptiontrace-collector/src/main/java/com/navercorp/pinpoint/exceptiontrace/collector/mapper/StackTraceMapper.java
  inspector-module/inspector-web/src/main/java/com/navercorp/pinpoint/inspector/web/definition/metric/AvgUsingIntervalPostProcessor.java
  inspector-module/inspector-web/src/main/java/com/navercorp/pinpoint/inspector/web/definition/metric/PercentageScalePostProcessor.java
  inspector-module/inspector-web/src/main/java/com/navercorp/pinpoint/inspector/web/service/DefaultAgentStatService.java
  inspector-module/inspector-web/src/main/java/com/navercorp/pinpoint/inspector/web/service/DefaultApdexStatService.java
  inspector-module/inspector-web/src/main/java/com/navercorp/pinpoint/inspector/web/service/DefaultApplicationStatService.java
  otlpmetric/otlpmetric-web/src/main/java/com/navercorp/pinpoint/otlp/web/view/legacy/OtlpChartViewBuilder.java
  otlpmetric/otlpmetric-web/src/main/java/com/navercorp/pinpoint/otlp/web/vo/MetricData.java
  otlpmetric/otlpmetric-web/src/test/java/com/navercorp/pinpoint/otlp/web/view/OtlpChartViewTest.java
  uristat/uristat-web/src/main/java/com/navercorp/pinpoint/uristat/web/model/UriStatGroup.java
  uristat/uristat-web/src/main/java/com/navercorp/pinpoint/uristat/web/view/UriStatView.java
  web/src/main/java/com/navercorp/pinpoint/web/view/histogram/TimeHistogramChartBuilder.java
Labels: enhancement

#12243 [#noissue] Remove unused SystemMetricChart
  metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/web/model/chart/AgentStatPoint.java
  metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/web/model/chart/AgentStatPointSerializer.java
  metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/web/model/chart/Chart.java
  metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/web/model/chart/CollectedMetricData.java
  metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/web/model/chart/Sampler.java
  metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/web/model/chart/SystemMetricChart.java
  metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/web/model/chart/TimeSeriesChartBuilder.java
  metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/web/model/chart/UncollectedPointCreatorFactory.java
  metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/web/view/SystemMetricChartSerializer.java
  metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/web/view/SystemMetricDataSerializer.java
  metric-module/metric/src/test/java/com/navercorp/pinpoint/metric/web/model/chart/SystemMetricChartTest.java
Labels: cleanup

#12245 [#12244] Add MetricCollectorProperties for configurable cache size
  metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/collector/MetricAppPropertySources.java
  metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/collector/MetricCollectorApp.java
  metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/collector/cache/MetricCacheConfiguration.java
  metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/collector/config/MetricCollectorProperties.java
  metric-module/metric/src/main/resources/pinot-collector/profiles/local/collector-metric.properties
  metric-module/metric/src/main/resources/pinot-collector/profiles/release/collector-metric.properties
Labels: enhancement, module:metric

#12233 [#noissue] Simplify StatPoint creation
  inspector-module/inspector-web/src/main/java/com/navercorp/pinpoint/inspector/web/service/DefaultApdexStatService.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/histogram/AgentTimeHistogram.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/histogram/ApdexScore.java
  web/src/main/java/com/navercorp/pinpoint/web/service/ApdexScoreServiceImpl.java
  web/src/main/java/com/navercorp/pinpoint/web/view/AgentStatPointSerializer.java
  web/src/main/java/com/navercorp/pinpoint/web/view/DoubleApplicationStatSerializer.java
  web/src/main/java/com/navercorp/pinpoint/web/vo/chart/UncollectedPointCreatorFactory.java
  web/src/main/java/com/navercorp/pinpoint/web/vo/stat/SampledApdexScore.java
  web/src/main/java/com/navercorp/pinpoint/web/vo/stat/chart/agent/AgentApdexScoreChart.java
  web/src/main/java/com/navercorp/pinpoint/web/vo/stat/chart/agent/AgentStatPoint.java
  web/src/main/java/com/navercorp/pinpoint/web/vo/stat/chart/agent/AgentStatPointSummary.java
  web/src/main/java/com/navercorp/pinpoint/web/vo/stat/chart/agent/DefaultAgentChart.java
  web/src/main/java/com/navercorp/pinpoint/web/vo/stat/chart/agent/DefaultAgentChartType.java
  web/src/main/java/com/navercorp/pinpoint/web/vo/stat/chart/application/ApplicationApdexScoreChart.java
  web/src/main/java/com/navercorp/pinpoint/web/vo/stat/chart/application/ApplicationStatPoint.java
  web/src/main/java/com/navercorp/pinpoint/web/vo/stat/chart/application/DefaultApplicationChart.java
  web/src/main/java/com/navercorp/pinpoint/web/vo/stat/chart/application/DoubleApplicationStatPoint.java
  web/src/test/java/com/navercorp/pinpoint/web/applicationmap/histogram/AgentTimeHistogramTest.java
  web/src/test/java/com/navercorp/pinpoint/web/vo/stat/chart/ChartGroupBuilderTest.java
Labels: module:web, cleanup
