Repository pinpoint-apm/pinpoint, pull requests merged in 2025-08, with the labels that each got.

#12732 [#noissue] Add serviceInfosString to use text_match in pinot
  agent-statistics/agent-statistics-collector/src/main/java/com/navercorp/pinpoint/agentstatistics/collector/entity/AgentInfoEntity.java
  agent-statistics/agent-statistics-collector/src/main/java/com/navercorp/pinpoint/agentstatistics/collector/mapper/AgentInfoMapper.java
Labels: module:collector

#12733 [#noissue] Cleanup
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/dao/mapper/ApplicationResponseTimeResultExtractor.java
Labels: cleanup

#12735 [#noissue] Memory Optimization of DistributedScanner
  commons-buffer/src/main/java/com/navercorp/pinpoint/common/buffer/ByteArrayUtils.java
  commons-buffer/src/test/java/com/navercorp/pinpoint/common/buffer/ByteArrayUtilsTest.java
  commons-hbase/pom.xml
  commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/HbaseTemplate.java
  commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/async/HbaseAsyncTemplate.java
  commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/parallel/ParallelResultScanner.java
  commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/parallel/ScanTask.java
  commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/parallel/ScanTaskConfig.java
  commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/wd/DistributedScanner.java
Labels: enhancement

#12736 [#noissue] Refactor HbaseApplicationTraceIndexDao
  web/src/main/java/com/navercorp/pinpoint/web/dao/hbase/HbaseApplicationTraceIndexDao.java
Labels: cleanup

#12712 [#12711] Update collector kafka max.block.ms option
  pinot/pinot-kafka/src/main/java/com/navercorp/pinpoint/pinot/kafka/KafkaConfiguration.java
  pinot/pinot-kafka/src/main/java/com/navercorp/pinpoint/pinot/kafka/KafkaProperties.java
  pinot/pinot-kafka/src/main/resources/profiles/local/kafka-producer-factory.properties
  pinot/pinot-kafka/src/test/java/com/navercorp/pinpoint/pinot/kafka/KafkaConfigurationTest.java
Labels: enhancement, module:collector

#12737 [#noissue] Refactor Rowkey handling
  commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/HbaseTemplate.java
  commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/async/HbaseAsyncTemplate.java
  commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/parallel/ParallelResultScanner.java
  commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/wd/DistributedScanner.java
  commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/wd/RowKeyDistributor.java
  commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/wd/RowKeyDistributorByHashPrefix.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/serializer/metadata/MetadataDecoder.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/serializer/metadata/MetadataEncoder.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/serializer/metadata/uid/UidMetadataDecoder.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/serializer/metadata/uid/UidMetadataEncoder.java
  commons-server/src/test/java/com/navercorp/pinpoint/common/server/bo/serializer/metadata/MetadataEncoderTest.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/dao/mapper/ApplicationResponseTimeResultExtractor.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/dao/mapper/InLinkMapper.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/dao/mapper/OutLinkMapper.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/dao/mapper/ResponseTimeMapper.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/dao/mapper/ResponseTimeResultExtractor.java
  web/src/main/java/com/navercorp/pinpoint/web/dao/hbase/HbaseApplicationTraceIndexDao.java
  web/src/main/java/com/navercorp/pinpoint/web/mapper/ApiMetaDataMapper.java
  web/src/main/java/com/navercorp/pinpoint/web/mapper/SqlMetaDataMapper.java
  web/src/main/java/com/navercorp/pinpoint/web/mapper/SqlUidMetaDataMapper.java
  web/src/main/java/com/navercorp/pinpoint/web/mapper/StringMetaDataMapper.java
  web/src/test/java/com/navercorp/pinpoint/web/mapper/ApiMetaDataMapperTest.java
Labels: cleanup

#12741 [#12740] Bump hbase-client from 2.5.11-hadoop3 to 2.5.12-hadoop3
  pom.xml
Labels: dependencies

#12743 [#noissue] Not use ApplicationValidator with nodeKey
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/config/ApplicationMapModule.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/controller/ServerMapHistogramController.java
Labels: module:web

#12747 [#noissue] Add SearchOptionForm for search parameters in application map
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/controller/MapController.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/controller/ServerMapHistogramController.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/controller/form/SearchDepthForm.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/controller/form/SearchOptionForm.java
Labels: cleanup

#12765 [#12764] Fix collector parent application name NPE
  collector/src/main/java/com/navercorp/pinpoint/collector/service/HbaseTraceService.java
Labels: bug, module:collector

#12767 [#noissue] Add new linkKey to further api call
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/link/Link.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/link/LinkName.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/view/LinkView.java
Labels: module:web

#12779 [#noissue] Simplify minimap in uristats
  uristat/uristat-web/src/main/java/com/navercorp/pinpoint/uristat/web/config/UriRegistryHandler.java
  uristat/uristat-web/src/main/java/com/navercorp/pinpoint/uristat/web/dao/PinotTotalCountChartDao.java
  uristat/uristat-web/src/main/java/com/navercorp/pinpoint/uristat/web/entity/UriHistogramEntity.java
  uristat/uristat-web/src/main/java/com/navercorp/pinpoint/uristat/web/entity/UriHistogramFailEntity.java
  uristat/uristat-web/src/main/java/com/navercorp/pinpoint/uristat/web/entity/UriHistogramTotalEntity.java
  uristat/uristat-web/src/main/java/com/navercorp/pinpoint/uristat/web/entity/UriStatChartEntity.java
  uristat/uristat-web/src/main/java/com/navercorp/pinpoint/uristat/web/mapper/EntityToModelMapper.java
  uristat/uristat-web/src/main/resources/mapper/uristat/UriStatChartMapper.xml
  uristat/uristat-web/src/main/resources/mapper/uristat/UriStatSummaryMapper.xml
  uristat/uristat-web/src/test/java/com/navercorp/pinpoint/uristat/web/mapper/EntityToModelMapperTest.java
Labels: module:web

#12784 [#noissue] Fix ci resttemplate it
  agent-module/plugins/resttemplate/src/main/java/com/navercorp/pinpoint/plugin/resttemplate/interceptor/AsyncHttpRequestInterceptor.java
Labels: Continuous Integration

#12791 [#12790] Bump zstd-jni from 1.5.5-11 to 1.5.7-4
  pom.xml
Labels: dependencies

#12792 Revert "[#noissue] Simplify minimap in uristats"
  uristat/uristat-web/src/main/java/com/navercorp/pinpoint/uristat/web/config/UriRegistryHandler.java
  uristat/uristat-web/src/main/java/com/navercorp/pinpoint/uristat/web/dao/PinotTotalCountChartDao.java
  uristat/uristat-web/src/main/java/com/navercorp/pinpoint/uristat/web/entity/UriHistogramEntity.java
  uristat/uristat-web/src/main/java/com/navercorp/pinpoint/uristat/web/entity/UriHistogramFailEntity.java
  uristat/uristat-web/src/main/java/com/navercorp/pinpoint/uristat/web/entity/UriHistogramTotalEntity.java
  uristat/uristat-web/src/main/java/com/navercorp/pinpoint/uristat/web/entity/UriStatChartEntity.java
  uristat/uristat-web/src/main/java/com/navercorp/pinpoint/uristat/web/mapper/EntityToModelMapper.java
  uristat/uristat-web/src/main/resources/mapper/uristat/UriStatChartMapper.xml
  uristat/uristat-web/src/main/resources/mapper/uristat/UriStatSummaryMapper.xml
  uristat/uristat-web/src/test/java/com/navercorp/pinpoint/uristat/web/mapper/EntityToModelMapperTest.java
Labels: module:web

#12794 [#12793] Bump HikariCP from 5.0.1 to 7.0.1
  pom.xml
Labels: dependencies

#12796 [#12795] Bump log4j from 2.24.2 to 2.25.1
  pom.xml
Labels: dependencies

#12802 [#noissue] Extract HbaseTable interface for adding tables
  commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/HbaseTable.java
  commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/HbaseTableV2.java
  commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/HbaseTables.java
  commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/config/AsyncWarmup.java
  commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/config/Warmup.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/dao/hbase/HbaseHostApplicationMapDao.java
Labels: cleanup

#12813 [#12811] Update collector reactor hook onErrorDropped
  collector/src/main/java/com/navercorp/pinpoint/collector/grpc/CollectorGrpcConfiguration.java
  collector/src/main/java/com/navercorp/pinpoint/collector/grpc/config/GrpcErrorHandleConfiguration.java
Labels: enhancement, module:collector

#12824 [#12823] Bump grpc from 1.74.0 to 1.75.0
  pom.xml
Labels: dependencies

#12826 [#12825] Bump netty from 4.1.110.Final to 4.1.124.Final
  pom.xml
Labels: dependencies

#12834 [#12833] Bump httpclient5 from 5.2.3 to 5.4.4
  pom.xml
Labels: dependencies

#12838 [#12837] Bump spring-data from 3.3.12 to 3.5.3
  pinot/pinot-datasource/pom.xml
  pom.xml
Labels: dependencies

#12836 [#noissue] Fix @TransactionalEventListener to @EventListener
  webhook/src/main/java/com/navercorp/pinpoint/web/webhook/service/WebhookAlarmServiceImpl.java
Labels: bug

#12840 [#12839] Bump spring-security from 6.4.6 to 6.5.3
  pom.xml
Labels: dependencies

#12841 [#12842] Bump spring-retry from 2.0.6 to 2.0.12
  batch/src/main/java/com/navercorp/pinpoint/batch/alarm/dao/pinot/PinotAlarmDao.java
  pom.xml
Labels: dependencies

#12848 [#12847] Bump spring-security-rsa from 1.0.13.RELEASE to 1.1.5
  pom.xml
Labels: dependencies

#12846 [#12845] Bump opentelemetry from 1.46.0 to 1.53.0
  commons-hbase/pom.xml
  pom.xml
Labels: dependencies
