Repository pinpoint-apm/pinpoint, pull requests merged in 2025-04, with the labels that each got.

#12248 [#12244] Change the distribution key of the systemMetricTag table
  metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/collector/dao/pinot/PinotMetricTagDao.java
Labels: module:metric

#12255 [#noissue] Refactor MetricPoint for improve memory efficiency
  otlpmetric/otlpmetric-common/src/main/java/com/navercorp/pinpoint/otlp/common/model/AggreTemporality.java
  otlpmetric/otlpmetric-common/src/main/java/com/navercorp/pinpoint/otlp/common/model/DoubleMetricPoint.java
  otlpmetric/otlpmetric-common/src/main/java/com/navercorp/pinpoint/otlp/common/model/LongMetricPoint.java
  otlpmetric/otlpmetric-common/src/main/java/com/navercorp/pinpoint/otlp/common/model/MetricPoint.java
  otlpmetric/otlpmetric-common/src/main/java/com/navercorp/pinpoint/otlp/common/util/DoubleUncollectedDataCreator.java
  otlpmetric/otlpmetric-common/src/main/java/com/navercorp/pinpoint/otlp/common/util/MetricPoints.java
  otlpmetric/otlpmetric-common/src/main/java/com/navercorp/pinpoint/otlp/common/util/TimeSeriesBuilder.java
  otlpmetric/otlpmetric-web/src/main/java/com/navercorp/pinpoint/otlp/web/config/pinot/OtlpMetricPinotRegistryHandler.java
  otlpmetric/otlpmetric-web/src/main/java/com/navercorp/pinpoint/otlp/web/service/OtlpMetricWebServiceImpl.java
  otlpmetric/otlpmetric-web/src/main/resources/otlpmetric/web/mapper/pinot/OtlpMetricMapper.xml
Labels: cleanup

#12258 [#12159] Create TimeSeriesBuilder for generating response data
  web/src/main/java/com/navercorp/pinpoint/web/heatmap/service/HeatmapChartServiceImpl.java
  web/src/main/java/com/navercorp/pinpoint/web/heatmap/util/TimeSeriesBuilder.java
  web/src/main/java/com/navercorp/pinpoint/web/heatmap/vo/ElapsedTimeBucketInfo.java
  web/src/main/java/com/navercorp/pinpoint/web/heatmap/vo/HeatMapData.java
  web/src/main/java/com/navercorp/pinpoint/web/heatmap/vo/HeatMapMetricCell.java
  web/src/main/java/com/navercorp/pinpoint/web/heatmap/vo/HeatMapMetricColumn.java
  web/src/main/java/com/navercorp/pinpoint/web/heatmap/vo/HeatmapSearchKey.java
  web/src/main/java/com/navercorp/pinpoint/web/heatmap/vo/HeatmapSize.java
  web/src/test/java/com/navercorp/pinpoint/web/heatmap/service/HeatmapChartServiceImplTest.java
  web/src/test/java/com/navercorp/pinpoint/web/heatmap/util/TimeSeriesBuilderTest.java
Labels: module:web

#12257 [#noissue] Refactor QueryParameter
  exceptiontrace/exceptiontrace-web/src/main/java/com/navercorp/pinpoint/exceptiontrace/web/util/ExceptionTraceQueryParameter.java
  metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/web/util/QueryParameter.java
  otlpmetric/otlpmetric-web/src/main/java/com/navercorp/pinpoint/otlp/web/vo/OtlpMetricChartQueryParameter.java
  otlpmetric/otlpmetric-web/src/main/java/com/navercorp/pinpoint/otlp/web/vo/OtlpMetricDataQueryParameter.java
  uristat/uristat-web/src/main/java/com/navercorp/pinpoint/uristat/web/util/UriStatChartQueryParameter.java
  uristat/uristat-web/src/main/java/com/navercorp/pinpoint/uristat/web/util/UriStatSummaryQueryParameter.java
Labels: cleanup

#12259 [#noissue] Refactor QueryParameter
  uristat/uristat-web/src/main/java/com/navercorp/pinpoint/uristat/web/mapper/MapperUtils.java
  uristat/uristat-web/src/test/java/com/navercorp/pinpoint/uristat/web/mapper/MapperUtilsTest.java
Labels: cleanup

#12260 [#noissue] Refactor AsyncQueueingUriStatStorage to use UriTransformer for improved URI handling
  agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/context/provider/UriStatStorageProvider.java
  agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/context/storage/AsyncQueueingUriStatStorage.java
  agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/context/storage/UriMethodTransformer.java
  agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/context/storage/UriOnlyTransformer.java
  agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/context/storage/UriTransformer.java
  agent-module/profiler/src/test/java/com/navercorp/pinpoint/profiler/context/storage/AsyncQueueingUriStatStorageTest.java
  agent-module/profiler/src/test/java/com/navercorp/pinpoint/profiler/context/storage/UriMethodTransformerTest.java
Labels: cleanup

#12262 [#noisie] Improved debuggability of TimeSeriesVirtualList
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/util/timewindow/TimeSeriesVirtualList.java
  commons-server/src/test/java/com/navercorp/pinpoint/common/server/util/timewindow/TimeSeriesVirtualListTest.java
Labels: cleanup

#12266 [#12265] Update the entry point for kafka stream
  agent-module/agent-testweb/spring-kafka-plugin-testweb/pom.xml
  agent-module/agent-testweb/spring-kafka-plugin-testweb/src/main/java/com/pinpoint/test/plugin/KafkaStreamsConfig.java
  agent-module/agent-testweb/spring-kafka-plugin-testweb/src/main/java/com/pinpoint/test/plugin/SpringKafkaApplication.java
  agent-module/agent-testweb/spring-kafka-plugin-testweb/src/main/java/com/pinpoint/test/plugin/SpringKafkaPluginController.java
  agent-module/agent-testweb/spring-kafka-plugin-testweb/src/main/java/com/pinpoint/test/plugin/SpringKafkaPluginTestConstants.java
  agent-module/agent-testweb/spring-kafka-plugin-testweb/src/main/java/com/pinpoint/test/plugin/SpringKafkaStreamConsumer.java
  agent-module/agent/src/main/resources/profiles/local/pinpoint.config
  agent-module/agent/src/main/resources/profiles/release/pinpoint.config
  agent-module/plugins/kafka/README.md
  agent-module/plugins/kafka/src/main/java/com/navercorp/pinpoint/plugin/kafka/KafkaConfig.java
  agent-module/plugins/kafka/src/main/java/com/navercorp/pinpoint/plugin/kafka/KafkaPlugin.java
  agent-module/plugins/kafka/src/main/java/com/navercorp/pinpoint/plugin/kafka/field/getter/StampedRecordGetter.java
  agent-module/plugins/kafka/src/main/java/com/navercorp/pinpoint/plugin/kafka/interceptor/RecordDeserializerInterceptor.java
  agent-module/plugins/kafka/src/main/java/com/navercorp/pinpoint/plugin/kafka/interceptor/StreamTaskDoProcessInterceptor.java
  agent-module/plugins/kafka/src/main/java/com/navercorp/pinpoint/plugin/kafka/util/KafkaRequestAdaptor.java
Labels: enhancement, module:plugin

#12264 [#noissue] Cleanup TimeWindowSampler
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/util/timewindow/FixedTimeWindowSampler.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/util/timewindow/TimeWindow.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/util/timewindow/TimeWindowDownSampler.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/util/timewindow/TimeWindowOneMinuteSampler.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/util/timewindow/TimeWindowSampler.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/util/timewindow/TimeWindowSlotCentricSampler.java
  commons-server/src/test/java/com/navercorp/pinpoint/common/server/util/timewindow/TimeWindowSlotCentricSamplerTest.java
  commons-server/src/test/java/com/navercorp/pinpoint/common/server/util/timewindow/TimeWindowTest.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/rawdata/LinkCallData.java
  web/src/test/java/com/navercorp/pinpoint/web/vo/chart/TimeSeriesChartBuilderTest.java
Labels: cleanup

#12268 [#noissue] Refactor Array utility
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/util/array/DoubleArray.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/util/array/IntArray.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/util/array/LongArray.java
Labels: cleanup

#12270 [#noissue] Refactor metric point classes
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/stat/DataPoint.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/timeseries/Point.java
  inspector-module/inspector-web/src/main/java/com/navercorp/pinpoint/inspector/web/definition/metric/field/DeltaProcessor.java
  inspector-module/inspector-web/src/main/java/com/navercorp/pinpoint/inspector/web/service/AgentWarningStatServiceImpl.java
  inspector-module/inspector-web/src/main/java/com/navercorp/pinpoint/inspector/web/service/DefaultApdexStatService.java
  inspector-module/inspector-web/src/main/java/com/navercorp/pinpoint/inspector/web/service/DefaultApplicationStatService.java
  metric-module/metric-commons/src/main/java/com/navercorp/pinpoint/metric/common/model/chart/AbstractSystemMetricPoint.java
  metric-module/metric-commons/src/main/java/com/navercorp/pinpoint/metric/common/model/chart/AvgMinMaxMetricPoint.java
  metric-module/metric-commons/src/main/java/com/navercorp/pinpoint/metric/common/model/chart/AvgMinMetricPoint.java
  metric-module/metric-commons/src/main/java/com/navercorp/pinpoint/metric/common/model/chart/DoubleSystemMetricPoint.java
  metric-module/metric-commons/src/main/java/com/navercorp/pinpoint/metric/common/model/chart/LongSystemMetricPoint.java
  metric-module/metric-commons/src/main/java/com/navercorp/pinpoint/metric/common/model/chart/MinMaxMetricPoint.java
  metric-module/metric-commons/src/main/java/com/navercorp/pinpoint/metric/common/model/chart/Point.java
  metric-module/metric-commons/src/main/java/com/navercorp/pinpoint/metric/common/model/chart/SystemMetricPoint.java
  metric-module/metric-commons/src/main/java/com/navercorp/pinpoint/metric/common/util/TimeSeriesBuilder.java
  otlpmetric/otlpmetric-common/src/main/java/com/navercorp/pinpoint/otlp/common/model/DoubleMetricPoint.java
  otlpmetric/otlpmetric-common/src/main/java/com/navercorp/pinpoint/otlp/common/model/LongMetricPoint.java
  otlpmetric/otlpmetric-common/src/main/java/com/navercorp/pinpoint/otlp/common/model/MetricPoint.java
  otlpmetric/otlpmetric-common/src/main/java/com/navercorp/pinpoint/otlp/common/util/TimeSeriesBuilder.java
  uristat/uristat-web/src/main/java/com/navercorp/pinpoint/uristat/web/model/UriStatChartValue.java
  web/src/main/java/com/navercorp/pinpoint/web/vo/chart/Chart.java
  web/src/main/java/com/navercorp/pinpoint/web/vo/chart/TimeSeriesChartBuilder.java
  web/src/main/java/com/navercorp/pinpoint/web/vo/stat/chart/ChartGroupBuilder.java
  web/src/main/java/com/navercorp/pinpoint/web/vo/stat/chart/StatChart.java
  web/src/main/java/com/navercorp/pinpoint/web/vo/stat/chart/StatChartGroup.java
  web/src/main/java/com/navercorp/pinpoint/web/vo/stat/chart/agent/AgentStatPoint.java
  web/src/main/java/com/navercorp/pinpoint/web/vo/stat/chart/application/ApplicationStatPoint.java
  web/src/main/java/com/navercorp/pinpoint/web/vo/stat/chart/application/DefaultStatChartGroup.java
  web/src/test/java/com/navercorp/pinpoint/web/applicationmap/histogram/AgentTimeHistogramTest.java
  web/src/test/java/com/navercorp/pinpoint/web/vo/chart/TimeSeriesChartBuilderTest.java
Labels: cleanup

#12274 [#noissue] Cleanup Point initialization
  commons-timeseries/src/main/java/com/navercorp/pinpoint/common/timeseries/window/TimeWindows.java
  metric-module/metric-commons/src/main/java/com/navercorp/pinpoint/metric/common/util/TimeSeriesBuilder.java
  otlpmetric/otlpmetric-common/src/main/java/com/navercorp/pinpoint/otlp/common/util/TimeSeriesBuilder.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/histogram/AgentTimeHistogram.java
  web/src/main/java/com/navercorp/pinpoint/web/vo/chart/TimeSeriesChartBuilder.java
Labels: cleanup

#12275 [#noissue] Refactor AgentUriStatBo
  collector/src/main/java/com/navercorp/pinpoint/collector/mapper/grpc/stat/GrpcAgentUriStatMapper.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/stat/AgentUriStatBo.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/stat/EachUriStatBo.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/stat/UriStatHistogram.java
  commons-server/src/test/java/com/navercorp/pinpoint/common/server/bo/codec/stat/CodecTestConfig.java
  commons-server/src/test/java/com/navercorp/pinpoint/common/server/bo/codec/stat/TestAgentStatDataPointFactory.java
  commons-server/src/test/java/com/navercorp/pinpoint/common/server/bo/codec/stat/TestAgentStatFactory.java
  uristat/uristat-collector/src/main/java/com/navercorp/pinpoint/uristat/collector/model/UriStat.java
  uristat/uristat-collector/src/main/java/com/navercorp/pinpoint/uristat/collector/service/PinotAgentUriStatService.java
Labels: cleanup

#12276 [#noissue] Cleanup InspectorMetric
  collector/src/main/java/com/navercorp/pinpoint/collector/mapper/grpc/stat/GrpcActiveTraceBoMapper.java
  collector/src/main/java/com/navercorp/pinpoint/collector/mapper/grpc/stat/GrpcCpuLoadBoMapper.java
  collector/src/main/java/com/navercorp/pinpoint/collector/mapper/grpc/stat/GrpcDataSourceBoMapper.java
  collector/src/main/java/com/navercorp/pinpoint/collector/mapper/grpc/stat/GrpcDeadlockThreadCountBoMapper.java
  collector/src/main/java/com/navercorp/pinpoint/collector/mapper/grpc/stat/GrpcDirectBufferBoMapper.java
  collector/src/main/java/com/navercorp/pinpoint/collector/mapper/grpc/stat/GrpcFileDescriptorBoMapper.java
  collector/src/main/java/com/navercorp/pinpoint/collector/mapper/grpc/stat/GrpcJvmGcBoMapper.java
  collector/src/main/java/com/navercorp/pinpoint/collector/mapper/grpc/stat/GrpcJvmGcDetailedBoMapper.java
  collector/src/main/java/com/navercorp/pinpoint/collector/mapper/grpc/stat/GrpcLoadedClassBoMapper.java
  collector/src/main/java/com/navercorp/pinpoint/collector/mapper/grpc/stat/GrpcResponseTimeBoMapper.java
  collector/src/main/java/com/navercorp/pinpoint/collector/mapper/grpc/stat/GrpcTotalThreadCountBoMapper.java
  collector/src/main/java/com/navercorp/pinpoint/collector/mapper/grpc/stat/GrpcTransactionBoMapper.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/stat/ActiveTraceBo.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/stat/AgentStatBo.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/stat/AgentStatDataPointList.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/stat/CpuLoadBo.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/stat/DataSourceBo.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/stat/DataSourceListBo.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/stat/DeadlockThreadCountBo.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/stat/DirectBufferBo.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/stat/FileDescriptorBo.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/stat/JvmGcBo.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/stat/JvmGcDetailedBo.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/stat/LoadedClassBo.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/stat/ResponseTimeBo.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/stat/TotalThreadCountBo.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/stat/TransactionBo.java
  web/src/test/java/com/navercorp/pinpoint/web/test/util/DataSourceTestUtils.java
Labels: cleanup

#12277 [#12159] Add heatmap visualization configuration to properties
  web/src/main/resources/pinpoint-web-root.properties
Labels: module:web

#12279 [#noissue] Cleanup TableNameManager
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/metric/dao/TableNameManager.java
Labels: cleanup

#12278 [#noissue] Refactor AgentStatService
  inspector-module/inspector-collector/src/main/java/com/navercorp/pinpoint/inspector/collector/InspectorCollectorConfig.java
  inspector-module/inspector-collector/src/main/java/com/navercorp/pinpoint/inspector/collector/dao/AgentStatDao.java
  inspector-module/inspector-collector/src/main/java/com/navercorp/pinpoint/inspector/collector/dao/pinot/DefaultAgentStatDao.java
  inspector-module/inspector-collector/src/main/java/com/navercorp/pinpoint/inspector/collector/dao/pinot/PinotDaoConfiguration.java
  inspector-module/inspector-collector/src/main/java/com/navercorp/pinpoint/inspector/collector/dao/pinot/PinotTypeMapper.java
  inspector-module/inspector-collector/src/main/java/com/navercorp/pinpoint/inspector/collector/model/kafka/AgentStat.java
  inspector-module/inspector-collector/src/main/java/com/navercorp/pinpoint/inspector/collector/model/kafka/AgentStatBuilder.java
  inspector-module/inspector-collector/src/main/java/com/navercorp/pinpoint/inspector/collector/model/kafka/AgentStatModelConverter.java
  inspector-module/inspector-collector/src/main/java/com/navercorp/pinpoint/inspector/collector/model/kafka/ApplicationStat.java
  inspector-module/inspector-collector/src/main/java/com/navercorp/pinpoint/inspector/collector/model/kafka/ApplicationStatModelConverter.java
  inspector-module/inspector-collector/src/main/java/com/navercorp/pinpoint/inspector/collector/service/PinotAgentStatService.java
  inspector-module/inspector-collector/src/main/java/com/navercorp/pinpoint/inspector/collector/service/PinotMappers.java
Labels: module:collector, cleanup

#12281 [#12280] Bump hbase-client from 2.5.10 to 2.5.11
  pom.xml
Labels: dependencies

#12282 [#noissue] Cleanup
  inspector-module/inspector-collector/src/main/java/com/navercorp/pinpoint/inspector/collector/service/PinotMappers.java
  inspector-module/inspector-collector/src/main/resources/log4j2-test.xml
  inspector-module/inspector-collector/src/test/java/com/navercorp/pinpoint/inspector/collector/service/PinotMappersTest.java
Labels: cleanup

#12284 [#12159] Change sort key combination to improve query performance
  collector/src/main/java/com/navercorp/pinpoint/collector/heatmap/dao/pinot/PinotHeatmapDao.java
  collector/src/main/java/com/navercorp/pinpoint/collector/heatmap/util/HashmapSortKeyUtils.java
  collector/src/main/java/com/navercorp/pinpoint/collector/heatmap/vo/HeatmapStat.java
  collector/src/main/resources/heatmap/collector/profiles/local/heatmap-collector.properties
  collector/src/main/resources/heatmap/collector/profiles/release/heatmap-collector.properties
  web/src/main/java/com/navercorp/pinpoint/web/authorization/controller/HeatmapChartController.java
  web/src/main/java/com/navercorp/pinpoint/web/heatmap/service/EmptyHeatmapService.java
  web/src/main/java/com/navercorp/pinpoint/web/heatmap/service/HeatmapChartService.java
  web/src/main/java/com/navercorp/pinpoint/web/heatmap/service/HeatmapChartServiceImpl.java
  web/src/main/java/com/navercorp/pinpoint/web/heatmap/vo/HeatmapSearchKey.java
Labels: module:collector, module:web

#12288 [#12287] Bump SpotBugs from 4.7.3.6 to 4.9.3.0
  pom.xml
Labels: dependencies

#12289 [#noissue] Cleanup PinotMetricMetaDataDao
  otlpmetric/otlpmetric-web/src/main/java/com/navercorp/pinpoint/otlp/web/dao/pinot/PinotMetricMetaDataDao.java
Labels: cleanup

#12290 [#noissue] Refactor LinkData
  batch/src/test/java/com/navercorp/pinpoint/batch/alarm/checker/ErrorCountToCalleCheckerTest.java
  batch/src/test/java/com/navercorp/pinpoint/batch/alarm/checker/ErrorRateToCalleCheckerTest.java
  batch/src/test/java/com/navercorp/pinpoint/batch/alarm/checker/SlowCountToCalleCheckerTest.java
  batch/src/test/java/com/navercorp/pinpoint/batch/alarm/checker/SlowRateToCalleCheckerTest.java
  batch/src/test/java/com/navercorp/pinpoint/batch/alarm/checker/TotalCountToCalleeCheckerTest.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/map/VirtualLinkMarker.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/map/processor/RpcCallProcessor.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/rawdata/LinkData.java
Labels: module:web, cleanup

#12292 [#noissue] Refactor TimeHistogramViewModel
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/histogram/AgentTimeHistogram.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/histogram/ApplicationTimeHistogram.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/link/Link.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/view/LoadTimeViewModel.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/view/LoadTimeViewModelBuilder.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/view/NodeHistogramSummaryView.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/view/ResponseTimeViewModel.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/view/ResponseTimeViewModelBuilder.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/view/TimeCount.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/view/TimeHistogramBuilder.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/view/TimeHistogramViewModel.java
  web/src/main/java/com/navercorp/pinpoint/web/view/ApplicationTimeHistogramViewModel.java
  web/src/main/java/com/navercorp/pinpoint/web/view/LinkHistogramSummaryView.java
  web/src/main/java/com/navercorp/pinpoint/web/view/LinkSerializer.java
  web/src/main/java/com/navercorp/pinpoint/web/view/NodeSerializer.java
  web/src/main/java/com/navercorp/pinpoint/web/view/TimeViewModel.java
  web/src/test/java/com/navercorp/pinpoint/web/applicationmap/histogram/AgentTimeHistogramTest.java
  web/src/test/java/com/navercorp/pinpoint/web/applicationmap/histogram/ApplicationTimeHistogramTest.java
  web/src/test/java/com/navercorp/pinpoint/web/applicationmap/service/FilteredMapServiceImplTest.java
  web/src/test/java/com/navercorp/pinpoint/web/applicationmap/view/ResponseTimeViewModelTest.java
Labels: module:web, cleanup

#12294 [#12287] Rollback spotbugs 4.7.3.6
  pom.xml
Labels: dependencies

#12295 [#noissue] Cleanup TimeCount
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/view/ResponseTimeViewModel.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/view/TimeCount.java
Labels: cleanup

#12297 [#noissue] Add validate commit messgae workflow
  .github/workflows/validate-commit.yml
Labels: configuration

#12300 [#noissue] Update validate commit workflow fetch depth
  .github/workflows/validate-commit.yml
Labels: configuration

#12301 [#noissue] Update validate commit workflow message
  .github/workflows/validate-commit.yml
Labels: configuration

#12302 [#noissue] Update validate commit workflow git show
  .github/workflows/validate-commit.yml
Labels: configuration

#12303 [#noissue] Update validate commit workflow commit_msg
  .github/workflows/validate-commit.yml
Labels: configuration

#12306 [#noissue] Update commit message convention of CONTRIBUTING.md
  CONTRIBUTING.md
Labels: document

#12291 [#12285] Update 3.x to async-http-client plugin
  agent-module/agent-testweb/ning-asynchttpclient-plugin-testweb/pom.xml
  agent-module/agent-testweb/ning-asynchttpclient-plugin-testweb/src/main/java/com/pinpoint/test/plugin/NingAsyncHttpClientPluginController.java
  agent-module/plugins/ning-asynchttpclient/src/main/java/com/navercorp/pinpoint/plugin/ning/asynchttpclient/NingAsyncHttpClientPlugin.java
  agent-module/plugins/ning-asynchttpclient/src/main/java/com/navercorp/pinpoint/plugin/ning/asynchttpclient/NingAsyncHttpClientPluginConfig.java
  agent-module/plugins/ning-asynchttpclient/src/main/java/com/navercorp/pinpoint/plugin/ning/asynchttpclient/interceptor/AsyncHandlerOnCompletedInterceptor.java
  agent-module/plugins/ning-asynchttpclient/src/main/java/com/navercorp/pinpoint/plugin/ning/asynchttpclient/interceptor/AsyncHandlerOnStatusReceivedInterceptor.java
  agent-module/plugins/ning-asynchttpclient/src/main/java/com/navercorp/pinpoint/plugin/ning/asynchttpclient/interceptor/AsyncHandlerOnThrowableInterceptor.java
  agent-module/plugins/ning-asynchttpclient/src/main/java/com/navercorp/pinpoint/plugin/ning/asynchttpclient/interceptor/ExecuteInterceptor.java
Labels: enhancement, module:plugin

#12299 [#noissue] Extract ApplicationMapView
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/ApplicationMap.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/ApplicationMapView.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/FilterMapView.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/MapView.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/controller/FilteredMapController.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/controller/MapController.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/link/Link.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/nodes/Node.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/view/LinkView.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/view/NodeView.java
  web/src/main/java/com/navercorp/pinpoint/web/view/LinkSerializer.java
  web/src/main/java/com/navercorp/pinpoint/web/view/NodeSerializer.java
  web/src/main/java/com/navercorp/pinpoint/web/view/TransactionInfoViewModel.java
  web/src/test/java/com/navercorp/pinpoint/web/applicationmap/service/FilteredMapServiceImplTest.java
  web/src/test/java/com/navercorp/pinpoint/web/view/LinkSerializerTest.java
Labels: module:web, cleanup

#12310 [#noissue] Cleanup api prefix of ServerMap
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/controller/FilteredMapController.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/controller/MapController.java
Labels: module:web, cleanup

#12311 [#noissue] Cleanup MapController validation
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/controller/MapController.java
Labels: cleanup

#12312 [#noissue] Remove unused TimeHistogramFormat in Link
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/link/Link.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/view/LinkView.java
Labels: cleanup

#12313 [#noissue] Cleanup FilteredMapController
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/controller/FilteredMapController.java
Labels: cleanup

#12317 [#noissue] Update validate commit workflow quote
  .github/workflows/validate-commit.yml
Labels: configuration

#12319 [#noissue] Refactor ResponseTimeViewModelBuilder
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/histogram/AgentTimeHistogramBuilder.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/histogram/Histogram.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/view/ResponseTimeViewModelBuilder.java
Labels: cleanup

#12316 [#12315] Optimize servermap json
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/ApplicationMapView.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/MapView.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/controller/MapController.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/histogram/TimeHistogramFormat.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/view/NodeHistogramSummaryView.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/view/TimeHistogramBuilder.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/view/TimeseriesHistogramViewModel.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/view/TimeseriesHistogramViewModelBuilder.java
Labels: enhancement, module:web

#12320 [#noissue] Add missing agentName field
  collector/src/main/java/com/navercorp/pinpoint/io/request/BindAttributes.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/grpc/BindAttribute.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/grpc/GrpcSpanBinder.java
  commons-server/src/test/java/com/navercorp/pinpoint/common/server/bo/grpc/CollectorGrpcSpanFactoryTest.java
  commons-server/src/test/java/com/navercorp/pinpoint/common/server/bo/grpc/GrpcSpanBinderTest.java
  commons-server/src/test/java/com/navercorp/pinpoint/common/server/bo/grpc/SpanFactoryTest.java
  commons-server/src/test/java/com/navercorp/pinpoint/common/server/bo/serializer/trace/v2/SpanEncoderTest.java
Labels: module:collector, module:project-common

#12321 [#noissue] Fix missing data in Inspector
  inspector-module/inspector-collector/src/main/java/com/navercorp/pinpoint/inspector/collector/service/PinotAgentStatService.java
Labels: bug, module:collector

#12323 [#noissue] Change ServerMap json from ts to timestamp
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/ApplicationMapView.java
Labels: cleanup

#12324 [#noissue] Cleanup AgentStat
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/stat/DefaultDataPoint.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/stat/FileDescriptorBo.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/stat/LoadedClassBo.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/stat/ResponseTimeBo.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/stat/TotalThreadCountBo.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/stat/TransactionBo.java
  inspector-module/inspector-collector/src/main/java/com/navercorp/pinpoint/inspector/collector/model/kafka/AgentStat.java
  inspector-module/inspector-collector/src/main/java/com/navercorp/pinpoint/inspector/collector/service/PinotAgentStatService.java
Labels: cleanup

#12327 [#noissue] Cleanup MapModule
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/config/ApplicationMapModule.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/controller/MapController.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/controller/MapHistogramController.java
  web/src/main/java/com/navercorp/pinpoint/web/view/ApplicationTimeHistogramViewModel.java
Labels: cleanup

#12328 [#12159] Change the url to heatmap api
  web-starter/src/main/resources/application.yml
  web/src/main/java/com/navercorp/pinpoint/web/authorization/controller/HeatmapChartController.java
  web/src/main/java/com/navercorp/pinpoint/web/heatmap/service/HeatmapChartServiceImpl.java
Labels: module:web

#12332 [#noissue] Cleanup FilteredMapBuilder
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/map/FilteredMapBuilder.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/service/FilteredMapServiceOption.java
Labels: cleanup

#12335 [#12159] Doubled the precision of the time slot in the chart.
  web/src/main/java/com/navercorp/pinpoint/web/authorization/controller/HeatmapChartController.java
Labels: module:web

#12339 [#nouissue] Refactor timestamp handling
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/ApplicationMapBuilder.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/appender/server/DefaultServerGroupListFactory.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/appender/server/DefaultServerInfoAppender.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/appender/server/EmptyServerGroupListFactory.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/appender/server/ServerGroupListFactory.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/appender/server/StatisticsServerGroupListFactory.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/appender/server/datasource/AgentInfoServerGroupListDataSource.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/appender/server/datasource/ServerGroupListDataSource.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/service/ResponseTimeHistogramServiceImpl.java
  web/src/main/java/com/navercorp/pinpoint/web/service/AgentInfoServiceImpl.java
  web/src/main/java/com/navercorp/pinpoint/web/service/ApplicationAgentListServiceImpl.java
  web/src/main/java/com/navercorp/pinpoint/web/vo/agent/AgentStatusQuery.java
  web/src/test/java/com/navercorp/pinpoint/web/applicationmap/appender/server/ServerInfoAppenderTest.java
  web/src/test/java/com/navercorp/pinpoint/web/applicationmap/service/ResponseTimeHistogramServiceImplTest.java
  web/src/test/java/com/navercorp/pinpoint/web/dao/hbase/HbaseAgentLifeCycleDaoTest.java
Labels: cleanup

#12341 [#noissue] Cleanup
  web/src/test/java/com/navercorp/pinpoint/web/applicationmap/LinkListTest.java
  web/src/test/java/com/navercorp/pinpoint/web/applicationmap/service/SearchDepthTest.java
  web/src/test/java/com/navercorp/pinpoint/web/filter/AcceptUrlFilterTest.java
Labels: cleanup

#12348 [#noissue] Fix max depth to 4
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/controller/SearchDepthForm.java
Labels: bug

#12338 [#12336] Support multi-table mode for systemMetric
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/metric/dao/FixedNameManager.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/metric/dao/HashedNameManager.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/metric/dao/NameManager.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/metric/dao/TableNameManager.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/metric/dao/TopicNameManager.java
  metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/collector/MetricAppPropertySources.java
  metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/collector/MetricCollectorApp.java
  metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/collector/MetricCollectorConfig.java
  metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/collector/config/MetricCollectorProperties.java
  metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/collector/dao/pinot/PinotMetricTagDao.java
  metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/collector/dao/pinot/PinotSystemMetricDataTypeDao.java
  metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/collector/dao/pinot/PinotSystemMetricDoubleDao.java
  metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/web/MetricWebConfig.java
  metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/web/WebMetricPropertySources.java
  metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/web/config/SystemMetricProperties.java
  metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/web/dao/model/SystemMetricDataSearchKey.java
  metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/web/dao/pinot/PinotSystemMetricDoubleDao.java
  metric-module/metric/src/main/pinot/multi-table/README.md
  metric-module/metric/src/main/pinot/multi-table/multi-table.sh
  metric-module/metric/src/main/pinot/multi-table/template_OFFLINE.json
  metric-module/metric/src/main/pinot/multi-table/template_REALTIME.json
  metric-module/metric/src/main/pinot/multi-table/template_SCHEMA.json
  metric-module/metric/src/main/resources/pinot-collector/kafka-topic-root.properties
  metric-module/metric/src/main/resources/pinot-collector/kafka-topic.properties
  metric-module/metric/src/main/resources/pinot-collector/profiles/local/kafka-topic.properties
  metric-module/metric/src/main/resources/pinot-collector/profiles/release/kafka-topic.properties
  metric-module/metric/src/main/resources/pinot-web/mapper/pinot/SystemMetricDoubleMapper.xml
  metric-module/metric/src/main/resources/pinot-web/pinpoint-web-metric-root.properties
  metric-module/metric/src/main/resources/pinot-web/profiles/local/pinpoint-web-metric.properties
  metric-module/metric/src/main/resources/pinot-web/profiles/release/pinpoint-web-metric.properties
  metric-module/metric/src/test/java/com/navercorp/pinpoint/metric/collector/dao/pinot/PinotSystemMetricDaoTest.java
Labels: module:metric

#12357 [#12159] Replace imported class
  web/src/main/java/com/navercorp/pinpoint/web/heatmap/HeatmapWebModule.java
Labels: module:web

#12337 [#noissue] Refactor HyperLinkFactory dependencies
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/ApplicationMapView.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/FilterMapView.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/MapView.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/appender/server/datasource/AgentInfoServerGroupListDataSource.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/config/ApplicationMapModule.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/controller/FilteredMapController.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/controller/MapController.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/controller/MapHistogramController.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/nodes/ServerBuilder.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/nodes/ServerGroup.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/nodes/ServerGroupList.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/nodes/ServerInstance.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/view/FilteredHistogramView.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/view/LinkHistogramSummaryView.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/view/NodeHistogramSummaryView.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/view/NodeView.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/view/ServerGroupListView.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/view/ServerInstanceView.java
  web/src/main/java/com/navercorp/pinpoint/web/authorization/controller/AgentListController.java
  web/src/main/java/com/navercorp/pinpoint/web/authorization/controller/ResponseTimeController.java
  web/src/main/java/com/navercorp/pinpoint/web/controller/BusinessTransactionController.java
  web/src/main/java/com/navercorp/pinpoint/web/hyperlink/HyperLinkConfiguration.java
  web/src/main/java/com/navercorp/pinpoint/web/hyperlink/HyperLinkFactory.java
  web/src/main/java/com/navercorp/pinpoint/web/service/ServerInstanceDatasourceService.java
  web/src/main/java/com/navercorp/pinpoint/web/view/ServerGroupListSerializer.java
  web/src/main/java/com/navercorp/pinpoint/web/view/ServerInstanceSerializer.java
  web/src/main/java/com/navercorp/pinpoint/web/view/ServiceTypeSerializer.java
  web/src/main/java/com/navercorp/pinpoint/web/view/TransactionInfoViewModel.java
  web/src/main/java/com/navercorp/pinpoint/web/view/histogram/ServerHistogramView.java
  web/src/test/java/com/navercorp/pinpoint/web/applicationmap/ApplicationMapBuilderTest.java
  web/src/test/java/com/navercorp/pinpoint/web/applicationmap/controller/MapControllerTest.java
  web/src/test/java/com/navercorp/pinpoint/web/applicationmap/service/FilteredMapServiceImplTest.java
  web/src/test/java/com/navercorp/pinpoint/web/view/LinkSerializerTest.java
  web/src/test/java/com/navercorp/pinpoint/web/view/ServerGroupListSerializerTest.java
  web/src/test/java/com/navercorp/pinpoint/web/vo/AgentsMapByHostTest.java
  web/src/test/resources/log4j2-test.xml
Labels: cleanup

#12360 [#noissue] Refactor LinkList and NodeList
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/ApplicationMapBuilder.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/DefaultApplicationMap.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/link/LinkList.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/link/LinkListFactory.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/nodes/NodeList.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/nodes/NodeListFactory.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/nodes/ServerGroup.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/nodes/ServerGroupList.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/service/ResponseTimeHistogramServiceImpl.java
  web/src/test/java/com/navercorp/pinpoint/web/applicationmap/ApplicationMapTest.java
  web/src/test/java/com/navercorp/pinpoint/web/applicationmap/LinkListTest.java
  web/src/test/java/com/navercorp/pinpoint/web/applicationmap/ServerGroupListTest.java
  web/src/test/java/com/navercorp/pinpoint/web/applicationmap/appender/histogram/NodeHistogramAppenderTest.java
  web/src/test/java/com/navercorp/pinpoint/web/applicationmap/appender/server/ServerInfoAppenderTest.java
  web/src/test/java/com/navercorp/pinpoint/web/applicationmap/nodes/NodeListTest.java
Labels: cleanup

#12363 [#12159] Change HeatMap data time order to ascending
  web/src/main/java/com/navercorp/pinpoint/web/heatmap/service/HeatmapChartServiceImpl.java
  web/src/main/java/com/navercorp/pinpoint/web/heatmap/view/HeatMapDataView.java
  web/src/main/java/com/navercorp/pinpoint/web/heatmap/vo/HeatMapData.java
Labels: module:web

#12362 [#noissue] Refactor MapViews
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/AnnotationTranscoder.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/serializer/trace/v2/bitfield/SpanBitField.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/serializer/trace/v2/bitfield/SpanEventBitField.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/serializer/trace/v2/bitfield/SpanEventQualifierBitField.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/util/BitFieldUtils.java
  commons-server/src/test/java/com/navercorp/pinpoint/common/server/util/BitFieldUtilsTest.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/ApplicationMapView.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/ApplicationMapViewV3.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/FilterMapView.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/MapView.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/MapViewV3.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/controller/FilteredMapController.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/controller/MapController.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/link/LinkViews.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/map/MapViews.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/nodes/NodeViews.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/view/LinkView.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/view/NodeView.java
  web/src/main/java/com/navercorp/pinpoint/web/view/TransactionInfoViewModel.java
  web/src/test/java/com/navercorp/pinpoint/web/applicationmap/link/LinkViewsTest.java
  web/src/test/java/com/navercorp/pinpoint/web/applicationmap/map/MapViewsTest.java
  web/src/test/java/com/navercorp/pinpoint/web/view/LinkSerializerTest.java
Labels: cleanup

#12367 [#noissue] Rename LinkSerializerTest to LinkViewTest
  web/src/test/java/com/navercorp/pinpoint/web/view/LinkViewTest.java
Labels: cleanup

#12369 [#12368] Clear unnecessary branches in CallTree
  web/src/main/java/com/navercorp/pinpoint/web/calltree/span/CallTree.java
  web/src/main/java/com/navercorp/pinpoint/web/calltree/span/CallTreeNodeNonProductiveFilter.java
  web/src/main/java/com/navercorp/pinpoint/web/calltree/span/LinkedCallTree.java
  web/src/main/java/com/navercorp/pinpoint/web/calltree/span/SpanAligner.java
  web/src/main/java/com/navercorp/pinpoint/web/calltree/span/SpanCallTree.java
  web/src/test/java/com/navercorp/pinpoint/web/calltree/span/CallTreeTest.java
Labels: enhancement, module:web

#12377 [#12376] Backport: Update kafka plugin for compatibility with kafka 4.x
  agent-module/plugins/kafka/src/main/java/com/navercorp/pinpoint/plugin/kafka/interceptor/ProducerAddHeaderInterceptor.java
Labels: enhancement, module:plugin

#12375 [#noissue] Improve empty list handling in NodeList
  web/src/main/java/com/navercorp/pinpoint/web/calltree/span/NodeList.java
  web/src/main/java/com/navercorp/pinpoint/web/calltree/span/SpanAligner.java
  web/src/test/java/com/navercorp/pinpoint/web/calltree/span/NodeListTest.java
Labels: cleanup

#12333 [#noissue] Remove viewVersion from FilteredMap
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/util/ApplicationMapStatisticsUtils.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/util/UserNodeUtils.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/controller/FilteredMapController.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/dao/mapper/InLinkMapper.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/map/FilteredMapBuilder.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/service/FilteredMapServiceImpl.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/service/FilteredMapServiceOption.java
  web/src/main/java/com/navercorp/pinpoint/web/controller/BusinessTransactionController.java
  web/src/test/java/com/navercorp/pinpoint/web/TestTraceUtils.java
  web/src/test/java/com/navercorp/pinpoint/web/applicationmap/map/FilteredMapBuilderTest.java
  web/src/test/java/com/navercorp/pinpoint/web/applicationmap/service/FilteredMapServiceImplTest.java
Labels: cleanup

#12381 [#noissue] Cleanup FilterMapView
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/FilterMapView.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/FilterMapViewV3.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/controller/FilteredMapController.java
Labels: cleanup

#12384 [#noissue] Cleanup FilteredMapController
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/controller/FilteredMapController.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/controller/MapController.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/controller/MapHistogramController.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/controller/form/ApplicationForm.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/controller/form/FilterForm.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/controller/form/GroupForm.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/controller/form/RangeForm.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/controller/form/SearchDepthForm.java
Labels: cleanup

#12380 [#12378] Backport: Update the entry point for kafka stream
  agent-module/agent/src/main/resources/profiles/local/pinpoint.config
  agent-module/agent/src/main/resources/profiles/release/pinpoint.config
  agent-module/plugins/kafka/README.md
  agent-module/plugins/kafka/src/main/java/com/navercorp/pinpoint/plugin/kafka/KafkaConfig.java
  agent-module/plugins/kafka/src/main/java/com/navercorp/pinpoint/plugin/kafka/KafkaPlugin.java
  agent-module/plugins/kafka/src/main/java/com/navercorp/pinpoint/plugin/kafka/field/getter/StampedRecordGetter.java
  agent-module/plugins/kafka/src/main/java/com/navercorp/pinpoint/plugin/kafka/interceptor/RecordDeserializerInterceptor.java
  agent-module/plugins/kafka/src/main/java/com/navercorp/pinpoint/plugin/kafka/interceptor/StreamTaskDoProcessInterceptor.java
  agent-module/plugins/kafka/src/main/java/com/navercorp/pinpoint/plugin/kafka/util/KafkaRequestAdaptor.java
Labels: enhancement, module:plugin

#12388 [#12159] Resolve anyone matching rule malfunction for tag in systemetric.
  metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/web/service/SystemMetricDataServiceImpl.java
  metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/web/service/SystemMetricHostInfoServiceImpl.java
Labels: module:metric

#12389 [#noissue] Cleanup
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/view/FilteredHistogramView.java
  web/src/main/java/com/navercorp/pinpoint/web/service/AgentInfoServiceImpl.java
  web/src/main/java/com/navercorp/pinpoint/web/service/ServerInstanceDatasourceService.java
  web/src/main/java/com/navercorp/pinpoint/web/view/histogram/ServerHistogramView.java
Labels: cleanup

#12391 [#noissue] Refactor TransactionController
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/histogram/TimeHistogramFormat.java
  web/src/main/java/com/navercorp/pinpoint/web/controller/BusinessTransactionController.java
  web/src/main/java/com/navercorp/pinpoint/web/view/TransactionInfoViewModel.java
Labels: cleanup

#12392 [#noissue] Cleanup
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/controller/FilteredMapController.java
  web/src/main/java/com/navercorp/pinpoint/web/calltree/span/SpanFilters.java
  web/src/main/java/com/navercorp/pinpoint/web/controller/TransactionController.java
Labels: cleanup

#12395 [#noissue] Cleanup
  web/src/main/java/com/navercorp/pinpoint/web/calltree/span/CallTreeIterator.java
  web/src/main/java/com/navercorp/pinpoint/web/view/tree/SimpleTreeView.java
  web/src/main/java/com/navercorp/pinpoint/web/view/tree/StaticTreeView.java
Labels: cleanup

#12394 [#noissue] Refactor TransactionController
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/service/FilteredMapServiceImpl.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/service/FilteredMapServiceOption.java
  web/src/main/java/com/navercorp/pinpoint/web/controller/TransactionController.java
  web/src/main/java/com/navercorp/pinpoint/web/view/TransactionInfoViewModel.java
Labels: cleanup

#12398 [#noissue] Extract HistogramFormat in Link
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/histogram/ApplicationTimeHistogram.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/histogram/NodeHistogram.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/link/Link.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/view/LinkHistogramSummaryView.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/view/LinkView.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/view/NodeHistogramSummaryView.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/view/NodeView.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/view/TimeHistogramBuilder.java
  web/src/test/java/com/navercorp/pinpoint/web/applicationmap/histogram/AgentTimeHistogramTest.java
  web/src/test/java/com/navercorp/pinpoint/web/applicationmap/histogram/ApplicationTimeHistogramTest.java
  web/src/test/java/com/navercorp/pinpoint/web/applicationmap/service/FilteredMapServiceImplTest.java
  web/src/test/java/com/navercorp/pinpoint/web/view/LinkViewTest.java
Labels: cleanup

#12397 [#12396] Update duplicated node in call tree
  web/src/main/java/com/navercorp/pinpoint/web/calltree/span/LinkMap.java
  web/src/main/java/com/navercorp/pinpoint/web/calltree/span/SpanAligner.java
  web/src/test/java/com/navercorp/pinpoint/web/calltree/span/SpanAlignerTest.java
Labels: enhancement, module:web

#12399 [#noissue] Refactor AgentHistogramList
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/histogram/AgentTimeHistogramBuilder.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/link/Link.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/nodes/ServerBuilder.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/rawdata/AgentHistogram.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/rawdata/AgentHistogramList.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/rawdata/LinkCallDataMap.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/service/ResponseTimeHistogramServiceImpl.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/view/LinkView.java
  web/src/test/java/com/navercorp/pinpoint/web/view/LinkViewTest.java
Labels: cleanup

#12400 [#noissue] Refactor NodeView to simplify service type checks
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/view/NodeView.java
Labels: cleanup

#12402 [#12222] Add Inconsistent applicationName Uid cleanup task
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/uid/HbaseCellData.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/uid/mapper/ApplicationNameRowMapper.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/util/ApplicationUidRowKeyUtils.java
  web/src/main/java/com/navercorp/pinpoint/web/uid/controller/ApplicationUidController.java
  web/src/main/java/com/navercorp/pinpoint/web/uid/dao/ApplicationNameDao.java
  web/src/main/java/com/navercorp/pinpoint/web/uid/dao/hbase/HbaseApplicationNameDao.java
  web/src/main/java/com/navercorp/pinpoint/web/uid/service/ApplicationUidService.java
  web/src/main/java/com/navercorp/pinpoint/web/uid/service/ApplicationUidServiceImpl.java
Labels: module:web

#12405 [#noissue] Prevent use of unknown or corrupted span as a viewpoint
  web/src/main/java/com/navercorp/pinpoint/web/service/TransactionInfoServiceImpl.java
Labels: module:web
