Repository pinpoint-apm/pinpoint, pull requests merged in 2025-09, with the labels that each got.

#12854 [#12814] Rollback agent NPE in annotation value mapper
  agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/context/grpc/mapper/AnnotationValueMapper.java
  agent-module/profiler/src/test/java/com/navercorp/pinpoint/profiler/context/grpc/mapper/AnnotationValueMapperTest.java
Labels: module:agent

#12858 [#12823] Cleanup
  agent-module/agent-testweb/grpc-plugin-testweb/pom.xml
Labels: cleanup

#12861 [#noissue] Remove unused defaultString method
  agent-module/bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/interceptor/EmptyInterceptor.java
  agent-module/bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/interceptor/LoggingInterceptor.java
Labels: cleanup

#12875 [#noissue] Refactor TimeWindowFunction usage and remove redundant method
  commons-timeseries/src/main/java/com/navercorp/pinpoint/common/timeseries/window/TimeWindowFunction.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/dao/hbase/HbaseMapInLinkDao.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/dao/hbase/HbaseMapOutLinkDao.java
Labels: cleanup

#12881 [#noissue] Throttle warning logs of RequestNotPermittedException
  collector/src/main/java/com/navercorp/pinpoint/collector/handler/grpc/GrpcSpanChunkHandler.java
  collector/src/main/java/com/navercorp/pinpoint/collector/handler/grpc/GrpcSpanHandler.java
Labels: module:collector, configuration

#12885 [#noissue] Fix malfunctioning behavior of /links API
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/controller/ServerMapHistogramController.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/service/HistogramService.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/service/HistogramServiceImpl.java
Labels: module:web

#12908 [#noissue] Remove duplicate mapLinkRowKeyDistributor
  collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/statistics/config/BulkConfiguration.java
  commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/config/DistributorConfiguration.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/config/MapHbaseConfiguration.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/config/MapMapperConfiguration.java
Labels: cleanup

#12906 [#12905] Backport: Update agent "not matched stack id" error log
  agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/context/ChildTrace.java
  agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DefaultTrace.java
Labels: enhancement, module:agent

#12924 [#12923] Update agent interceptorHolder generated class module
  agent-module/agent/src/assembly/component/core.xml
  agent-module/bootstraps/bootstrap-core/pom.xml
  agent-module/bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/interceptor/holder/InterceptorHolderAnnotationProcessor.java
  agent-module/bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/interceptor/holder/InterceptorHolderBootstrap.java
  agent-module/bootstraps/bootstrap-interceptor/pom.xml
  agent-module/bootstraps/bootstrap-interceptor/src/main/java/com/navercorp/pinpoint/bootstrap/interceptor/holder/InterceptorHolderGenerator.java
  agent-module/bootstraps/bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/agentdir/AgentDirBaseClassPathResolver.java
  agent-module/bootstraps/pom.xml
  annotations/pom.xml
  annotations/src/main/resources/META-INF/services/javax.annotation.processing.Processor
Labels: enhancement, module:agent

#12921 [#noissue] Refactor BulkWriter
  agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/name/v1/ObjectNameResolverV1.java
  collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/config/MapV2Configuration.java
  collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/config/MapV3Configuration.java
  collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/dao/hbase/HbaseHostApplicationMapDao.java
  collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/statistics/config/BulkConfiguration.java
  collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/statistics/config/BulkFactory.java
  collector/src/test/java/com/navercorp/pinpoint/collector/applicationmap/dao/hbase/HbaseHostApplicationMapDaoTest.java
  commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/CheckAndMax.java
  commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/config/DistributorConfiguration.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/applicationmap/statistics/UidLinkRowKey.java
  commons/src/main/java/com/navercorp/pinpoint/common/PinpointConstants.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/config/MapHbaseConfiguration.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/config/MapMapperConfiguration.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/config/MapV3MapperConfiguration.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/dao/v3/InLinkV3Mapper.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/dao/v3/OutLinkV3Mapper.java
Labels: cleanup

#12929 [#12928] Bump asm from 9.7.1 to 9.8
  pom.xml
Labels: module:agent

#12942 [#noissue] Cleanup
  collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/config/MapV2Configuration.java
  collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/config/MapV3Configuration.java
  collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/dao/hbase/HbaseMapInLinkDao.java
  collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/dao/hbase/HbaseMapOutLinkDao.java
  collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/dao/hbase/HbaseMapResponseTimeDao.java
  collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/statistics/BulkIncrementer.java
  collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/statistics/BulkUpdater.java
  collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/statistics/BulkWriter.java
  collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/statistics/DefaultBulkIncrementer.java
  collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/statistics/DefaultBulkUpdater.java
  collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/statistics/DefaultBulkWriter.java
  collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/statistics/DefaultRowInfo.java
  collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/statistics/RowInfo.java
  collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/statistics/RowKeyMerge.java
  collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/statistics/SizeLimitedBulkIncrementer.java
  collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/statistics/SizeLimitedBulkUpdater.java
  collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/statistics/SyncWriter.java
  collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/statistics/config/BulkFactory.java
  collector/src/test/java/com/navercorp/pinpoint/collector/applicationmap/statistics/BulkIncrementerTestClazz.java
  collector/src/test/java/com/navercorp/pinpoint/collector/applicationmap/statistics/DefaultBulkUpdaterTest.java
  collector/src/test/java/com/navercorp/pinpoint/collector/applicationmap/statistics/SizeLimitedBulkIncrementerTest.java
Labels: cleanup

#12943 [#noissue] Refactor to use HistogramSlot in application map data handling
  collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/dao/hbase/HbaseMapInLinkDao.java
  collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/dao/hbase/HbaseMapOutLinkDao.java
  collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/dao/hbase/HbaseMapResponseTimeDao.java
  collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/dao/hbase/InLinkFactory.java
  collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/dao/hbase/InLinkFactoryV2.java
  collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/dao/hbase/OutLinkFactory.java
  collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/dao/hbase/OutLinkFactoryV2.java
  collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/dao/hbase/SelfNodeFactory.java
  collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/dao/hbase/SelfNodeFactoryV2.java
  collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/dao/v3/InLinkFactoryV3.java
  collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/dao/v3/InLinkV3ColumnName.java
  collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/dao/v3/OutLinkFactoryV3.java
  collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/dao/v3/OutLinkV3ColumnName.java
  collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/dao/v3/SelfNodeFactoryV3.java
  collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/statistics/InLinkV2ColumnName.java
  collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/statistics/OutLinkV2ColumnName.java
  collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/statistics/ResponseColumnName.java
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/util/MapSlotUtils.java
Labels: cleanup

#12945 [#noissue] Cleanup
  collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/statistics/DefaultBulkWriter.java
  collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/statistics/RowKeyMerge.java
  collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/statistics/SyncWriter.java
  collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/statistics/config/BulkFactory.java
  collector/src/test/java/com/navercorp/pinpoint/collector/applicationmap/statistics/BulkIncrementerTestClazz.java
  collector/src/test/java/com/navercorp/pinpoint/collector/applicationmap/statistics/DefaultBulkUpdaterTest.java
  collector/src/test/java/com/navercorp/pinpoint/collector/applicationmap/statistics/SizeLimitedBulkIncrementerTest.java
  commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/wd/RowKeyDistributorByHashPrefix.java
Labels: cleanup

#12954 [#noissue] Cleanup log4j2-test.xml
  inspector-module/inspector-collector/src/test/resources/log4j2-test.xml
Labels: cleanup
