Repository pinpoint-apm/pinpoint, pull requests merged in 2025-06, with the labels that each got.

#12516 [#noissue] Increase timeout for docker image readiness check
  agent-module/plugins-test-module/plugins-test/src/main/java/com/navercorp/pinpoint/test/plugin/DefaultPluginTestInstance.java
Labels: cleanup

#12517 [#noissue] Refactor ApplicationPairsConverter
  web/src/main/java/com/navercorp/pinpoint/web/WebMvcConfig.java
  web/src/main/java/com/navercorp/pinpoint/web/vo/ApplicationPairsConverter.java
Labels: cleanup

#12519 [#12518] Bump commons-beantuils from 1.9.4 to 1.11.0
  pom.xml
Labels: dependencies

#12515 [#noissue] Refactor JacksonSerde
  channel/src/main/java/com/navercorp/pinpoint/channel/ChannelSpringConfig.java
  channel/src/main/java/com/navercorp/pinpoint/channel/serde/JacksonSerde.java
  channel/src/main/java/com/navercorp/pinpoint/channel/serde/JacksonSerdeFactory.java
  channel/src/main/java/com/navercorp/pinpoint/channel/serde/JsonSerdeFactory.java
  channel/src/test/java/com/navercorp/pinpoint/channel/ChannelSpringConfigTest.java
  channel/src/test/java/com/navercorp/pinpoint/channel/serde/JacksonSerdeTest.java
  channel/src/test/java/com/navercorp/pinpoint/channel/service/ChannelServiceProtocolTest.java
  channel/src/test/java/com/navercorp/pinpoint/channel/service/FluxChannelServiceTest.java
  channel/src/test/java/com/navercorp/pinpoint/channel/service/MonoChannelServiceTest.java
  log/log-common/src/main/java/com/navercorp/pinpoint/log/LogServiceProtocolConfig.java
  log/log-web/src/main/java/com/navercorp/pinpoint/log/web/websocket/LogWebSocketConfig.java
  realtime/realtime-common/src/main/java/com/navercorp/pinpoint/realtime/config/ATCServiceProtocolConfig.java
  realtime/realtime-common/src/main/java/com/navercorp/pinpoint/realtime/config/ATDServiceProtocolConfig.java
  realtime/realtime-common/src/main/java/com/navercorp/pinpoint/realtime/config/EchoServiceProtocolConfig.java
  realtime/realtime-common/src/main/java/com/navercorp/pinpoint/realtime/serde/ClusterKeyDeserializer.java
  realtime/realtime-common/src/test/java/com/navercorp/pinpoint/realtime/serde/ClusterTest.java
  realtime/realtime-web/src/main/java/com/navercorp/pinpoint/web/realtime/activethread/count/WebActiveThreadCountConfig.java
  realtime/realtime-web/src/main/java/com/navercorp/pinpoint/web/realtime/activethread/count/websocket/RedisActiveThreadCountWebSocketHandler.java
Labels: enhancement

#12529 [#12528] Bump snakeyaml to 2.4
  pom.xml
Labels: dependencies

#12532 [#noissue] Fix grpc plugin it endPoint
  agent-module/plugins-it/google-grpc-it/google-grpc-1-42-it/src/test/java/com/navercorp/pinpoint/it/plugin/grpc/GrpcITBase.java
  agent-module/plugins-it/google-grpc-it/google-grpc-1-8-it/src/test/java/com/navercorp/pinpoint/it/plugin/grpc/GrpcITBase.java
Labels: Continuous Integration

#12539 [#noissue] Remove deprecated API in HeatMapService
  web/src/main/java/com/navercorp/pinpoint/web/dao/ApplicationTraceIndexDao.java
  web/src/main/java/com/navercorp/pinpoint/web/dao/hbase/HbaseApplicationTraceIndexDao.java
  web/src/main/java/com/navercorp/pinpoint/web/service/HeatMapService.java
  web/src/main/java/com/navercorp/pinpoint/web/service/HeatMapServiceImpl.java
Labels: cleanup

#12542 [#noissue] Cleanup
  channel/src/main/java/com/navercorp/pinpoint/channel/ChannelSpringConfig.java
  channel/src/test/java/com/navercorp/pinpoint/channel/ChannelSpringConfigTest.java
Labels: cleanup

#12551 [#noissue] Cleanup Objects.toString
  collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/dao/hbase/HbaseMapInLinkDao.java
  collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/dao/hbase/HbaseMapOutLinkDao.java
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/dao/mapper/InLinkMapper.java
  web/src/main/java/com/navercorp/pinpoint/web/vo/activethread/AgentActiveThreadCountList.java
Labels: cleanup

#12556 [#12555] Bump spring-kafka from 3.2.4 to 3.2.9
  pom.xml
Labels: dependencies

#12546 [#noissue] Remove deprecated util functions
  commons-server/src/main/java/com/navercorp/pinpoint/common/server/mapper/MapStructUtils.java
  commons-server/src/test/java/com/navercorp/pinpoint/common/server/mapper/MapStructUtilsTest.java
  exceptiontrace/exceptiontrace-web/src/main/java/com/navercorp/pinpoint/exceptiontrace/web/mapper/ExceptionEntityMapper.java
Labels: module:web, module:project-common

#12557 [#12554] Add isolate system properties
  agent-module/agent/src/main/resources/profiles/local/pinpoint.config
  agent-module/agent/src/main/resources/profiles/release/pinpoint.config
  agent-module/bootstraps/bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/AgentBootLoader.java
  agent-module/bootstraps/bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/config/SystemPropertyManager.java
  agent-module/bootstraps/bootstrap/src/test/java/com/navercorp/pinpoint/bootstrap/config/SystemPropertyManagerTest.java
Labels: enhancement, module:agent

#12562 [#12561] Update forwarding server call tracking in grpc plugin
  agent-module/plugins/grpc/src/main/java/com/navercorp/pinpoint/plugin/grpc/interceptor/server/CopyAsyncContextInterceptor.java
Labels: enhancement, module:plugin

#12565 [#12564] Backport: Update forwarding server call tracking in grpc plugin
  agent-module/plugins/grpc/src/main/java/com/navercorp/pinpoint/plugin/grpc/interceptor/server/CopyAsyncContextInterceptor.java
Labels: enhancement, module:plugin

#12567 [#noissue] Bug fix in AsyncQueueingUriStatStorage
  agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/context/storage/AsyncQueueingUriStatStorage.java
  commons-profiler/src/main/java/com/navercorp/pinpoint/common/profiler/concurrent/executor/UnsafeArrayCollection.java
  commons-profiler/src/test/java/com/navercorp/pinpoint/common/profiler/concurrent/executor/UnsafeArrayCollectionTest.java
Labels: bug

#12570 [#12434] Refactor ServerMap
  collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/Vertex.java
  collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/dao/HostApplicationMapDao.java
  collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/dao/MapInLinkDao.java
  collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/dao/MapOutLinkDao.java
  collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/dao/MapResponseTimeDao.java
  collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/dao/hbase/HbaseHostApplicationMapDao.java
  collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/dao/hbase/HbaseMapInLinkDao.java
  collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/dao/hbase/HbaseMapOutLinkDao.java
  collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/dao/hbase/HbaseMapResponseTimeDao.java
  collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/service/LinkService.java
  collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/service/LinkServiceImpl.java
  collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/statistics/InLinkColumnName.java
  collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/statistics/LinkRowKey.java
  collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/statistics/OutLinkColumnName.java
  collector/src/main/java/com/navercorp/pinpoint/collector/service/HbaseTraceService.java
  collector/src/test/java/com/navercorp/pinpoint/collector/applicationmap/dao/hbase/HbaseHostApplicationMapDaoTest.java
Labels: cleanup

#12572 [#12571] Update mono runnable interceptor of reactor pulgin
  agent-module/agent-testweb/reactor-plugin-testweb/src/main/java/com/pinpoint/test/plugin/AsyncStorageService.java
  agent-module/agent-testweb/reactor-plugin-testweb/src/main/java/com/pinpoint/test/plugin/ReactorPluginController.java
  agent-module/plugins/reactor/src/main/java/com/navercorp/pinpoint/plugin/reactor/interceptor/CoreSubscriberRunInterceptor.java
Labels: enhancement, module:plugin

#12563 [#noissue] Fix sys properties isolate config
  agent-module/agent/src/main/resources/profiles/local/pinpoint.config
  agent-module/agent/src/main/resources/profiles/release/pinpoint.config
Labels: configuration

#12580 [#noissue] Fix api `/getResponseTimeHistogramDataV2`
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/controller/MapHistogramController.java
Labels: module:web

#12590 [#12589] Bump checkerframework to 3.49.3
  pom.xml
Labels: dependencies

#12591 [#noissue] Fix ArrayIndexOutOfBoundsException message in BytesUtils
  commons-buffer/src/test/java/com/navercorp/pinpoint/common/util/BytesUtilsTest.java
  commons/src/main/java/com/navercorp/pinpoint/common/util/BytesUtils.java
Labels: cleanup

#12593 [#12592] Bump aspectjweaver from 1.9.5 to 1.9.24
  pom.xml
Labels: dependencies

#12594 [#noissue] Cleanup
  collector/src/main/java/com/navercorp/pinpoint/collector/grpc/config/GrpcAgentConfiguration.java
  collector/src/main/java/com/navercorp/pinpoint/collector/grpc/config/GrpcComponentConfiguration.java
  collector/src/main/java/com/navercorp/pinpoint/collector/grpc/config/GrpcSpanReceiverConfiguration.java
  collector/src/main/java/com/navercorp/pinpoint/collector/grpc/config/GrpcStatReceiverConfiguration.java
  collector/src/main/java/com/navercorp/pinpoint/collector/grpc/config/ServerServiceDefinitions.java
  collector/src/main/java/com/navercorp/pinpoint/collector/receiver/grpc/service/DefaultServerRequestFactory.java
  collector/src/main/java/com/navercorp/pinpoint/collector/receiver/grpc/service/ServerRequestPostProcessor.java
Labels: cleanup

#12576 [#12575] Fix Call Tree focus of Web
  web/src/main/java/com/navercorp/pinpoint/web/service/TransactionInfoServiceImpl.java
  web/src/main/java/com/navercorp/pinpoint/web/view/TransactionInfoViewModel.java
  web/src/main/java/com/navercorp/pinpoint/web/vo/callstacks/RecordSet.java
Labels: bug, module:web

#12608 [#12606] Fix CallStack NPE of web
  web/src/main/java/com/navercorp/pinpoint/web/applicationmap/map/FilteredMapBuilder.java
Labels: bug, module:web

#12618 [#12617] Add server.port to PinpointSpringBanner
  collector/src/main/resources/pinpoint-collector-root.properties
  web/src/main/resources/pinpoint-web-root.properties
Labels: cleanup
